### ISSUE TITLE
On kde (x11), floating search bar immediatly lost focus in certain conditions.

### ISSUE THREAD

**Issue by shenlebantongying** [xiaoyifang/goldendict-ng#1001]
Drag out the search bar, try to click the search box -> immediately lost focus (to mainwindow (actually the articleview)). Thus the floating search box is not unusable. Note that the dark title bar indicates the focus.

Also, if GD starts with the search bar already dragged out, the problem will be gone :sweat_smile: 

![](https://github.com/xiaoyifang/goldendict-ng/assets/20123683/2dd6ccbe-2291-4df9-a5f9-0fa1be788169)

**Comment by xiaoyifang** [comment]
![image](https://github.com/xiaoyifang/goldendict-ng/assets/105986/6b44c358-f723-47a1-ac7a-3b9b7402d998)

maybe caused by this.


but can not reproduced on Windows.
