### ISSUE TITLE
Window maximization still doesn't work

### ISSUE THREAD

**Issue by atauzki** [xiaoyifang/goldendict-ng#1016]
win11，pull最新版本(commit id:[3283a58](https://github.com/xiaoyifang/goldendict-ng/commit/3283a586097223f530f8913f0681a8a8a3ed466e))清除缓存重新编译后，运行窗口最大化，再退出重新启动，窗口仍然无法自动最大化

**Comment by shenlebantongying** [comment]
据观察在一瞬间会最大化，应该是这个 bug， https://bugreports.qt.io/browse/QTBUG-115074

我复制 bug 里面的代码，可以在 Windows 上稳定复现，存在 QWebEngineView 的情况下，showMaxmized 直接用不了 😅 

https://github.com/xiaoyifang/goldendict-ng/assets/20123683/93defc92-156c-487c-a337-069fccb2932d

**Comment by shenlebantongying** [comment]
我觉得 https://github.com/xiaoyifang/goldendict-ng/pull/1013 需要 revert 掉，这是 Qt 本体的 bug

**Comment by xiaoyifang** [comment]
> 我觉得 #1013 可能需要 revert 掉，这是 Qt 本体的 bug

reverted

**Comment by shenlebantongying** [comment]
这个 bug 的触发条件是网页没有加载任何内容前 showMaxmized 直接不能用

那把 restoreState restoreGeometry 
https://github.com/xiaoyifang/goldendict-ng/blob/69905ed92d1204db43d3a8d5bbde504f13347e91/src/ui/mainwindow.cc#L744-L747

移动到 加载完 "Welcome" 的 下面 就可以了 😅 

https://github.com/xiaoyifang/goldendict-ng/blob/69905ed92d1204db43d3a8d5bbde504f13347e91/src/ui/mainwindow.cc#L773

**Comment by xiaoyifang** [comment]
> 移动到 加载完 "Welcome" 的 下面 就可以了 😅

you can make a PR .
