### ISSUE TITLE
A bug with some dictionaries in versions with qt 6.5.X

### ISSUE THREAD

**Issue by PrinceOC912** [xiaoyifang/goldendict-ng#1053]
**Describe the bug**
On Windows 11, a bug first introduced in 6.5.X versions that prevent some dictionaries from functioning properly.

**To Reproduce**
1. Search for any word
2. Navigate to OALD 
3. Click on the speaker icon to pronounce the word
4. Nothing happened (This also affects the additional sections like Collocations, extra examples and word origin, they don't expand on click)

**Affected Dictionaries**

Oxford Advanced Learner's Dictionary 1.0a and OALD10 are affected, both are in MDX format

**Download link:**
[delete]

**Expected behavior**
The mentioned dictionary should work properly as it was working with prior versions.

**Screenshots**
6.5.2
![6 5 2](https://github.com/xiaoyifang/goldendict-ng/assets/95992906/87bf13f4-82f9-4e5b-8820-40507b8c6440)

6.4.3
![6 4 3](https://github.com/xiaoyifang/goldendict-ng/assets/95992906/a0fa9c04-5517-4328-9352-8c49a654b1b5)

(The mouse loading icon is stuck in 6.5.2 even though task manager is not showing any increased consumption)

**OS and software versions**

Goldendict 23.06.01
windows winnt 10.0.22621 Qt 6.4.3 x86_64-little_endian-llp64
Visual C++ Compiler: 192930148
Flags: USE_XAPIAN  MAKE_ZIM_SUPPORT USE_ICONV MAKE_CHINESE_CONVERSION_SUPPORT
- OS: [e.g. Windows10,  Fedora37]

AND

Goldendict-ng 23.07.25-alpha.20230807.fd42f877
Qt 6.5.2 Visual C++ Compiler 192930151 windows winnt 10.0.22621 x86_64-little_endian-llp64
Flags:USE_XAPIAN MAKE_ZIM_SUPPORT USE_ICONV MAKE_CHINESE_CONVERSION_SUPPORT

(Although that issue is present in all 6.5.X versions, I tried downloading the latest alpha build to see if it was fixed.)

**Additional context**
This happens when Wiktionary is added, but when removed everything works fine. 

Windows:

No dmp in the crash folder.

**Comment by xiaoyifang** [comment]
应该是词典制作的问题。估计js冲突无效了，F12检查下console面板。

**Comment by PrinceOC912** [comment]
I am not sure what I am supposed to do, but as I mentioned above this happens when Wiktionary is added to dictionary list when it is removed the dictionary works fine. This is the js file of said dictionary.
https://www.swisstransfer.com/d/a7d12b9c-a53a-4cd3-a9c7-de6f79cb644f

**Comment by damoncro** [comment]
Same issue found on NHK日本語発音アクセント辞書. No such issue on goldendict.

**Comment by xiaoyifang** [comment]
> . No such issue on goldendict.

provide a link if necessary

**Comment by xiaoyifang** [comment]
I think all the above issues are related with javascript .
Here is a document illustrated about how to pinpoint the javascript issue.
https://xiaoyifang.github.io/goldendict-ng/howto/how%20to%20debug%20dictionary%20js/
