### ISSUE TITLE
Compile link error, can not find lzma

### ISSUE THREAD

**Issue by binglius** [xiaoyifang/goldendict-ng#1058]
**描述 bug**
在编译最后一步提示找不到 lzma，其实 系统中 xz-utils 已经安装。

esample /usr/lib64/libQt5Svg.so /usr/lib64/libQt5WebEngineWidgets.so /usr/lib64/libQt5PrintSupport.so /usr/lib64/libQt5Widgets.so /usr/lib64/libQt5WebEngineCore.so /usr/lib64/libQt5Quick.so /usr/lib64/libQt5Multimedia.so /usr/lib64/libQt5X11Extras.so /usr/lib64/libQt5Gui.so /usr/lib64/libQt5Xml.so /usr/lib64/libQt5QmlModels.so /usr/lib64/libQt5WebChannel.so /usr/lib64/libQt5Qml.so /usr/lib64/libQt5Network.so /usr/lib64/libQt5Concurrent.so /usr/lib64/libQt5TextToSpeech.so /usr/lib64/libQt5Core.so -lGL -pthread
/usr/lib/gcc/x86_64-pc-linux-gnu/13/../../../../x86_64-pc-linux-gnu/bin/ld: build/decompress.o: undefined reference to symbol 'lzma_lzma_preset@@XZ_5.0'
/usr/lib/gcc/x86_64-pc-linux-gnu/13/../../../../x86_64-pc-linux-gnu/bin/ld: /usr/lib64/liblzma.so.5: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make: *** [Makefile:895: goldendict] Error 1

解决方案，Makefile 中 LIBS 中加入 "-llzma"

LIBS          = $(SUBLIBS) -lxapian -lbz2 -llzo2 -lz -lX11 -lXtst -leb -lvorbisfile -lvorbis -logg -lhunspell-1.7 -lavutil -lavformat -lavcodec -lswresample /usr/lib64/libQt5Svg.so /usr/lib64/libQt5WebEngineWidgets.so /usr/lib64/libQt5PrintSupport.so /usr/lib64/libQt5Widgets.so /usr/lib64/libQt5WebEngineCore.so /usr/lib64/libQt5Quick.so /usr/lib64/libQt5Multimedia.so /usr/lib64/libQt5X11Extras.so /usr/lib64/libQt5Gui.so /usr/lib64/libQt5Xml.so /usr/lib64/libQt5QmlModels.so /usr/lib64/libQt5WebChannel.so /usr/lib64/libQt5Qml.so /usr/lib64/libQt5Network.so /usr/lib64/libQt5Concurrent.so /usr/lib64/libQt5TextToSpeech.so /usr/lib64/libQt5Core.so -lGL -pthread

改成

LIBS          = $(SUBLIBS) -llzma -lxapian -lbz2 -llzo2 -lz -lX11 -lXtst -leb -lvorbisfile -lvorbis -logg -lhunspell-1.7 -lavutil -lavformat -lavcodec -lswresample /usr/lib64/libQt5Svg.so /usr/lib64/libQt5WebEngineWidgets.so /usr/lib64/libQt5PrintSupport.so /usr/lib64/libQt5Widgets.so /usr/lib64/libQt5WebEngineCore.so /usr/lib64/libQt5Quick.so /usr/lib64/libQt5Multimedia.so /usr/lib64/libQt5X11Extras.so /usr/lib64/libQt5Gui.so /usr/lib64/libQt5Xml.so /usr/lib64/libQt5QmlModels.so /usr/lib64/libQt5WebChannel.so /usr/lib64/libQt5Qml.so /usr/lib64/libQt5Network.so /usr/lib64/libQt5Concurrent.so /usr/lib64/libQt5TextToSpeech.so /usr/lib64/libQt5Core.so -lGL -pthread

**Comment by atauzki** [comment]
It maybe the bug of goldebdict.pro without `CONFIG+=zim_support`.

**Comment by xiaoyifang** [comment]
https://github.com/xiaoyifang/goldendict-ng/pull/1059

**Comment by binglius** [comment]
> @binglius 编译的命令发一下。

自己写的ebuild， 但是他的编译过程和手动编译一致，如下：

qmake5 -o Makefile goldendict.pro
make

**Comment by xiaoyifang** [comment]
用最新的代码试下staged分支

**Comment by xiaoyifang** [comment]
should be fixed in the latest code

**Comment by binglius** [comment]
谢谢，今天我测试了下，确实已经修复了。
