### ISSUE TITLE
After the mouse clicks the candidate word in the drop-down box, it cannot be automatically queried

### ISSUE THREAD

**Issue by susanooxyz** [xiaoyifang/goldendict-ng#1062]
**描述 bug**
用鼠标点选下拉框中的候选单词后不能自动查询，还需要按回车键才会查词。

我用的是稳定版
6.4.3-GoldenDict.exe_windows-2022_20230501这个版本没上述问题。
好像从6.5.1-GoldenDict.exe_windows-2019_20230722开始出现上述问题。现在最新的alpha版本也是如此。

不知道是bug还是feature🤔

**Comment by xiaoyifang** [comment]
像是个bug

**Comment by xiaoyifang** [comment]
https://stackoverflow.com/questions/47102602/qcompleteractivated-disconnected-after-losing-and-gaining-focus#:~:text=The%20interesting%20part,%2C%200)%3B%0A%7D


https://stackoverflow.com/a/47110753


查询的输入框失去焦点后，  相关的事件被重置了。
