### ISSUE TITLE
The effect of sliding up and down on the word explanation page on macOS is not good.

### ISSUE THREAD

**Issue by Andrewlearntocode** [xiaoyifang/goldendict-ng#1063]
在 macOS 上，上下滑动单词解释时，有两个体验比较不好的地方：

1）用触控板快速上下滑动时，解释页面不能马上随双指停住而停下，往往会有一段较大的滑动惯性。视觉上看起来流畅，但实际查词体验不太好，页面定位不容易随滑随停。

2）当解释页面滑动到顶/底部时，会出现橡皮筋回弹的效果，回弹效果一般需耗时3秒才会完全静止，这个体验也不太好，不知道能不能提供手动禁止的选项。

**Comment by xiaoyifang** [comment]
https://bugreports.qt.io/browse/QTBUG-67716

https://github.com/qutebrowser/qutebrowser/issues/7810#issuecomment-1662960610

**Comment by xiaoyifang** [comment]
duplicate #180
