### ISSUE TITLE
Qt4 support feasible?

### ISSUE THREAD

**Issue by barracuda156** [xiaoyifang/goldendict-ng#1083]
Not that I have much hope here, but just in case :)

Darwin PowerPC has no Qt5 (and even if early versions could be fixed, they will be very outdated anyway) and obviously no Qt6. Qt4 works beautifully though.

**Comment by xiaoyifang** [comment]
In case you have a wrong hope,
Qt4 will not be supported.    this fork rely on webengine which qt4 does not has.

**Comment by barracuda156** [comment]
@xiaoyifang Thank you for a clarification! Got it.
