### ISSUE TITLE
There seems to be a problem with the new welcome page display

### ISSUE THREAD

**Issue by czz404** [xiaoyifang/goldendict-ng#1088]
**描述bug**
新欢迎页“论坛”的链接未能正常显示

**相关的截图**
<img width="913" alt="欢迎页" src="https://github.com/xiaoyifang/goldendict-ng/assets/64689594/f2b3d9d5-4558-4b75-8de4-b7ef646677d3">

**系统和软件的版本**
- OS: Windows 11 22H2
- Version：GoldenDict-ng-v23.07.25-alpha.230826.748a644c

**Comment by xiaoyifang** [comment]
Thanks for reporting

**Comment by xiaoyifang** [comment]
修改了
