### ISSUE TITLE
Doesn't delete index files of removed dictionaries

### ISSUE THREAD

**Issue by GD-fix** [xiaoyifang/goldendict-ng#1113]
**Describe the bug**
In classical releases (/goldendict/goldendict) after removing dictionaries from folder of path to search for the dictionary files their indexes are deleted. In GoldenDict-ng v23.07.23.1-GreatHeat.230731.a08d3adb 6.5.2-... or from [system repository](https://software.opensuse.org/package/goldendict-ng?search_term=goldendict) their index files doesn't delete.

**To Reproduce**
I spent one day to find and delete obsolete index files (of a ~ hundred GB summary size) after a hundred of dictionaries update...

**Expected behavior**
I think, it may be the feature in preferences (remove or not), but without such choice it's the bug.

**OS and software versions**
- OS: OpenSUSE Tumbleweed
- Version up to date

**Comment by xiaoyifang** [comment]
Remove invalid index has already existed in the original version for a time.

and now there is an option to turn it off
![image](https://github.com/xiaoyifang/goldendict-ng/assets/105986/226deafc-cf98-41c1-acb8-999cc3447283)

**Comment by xiaoyifang** [comment]
https://github.com/xiaoyifang/goldendict-ng/pull/1071

**Comment by GD-fix** [comment]
I'm not sure, that I can compile (original version doesn't compile on my PC long ago). 
On release version there is absent:
![Screenshot_advanced_pref](https://github.com/xiaoyifang/goldendict-ng/assets/21008593/2f6497cb-7219-4165-80aa-3cc98f1f2444)
When it planned to be in release version?

**Comment by xiaoyifang** [comment]
> When it planned to be in release version?

Currently it is in staged branch,the next scheduled date for release is about one week to come.

**Comment by GD-fix** [comment]
OK. I'll try to download and test after a week.

**Comment by xiaoyifang** [comment]
released

**Comment by GD-fix** [comment]
I have downloaded and it works.
