### ISSUE TITLE
Dictionary headwords window bug

### ISSUE THREAD

**Issue by GD-fix** [xiaoyifang/goldendict-ng#1114]
**Describe the bug**
There is incorrect display of dictionary headwords in the window.
Such bug is absent in classical GoldenDict...

**To Reproduce**
1. Right click on the dictionary button on the panel.
2. Click on 'Dictionary headwords' of context menu.
3. See headwords_screenshot_1.
4. Type some letters and delete they.
5. See headwords_screenshot_2.
6. Right click on the another dictionary button on the panel.
7. Click on 'Dictionary headwords' of context menu.
8. See headwords_screenshot_3.

**Affected Dictionaries**
I had test with [ZIM dictionaries](https://wiki.kiwix.org/wiki/Content_in_all_languages/en).

**Expected behavior**
With empty filter there must be equality of filtered and total unique headwords.
And there must not be headwords from previous dictionaries...

**Screenshots**
![headwords_screenshot_1](https://github.com/xiaoyifang/goldendict-ng/assets/21008593/67ad73df-9eb1-44ef-9a56-98d1e3b3c324)
![headwords_screenshot_2](https://github.com/xiaoyifang/goldendict-ng/assets/21008593/883840c1-4293-4f9a-9990-d1c671f1852d)
![headwords_screenshot_3](https://github.com/xiaoyifang/goldendict-ng/assets/21008593/1f3eea8c-4b45-47de-99e7-19fa4bbc597a)

**OS and software versions**
- OS: OpenSUSE Tumbleweed
- Version up to date

**Comment by xiaoyifang** [comment]
You mean the headwords got mixed together?

**Comment by xiaoyifang** [comment]
confirmed ,  this is a bug ,thanks for reporting.

**Comment by GD-fix** [comment]
Not only when mixed from few dictionaries headwords, but the number of filtered headwords is wrong at all (when only one dictionary headwords window was opened too).

**Comment by xiaoyifang** [comment]
> ed headwords is wrong at all (when only one dictionary headwords window was opened too).

As the headwords are loaded in batch .   when first loaded ,only part of the headwords have been loaded,  so the filtered number changed.
