### ISSUE TITLE
Cannot export to Anki 2.1.66 now

### ISSUE THREAD

**Issue by HQYang1979** [xiaoyifang/goldendict-ng#1115]
Windows 11

Anki 2.1.66

Goldendict 23.07.25-alpha.20230902.eb238c00

显示：Anki发送失败

**Comment by xiaoyifang** [comment]
怎么配置的，
https://xiaoyifang.github.io/goldendict-ng/topic_anki/

**Comment by HQYang1979** [comment]
> 怎么配置的， https://xiaoyifang.github.io/goldendict-ng/topic_anki/

配置没有问题，一致都是可用，就是突然今天用不了了。

**Comment by HQYang1979** [comment]
![image](https://github.com/xiaoyifang/goldendict-ng/assets/74698160/5862ebac-3e82-42f6-8364-d16bb158ac3b)

**Comment by xiaoyifang** [comment]
如果之前可以用，gd-ng没有升级新版本的话，是不是anki的本地服务关掉了？

**Comment by HQYang1979** [comment]
> 如果之前可以用，gd-ng没有升级新版本的话，是不是anki的本地服务关掉了？

anki connect正常

**Comment by xiaoyifang** [comment]
goldendict.exe 后面添加    --log-to-file   ,然后启动，复现问题后，查看下  gd_log.txt里面的信息，里面有完整的失败原因。

**Comment by HQYang1979** [comment]
删除了旧版goldendict，然后重新配置一下可以了。多谢你无私奉献！帮我了大忙

**Comment by xiaoyifang** [comment]
估计是旧版的gd退出的时候，把配置文件中的一些选项的值重新覆盖了
