### ISSUE TITLE
If there is a networked dictionary, the content will not be displayed until the networked dictionary returns the result

### ISSUE THREAD

**Issue by OvidioLee** [xiaoyifang/goldendict-ng#1120]
![Snipaste_2023-09-04_09-48-51](https://github.com/xiaoyifang/goldendict-ng/assets/19760900/e95b572f-bf80-452a-a9e0-045d1d6eadda)

如果有联网词典,必须等联网词典返回结果后,才会显示内容

而不是,先显示离线的,再显示联网的

**Comment by xiaoyifang** [comment]
这个程序词典你是放到组内第一个吗？

**Comment by OvidioLee** [comment]
> 这个程序词典你是放到组内第一个吗？

我又试了好几次,好像没这个问题了......

**Comment by OvidioLee** [comment]
> 这个程序词典你是放到组内第一个吗？

又出现了.......

程序是组内最下面的.

搜索的时候会卡一下,然后在显示,如果组内没联网词典就不会卡.

**Comment by xiaoyifang** [comment]
返回词典数据的时候，应该已经是按照顺序，从上到下返回的了。  猜测页面渲染是  webengine独立做的。

如果用的是qt5.15的版本，可以尝试下qt6的版本。  

暂时没办法改了。
