### ISSUE TITLE
Tibetan stacked characters are displayed incorrectly in the search bar

### ISSUE THREAD

**Issue by jerefrer** [xiaoyifang/goldendict-ng#1124]
In Tibetan some letters are formed by stacking several letters or modifiers on top of one another. In Unicode it results in having multiple characters in a sequence that are in fact displayed as one visual character.

Everywhere in the app the characters are displayed just fine (especially since I can select a proper Tibetan Unicode font in the settings), but in the search bar the stacked letters are displayed as separate characters instead of being merged into one.

You can see in the screenshot below how it is displayed in the search bar, and below how it should be displayed:

![Capture](https://github.com/xiaoyifang/goldendict-ng/assets/140954/d64b3156-4596-43e9-97cb-edaa4fc10448)

I thought that I could fix the problem by going in the settings and specifying as "Monospace font" one that supports Tibetan nicely, but even if I use "Noto Mono" it doesn't fix the problem. In fact I'm not sure to understand where exactly this monospace font is used in the app since when I change it nothing seems to move.

One possible fix would be then to have the search bar actually use the monospace font defined in the settings so that one could use Noto or any other that supports Tibetan fully.

Thanks for your efforts in reviving this amazing tool that has been invaluable in our studies in a retreat environment without access to the Internet :)
We've been using the old GoldenDict through the years and it worked well with Tibetan in everywhere. We didn't have all the goodies of the dark mode and more customization but at least it was usable. Without support for this I think that we can't really move to this new version yet so we'd be extremely grateful if you could provide a fix for this.

Cheers,
j.

**To Reproduce**
1. Just type some Tibetan in the search bar: འགྲོ་ཀུན་ for instance.
2. If it it displayed as you can see in the upper part of the screenshot, then something is wrong. If it is like the lower part, then it's working.

**OS and software versions**

Goldendict-ng 23.07.23.1-GreatHeat.20230731.a08d3adb
Qt 5.15.2 Visual C++ Compiler 192930151 windows winnt 10.0.19045 x86_64-little_endian-llp64
Flags:USE_XAPIAN MAKE_ZIM_SUPPORT USE_ICONV MAKE_CHINESE_CONVERSION_SUPPORT

**Comment by xiaoyifang** [comment]
![image](https://github.com/xiaoyifang/goldendict-ng/assets/105986/7a07b259-0f03-4358-b8f0-5d3e105861ee)


can not reproduced with qt6 version .   Can you try the goldendict release built with qt6.5.2  ?

**Comment by jerefrer** [comment]
Thanks for the quick reply.

Unfortunately the qt6 version doesn't work on my machine. I can see the splash screen for an instant, then it hides in the tray bar, and when I reveal it I see a white screen then it crashes.

I don't know much about qt6 and its requirements but I somewhat figured I couldn't use it on this machine that is quite old now (Thinkpad W520 from around 2012) when I tried to use the qt6 version of Anki that, while actually running, was using a tremendous amount of resources for seemingly such a tiny app.

Here's the dump just in case.
[4e23c7c2-afad-46f9-913f-727ad76af584.zip](https://github.com/xiaoyifang/goldendict-ng/files/12519852/4e23c7c2-afad-46f9-913f-727ad76af584.zip)

**Comment by jerefrer** [comment]
Also I mentioned that it worked on the "old" GoldenDict without specifying which one.

I just tested their 1.5.0 version and it has the same issue with the Tibetan in the search bar, using the same exact font it seems.
The version 1.0.1 though is working well, as shown below.

![image](https://github.com/xiaoyifang/goldendict-ng/assets/140954/5621a85f-1487-44be-8a84-3ef486b0708c)

**Comment by xiaoyifang** [comment]
This is the QLineEdit control ,  I can not reproduce the issue on my Windows.
About the crash dump ,  what's the exact gd-ng version? the download link.

**Comment by jerefrer** [comment]
That guy : https://github.com/xiaoyifang/goldendict-ng/releases/download/v23.07.23.1-GreatHeat.a08d3adb/6.5.2-GoldenDict-ng-Installer.exe

**Comment by xiaoyifang** [comment]
> That guy : https://github.com/xiaoyifang/goldendict-ng/releases/download/v23.07.23.1-GreatHeat.a08d3adb/6.5.2-GoldenDict-ng-Installer.exe

Not too much useful information 
![image](https://github.com/xiaoyifang/goldendict-ng/assets/105986/e261a580-c95b-4fc5-bc64-c7b5ed63f0fb)


Can you try to disable the fulltext option and try again?
You can disable through the qt5 version gd-ng and then open gd-ng built with qt6

**Comment by jerefrer** [comment]
I turned off the fulltext search option in the qt5 version then installed the qt6 version and when launching it crashes in the same way.
Here's the dump.

[2741569b-557c-43ca-a6a3-654ac8f8e01f.zip](https://github.com/xiaoyifang/goldendict-ng/files/12534529/2741569b-557c-43ca-a6a3-654ac8f8e01f.zip)

Anyhow I'm pretty much ok with sticking with qt5 since I kind of gave up running anything qt6 on this machine.

Therefore I agree with your idea of adding an option to change the font for the appearance interface. We can already change all fonts in the app except this one, why not enable users to change all of them? That would allow for maximum flexibility in the eventuality that there would be such cases with other complex languages.

**Comment by jerefrer** [comment]
Alright !

![image](https://github.com/xiaoyifang/goldendict-ng/assets/140954/be97fc40-ba85-48a0-add3-475fdd93545e)

Works perfectly now, and that's quite nice to be able to choose one's interface font as well.

The only thing was that I had to exit and restart the app for it to fully take effect. At first the font would indeed change but the problem of separate stacked characters still remained for some reason. You might want to add a popup saying that the interface font needs the app to be restarted.

Thank you so much for doing all this work for just my little edge case scenario, I'm touched by your patience, kindness and dedication :)

**Comment by xiaoyifang** [comment]
> You might want to add a popup saying that the interface font needs the app to be restarted.

added
