### ISSUE TITLE
Non correct filtered headwords number

### ISSUE THREAD

**Issue by GD-fix** [xiaoyifang/goldendict-ng#1131]
**Describe the bug**
Initially (i.e. with empty filter) in Dictionary headwords window there is non correct number (0) of filtered those (see the first and the second screenshots).
After applying the non empty and then the empty again filter the number changes: for some dictionaries it is non correct (i.e. non equal to the Unique headwords total number) still (see the third screenshot: may be it's because of ignored due to the long size headwords?) and for other dictionaries it becomes correct (see the forth screenshot).

**To Reproduce**
1. Go to 'Dictionaries panel'
2. Click right on a dictionary
3. Scroll down to the end of headwords list
5. Print and then delete some letters in filter string
6. Scroll down to the end of headwords list
7. Compare

**Expected behavior**
The equal numbers of Unique headwords total and filtered in case of empty filter.

**Screenshots**
![Screenshot_headwords_initial](https://github.com/xiaoyifang/goldendict-ng/assets/21008593/f5d2cf0a-fe72-4fe5-b048-be613fb28333)
![Screenshot_initial2](https://github.com/xiaoyifang/goldendict-ng/assets/21008593/7da18bdd-8879-41ff-9ee4-b22b010c8bd2)
![Screenshot_headwords_noncorrect](https://github.com/xiaoyifang/goldendict-ng/assets/21008593/44568428-23a0-40d4-85b0-de80aaa62dd4)
![Screenshot_headwords_correct](https://github.com/xiaoyifang/goldendict-ng/assets/21008593/bb702c4e-ba1f-46d0-927c-2380c59e6a4c)

**OS and software versions**
- OS: OpenSUSE Tumbleweed
- Version up to date

**Comment by GD-fix** [comment]
P. S. ArchWiki doesn't have skipped during indexing headwords...

**Comment by GD-fix** [comment]
In current pre-release all the same...

**Comment by GD-fix** [comment]
In current pre-release all the same...

**Comment by GD-fix** [comment]
In current pre-release all the same...

And additional question: the fact that in ZIM dictionaries after applying the non empty and then the empty again filter the numbers of Unique headwords total and filtered aren't equal still is due to [this](https://github.com/xiaoyifang/goldendict-ng/issues/1185#issuecomment-1741783408) (in case when abbreviated headwords are the same)?

**Comment by GD-fix** [comment]
In current release all the same...

**Comment by xiaoyifang** [comment]
I'll let you know when I finished this,

And I do not think this is a high priority issue.

**Comment by GD-fix** [comment]
Yes, of course, the impossibility of adding to GD-ng any dictionary at all is a [much higher priority issue](https://github.com/xiaoyifang/goldendict-ng/issues/1327). But it also still not solved...

**Comment by GD-fix** [comment]
And what is the problem to correct the code, that it will be initially (on headwords window opening) the same as after filter applying?

**Comment by GD-fix** [comment]
The problem was solved.
