### ISSUE TITLE
Can't search a word with Keyboard key "Enter"

### ISSUE THREAD

**Issue by BEST8OY** [xiaoyifang/goldendict-ng#1132]
**Describe the bug**

**To Reproduce**
1. Search half of a word
![image](https://github.com/xiaoyifang/goldendict-ng/assets/70865987/8975580e-22ec-42d8-a35a-30d325660ae5)
2. Move to one of the words with keyboard keys
3. Hit enter button
4. And you see it's not working as it should
5. But you should know if you click on one of the words like provided in the screenshot with mouse (touchpad) it works as it should

**OS and software versions**

Goldendict-ng 23.09.08-WhiteDew.20230907.216505c9
Qt 6.5.2 Visual C++ Compiler 192930151 windows winnt 10.0.22621 x86_64-little_endian-llp64
Flags:USE_XAPIAN MAKE_ZIM_SUPPORT USE_ICONV MAKE_CHINESE_CONVERSION_SUPPORT
**Additional context**

**Comment by dbedrenko** [comment]
I was just about to file the same bug myself! On top of this, in the original GoldenDict you could use Tab to cycle through the word suggestions, which was very handy, rather than having to move your hand to the directional keys. I wonder if this behaviour could be maintained too?

**Comment by xiaoyifang** [comment]
About the Tab navigtion ,   seems a little difficult to fix.  I have changed the original implementation to qcompleter widget to show the popup.  the Tab action seems does not support yet.

**Comment by BEST8OY** [comment]
@xiaoyifang 
The issue still exists in popup menu.

**Comment by BEST8OY** [comment]
There is another issue with Enter
Reproduce 
1- Type part of a word in search box 
2- Move into results in drop-down with down key
3- Get back to search box with up key
4- Press Enter and you'll see it's not functioning.

**Comment by xiaoyifang** [comment]
confirmed

**Comment by BEST8OY** [comment]
@xiaoyifang 
There are some other issues.
First:
1- Type part of a word in search box
2- Move into results in drop-down with down key
3- Move within the typed word in search box with left arrow key
4- Try to get back to search box with up key
5- You'll see you can't get back into the search box 
Second:
This one somehow is my weirdness :)
1- Type something in search box
2- Select the **whole** of whatever is typed with touchpad or Ctrl+A
3- Try to empty it with Ctrl + Backspace
4- Instead of erasing it, it goes to the start of whatever is typed
I said weirdness because no one try to empty a selected line with Ctrl + Backspace you just press Backspace but it's just a bad habit of mine and I think a search box should not behave like this.
But I must say if you select some of the typed word, Ctrl + Backspace erase that part.

**Comment by xiaoyifang** [comment]
> @xiaoyifang There are some other issues. First: 1- Type part of a word in search box 2- Move into results in drop-down with down key 3- Move within the typed word in search box with left arrow key 4- Try to get back to search box with up key 5- You'll see you can't get back into the search box Second: This one somehow is my weirdness :) 1- Type something in search box 2- Select the **whole** of whatever is typed with touchpad or Ctrl+A 3- Try to empty it with Ctrl + Backspace 4- Instead of erasing it, it goes to the start of whatever is typed I said weirdness because no one try to empty a selected line with Ctrl + Backspace you just press Backspace but it's just a bad habit of mine and I think a search box should not behave like this. But I must say if you select some of the typed word, Ctrl + Backspace erase that part.

try the new patch PR, seems fixed.

**Comment by BEST8OY** [comment]
> try the new patch PR, seems fixed.

Yes, the first one is fixed but not the second one.

Explanation:
In the whole video I'm selecting the typed text with Ctrl + A and erase it with Ctrl + Backspace 
https://github.com/xiaoyifang/goldendict-ng/assets/70865987/1ccdf6d6-e471-4b9c-ad24-1330add75848

**Comment by xiaoyifang** [comment]
![image](https://github.com/xiaoyifang/goldendict-ng/assets/105986/8e233bae-4ee0-4193-8a8b-e81ba1838aa6)

I think the Ctrl+Backspace is a qt bug. it can reproduced in other QLineEdit controls.

- select the text from left to right ,then press `Ctrl+Backpace` , cursor moved to the left ,no text is deleted.

- select the text from right to left ,then press `Ctrl+Backspace`,cursor moved to the left (it already at the left ,so no move), text is deleted.

**Comment by BEST8OY** [comment]
Well, the search box is working great now.
So, I close the issue.
