### ISSUE TITLE
Unable to search words by pressing enter

### ISSUE THREAD

**Issue by czz404** [xiaoyifang/goldendict-ng#1136]
**描述 bug**
GoldenDict-ng-v23.09.10-WhiteDew.230910.08816a0c 按enter查词功能仍失效

**系统和软件的版本**
系统 win11 22H2
Goldendict-ng 23.09.10-WhiteDew.20230910.08816a0c
Qt 6.5.2 Visual C++ Compiler 192930151 windows winnt 10.0.22621 x86_64-little_endian-llp64
Flags:USE_XAPIAN MAKE_ZIM_SUPPORT USE_ICONV MAKE_CHINESE_CONVERSION_SUPPORT

**Comment by xiaoyifang** [comment]
很抱歉，用最新的版本试下，我重新发布了一份

**Comment by czz404** [comment]
新版解决了，感谢大佬修复
