### ISSUE TITLE
Need to scroll to see all words in search box

### ISSUE THREAD

**Issue by BEST8OY** [xiaoyifang/goldendict-ng#1139]
**Describe the bug**
Need to scroll to see all words in the search box

**To Reproduce**

https://github.com/xiaoyifang/goldendict-ng/assets/70865987/1a12f858-9d39-4dbf-97e0-3ae4ebbc4045

**OS and software versions**
Goldendict-ng 23.09.10-WhiteDew.20230910.54c8bd56
Qt 6.5.2 Visual C++ Compiler 192930151 windows winnt 10.0.22621 x86_64-little_endian-llp64
Flags:USE_XAPIAN MAKE_ZIM_SUPPORT USE_ICONV MAKE_CHINESE_CONVERSION_SUPPORT

**Comment by xiaoyifang** [comment]
Do you mean the dropdown list ,the dropdown windows is limited to about 16 items. 
If you want to reduce the hitted items , more words need to be typed.

**Comment by BEST8OY** [comment]
> Do you mean the dropdown list ,the dropdown windows is limited to about 16 items. If you want to reduce the hitted items , more words need to be typed.

No
What I'm trying to show is that when I'm typing a word the scroll bar in dropdown menu should be in top no matter what but as you can see in this video, when I write bac, the scroll bar is in the middle and when I write back, the scroll bar is near to uppermost situation but still some of word are not shown and need me to scroll to top of the dropdown list to see the first results.

https://github.com/xiaoyifang/goldendict-ng/assets/70865987/2806647e-7b5e-4d48-9b1b-08a1086107ad

**Comment by xiaoyifang** [comment]
I got your idea now.

I use QCompleter in the suggestion word list.   Currently I do not think I can do any further.   Will inverstigate later.
