### ISSUE TITLE
unexpected exit

### ISSUE THREAD

**Issue by yshumy** [xiaoyifang/goldendict-ng#1144]
-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               GoldenDict [31707]
Path:                  /Applications/GoldenDict.app/Contents/MacOS/GoldenDict
Identifier:            org.xiaoyifang
Version:               23.09 (???)
Code Type:             X86-64 (Translated)
Parent Process:        launchd [1]
User ID:               501

Date/Time:             2023-09-15 01:50:13.9357 +0800
OS Version:            macOS 12.6.8 (21G725)
Report Version:        12
Anonymous UUID:        ACE98172-167E-A198-0C40-13044CC98919

Time Awake Since Boot: 990000 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    Namespace DYLD, Code 1 Library missing
Library not loaded: '@loader_path/../../../../opt/highway/lib/libhwy.1.dylib'
Referenced from: '/Applications/GoldenDict.app/Contents/Frameworks/libjxl.0.8.dylib'
Reason: tried: '' (no such file), '' (no such file), '' (no such file)
(terminated at launch; ignore backtrace)

Thread 0 Crashed:
0   Rosetta Runtime Routines	       0x10131b940 ???
1   <translation info unavailable>	       0x10136eb7c ???
2   dyld                          	       0x2011aaa72 abort_with_payload_wrapper_internal + 80
3   dyld                          	       0x2011aaaa4 abort_with_payload + 9
4   dyld                          	       0x201158699 dyld4::halt(char const*) + 615
5   dyld                          	       0x2011545b5 dyld4::prepare(dyld4::APIs&, dyld3::MachOAnalyzer const*) + 3995
6   dyld                          	       0x2011534e4 start + 388

Thread 1:: com.apple.rosetta.exceptionserver
0   runtime                       	    0x7ff7ffefc944 0x7ff7ffef8000 + 18756
1   runtime                       	    0x7ff7fff0a3e0 0x7ff7ffef8000 + 74720
2   runtime                       	    0x7ff7fff0be58 0x7ff7ffef8000 + 81496

Thread 0 crashed with ARM Thread State (64-bit):
    x0: 0x0000000000000006   x1: 0x0000000000000001   x2: 0x00000003059b0090   x3: 0x000000000000008e
    x4: 0x00000003059afc90   x5: 0x0000000000000000   x6: 0x00007ff80f3e9000   x7: 0x000000208e29f7cc
    x8: 0x00000003059afc90   x9: 0x0000000000000000  x10: 0x000000000000008e  x11: 0x00000003059b00dc
   x12: 0x000000000000008e  x13: 0x00000003059b0090  x14: 0x0000000000000001  x15: 0x0000000000000006
   x16: 0x0000000000000209  x17: 0x0000000000000000  x18: 0x8000000109384b70  x19: 0x0000000101311000
   x20: 0x00000000000007ff  x21: 0x0000000109389fa0  x22: 0xffffffffffffffff  x23: 0x000000010131b914
   x24: 0x00000002011aaa72  x25: 0x000000010131b1f4  x26: 0x000000010136e120  x27: 0x0000000000000000
   x28: 0x000000020119498e   fp: 0x000000002c000000   lr: 0x000000010136eb7c
    sp: 0x0000000109384b70   pc: 0x000000010131b940 cpsr: 0x80001000
   far: 0x000000010136e000  esr: 0x56000080  Address size fault

Binary Images:
               0x0 - 0xffffffffffffffff ??? (*) <00000000-0000-0000-0000-000000000000> ???
       0x20114e000 -        0x2011b9fff dyld (*) <baab2c6d-3797-3264-8595-a591561979de> /usr/lib/dyld
    0x7ff7ffef8000 -     0x7ff7fff27fff runtime (*) <87e9f97a-a2d1-31c7-946a-ee19bf6083e6> /usr/libexec/rosetta/runtime

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 17
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=1.1G resident=0K(0%) swapped_out_or_unallocated=1.1G(100%)
Writable regions: Total=168.0M written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=168.0M(100%)

                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
Rosetta Arena                     4096K        2 
Rosetta Generic                    820K      202 
Rosetta IndirectBranch              32K        1 
Rosetta JIT                      128.0M        1 
Rosetta Return Stack                20K        2 
Rosetta Thread Context              20K        2 
Stack                             8176K        1 
Stack Guard                       56.0M        1 
VM_ALLOCATE                       13.3M        6 
VM_ALLOCATE (reserved)             756K       59         reserved VM address space (unallocated)
__DATA                            36.4M      301 
__DATA_CONST                      12.5M      186 
__DATA_DIRTY                       485K       85 
__FONT_DATA                          4K        1 
__LINKEDIT                       719.2M       70 
__OBJC_RO                         82.8M        1 
__OBJC_RW                         3200K        1 
__TEXT                           435.7M      319 
__UNICODE                          592K        1 
dyld private memory               1024K        1 
mapped file                        5.5G      496 
===========                     =======  ======= 
TOTAL                              7.0G     1739 
TOTAL, minus reserved VM space     7.0G     1739 

-----------
Full Report
-----------

{"app_name":"GoldenDict","timestamp":"2023-09-15 01:50:14.00 +0800","app_version":"23.09","slice_uuid":"32f8f910-34bd-34c6-ba01-8e2b98e1d602","build_version":"","platform":1,"bundleID":"org.xiaoyifang","share_with_app_devs":1,"is_first_party":0,"bug_type":"309","os_version":"macOS 12.6.8 (21G725)","incident_id":"48A66445-BDEF-4B52-903C-46E05819B91C","name":"GoldenDict"}
{
  "uptime" : 990000,
  "procLaunch" : "2023-09-15 01:50:13.8327 +0800",
  "procRole" : "Default",
  "version" : 2,
  "userID" : 501,
  "deployVersion" : 210,
  "modelCode" : "Macmini9,1",
  "procStartAbsTime" : 23960561283768,
  "coalitionID" : 88954,
  "osVersion" : {
    "train" : "macOS 12.6.8",
    "build" : "21G725",
    "releaseType" : "User"
  },
  "captureTime" : "2023-09-15 01:50:13.9357 +0800",
  "incident" : "48A66445-BDEF-4B52-903C-46E05819B91C",
  "bug_type" : "309",
  "pid" : 31707,
  "procExitAbsTime" : 23960563741791,
  "translated" : true,
  "cpuType" : "X86-64",
  "procName" : "GoldenDict",
  "procPath" : "\/Applications\/GoldenDict.app\/Contents\/MacOS\/GoldenDict",
  "bundleInfo" : {"CFBundleShortVersionString":"23.09","CFBundleIdentifier":"org.xiaoyifang"},
  "storeInfo" : {"deviceIdentifierForVendor":"96C16DBB-117C-5E17-9023-77CA1BCD7887","thirdParty":true},
  "parentProc" : "launchd",
  "parentPid" : 1,
  "coalitionName" : "org.xiaoyifang",
  "crashReporterKey" : "ACE98172-167E-A198-0C40-13044CC98919",
  "sip" : "enabled",
  "isCorpse" : 1,
  "exception" : {"codes":"0x0000000000000000, 0x0000000000000000","rawCodes":[0,0],"type":"EXC_CRASH","signal":"SIGABRT"},
  "termination" : {"code":1,"flags":518,"namespace":"DYLD","indicator":"Library missing","details":["(terminated at launch; ignore backtrace)"],"reasons":["Library not loaded: '@loader_path\/..\/..\/..\/..\/opt\/highway\/lib\/libhwy.1.dylib'","Referenced from: '\/Applications\/GoldenDict.app\/Contents\/Frameworks\/libjxl.0.8.dylib'","Reason: tried: '' (no such file), '' (no such file), '' (no such file)"]},
  "extMods" : {"caller":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"system":{"thread_create":0,"thread_set_state":0,"task_for_pid":17},"targeted":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"warnings":0},
  "faultingThread" : 0,
  "threads" : [{"triggered":true,"id":8603787,"threadState":{"x":[{"value":6},{"value":1},{"value":12978946192},{"value":142},{"value":12978945168},{"value":0},{"value":140703384375296},{"value":139824068556},{"value":12978945168},{"value":0},{"value":142},{"value":12978946268},{"value":142},{"value":12978946192},{"value":1},{"value":6},{"value":521},{"value":0},{"value":9223372041304427376},{"value":4314959872},{"value":2047},{"value":4449673120},{"value":18446744073709551615},{"value":4315003156},{"value":8608459378,"symbolLocation":80,"symbol":"abort_with_payload_wrapper_internal"},{"value":4315001332},{"value":4315341088},{"value":0},{"value":8608369038,"symbolLocation":10,"symbol":"__abort_with_payload"}],"flavor":"ARM_THREAD_STATE64","lr":{"value":4315343740},"cpsr":{"value":2147487744},"fp":{"value":738197504},"sp":{"value":4449651568},"esr":{"value":1442840704,"description":" Address size fault"},"pc":{"value":4315003200,"matchesCrashFrame":1},"far":{"value":4315340800}},"frames":[{"imageOffset":4315003200,"region":"Rosetta Runtime Routines","symbolLocation":10560,"imageIndex":0},{"imageOffset":4315343740,"region":"<translation info unavailable>","imageIndex":0},{"imageOffset":379506,"symbol":"abort_with_payload_wrapper_internal","symbolLocation":80,"imageIndex":1},{"imageOffset":379556,"symbol":"abort_with_payload","symbolLocation":9,"imageIndex":1},{"imageOffset":42649,"symbol":"dyld4::halt(char const*)","symbolLocation":615,"imageIndex":1},{"imageOffset":26037,"symbol":"dyld4::prepare(dyld4::APIs&, dyld3::MachOAnalyzer const*)","symbolLocation":3995,"imageIndex":1},{"imageOffset":21732,"symbol":"start","symbolLocation":388,"imageIndex":1}]},{"id":8603789,"name":"com.apple.rosetta.exceptionserver","frames":[{"imageOffset":18756,"imageIndex":2},{"imageOffset":74720,"imageIndex":2},{"imageOffset":81496,"imageIndex":2}]}],
  "usedImages" : [
  {
    "size" : 0,
    "source" : "A",
    "base" : 0,
    "uuid" : "00000000-0000-0000-0000-000000000000"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 8608079872,
    "size" : 442368,
    "uuid" : "baab2c6d-3797-3264-8595-a591561979de",
    "path" : "\/usr\/lib\/dyld",
    "name" : "dyld"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 140703127535616,
    "size" : 196608,
    "uuid" : "87e9f97a-a2d1-31c7-946a-ee19bf6083e6",
    "path" : "\/usr\/libexec\/rosetta\/runtime",
    "name" : "runtime"
  }
],
  "sharedCache" : {
  "base" : 140703184404480,
  "size" : 19331678208,
  "uuid" : "68f46821-a873-3448-a8f6-f06309f3f5bc"
},
  "vmSummary" : "ReadOnly portion of Libraries: Total=1.1G resident=0K(0%) swapped_out_or_unallocated=1.1G(100%)\nWritable regions: Total=168.0M written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=168.0M(100%)\n\n                                VIRTUAL   REGION \nREGION TYPE                        SIZE    COUNT (non-coalesced) \n===========                     =======  ======= \nRosetta Arena                     4096K        2 \nRosetta Generic                    820K      202 \nRosetta IndirectBranch              32K        1 \nRosetta JIT                      128.0M        1 \nRosetta Return Stack                20K        2 \nRosetta Thread Context              20K        2 \nStack                             8176K        1 \nStack Guard                       56.0M        1 \nVM_ALLOCATE                       13.3M        6 \nVM_ALLOCATE (reserved)             756K       59         reserved VM address space (unallocated)\n__DATA                            36.4M      301 \n__DATA_CONST                      12.5M      186 \n__DATA_DIRTY                       485K       85 \n__FONT_DATA                          4K        1 \n__LINKEDIT                       719.2M       70 \n__OBJC_RO                         82.8M        1 \n__OBJC_RW                         3200K        1 \n__TEXT                           435.7M      319 \n__UNICODE                          592K        1 \ndyld private memory               1024K        1 \nmapped file                        5.5G      496 \n===========                     =======  ======= \nTOTAL                              7.0G     1739 \nTOTAL, minus reserved VM space     7.0G     1739 \n",
  "legacyInfo" : {
  "threadTriggered" : {

  }
},
  "trialInfo" : {
  "rollouts" : [
    {
      "rolloutId" : "6297d96be2c9387df974efa4",
      "factorPackIds" : {

      },
      "deploymentId" : 240000014
    },
    {
      "rolloutId" : "607844aa04477260f58a8077",
      "factorPackIds" : {
        "SIRI_MORPHUN_ASSETS" : "6103050cbfe6dc472e1c982a"
      },
      "deploymentId" : 240000066
    }
  ],
  "experiments" : [
    {
      "treatmentId" : "6dd670af-0633-45e4-ae5f-122ae4df02be",
      "experimentId" : "64406ba83deb637ac8a04419",
      "deploymentId" : 900000017
    }
  ]
}
}

Model: Macmini9,1, BootROM 8422.141.2, proc 8:4:4 processors, 16 GB, SMC 
Graphics: Apple M1, Apple M1, Built-In
Display: VX2880-4K-HDU, 3840 x 2160 (2160p/4K UHD 1 - Ultra High Definition), Main, MirrorOff, Online
Memory Module: LPDDR4
AirPort: Wi-Fi, wl0: Mar 23 2022 19:57:59 version 18.60.27.0.7.8.129 FWID 01-570be953
Bluetooth: Version (null), 0 services, 0 devices, 0 incoming serial ports
Network Service: Ethernet, Ethernet, en0
Network Service: Wi-Fi, AirPort, en1
USB Device: USB31Bus
USB Device: USB31Bus
USB Device: USB2.0 Hub
USB Device: USB30Bus
USB Device: Rapoo Gaming Device
USB Device: Keychron K8 Pro
Thunderbolt Bus: Mac mini, Apple Inc.
Thunderbolt Bus: Mac mini, Apple Inc.

**Comment by xiaoyifang** [comment]
libhwy.1.dylib libjxl.0.8.dylib

GoldenDict does not need this dylib ,I guess some third party dependencies have introduced this two more libs.

**Comment by xiaoyifang** [comment]
https://github.com/xiaoyifang/goldendict-ng/releases/tag/v23.09.11-alpha.dcbf0ee6  

用上面的版本试一下

**Comment by xiaoyifang** [comment]
```
GoldenDict.app/Contents/Frameworks/libjxl.0.8.dylib:
	@executable_path/../Frameworks/libjxl.0.8.dylib (compatibility version 0.8.0, current version 0.8.2)
	@loader_path/../../../../opt/highway/lib/libhwy.1.dylib (compatibility version 1.0.0, current version 1.0.7)
	@loader_path/../../../../opt/brotli/lib/libbrotlidec.1.dylib (compatibility version 1.0.0, current version 1.0.9)
	@loader_path/../../../../opt/brotli/lib/libbrotlicommon.1.dylib (compatibility version 1.0.0, current version 1.0.9)
	@loader_path/../../../../opt/brotli/lib/libbrotlienc.1.dylib (compatibility version 1.0.0, current version 1.0.9)
	@loader_path/../../../../opt/little-cms2/lib/liblcms2.2.dylib (compatibility version 3.0.0, current version 3.15.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 1300.23.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1311.100.3)



```

Why this dylib got involved?

**Comment by xiaoyifang** [comment]
seems introduced by this https://github.com/homebrew-ffmpeg/homebrew-ffmpeg/pull/139

**Comment by xiaoyifang** [comment]
https://github.com/xiaoyifang/goldendict-ng/releases/tag/v23.09.11-alpha.85b8cf2f 

你可以试下这个版本，移除了 ffmpeg的包，   缺点就是默认没法播放speex的音频，  不过应该是个小问题。可以通过外置音频播放器解决。

**Comment by xiaoyifang** [comment]
https://github.com/xiaoyifang/goldendict-ng/releases/tag/v23.09.11-alpha.02918ef1
