### ISSUE TITLE
音频不能播放！

### ISSUE THREAD

**Issue by yshumy** [xiaoyifang/goldendict-ng#1152]
<img width="514" alt="截屏2023-09-17 23 10 56" src="https://github.com/xiaoyifang/goldendict-ng/assets/103359913/3fa51bdb-1c05-4124-8dc2-2a7e142ebf11">

### 
<img width="406" alt="截屏2023-09-17 23 12 31" src="https://github.com/xiaoyifang/goldendict-ng/assets/103359913/cc5c8f24-cda3-4da0-be2a-bdb9872713b5">

**Comment by xiaoyifang** [comment]
配置的外置播放器，估计配置错了，

验证的方式，把你配置的播放器  在命令行里执行下看是否报错。

**Comment by yshumy** [comment]
> 配置的外置播放器，估计配置错了，
> 
> 验证的方式，把你配置的播放器 在命令行里执行下看是否报错。 https://developer.aliyun.com/article/683719

内置的也一样。

**Comment by yshumy** [comment]
> 配置的外置播放器，估计配置错了，
> 
> 验证的方式，把你配置的播放器 在命令行里执行下看是否报错。 https://developer.aliyun.com/article/683719
<img width="450" alt="截屏2023-09-18 13 12 06" src="https://github.com/xiaoyifang/goldendict-ng/assets/103359913/8e3f7ced-a439-49da-9a63-02d358ea2a82">

**Comment by xiaoyifang** [comment]
确定词典本身的音频正常吗？
比如右键保存成文件后，可以用播放器正常播放吗

**Comment by yshumy** [comment]
> 确定词典本身的音频正常吗？ 比如右键保存成文件后，可以用播放器正常播放吗

一直是正常的，升级最新版之后就不能播放了。

**Comment by xiaoyifang** [comment]
那估计是spx音频，由于  #1144中遇到的问题，    ffmpeg在macos上有奇怪的依赖问题，先禁用了。

如果是spx音频，估计只能通过外置播放器了。

**Comment by yshumy** [comment]
> 那估计是spx音频，由于 #1144 中遇到的问题， ffmpeg在macos上有奇怪的依赖问题，先禁用了。
> 
> 如果是spx音频，估计只能通过外置播放器了。

开机随系统启动的设置也是无效的。

**Comment by xiaoyifang** [comment]
我的意思是被我禁用了ffmpeg。

你可以使用外置播放器。

**Comment by yshumy** [comment]
> 外置播放器

**Comment by xiaoyifang** [comment]
https://github.com/xiaoyifang/goldendict-ng/releases/tag/v23.09.11-alpha.02918ef1
