### ISSUE TITLE
Strange dictionary main window edge rebound effect

### ISSUE THREAD

**Issue by qq420100523** [xiaoyifang/goldendict-ng#1154]
**描述 bug**
在词典主窗口浏览词典内容时，当上下左右滚动到可显示的内容边缘时，词典内容整体会与主窗口产生继续移动的错位，停顿再回弹，非常奇怪的弹力阻尼感。

**受影响的词典**
所有

**期望的结果**
如果这种奇怪的边缘回弹效果是一个特性的话，希望能提供一个可关闭这种特效的开关配置

**系统和软件的版本**

Goldendict-ng 23.09.11-alpha.20230917.76a2cd55
Qt 6.4.3 Clang 14.0.3 (clang-1403.0.22.14.1) macos darwin 22.6.0 x86_64-little_endian-lp64
Flags:USE_XAPIAN MAKE_ZIM_SUPPORT MAKE_CHINESE_CONVERSION_SUPPORT

- OS: [macOs 13.5.2 (22G91)]
- Version [23.09.11-alpha.20230917.76a2cd55]

**Comment by xiaoyifang** [comment]
duplicated #180
