### ISSUE TITLE
[GNOME Shell] Double icons on the dash while the app is running, and the app is pinned on the dash

### ISSUE THREAD

**Issue by Amr-Ibra** [xiaoyifang/goldendict-ng#1160]
**Describe the bug**

On GNOME Shell and the app is pinned on the dash, while the app is running, it uses a second icon, not the pinned icon.

**To Reproduce**

1. On GNOME Shell, pin the app to the dash
2. Start the app
3. A second icon is used, not the pinned icon.

**Expected behaviour**

The pinned icon should be used.

**Screenshots**

![goldendict-double-icons](https://github.com/xiaoyifang/goldendict-ng/assets/45657128/34876e4f-df6d-4b2f-bf43-754e4d6ec844)

**OS and software versions**

Goldendict-ng 23.07.25. on 2023-07-27T17:41:10
Qt 6.4.2 GCC 13.1.0debian linux 6.4.0-4-amd64 x86_64-little_endian-lp64
Flags:USE_XAPIAN MAKE_ZIM_SUPPORT USE_ICONV MAKE_CHINESE_CONVERSION_SUPPORT

- OS: Debian testing
- Version: 23.07.25

**Additional context**

When using a different icon theme, the pinned icon is the themed icon while the running app icon is the original one.

![goldendict-themed-double-icons](https://github.com/xiaoyifang/goldendict-ng/assets/45657128/06eb6245-00f5-4d67-bf4b-78f7f1bb2d6f)

**Comment by shenlebantongying** [comment]
> When using a different icon theme, the pinned icon is the themed icon while the running app icon is the original one.

I suspect the problem might be that we are still installing the icon to the legacy location `/usr/share/pixmaps/goldendict.png`,

while the theme installs the icon to the XDG location https://github.com/PapirusDevelopmentTeam/papirus-icon-theme/blob/master/Papirus/64x64/apps/goldendict.svg

The running app prioritizes using the legacy icon, while the GNOME's pin prioritizes XDG icons, and they disagree.

If so, a temporal workaround would be deleting `/usr/share/pixmaps/goldendict.png` when using a theme.

A fix would be to install the icon to `/usr/share/icons/hicolor/256x256/apps/goldendict.png` like https://github.com/goldendict/goldendict/pull/1532

**Comment by Amr-Ibra** [comment]
I would like to make it clear that the bug exists with and without a third-party theme. It is just more obvious with a theme because of the different icons.
