### ISSUE TITLE
Goldendict-ng 23.09.11-alpha.20230924.8163fbaf Qt 6.6.0 word search interface stuck in loading

### ISSUE THREAD

**Issue by czz404** [xiaoyifang/goldendict-ng#1166]
**描述 bug**
查词界面卡在加载
查词后能听到自动朗读窗口词条的声音，但查词界面一直卡在加载
尝试重建索引无效

**相关的截图**
![录制_2023_09_25_09_45_00_917](https://github.com/xiaoyifang/goldendict-ng/assets/64689594/0b00b171-6b2f-4c01-bed9-0bf020dbdd95)

**系统和软件的版本**
- OS: [e.g. Windows11,  22H2]
- Version [Goldendict-ng 23.09.11-alpha.20230924.8163fbaf
Qt 6.6.0 Visual C++ Compiler 192930152 windows winnt 10.0.22621 x86_64-little_endian-llp64
Flags:USE_XAPIAN MAKE_ZIM_SUPPORT USE_ICONV MAKE_CHINESE_CONVERSION_SUPPORT
]

**Comment by xiaoyifang** [comment]
应该是qt6.6的bug，还没修改好。
换用6.5的版本看下。

**Comment by czz404** [comment]
> 应该是 qt6.6 的 bug，还没修改好。 换用 6.5 的版本看下。

6.5版本正常，感谢回复
