### ISSUE TITLE
The font of phonetic symbols seems not correct

### ISSUE THREAD

**Issue by gapplef** [xiaoyifang/goldendict-ng#1180]
**Describe the bug**
The font of phonetic symbols seems not correct, and changes with the display style. 
Goldendict on Ubuntu 22.04 have no such problem.

**Affected Dictionaries**
CollinsCobuild(En-En)
OALD 8th(En-En)

**Screenshots**
Ubuntu 23.10 goldendict-ng 23.07.25
display style: default
![n-edit1](https://github.com/xiaoyifang/goldendict-ng/assets/5604665/f3ae4bc9-560c-444d-a373-6cc1e27ee56d)
![n-edit2](https://github.com/xiaoyifang/goldendict-ng/assets/5604665/ca4d110e-02d5-4a92-b130-0579dc23775c)
![n-golden1](https://github.com/xiaoyifang/goldendict-ng/assets/5604665/9fda51c6-be34-407b-baf5-729bf3115aea)
![n-golden2](https://github.com/xiaoyifang/goldendict-ng/assets/5604665/4aeef6e1-cd85-4dd6-8c3f-ad12266dde6f)

display style: Lingoes-Blue
![n-edit1'](https://github.com/xiaoyifang/goldendict-ng/assets/5604665/19ae000f-8b41-42fa-ac38-70d9581b18db)
![n-edit2'](https://github.com/xiaoyifang/goldendict-ng/assets/5604665/16a38f6a-9996-413a-b02d-7eadea2066d2)
![n-golden1'](https://github.com/xiaoyifang/goldendict-ng/assets/5604665/82b8f8e5-7c24-44c5-b9fc-8229ac81396e)
![n-golden2'](https://github.com/xiaoyifang/goldendict-ng/assets/5604665/a4e3040a-da5c-4cfe-a7c2-3276ff274f36)

-----------------

Ubuntu 22.04 goldendict 1.5.0~rc2+git20210630
![edit1](https://github.com/xiaoyifang/goldendict-ng/assets/5604665/2b34568a-4df9-4569-80af-de43c27f21c6)
![edit2](https://github.com/xiaoyifang/goldendict-ng/assets/5604665/03741067-89a7-4d63-9c71-25053c38d954)
![golden1](https://github.com/xiaoyifang/goldendict-ng/assets/5604665/039de43d-1dd3-4355-b6da-00d53c2af458)
![golden2](https://github.com/xiaoyifang/goldendict-ng/assets/5604665/b1d0ce81-6a36-4657-be19-0f02486cd712)

**Comment by xiaoyifang** [comment]
I have no such dictionaries to debug the issue,

you can follow the instruction to pinpoint the issue if possible.
https://xiaoyifang.github.io/goldendict-ng/howto/how%20to%20debug%20dictionary%20js/

Online font?

**Comment by gapplef** [comment]
> I have no such dictionaries to debug the issue,

It may not appropriate to share these dictionaries public on github, I can send you in private if necessary.

> Online font?

These dictionaries can be used offline, so should have nothing to do with online font.

- - -

I'm not familiar with html/js, here are some screenshots:
Ubuntu 23.10 goldendict-ng 23.07.25
display style: default
![golden](https://github.com/xiaoyifang/goldendict-ng/assets/5604665/acf915cc-e91a-4038-9037-1acab821bea6)
![golden1](https://github.com/xiaoyifang/goldendict-ng/assets/5604665/4c5c9584-3500-4d13-93b0-95af2bf7e24f)

display style: Lingoes-Blue
![golden'](https://github.com/xiaoyifang/goldendict-ng/assets/5604665/485e388b-bfb4-48c5-b641-26f13c195684)
![golden1'](https://github.com/xiaoyifang/goldendict-ng/assets/5604665/c2836dec-8385-4640-8ba2-cd69e6bc114c)

-----

Ubuntu 22.04 goldendict 1.5.0~rc2+git20210630
![golden](https://github.com/xiaoyifang/goldendict-ng/assets/5604665/50ce7097-29a9-4cea-bf95-92e497d33792)
![golden1](https://github.com/xiaoyifang/goldendict-ng/assets/5604665/766b8057-14ae-4adc-a9ab-97438a84430b)

**Comment by xiaoyifang** [comment]
seems some encoding conversion problem.
Can you  share me with one of the dictionaries to debug the issue?

**Comment by xiaoyifang** [comment]
Which qt version do you use ? Qt 5.15 or Qt 6 ,in the goldendict->About

**Comment by gapplef** [comment]
> Can you share me with one of the dictionaries to debug the issue?

Email?

**Comment by xiaoyifang** [comment]
google drive ,shared a link ,when I accessed ,you should be prompted for the permission

**Comment by gapplef** [comment]
[CollinsCobuild(En-En)](https://drive.google.com/file/d/1Iv6RKHS0VqxJRn-_y5nVIFt_86qkwfDw/view?usp=sharing)

**Comment by xiaoyifang** [comment]
![image](https://github.com/xiaoyifang/goldendict-ng/assets/105986/2f9ed09c-b0da-4936-973e-14f0e7a9d75a)


I save the article and open the html with browser ,it is displayed normally.

So I guess the issue is some font problems.
Maybe related with webengine default font settings?

**Comment by xiaoyifang** [comment]
try the new release
https://github.com/xiaoyifang/goldendict-ng/releases/tag/v23.09.11-alpha.dcabb769

**Comment by gapplef** [comment]
I tried the latest AppImage file. The problem still exits on Ubuntu 23.10, but on Ubuntu 22.04 every thing is fine.
I tried previous release, also no such problem on Ubuntu 23.04. So the problem seems relate to Ubuntu 23.10.

![golden](https://github.com/xiaoyifang/goldendict-ng/assets/5604665/2a72f5bf-5f27-4cd1-a907-7cd02b6ea278)
![golden](https://github.com/xiaoyifang/goldendict-ng/assets/5604665/065435e3-48f3-49aa-839a-de0ce1b77a08)
![golden](https://github.com/xiaoyifang/goldendict-ng/assets/5604665/103fb4e1-9519-43ce-87cb-2e15babcafae)
![golden](https://github.com/xiaoyifang/goldendict-ng/assets/5604665/77ddd4ce-fabe-4a87-9a66-719797e4bbec)
