### ISSUE TITLE
Small dropdown bug

### ISSUE THREAD

**Issue by BEST8OY** [xiaoyifang/goldendict-ng#1182]
**Describe the bug**
Present in both Popup GD and Main GD

https://github.com/xiaoyifang/goldendict-ng/assets/70865987/182c2d15-3bfb-4055-9c72-61283ed33ca9

**Expected behavior**
It's a bit tricky to reproduce but I hope it'd be obvious in the video.
The dropdown should be taller.

**OS and software versions**
Goldendict-ng 23.09.11-alpha.20230928.fa79148d
Qt 6.5.2 Visual C++ Compiler 192930152 windows winnt 10.0.22621 x86_64-little_endian-llp64
Flags:USE_XAPIAN MAKE_ZIM_SUPPORT USE_ICONV MAKE_CHINESE_CONVERSION_SUPPORT NO_TTS_SUPPORT no_ffmpeg_player

**Comment by xiaoyifang** [comment]
I'll see what I can do .
