### ISSUE TITLE
Doesn't find abbreviated headwords

### ISSUE THREAD

**Issue by GD-fix** [xiaoyifang/goldendict-ng#1185]
**Describe the bug**
Doesn't find in Dictionary headwords window the must be abbreviated headwords.

**To Reproduce**
0. Run from console last release, append dictionary with long headwords, copy from output the printed beginning of any skipped headword, quit GD, delete this dictionary indexes and run current pre-release.
1. Go to 'dictionaries panel'
2. Click right on the mentioned dictionary
3. Scroll down to 'Dictionary headwords'
4. Paste to the Filter string the copied headword beginning
5. See error

**Affected Dictionaries**
Almost any of https://download.kiwix.org/zim/stack_exchange

**Expected behavior**
Add to Preferences configurable number of "too long headword" characters and remove not working function "Abbreviate the too long headword"

**OS and software versions**
- OS: OpenSUSE Tumbleweed
- Version up to date

**Comment by xiaoyifang** [comment]
give a specific dictionary and a headword plz

**Comment by GD-fix** [comment]
[This one](https://download.kiwix.org/zim/stack_exchange/3dprinting.stackexchange.com_en_all_2023-01.zim) for small example...

**Comment by xiaoyifang** [comment]
give a headword

**Comment by xiaoyifang** [comment]
when you paste the headword ,remember to  drop the ending '...'

**Comment by GD-fix** [comment]
I don't understand: when I paste|print in Filter string the beginning of headword (in "Text" Search mode) it's filtered all matching headwords, that beginning from this string. And what is the ending '...' here then?

**Comment by xiaoyifang** [comment]
> [This one](https://download.kiwix.org/zim/stack_exchange/3dprinting.stackexchange.com_en_all_2023-01.zim) for small example...

provide a headword ,so I can reproduce the same result .

**Comment by GD-fix** [comment]
Wait a minute, please. When I had delete dictionary indexes and run current pre-release, things are even worse here:
"Zim: Failed building full-text search index for \"3D Printing\", reason: Corrupted chain data in the leaf of a btree encountered\n" (on output).
And when I tried to open this dictionary headword window, the pre-release was crushed...

**Comment by GD-fix** [comment]
...And when I deleted indexes, start last release, quit it after all (including FTS) indexing and start current pre-release without indexes deleting, then everything is according to the previously described (try "Would it be possible to use an" for example or any other from Skipped too long headword output in this case). But this is due of reindexing absent...

**Comment by xiaoyifang** [comment]
> Wait a minute, please. When I had delete dictionary indexes and run current pre-release, things are even worse here: "Zim: Failed building full-text search index for "3D Printing", reason: Corrupted chain data in the leaf of a btree encountered\n" (on output). And when I tried to open this dictionary headword window, the pre-release was crushed...

this is a bug introduced with 0278597b ("opt: abbreviate the too long headword to maxHeadwordSize (#1137)", 2023-09-10)

**Comment by xiaoyifang** [comment]
plz try the latest release 
![image](https://github.com/xiaoyifang/goldendict-ng/assets/105986/34a1aa6a-b6cb-4c26-94b9-0b097c6cabdd)

**Comment by GD-fix** [comment]
Yes, I had test (after indexes deleting): it works. 
Thanks, but I ask you to think after all about adding to Preferences configurable number of "too long headword" characters...

To close the theme (non [main](https://github.com/xiaoyifang/goldendict-ng/issues/1128#issuecomment-1741724452)) with headwords at all, what about [Non correct filtered headwords number](https://github.com/xiaoyifang/goldendict-ng/issues/1131#top)? For example with mentioned dictionary:
after opening Dictionary headwords 
![headwords_1](https://github.com/xiaoyifang/goldendict-ng/assets/21008593/20fae560-3b0f-4463-8769-d63c700c0103)
after using filter
![headwords_2](https://github.com/xiaoyifang/goldendict-ng/assets/21008593/33c12a04-27b2-4d2c-b8cb-fc3ff343c070)
In these both cases the total and the filtered numbers of headwords must be equal, I think.
You don't agree with me?

**Comment by xiaoyifang** [comment]
> In these both cases the total and the filtered numbers of headwords must be equal, I think.
> You don't agree with me?

Yes ,I agree. 

I'm think about rewrite the whole logic about headword dialog(relate with #1138) ,  maybe leave the implementation in that time.

**Comment by xiaoyifang** [comment]
> but I ask you to think after all about adding to Preferences configurable number of "too long headword" characters...

I think I'll stick with the default max headword length(which is 100). normally a real headword will have no such length.  and  Wrongly configure this number will lead to performance issue.

**Comment by GD-fix** [comment]
But it will be the user selection: performance or exactly matching...

This isn't important anyway. Most important (critical) is [this](https://github.com/xiaoyifang/goldendict-ng/issues/1128#issuecomment-1741724452)!

**Comment by GD-fix** [comment]
And what about this small correction with adding  to Preferences configurable number of "too long headword" characters?

**Comment by GD-fix** [comment]
In new release it wasn't added...

**Comment by xiaoyifang** [comment]
> And what about this small correction with adding to Preferences configurable number of "too long headword" characters?

It is not this easy , the index will be affected when changing the headword length.

**Comment by GD-fix** [comment]
Yes, of course. Who will change it, will get the reindexing. If the default length remains the old one, not changing the parameter must remain the old index.

**Comment by xiaoyifang** [comment]
alternative solution.  you can change the config settings  in the file   `goldendict/config`

![image](https://github.com/user-attachments/assets/d467d73c-49e9-406e-9a91-f577682c3de1)

**Comment by GD-fix** [comment]
I had receive on e-mail:
>  [xiaoyifang/goldendict-ng] Doesn't find abbreviated headwords (Issue #1185)
> [author@noreply.github.com](https://mail.yandex.ru/lite/compose?to=author@noreply.github.com)
> 
> alternative solution. you can change the config settings in the file goldendict/config
> 
> [image.png (view on web)](https://github.com/user-attachments/assets/d467d73c-49e9-406e-9a91-f577682c3de1)

I had changed it to 512, but it doesn't matter. I think, it applies to open articles. The headwords are really abbreviated on 87 symbol (see the screenshot) and in this case there isn't any reason to so big number by default (256). But it is a really good length for headword abbreviation...
![article_abbrev headword](https://github.com/user-attachments/assets/043bd718-e20b-4da9-918d-4e988dc70f19)

**Comment by GD-fix** [comment]
In ver. 24.09.1.ca9dd13 at 2024-11-05T05:18:15Z headword is abbreviated on 87 symbol and in Preferences it's not possible to change it still...

**Comment by GD-fix** [comment]
In ver. 24.11.0 at 2024-11-21T11:57:12Z all the same...

**Comment by xiaoyifang** [comment]
not in plan

**Comment by GD-fix** [comment]
In classical GD it's a 250 symbols length, not a 87...
