### ISSUE TITLE
Latest release bugs

### ISSUE THREAD

**Issue by BEST8OY** [xiaoyifang/goldendict-ng#1187]
I mentioned some of the bugs in here
https://github.com/xiaoyifang/goldendict-ng/issues/1181#issuecomment-1741783666

But the more serious issue for me is that Capture2Text doesn't open Popup screen anymore and opens the main GD!

**Comment by shenlebantongying** [comment]
> Capture2Text doesn't open Popup screen anymore and opens the main GD!

Not exactly a bug, the original behaviour has a limitation that word cannot be directly send to mainwindow.

https://github.com/xiaoyifang/goldendict-ng/discussions/1072

Now, if the 💡 on toolbar is not enabled, then the word will be send to mainwindow.

After enabling 💡 , it will be send to the popup.

You can also add a `-s` to force goldendict to use popup (by modifing how Capture2Text invokes GD `.../path_to_GD/goldendict.exe -s <word>`)

Although being a breaking change, the new behaviour is more flexible.

**Comment by BEST8OY** [comment]
Another bug
Sounds added via Sound Dir don't play by Qt multimedia.

**Comment by xiaoyifang** [comment]
what is the audio format?

**Comment by BEST8OY** [comment]
> what is the audio format?

OPUS

**Comment by xiaoyifang** [comment]
which package do you use ,the qt5 version or qt6?
try release with qt6

**Comment by BEST8OY** [comment]
> which package do you use ,the qt5 version or qt6? try release with qt6

Uhhhhhh..
Yes, I mistakenly downloaded qt5 version.
I don't know why I always downloaded Qt6 version up until now.
All the problems I encountered was because of the Qt5 version.
Also, it was hella slow in loading words.
Personally, I suggest drop support for Qt5.
I close the issue.
Sorry for the mistake!

**Comment by xiaoyifang** [comment]
> Personally, I suggest dropping the support of Qt5.

Agree. Wait until next release.
