### ISSUE TITLE
MacOS 14 Sonoma incompatible label:macOS

### ISSUE THREAD

**Issue by stellalong** [xiaoyifang/goldendict-ng#1189]
**goldendict version**
Goldendict-ng 23.09.29-MoonCake.20230930.7f0f8778
Qt 6.5.2 Clang 14.0.3 (clang-1403.0.22.14.1) macos darwin 23.0.0 x86_64-little_endian-lp64
Flags:USE_XAPIAN MAKE_ZIM_SUPPORT MAKE_CHINESE_CONVERSION_SUPPORT no_ffmpeg_player 

**Describe the bug**
"**Failed loading** article from LDOCE5++ V 2-15" while successfully load from "牛津高阶英汉双解词典(第8版)". Before I upgrade the macOS version, I can match words in both dictionary. 

bug screenshot 
<img width="789" alt="image" src="https://github.com/xiaoyifang/goldendict-ng/assets/36492352/4cba5bb0-4658-4d9d-9a56-1bc17ce68777">

**Affected Dictionaries**
LDOCE5++ V 2-15.mdx

**Expected behavior**
load the dictionary as before 

Thx.

**Comment by xiaoyifang** [comment]
need more information.

**Comment by xiaoyifang** [comment]
> "**Failed loading** article from LDOCE5++ V 2-15"

What does it look like?
What's your gd-ng version?

**Comment by stellalong** [comment]
problem solved. 
iCloud messed my dictionary files which failed the software.
