### ISSUE TITLE
fix typo in GUI

### ISSUE THREAD

**Issue by fftmp** [xiaoyifang/goldendict-ng#1190]
**To Reproduce**
1. Go to Edit->Dictionaries->Lingua Libre
1. See text "Prouncations provied by ..."

**Expected behavior**
I assume, it must be "Pro**n**unc**i**ations provi**d**ed by ..."
Also need to fix translations, at least Russian variant sounds stupid.

**Comment by xiaoyifang** [comment]
Thanks for report

**Comment by fftmp** [comment]
@xiaoyifang , thank you for quick fix. Seems still one typo remain:
Prounciations
need to be
Pro**n**unciations
