### ISSUE TITLE
Playback device recognition bug in Qt6 version

### ISSUE THREAD

**Issue by BEST8OY** [xiaoyifang/goldendict-ng#1191]
If you open GD (new instance) with jack 3.5 plugged and then unplug it there will be no sound from system speaker.
If you open GD (new instance) with system speaker and then plug 3.5 jack the sound will play from system speaker.

Goldendict-ng 23.09.29-MoonCake.20230930.7f0f8778
Qt 6.5.2 Visual C++ Compiler 192930152 windows winnt 10.0.22621 x86_64-little_endian-llp64
Flags:USE_XAPIAN MAKE_ZIM_SUPPORT USE_ICONV MAKE_CHINESE_CONVERSION_SUPPORT no_ffmpeg_player

**Comment by BEST8OY** [comment]
@xiaoyifang 
Is this investigated?!

**Comment by xiaoyifang** [comment]
will be investigated when I'm available?
