### ISSUE TITLE
unresponsive dict server will cause the whole interface hanged

### ISSUE THREAD

**Issue by blucca** [xiaoyifang/goldendict-ng#1194]
**描述 bug**
多次切换词典群组后会无响应，有时仅切换两次就会无响应

**复现 bug 的步骤**
![test](https://github.com/xiaoyifang/goldendict-ng/assets/127029904/4f69322e-58e0-4479-8a68-7dc5525f418e)

**软件版本**
https://github.com/xiaoyifang/goldendict-ng/releases/tag/v23.09.29-MoonCake.7f0f8778
6.5.2

**Comment by xiaoyifang** [comment]
重建下索引看下是否可以解决

**Comment by xiaoyifang** [comment]
搜索具体的词 之后，再切换也这样吗

**Comment by atauzki** [comment]
尝试一下把兼容性改为Windows8，之前有部分版本启动崩溃我是这么解决的，副作用是各种响应都会变慢
![image](https://github.com/xiaoyifang/goldendict-ng/assets/19769843/132749bb-b3cd-4cfe-aaec-0d69e67a793b)
