### ISSUE TITLE
Program quits immediately after start

### ISSUE THREAD

**Issue by BMuXBeats** [xiaoyifang/goldendict-ng#1195]
**Describe the bug**

**To Reproduce**
Program quits immediately after start. No window or dialogbox is shown.

**Affected Dictionaries**

If certain dictionaries don't work, list their names and types.

If possible, please attach the dictionary files or provide a downloadable link. (GitHub allows uploading 25MiB zip file as attachment)

**Expected behavior**
Start GUI

**Screenshots**

**OS and software versions**
OS: Linux Manjaro
goldendict-ng Version 23.09.10-1

Copy & paste `help` -> `about` -> `Copy version info` to here

- OS: [e.g. Windows10,  Fedora37]

**Additional context**

Windows:

Upload the dmp file in the crash folder located in the configuration folder (can be opened through the menu help->configuration folder) to here

Macos:

upload the crashpad crash log

Linux:

gdb backtrace info.

**Comment by xiaoyifang** [comment]
start in the console(command line) and upload the log
such as 
`goldendict `

**Comment by xiaoyifang** [comment]
Need more information
