### ISSUE TITLE
Original GD's problem: Every image is read twice (at least for DSL)

### ISSUE THREAD

**Issue by shenlebantongying** [xiaoyifang/goldendict-ng#1197]
DSL::nodeToHtml loads the image and then checks the image's size https://github.com/goldendict/goldendict/blob/1.5.0/dsl.cc#L915-L1003

DslResourceRequest::run sends the data to the browser https://github.com/goldendict/goldendict/blob/1.5.0/dsl.cc#L1912-L1955

Try this dict with single image [test_dsl.zip](https://github.com/xiaoyifang/goldendict-ng/files/12826888/test_dsl.zip)

Set a breakpoint at File::loadFromFile, and you can see 2 calls reaches it.

![image](https://github.com/xiaoyifang/goldendict-ng/assets/20123683/e1af824e-837a-4828-813f-d0da7301ca72)

![image](https://github.com/xiaoyifang/goldendict-ng/assets/20123683/353679d6-e4f1-456e-9877-e30e3b500a6c)

Better solution: replace the size checking with CSS's image max-width.

**Comment by xiaoyifang** [comment]
Agree, use css to control the image size should be better

**Comment by xiaoyifang** [comment]
> DSL::nodeToHtml loads the image and then checks the image's size https://github.com/goldendict/goldendict/blob/1.5.0/dsl.cc#L915-L1003

this whole logic can be removed . because there is no place to configure the maxPictureWidth, which lead the `resize` variable is always false.
