### ISSUE TITLE
Automatically turn on and off dark mode and dark reading mode following Windows themes (跟随Windows主题自动开启关闭深色模式及深色阅读模式)

### ISSUE THREAD

**Issue by xuangeyouneihan** [xiaoyifang/goldendict-ng#1206]
**Is your feature request related to a problem? Please describe.**
电脑上安装了Auto Dark Mode。晚上切换到深色主题时本软件仍然是浅色模式。即使手动开启深色的选项，启动时打开的欢迎使用页面也无法切换成深色，需要重新启动软件才可以

**Describe the solution you'd like**
见标题，且开启深色阅读模式时自动将欢迎页面调整为深色，关闭时反之

**Describe alternatives you've considered**

**Additional context**

**Comment by xiaoyifang** [comment]
duplicate with #687
