### ISSUE TITLE
Command: [goldendict "word"] open main window instead of popup window

### ISSUE THREAD

**Issue by cuongha0701** [xiaoyifang/goldendict-ng#1212]
Goldendict open main window instead of popup when run command: `goldendict "word"` in terminal
- OS: Linux (Arch Linux with KDE)
- GoldenDict version: Goldendict-ng 23.09.08.db0ca76e at 2023-10-06T20:59:50

**Comment by shenlebantongying** [comment]
`goldendict -s <word>` or enable scanPopup will send the word to scanPopup now. Otherwise, it will be sent to mainwindow.

It is changed https://github.com/xiaoyifang/goldendict-ng/pull/1173#issue-1914456812 to overcome this limitation https://github.com/xiaoyifang/goldendict-ng/discussions/1072

**Comment by cuongha0701** [comment]
> `goldendict -s <word>` or enable scanPopup (💡 on toolbar or right click tray icon) will send the word to scanPopup now. Otherwise, it will be sent to mainwindow.
> 
> It is changed [#1173 (comment)](https://github.com/xiaoyifang/goldendict-ng/pull/1173#issue-1914456812) to overcome this limitation #1072

Thank you
