### ISSUE TITLE
Can the title bar in dark mode also be turned black?

### ISSUE THREAD

**Issue by blucca** [xiaoyifang/goldendict-ng#1229]
<img width="799" alt="image" src="https://github.com/xiaoyifang/goldendict-ng/assets/127029904/653a7b54-0773-48bf-9651-140d8c5c401b">

如图，现在深色模式的标题栏是白色的，能否切换成黑色？

**Comment by czz404** [comment]
![pic_1697017512.png](https://s2.loli.net/2023/10/11/DU1iZk8vWBsJxGI.png)

**Comment by czz404** [comment]
> > ![pic_1697017512.png](https://camo.githubusercontent.com/603ac219528a7851feae46fdd495270ba3e87663cca68be73057f41b4ac38948/68747470733a2f2f73322e6c6f6c692e6e65742f323032332f31302f31312f445531695a6b38765742734a7847492e706e67)
> 
> 这样窗口失去焦点就会变回白色吧。有没有像chrome的隐私窗口一样一直让标题栏保持黑色的方法呢。。

https://winaero.com/change-color-of-inactive-title-bars-in-windows-10/amp/
善用搜索引擎

**Comment by xiaoyifang** [comment]
> 并且在搜索找不到的词汇以后清空搜索框，搜索框就又会变回白色了 ![test](https://user-images.githubusercontent.com/127029904/274298288-e53e37d8-efce-4870-9d47-7a1666f38482.gif) [ ![test](https://user-images.githubusercontent.com/127029904/274298288-e53e37d8-efce-4870-9d47-7a1666f38482.gif) ](https://user-images.githubusercontent.com/127029904/274298288-e53e37d8-efce-4870-9d47-7a1666f38482.gif) [ ](https://user-images.githubusercontent.com/127029904/274298288-e53e37d8-efce-4870-9d47-7a1666f38482.gif)

This seems a bug

**Comment by xiaoyifang** [comment]
> 并且在搜索找不到的词汇以后清空搜索框，搜索框就又会变回白色了 

改为斜体如何？
![image](https://github.com/xiaoyifang/goldendict-ng/assets/105986/4d124959-c4e2-4c06-9bbf-a267b49a3eb0)

**Comment by czz404** [comment]
似乎没有什么好办法，我目前想到的是直接使用winsize隐藏标题栏
winsize：https://meta.appinn.net/t/topic/41358/13
（不是打广告，只是我是这个软件的用户）
![pic_1697070364.png](https://s2.loli.net/2023/10/12/S3cNdmwIZhDnG2e.png)

**Comment by xiaoyifang** [comment]
主要是qt对windows下暗黑模式支持的不好。

单独实现的话，改动比较多，还要额外实现  最大最小的那几个功能。  标题栏 暂时没计划处理。

**Comment by shenlebantongying** [comment]
This was fixed.

The title bar should sync with the system.

https://github.com/xiaoyifang/goldendict-ng/blob/5406b3022a4af8b2ff2c6dcd814b8a986dc720ad/src/main.cc#L346

https://doc.qt.io/qt-6/qguiapplication.html#platform-specific-arguments
