### ISSUE TITLE
Crash on full-text indexing on some dictionaries

### ISSUE THREAD

**Issue by zendynar** [xiaoyifang/goldendict-ng#1230]
Hello, I get a hard crash on full-text indexing on some dictionaries. So far I found one specific example I am attaching here below. This is the error message I am getting in the terminal:

```
Dsl: Building the full-text index for dictionary: Nuclear Energy Dictionary ER

/usr/include/c++/12.2.0/bits/basic_string.h:1221: std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::reference std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::operator[](size_type) [with _CharT = char32_t; _Traits = std::char_traits<char32_t>; _Alloc = std::allocator<char32_t>; reference = char32_t&; size_type = long unsigned int]: Assertion '__pos <= size()' failed.
```

1. Download the DSL dict [here](https://upload.disroot.org/r/4dsF667r#YNJKsDndFJMUXrOKK8J2X8oSPYo2nYiN4be5DDx+OMs=)
2. Point Goldendict-ng to the folder with the file
3. Wait for full-text indexing

Software version:
Goldendict-ng 23.09.29.7f0f877 at 2023-10-06T06:57:11
Qt 6.5.3 GCC 12.2.0 org.kde.Platform linux 6.2.0-10027-tuxedo x86_64-little_endian-lp64
Flags:USE_XAPIAN MAKE_ZIM_SUPPORT USE_ICONV MAKE_CHINESE_CONVERSION_SUPPORT

OS: Tuxedo OS2 (Ubuntu 22.04 base with up-to-date Qt, KDE etc.)
Goldendict-ng is installed as flatpak from flathub. I don't think it matters here as I am able to index other dictionaries.

**Comment by xiaoyifang** [comment]
![image](https://github.com/xiaoyifang/goldendict-ng/assets/105986/3c4ffacf-622c-4043-8846-173837b5c95c)

The dsl has some encoding problem.

and the crash has been fixed

**Comment by zendynar** [comment]
Thanks! This dictionary is pretty old and likely uses other encoding than UTF-8, that's the reason for the encoding problem. Does it make sense to explore that further? I can try finding which encoding this is

**Comment by xiaoyifang** [comment]
> Does it make sense to explore that further?

If you need to use dictionary , you can continue to explore the encoding.
From the software perspective ,it is not neccessary.

**Comment by zendynar** [comment]
Thanks! I will probably create another ussue for this.
