### ISSUE TITLE
Extra space appears below the online dictionary

### ISSUE THREAD

**Issue by ChenPeeer** [xiaoyifang/goldendict-ng#1236]
**描述 bug**
在线词典下方会出现多余空白，或者说在线词典无法纵向完全展开

**复现 bug 的步骤**
1. 打开任意一本在线词典，任意查询一个单词

**受影响的词典**
https://www.youdao.com/result?word=%GDWORD%&lang=en

**相关的截图**
<img width="960" alt="2023-10-13_115735" src="https://github.com/xiaoyifang/goldendict-ng/assets/30888522/ed9d1047-4dbc-4dd8-aa65-0e03f13ffa36">

**系统和软件的版本**
win10专业版 22h2
goldendict-ng 23.10.01-alpha.20231009.0067d19f

**Comment by xiaoyifang** [comment]
特意的，否则的话，小词典会固定在下面没法滚动，体验不好。
