### ISSUE TITLE
Emacs integration

### ISSUE THREAD

**Issue by benthamite** [xiaoyifang/goldendict-ng#1240]
**Is your feature request related to a problem? Please describe.**
I would like to be able to use GoldenDict from within Emacs.

**Describe the solution you'd like**
A package that allows the user to search for a chosen string and browse the results in an Emacs buffer.

**Describe alternatives you've considered**
The best current alternative is to create a simple Elisp function that uses the [command line](https://xiaoyifang.github.io/goldendict-ng/topic_commandline/) to search GoldenDict. However, the results are still displayed externally in the GoldenDict app.

I am willing to pay someone to develop such a package. Please get in touch if you are an Elisp programmer.

**Comment by xiaoyifang** [comment]
I think @shenlebantongying  has already implemented this

https://emacs-china.org/t/emacs-goldendict/22947

**Comment by benthamite** [comment]
Thanks. What @shenlebantongying implemented is an example of the alternative I describe above: “to
create a simple Elisp function that uses the [command line](https://xiaoyifang.github.io/goldendict-ng/topic_commandline/) to search
GoldenDict.” I actually have developed a slightly more sophisticated version of this, which I’ll release later in case it’s useful to others. However, this falls short of the idea of displaying the search results themselves in an Emacs buffer, which is a more significant development effort.

**Comment by benthamite** [comment]
[Here](https://github.com/benthamite/goldendict-ng)'s the little package I created.

**Comment by shenlebantongying** [comment]
> [Here](https://github.com/benthamite/goldendict-ng)'s the little package I created.

Nice :+1: 

>  However, this falls short of displaying the search results themselves in an Emacs buffer, which is a more significant development effort.

A possible generic solution is something like this https://github.com/xiaoyifang/goldendict-ng/issues/229

However, the current code is deeply entangled with Qt & Webengine. A lot of effort is indeed needed to provide alternative frontends.
