### ISSUE TITLE
Input focus error

### ISSUE THREAD

**Issue by czz404** [xiaoyifang/goldendict-ng#1245]
**描述 bug**
查词拼写错误，重新输入时焦点不在软件输入框而在在线网站输入框

**复现 bug 的步骤**
1. 查词输入时拼写错误
2. 添加的在线网站词典提示拼写错误并显示相似词
3. 重新键盘输入单词
4. 输入焦点不在词典查询窗口而在在线网站词典的查询窗口

**受影响的词典**
在线词典文件来自 https://forum.freemdict.com/t/topic/16552/1
文件传附件失败了，传到蓝奏云了：https://wwzp.lanzoum.com/iQFFo1byxcmj密码:77py

**相关的截图**
<img width="1080" alt="截图_20231016161448" src="https://github.com/xiaoyifang/goldendict-ng/assets/64689594/c0301631-59d9-4d1d-ae81-67ac26e4ee73">

**系统和软件的版本**

Goldendict-ng 23.10.01-alpha.20231015.955c8ca8
Qt 6.6.0 Visual C++ Compiler 192930152 windows winnt 10.0.22621 x86_64-little_endian-llp64
Flags:USE_XAPIAN MAKE_ZIM_SUPPORT USE_ICONV MAKE_CHINESE_CONVERSION_SUPPORT NO_TTS_SUPPORT no_ffmpeg_player

- OS: Win11 22H2

**Comment by xiaoyifang** [comment]
直接添加  在线词典    https://www.bing.com/dict/search?q=%GDWORD%&FORM=BDVSP6&cc=cn
的方式，没有问题。

**Comment by czz404** [comment]
好的，谢谢
比较了一下直接添加在线词典排版上不是太理想
还是用现在的方案好了

**Comment by czz404** [comment]
> 直接添加 在线词典 https://www.bing.com/dict/search?q=%GDWORD%&FORM=BDVSP6&cc=cn 的方式，没有问题。

请问下这样直接添加网站的方法是不是无法应用css

**Comment by xiaoyifang** [comment]
> > 直接添加 在线词典 https://www.bing.com/dict/search?q=%GDWORD%&FORM=BDVSP6&cc=cn 的方式，没有问题。
> 
> 请问下这样直接添加网站的方法是不是无法应用css

目前这种在线词典的实现方式  是  iframe，  原则上自定义样式是不生效的。

**Comment by czz404** [comment]
感谢解答
