### ISSUE TITLE
Is it possible to pick up the text on the picture?

### ISSUE THREAD

**Issue by buddhiko1** [xiaoyifang/goldendict-ng#1248]
首先，再次感谢这个开源项目的所有贡献人员，GoldenDict是我日常生活和工作中不可或缺的一个工具。

最近我在pc上读一些pdf格式的古籍（如下图），经常需要查字典。因为文字是在图片上的，所以没办法选择文字。每次都要拿出手机，然后在欧陆上手写查询，非常的耗时耗力。

对于图片上的文字，能否通过hover去拾取呢？是否有实现的可能性？因为有很多pdf都是图片形式的，这个问题我想很多人都会遇到。

![last](https://github.com/xiaoyifang/goldendict-ng/assets/8435488/7446df33-765a-486d-b06d-19c45a494b10)

**Comment by buddhiko1** [comment]
应该没有可能识别这种估计字体。

**Comment by xiaoyifang** [comment]
https://xiaoyifang.github.io/goldendict-ng/howto/ocr/

**Comment by buddhiko1** [comment]
> https://xiaoyifang.github.io/goldendict-ng/howto/ocr/

非常感谢! 帮了我的大忙. 给capture2text安装额外的繁体语言包后亲测可用，识别率还挺高.
