### ISSUE TITLE
Dictionary info is not shown for a specific DSL dictionary

### ISSUE THREAD

**Issue by homocomputeris** [xiaoyifang/goldendict-ng#1250]
**Describe the bug**
Dictionary info (name, languages) is not shown for this specific DSL dictionary (attached below). For other DSL dictionaries with the same structure and encoding the info is shown.

**To Reproduce**
1. Go to F3 dictionary list
2. Select dictionary without name

**Affected Dictionaries**
[jpn-rus_Warodai.dsl.zip](https://github.com/xiaoyifang/goldendict-ng/files/13032830/jpn-rus_Warodai.dsl.zip)
DSL
UTF-8 with BOM
LF

**Expected behavior**
Show dictionari info: name, languages, etc.

**Screenshots**
![dsl_list](https://github.com/xiaoyifang/goldendict-ng/assets/7422433/fc2211a1-4f55-4398-bc6e-5b17532261e0)

![dsl](https://github.com/xiaoyifang/goldendict-ng/assets/7422433/c59d7f36-29a7-424e-97d8-f57edcd0619f)

**OS and software versions**

Goldendict-ng 23.10.01-alpha.20231015.743226e5
Qt 6.5.2 Clang 14.0.3 (clang-1403.0.22.14.1) macos darwin 23.0.0 x86_64-little_endian-lp64
Flags:USE_XAPIAN MAKE_ZIM_SUPPORT MAKE_CHINESE_CONVERSION_SUPPORT NO_TTS_SUPPORT no_ffmpeg_player

- OS: macos
- Version: 14.0 (23A344)

**Comment by shenlebantongying** [comment]
Replace this tab with a space.

![image](https://github.com/xiaoyifang/goldendict-ng/assets/20123683/ab0b9b90-1a13-4a60-a0e6-95df2c8f2877)
---
![image](https://github.com/xiaoyifang/goldendict-ng/assets/20123683/e7662efa-d0cb-48cf-b179-9795696f50de)

**Comment by homocomputeris** [comment]
> Replace this tab with a space.

Doesn't change anything.

**Comment by shenlebantongying** [comment]
Yes, you are right.

Super weird, I just open he file the save as another file, then it will display correctly

Result after I re-save [jpn-rus_Warodai.zip](https://github.com/xiaoyifang/goldendict-ng/files/13034981/jpn-rus_Warodai.zip)

---

I just figured out, re-saving will remove few bytes from the first line.

From `EF BB BF EF BB BF` to just `EF BB BF`, the original file contains two BOMs :sweat_smile: Re-save will remove duplicated BOM and it will work.

![image](https://github.com/xiaoyifang/goldendict-ng/assets/20123683/483c681b-9ef3-4ff0-bfd4-d0cac6980185)

**Comment by homocomputeris** [comment]
> From EF BB BF EF BB BF to just EF BB BF, the original file contains two BOMs 
The dangers of downloading files from the internet 😅
