### ISSUE TITLE
scan popup does not open in some app

### ISSUE THREAD

**Issue by trunglebka** [xiaoyifang/goldendict-ng#1252]
**Describe the bug**
I have two machine both running Fedora 38,
In a machine, some app like Evince document viewer, Okular (both are default pdf reader in major linux OSes) does not show popup when turning on "Only tack selection ... are kept pressed" option (tried with all keys sub-options); if uncheck that option, the popup is showed up but it's too annoyed to use. In some app like chrome/edge it is working perfectly (same pdf file).

In the other machine, all apps are working as expected.

All are tested with the latest master branch. I've installed another version below, but it still does not work.

**Expected behavior**
Show scan popup in all app.

**OS and software versions**
Fedora 38/Wayland
Version: Goldendict-ng 23.10.01.22f35dd7 at 2023-10-20T07:54:36
Qt 6.5.2 GCC 13.2.1 20231011 (Red Hat 13.2.1-4) fedora linux 6.3.4-201.fc38.x86_64 x86_64-little_endian-lp64
Flags:USE_XAPIAN MAKE_ZIM_SUPPORT USE_ICONV MAKE_CHINESE_CONVERSION_SUPPORT

**Comment by shenlebantongying** [comment]
Probably the same as https://github.com/xiaoyifang/goldendict-ng/issues/741#issuecomment-1559849195

Okular/Evince runes in Wayland, while chrome is likely runs under XWayland.

XWayland (GD currently needs it) cannot obtain clipboard changes from Wayland apps in some environments like KDE.

**Comment by trunglebka** [comment]
I've checked the "normal" machine, it use X11.
Next Monday, comeback to work I will set up X11 in the "abnormal" machine and report result later

**Comment by trunglebka** [comment]
I've switched windowing system to X11 and now it is working as expected - scan popup with alt key pressed in pdf reader.
Related to https://github.com/xiaoyifang/goldendict-ng/issues/741#issuecomment-1559849195, all of my machines use Gnome so `Meanwhile, it works OK on GNOME Wayland.` seem incorrect

**Comment by mhasadi78** [comment]
Any fix on this after updating to 23.11.08 version?
