### ISSUE TITLE
During each startup ZIM dictionaries are indexing (instead of loading)

### ISSUE THREAD

**Issue by GD-fix** [xiaoyifang/goldendict-ng#1253]
**Describe the bug**
[A clear and concise description of what the bug is.](https://github.com/xiaoyifang/goldendict-ng/issues/1128#issuecomment-1751720460)

Was it checked, reproduced and (if true) will it be fixed in nearest release? 

And what about [this](https://github.com/xiaoyifang/goldendict-ng/issues/1128#issuecomment-1773710703) and [this](https://github.com/xiaoyifang/goldendict-ng/issues/1128#issuecomment-1773717140) questions (if You don't answer in closed issues)?

**Comment by xiaoyifang** [comment]
https://github.com/xiaoyifang/goldendict-ng/issues/1128#issuecomment-1763001327

they are not indexing.
only checking the index

**Comment by GD-fix** [comment]
There was "indexing" on startup splash window for ZIM dictionaries and "loading" for other.
**When is planned next release?** I'll download it, rearrange ZIM dictions (although **I didn't understand, what guarantees You can give, that it will not be needed to rearrange them again** in future releases) and see, what it will be with indexing|loading (then may be I'll something upload).

**Comment by xiaoyifang** [comment]
> There was "indexing" on startup splash window for ZIM dictionaries and "loading" for other.

How many time does the indexing information takes?



> **I didn't understand, what guarantees You can give, that it will not be needed to rearrange them again** in future releases)

I can not guarantee about this.        and I think there is no thing is unchanged in this world.

**Comment by GD-fix** [comment]
It fast with already indexed dictionaries, but is "indexing", not "loading"...

**Comment by xiaoyifang** [comment]
you can take it as "index checking".

**Comment by GD-fix** [comment]
I just drew your attention to the fact that in case of ZIM dictionaries there isn't any difference on startup splash window between not indexed and already indexed dictionaries, while in other case there are "indexing" and "loading" respectively...

> I can not guarantee about this. and I think there is no thing is unchanged in this world.
I can only guarantee that If there is no necessary I will not change it again.

OK. Can You guarantee that if You'll change in the next times something, that will rearrange the dictionaries, then You'll leave for compatibility old variant on user selection?

Thanks in advance.
