### ISSUE TITLE
The latest version of automatic pronunciation fails

### ISSUE THREAD

**Issue by popyoung** [xiaoyifang/goldendict-ng#1256]
**描述 bug**

**复现 bug 的步骤**
本来查词带自动发音，现在没有了。选项里还勾着，个人怀疑和去除ffmpeg有关。我之前用的应该是ffmpeg。

**系统和软件的版本**

复制 & 粘贴 `帮助` -> `关于` -> `复制版本信息` 到这里
Goldendict-ng 23.10.01-alpha.20231024.8905de63
Qt 6.6.0 Visual C++ Compiler 192930152 windows winnt 10.0.19045 x86_64-little_endian-llp64
Flags:USE_XAPIAN MAKE_ZIM_SUPPORT USE_ICONV MAKE_CHINESE_CONVERSION_SUPPORT NO_TTS_SUPPORT no_ffmpeg_player
- OS: [e.g. Windows10,  Fedora37]

**Comment by xiaoyifang** [comment]
后端的发音 引擎的地方切换下看看。

qt6.5之后的版本，qtmultimedia是基于ffmpeg实现的。所以ffmpeg的选项就移除了。

**Comment by popyoung** [comment]
看过的，只有qtmultimedia一个选项，没法切换，我还试过切到外部播放器mpv。都能播放声音，就是不能自动播放。

**Comment by xiaoyifang** [comment]
自动播放的音频，是解析到的第一个音频文件。  估计是你的词典的中有一个无效的音频文件。
你可以调整下词典的顺序，或者禁用一些词典后看下。

**Comment by popyoung** [comment]
禁用了原先的一个之后发音了。不知道为什么原先是正常的，原先默认调用的也是第一个词典吗？是不是应该没找到再去找下一个音频？
另外我其实在js里写了，让后面的一本词典发音的，现在这个版本的自动发音也没有生效。现在自动发音的是排在最前面的那本。但是奇怪的是如果我手动点alt+S，它确实是用后面那本发音。

**Comment by popyoung** [comment]
另外这个版本还有个bug。我的鼠标有5个键，4、5键是前进后退。现在一次点击会前进后退两次，放慢点击速度发现 mouse down 和 mouse up 分别触发了一次事件。

**Comment by xiaoyifang** [comment]
> 另外这个版本还有个bug。我的鼠标有5个键，4、5键是前进后退。现在一次点击会前进后退两次，放慢点击速度发现 mouse down 和 mouse up 分别触发了一次事件。

后续调查下

**Comment by xiaoyifang** [comment]
> 是不是应该没找到再去找下一个音频？

找到了，但是找到的音频无效。   不好判断无效的音频。

**Comment by popyoung** [comment]
> > 另外这个版本还有个bug。我的鼠标有5个键，4、5键是前进后退。现在一次点击会前进后退两次，放慢点击速度发现 mouse down 和 mouse up 分别触发了一次事件。
> 
> 后续调查下

我试了929月饼版本，没这个问题。应该就是最近改出来的。

**Comment by popyoung** [comment]
> > 是不是应该没找到再去找下一个音频？
> 
> 找到了，但是找到的音频无效。 不好判断无效的音频。

我猜测是不是加载页面那块时间顺序上有变化，导致手动发音和自动发音的音频不是同一个。感觉是自动发音时间提早了，js还没生效就开始了。

**Comment by xiaoyifang** [comment]
> 导致手动发音和自动发音的音频不是同一个

应该是这个原因

**Comment by popyoung** [comment]
在js里手动加了个模拟点击，暂时解决了这个问题。
```
window.onload = function() {
    var script = document.querySelector('a.circle.circle-btn.sound.audio_play_button');
    gdAudioLinks.first = script.getAttribute('href');
    script.click();     //这行是新加的代码
  };
```

**Comment by popyoung** [comment]
结果测试了一会还是有个别单词会无法发音。现在又加了一个延时。
```js
window.onload = function () {
    var script = document.querySelector('a.circle.circle-btn.sound.audio_play_button');
    gdAudioLinks.first = script.getAttribute('href');
    setTimeout(function () {
        script.click();
    }, 100);
};
```

**Comment by xiaoyifang** [comment]
可能会造成重复发音

**Comment by popyoung** [comment]
> 可能会造成重复发音

有可能的，不过我把自动发音关了

**Comment by xiaoyifang** [comment]
https://github.com/xiaoyifang/goldendict-ng/releases/tag/v23.10.01-alpha.61b22b58

使用这个版本，然后复现下bug，把日志gd_log.txt发上来。

启用日志的方式    goldendict --log-to-file.

**Comment by popyoung** [comment]
单独更新6.6.0.windows-2019-GoldenDict.exe这个？
我现在用的是1029那个版本。

**Comment by xiaoyifang** [comment]
> 单独更新6.6.0.windows-2019-GoldenDict.exe这个？ 我现在用的是1029那个版本。

可以只下载这一个文件，然后拷贝到  goldendict.exe的文件夹里运行

`6.6.0.windows-2019-GoldenDict.exe  --log-to-file`

**Comment by popyoung** [comment]
[gd_log.txt](https://github.com/xiaoyifang/goldendict-ng/files/13214553/gd_log.txt)
我提前屏蔽了js里的发音，43行看上去是我手动设置的剑桥的音频，但看日志它播放的是90行的音频。那个应该是另一本词典的，它的音频文件我一直没有下载。顺带可以看到它因为创建目录失败所以没有给我建立全文索引，原因不清楚。我这里特别一点的是content目录是个软链接，但看似和这个报错没有关系。

**Comment by xiaoyifang** [comment]
> 43行看上去是我手动设置的剑桥的音频，但看日志它播放的是90行的音频。那个应该是另一本词典的，它的音频文件我一直没有下载。顺带可以看到它因为创建目录失败所以没有给我建立全文索引

你的剑桥词典是第一本吗？

你的portable目录下index目录存在吗？

**Comment by popyoung** [comment]
> 你的剑桥词典是第一本吗？

不是，很后面了。第一本是TheLittleDict，条目太多，没让他全文索引，所以在日志里看不到。90行音频对应的词典id应该是TheLittleDict的。

> 你的portable目录下index目录存在吗？
存在，里面有索引文件，但是没有全文索引。我可以试试手动创建一个对应名称的目录……

**Comment by popyoung** [comment]
> 我可以试试手动创建一个对应名称的目录……

手动创建了一个这个目录，但依旧有这句话。
Warning: 10-31 21:09:54 create xapian index: "DatabaseCreateError: D:/@绿色软件/常用软件/GoldenDict-ng/portable/index\\2436fb8cb7a6cb09c78ae436b23d0b24_FTS_x_temp: mkdir failed (No such file or directory)"

我记得和你说过，普通模式下全文索引正常，portable就出问题，不知道为什么。

**Comment by popyoung** [comment]
仔细想想，有可能是路径里的@，导致数据库里字符串处理出问题？

**Comment by popyoung** [comment]
另外最近的版本鼠标状态也不太正常，这里也一并反馈下。经过试验，逻辑大概是这样，从其他程序切换回goldendict，鼠标状态失常，然后鼠标去菜单栏那边转一圈，状态就正常了。

![Uploading 动画.gif…]()

**Comment by popyoung** [comment]
> 那么自动发音取了第一本应该没问题， 目前的自动发音就是按词典顺序，取第一个可用的音频。

但我js代码里已经把剑桥的放到第一个了，不知为何这个版本没生效。几个月前的版本是有效的。
```js
window.onload = function () {
    var script = document.querySelector('a.circle.circle-btn.sound.audio_play_button');
    gdAudioLinks.first = script.getAttribute('href');
};
```

> 你的TheLittleDict可以手工发音吗

不行，因为我没下载他的mdd文件。

**Comment by popyoung** [comment]
> > 仔细想想，有可能是路径里的@，导致数据库里字符串处理出问题？
> > 因为之前我印象里我也编译过，自己编译的版本，portable里也是正常的。
> 
> 可能是权限问题。

应该不是权限，我给目录加了everyone所有权限，还是没用。我把goldendict目录移动到D盘下，就正常建立全文索引了。
日志里说DatabaseCreateError，如果你读取路径后没有做字符串处理就直接往数据库里仍，那样的话@可能会导致execute时字符出问题。

**Comment by xiaoyifang** [comment]
> > 那么自动发音取了第一本应该没问题， 目前的自动发音就是按词典顺序，取第一个可用的音频。
> 
> 但我js代码里已经把剑桥的放到第一个了，不知为何这个版本没生效。几个月前的版本是有效的。
> 
> ```js
> window.onload = function () {
>     var script = document.querySelector('a.circle.circle-btn.sound.audio_play_button');
>     gdAudioLinks.first = script.getAttribute('href');
> };
> ```
> 
> > 你的TheLittleDict可以手工发音吗
> 
> 不行，因为我没下载他的mdd文件。

那么不发音是正常的，目前设计如此。

**Comment by xiaoyifang** [comment]
> > > 仔细想想，有可能是路径里的@，导致数据库里字符串处理出问题？
> > > 因为之前我印象里我也编译过，自己编译的版本，portable里也是正常的。
> > 
> > 
> > 可能是权限问题。
> 
> 应该不是权限，我给目录加了everyone所有权限，还是没用。我把goldendict目录移动到D盘下，就正常建立全文索引了。 日志里说DatabaseCreateError，如果你读取路径后没有做字符串处理就直接往数据库里仍，那样的话@可能会导致execute时字符出问题。

没用到数据库，路径也没有保存。xapian可能不支持这种含@的路径

**Comment by popyoung** [comment]
> 那么不发音是正常的，目前设计如此：自动发音，用的是按照你词典排序的顺序，第一个找到的音频链接

那我继续用js手动发音吧

> 没用到数据库，路径也没有保存。xapian可能不支持这种含@的路径

应该是的，随便试了一下，用带双引号的词组搜索出来的结果还是很奇怪。然后我突然想到是不是这个实现方案走入了误区。其实不必使用会导致索引文件翻倍的位置索引。只要给出的结果足够少，比如小于10000条，然后做个循环来匹配字符串就行了。如果条目过多给出提示，说明一下，就说关键词太少无法精确匹配就好了。不追求一步到位可能结果更可控，毕竟xapian是第三方插件，修改不易。
