### ISSUE TITLE
Current prerelease crash during loading

### ISSUE THREAD

**Issue by GD-fix** [xiaoyifang/goldendict-ng#1261]
**Describe the bug**
`./GoldenDict-ng-v23.10.01-alpha.231024.8905de63.AppImage`
`[1028/132754.121969:FATAL:v8_initializer.cc(516)] Error loading V8 startup snapshot file`
`[1028/132754.124669:FATAL:v8_initializer.cc(516)] Error loading V8 startup snapshot file`
`Ловушка трассировки/останова (образ памяти сброшен на диск)`
(I don't translate to English last line because I'm not a developer and afraid only to confuse with incorrect automatic translation...)

**To Reproduce**
1. Go to console
2. Start the GD-ng
3. See error

**OS and software versions**
  - OS: OpenSUSE Tumbleweed
  - Version up to date

**Comment by xiaoyifang** [comment]
maybe related with #1244 ,

recommend to use flatpak https://flathub.org/zh-Hans/apps/io.github.xiaoyifang.goldendict_ng
or build from source.

**Comment by GD-fix** [comment]
From Your recommendations: the first one [has a very old version](https://user-images.githubusercontent.com/21008593/271764568-3f0b0cff-edc3-4949-bed1-8d4c68e76026.png) (as I have previously mentioned), that will need (among other) to rearrange dictionaries back; and the second one is in hieroglyphs not available to me...
I download pre-releases for help You with testing only (for using I have downloaded [last release](https://github.com/xiaoyifang/goldendict-ng/releases/latest) long time ago).

So I have two questions:
1. When is planned next release (workable, of course)?
2. [Not answered yet](https://github.com/xiaoyifang/goldendict-ng/issues/1253#issuecomment-1783758482).

Thanks in advance.

**Comment by xiaoyifang** [comment]
> 1. When is planned next release (workable, of course)?

Can not be sure about this?,AppImage is always fails in one way or another ,  This is not depend on me but on AppImage

**Comment by GD-fix** [comment]
It's first time, when AppImage fail on my PC. For example, GoldenDict-ng-v23.09.29-MoonCake.230930.7f0f8778.AppImage I run right now...

**Comment by GD-fix** [comment]
OK. You begin using Flatpak instead of AppImage.
I had: downloaded io.github.xiaoyifang.goldendict_ng.flatpakref and opened (and installed) it in Discover.

As a result, I have some questions.
1. In Discover I have now 2 goldendicts marked by "Flatpak" (additional to non-marked "GoldenDict" which runs mentioned old GoldenDict-ng version from system repository): runnable "GoldenDict-ng" and non-runnable "io.github.xiaoyifang.goldendict_ng.Locale". So is this GoldenDict-ng updatable (when You create new releases) and are these goldendicts needed both?
2. Flatpak version uses configuration from ~/.var/app/io.github.xiaoyifang.goldendict_ng/config/goldendict/ (instead of standard ~/.goldendict/). When I had copied configuration to mentioned new location all preferences had applied, but it can't read dictionaries from existing path (it reads added in running GoldenDict-ng path for dictionaries files searching in next format: /run/user/{UID}/doc/{path_code?}/{dictionaries_folder}). Can You return back normal path (but which considers dictionaries through the direct and the same name symbolic links paths to be the same) reading (**it's very critical!**)?
3. I'm using GD on PC with net only for test purposes. I'm using it normally only on stand alone PC. If I'll copy _/var/lib/flatpak/app/io.github.xiaoyifang.goldendict_ng/_ and _~/.var/app/io.github.xiaoyifang.goldendict_ng/_ folders on PC without Internet but with Flatpak installed, will it be there GD-ng runnable?

Thanks in advance.

**Comment by shenlebantongying** [comment]
By default, the Flatpak version doesn't have access to your home `~` and have to add them through protocols (the `/run/user/{UID}/doc/...` thing.

> Can You return back normal path (but which considers dictionaries through the direct and the same name symbolic links paths to be the same) reading?

Yes, you can.

Turn on this option if you want to copy the old index & configures.
 
https://github.com/xiaoyifang/goldendict-ng/issues/1266#issuecomment-1793771730

**Comment by GD-fix** [comment]
I didn't find "Flatseal" even on net repositories. But when in SystemParameters/Applications/Flatpak_packets_permissions (in my own translation to English) I had set write access permissions to GD-ng on "All system files" it worked (see picture).
![GD-ng_flatpak_permissions](https://github.com/xiaoyifang/goldendict-ng/assets/21008593/0c87b316-21c3-4da9-bbba-6098f81f32da)

Can You answer on third my question?

Thanks in advance.

**Comment by shenlebantongying** [comment]
> I'm using GD on PC with net only for test purposes. I'm using it normally only on stand alone PC. If I'll copy /var/lib/flatpak/app/io.github.xiaoyifang.goldendict_ng/ and ~/.var/app/io.github.xiaoyifang.goldendict_ng/ folders on PC without Internet but with Flatpak installed, will it be there GD-ng runnable?

No.

However, they do have a doc on how to move an app to another machine via usb 

https://docs.flatpak.org/en/latest/usb-drives.html

I briefly tried those commands, and appears to work. But I don't have another machine to try. There seem to be other requirements, like adding flathub as remote on the other machine too, and setting "collection id"?

```
mkdir gd_offline
flatpak remote-modify --collection-id=org.flathub.Stable flathub

# the --system may or may not be needed depending on if you install the package to the system.
flatpak create-usb (--system) ./gd_offline/ io.github.xiaoyifang.goldendict_ng

flatpak remove io.github.xiaoyifang.goldendict_ng

# on other machine
flatpak install --sideload-repo ./gd_offline/.ostree/repo/ flathub io.github.xiaoyifang.goldendict_ng
```

---

> You simply create and distribute binaries compiled with statically linked libraries ([like here](https://github.com/lightvector/KataGo/releases/tag/v1.13.0) for example) for GNU/Linux OS?

If that can be "simply" done, the pain of Linux Distro Fragmentation won't even be mentioned :sweat_smile: :sweat_smile:

**Comment by shenlebantongying** [comment]
I think this can be closed, as it is simply too hard to get AppImage to work all the time.
