### ISSUE TITLE
Searching from terminal normalizes text

### ISSUE THREAD

**Issue by seth-js** [xiaoyifang/goldendict-ng#1265]
If I open a command prompt, and enter `goldendict "brüllen"` or `goldendict "rápido"`, GoldenDict searches for "brullen" and "rapido" instead. Is there an option to disable text normalization? Could also be a Windows issue.

- OS: Windows10
- Version: GoldenDict-ng-v23.10.01-alpha.231018.375c537e

**Comment by seth-js** [comment]
It's a Windows issue. Everything is working as expected on macOS. I'll keep trying to see how to fix it.

**Comment by shenlebantongying** [comment]
Cannot reproduce with Windows Terminal + Powershell + Win11.

Maybe it is a problem of the traditional `cmd.exe`? It has nasty details around unicode and got replaced in win11 by Windows Terminal.

https://github.com/xiaoyifang/goldendict-ng/assets/20123683/2ef14fa5-2f90-4446-9de3-7ea59c9b4bb4

**Comment by seth-js** [comment]
Enabling this option in the locale settings fixes it.

![option](https://github.com/xiaoyifang/goldendict-ng/assets/83692925/767fcad7-4615-48c2-908c-6276e45896c9)
