### ISSUE TITLE
Flatpak Version Doesn't Have System File Access

### ISSUE THREAD

**Issue by Harmonyano** [xiaoyifang/goldendict-ng#1266]
**Describe the bug**
Flatpak version doesn't have system file access, so if you want to store your dictionaries in directory such as `~/dicts`, it will be under `/run/user/...` directory instead. After a system reboot, the dictionary settings will be lost. 

**To Reproduce**
1. Use Flatpak version of this app
2. `Edit` -> `Dictionaries` -> `Files`-> `Add...`, look at the **Path** of this newly added dictionary directory

**Expected behavior**
The path should appear as `~/dicts` and should not be lost on every system startup

**Screenshots**
![Screenshot](https://github.com/xiaoyifang/goldendict-ng/assets/30450690/ff6f2d98-dc24-4e5b-83b7-adf7da2827db)

**OS and software versions**

Goldendict-ng 23.09.29.7f0f877 at 2023-10-15T15:05:50
Qt 6.5.3 GCC 12.2.0 org.kde.Platform linux 5.15.0-87-generic x86_64-little_endian-lp64
Flags:USE_XAPIAN MAKE_ZIM_SUPPORT USE_ICONV MAKE_CHINESE_CONVERSION_SUPPORT

Platform | Context
---------|----------
Linux Flatpak

**Comment by shenlebantongying** [comment]
What distro are you using?

The paths are written in the `${XDG_CONFIG_HOME}/goldendict/config`. In flatpak, the config will be inside `~/.var/app/io.github.xiaoyifang.goldendict_ng/config/goldendict/` if installed with `flatpak install --user` or `/var/app/......`

> After a system reboot, the dictionary settings will be lost.

I think for some reason, for every reboot, your `~/.var/app/...` or `/var/app/...` is somehow gone?

Can you check their contents?

Does `~/.var/app/io.github.xiaoyifang.goldendict_ng/config/goldendict/` exists?

---

`/run/user/...` yes this is supposed to happen.

**Comment by Harmonyano** [comment]
Hi, sorry for the late reply. Yes the `~/.var/app/io.github.xiaoyifang.goldendict_ng/config/goldendict/config` file exists and it shows the `/run/user/...` directory as in the GUI. What I'm concerned about is this `/run/user/...` dir itself. 

Please correct me if I'm wrong since I'm new to Linux. Based on my understanding, `/run/user/$UID` dir is wiped once the user with `$UID` logs out and that's the problem I was talking about. When I log into the system next time, hoping to use the dicts I set up in my previous session, those dicts are already gone and I have to import them again.

**Comment by shenlebantongying** [comment]
> /run/user/$UID dir is wiped once the user with $UID logs out 

Yes, that's true. However, the file mappings are stored somewhere else (`.local/share/flatpak/db/documents`). The mapping between `/run/user/$UID/doc/...` <-> `actual paths` should always be stable and same, even between reboots.

<img src="https://github.com/xiaoyifang/goldendict-ng/assets/20123683/f41b0df6-1898-4b54-ad55-72ac3319effd" width=500px>

**Comment by shenlebantongying** [comment]
I don't see a problem with `/run/user/$ID/doc...` which limits apps' ability to access the host system's files arbitrarily, thus safer.

In case you don't like this, you can enable this one in Flatseal, and the folders will be used as normal `~/path_to_dicts`

![image](https://github.com/xiaoyifang/goldendict-ng/assets/20123683/dfd1daa2-e060-4da5-b53d-c4a3ac4e8e80)

**Comment by jrpear** [comment]
> The mapping between `/run/user/$UID/doc/...` <-> `actual paths` should always be stable and same, even between reboots.

This was not my experience so I did some research.

This is true of the XDG Desktop Portal [*Documents* API](https://flatpak.github.io/xdg-desktop-portal/docs/doc-org.freedesktop.portal.Documents.html) when the `persistent` flag is set on one of the `Add` methods.

But currently GoldenDict is using the XDG Desktop Portal [*FileChooser* API](https://flatpak.github.io/xdg-desktop-portal/docs/doc-org.freedesktop.portal.FileChooser.html). Files opened with this interface are not persisted across reboots.

Observe that FileChooser is used:
```
flatpak install io.github.xiaoyifang.goldendict_ng
flatpak run io.github.xiaoyifang.goldendict_ng
dbus-monitor 'interface=org.freedesktop.portal.FileChooser'
# add a new dictionary path with Alt-E-D-A (Edit>Dictionaries>Add)
# observe a use of member OpenFile of org.freedesktop.portal.FileChooser is logged
```

<details>
<summary>(my output)</summary><p>

```
signal time=1717186614.032100 sender=org.freedesktop.DBus -> destination=:1.141 serial=2 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=NameAcquired
   string ":1.141"
signal time=1717186614.032140 sender=org.freedesktop.DBus -> destination=:1.141 serial=4 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=NameLost
   string ":1.141"
method call time=1717186617.410943 sender=:1.117 -> destination=org.freedesktop.portal.Desktop serial=48 path=/org/freedesktop/portal/desktop; interface=org.freedesktop.portal.FileChooser; member=OpenFile
   string "x11:2c000b9"
   string "Choose a directory"
   array [
      dict entry(
         string "current_folder"
         variant             array of bytes "/app/share/goldendict" + \0
      )
      dict entry(
         string "directory"
         variant             boolean true
      )
      dict entry(
         string "filters"
         variant             array [
               struct {
                  string "All Files "
                  array [
                     struct {
                        uint32 0
                        string "*"
                     }
                  ]
               }
            ]
      )
      dict entry(
         string "handle_token"
         variant             string "qt4165284574"
      )
      dict entry(
         string "modal"
         variant             boolean true
      )
      dict entry(
         string "multiple"
         variant             boolean false
      )
   ]
```

</p>
</details>

And Documents is not:

```
dbus-monitor 'interface=org.freedesktop.portal.Documents
# add a new dictionary path with Alt-E-D-A (Edit>Dictionaries>Add)
# observe no use of the org.freedesktop.portal.Documents interface is used
```

<details>
<summary>(my output)</summary><p>

```
signal time=1717186645.092821 sender=org.freedesktop.DBus -> destination=:1.142 serial=2 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=NameAcquired
   string ":1.142"
signal time=1717186645.092943 sender=org.freedesktop.DBus -> destination=:1.142 serial=4 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=NameLost
   string ":1.142"
```

</p></details>

The org.freedesktop.portal.Documents.AddFull API is the one that allows a whole directory to persist rather than just a file (since v4 according to the docs).

Unfortunately I cannot find a helper function in Qt to use this API, so one has to use the DBus interface directly. ChatGPT suggested this code:

<details>
<summary>ChatGPT Code</summary><p>

```cpp
#include <QDBusInterface>
#include <QDBusPendingCall>
#include <QDBusPendingReply>
#include <QVariantMap>
#include <QDebug>

void openFileDialog() {
    QDBusInterface fileChooser(
        "org.freedesktop.portal.Desktop",
        "/org/freedesktop/portal/desktop",
        "org.freedesktop.portal.FileChooser"
    );

    QVariantMap options;
    options["handle_token"] = "mytoken";  // Unique token to identify the request
    options["multiple"] = false;  // Allow multiple file selection

    QDBusPendingCall call = fileChooser.asyncCall("OpenFile", "", options);
    QDBusPendingReply<QVariantMap> reply(call);

    reply.waitForFinished();
    if (reply.isValid()) {
        QVariantMap response = reply.value();
        qDebug() << "File selected:" << response["uris"].toStringList();
    } else {
        qDebug() << "Error:" << reply.error().message();
    }
}
```

</p></details>

However, [this guy](https://bugreports.qt.io/browse/QTBUG-125106) seems to have encountered some trouble doing raw DBus stuff within Qt so that AI-generated code is probably missing something.

The other option I see is to give the flatpak host filesystem permissions by default. But I don't like it.

**Comment by jrpear** [comment]
In the mean time, folks can `sudo flatpak override --filesystem=host io.github.xiaoyifang.goldendict_ng`

**Comment by shenlebantongying** [comment]
The paths exported in flatpak can be inspected with `flatpak documents --columns=id,path`. I still don't find any auto-clean up logic in flatpak. @jrpear 

> But currently GoldenDict is using the XDG Desktop Portal [FileChooser API](https://flatpak.github.io/xdg-desktop-portal/docs/doc-org.freedesktop.portal.FileChooser.html). Files opened with this interface are not persisted across reboots.

Yes, but file opened with be returned through document portal I think.

**Comment by jrpear** [comment]
Ah yes, whoops, you are right. I tried again to observe the export disappearing across a reboot and it did not. I must have made some mistake earlier.
