### ISSUE TITLE
URL handler may fail in some cases

### ISSUE THREAD

**Issue by shenlebantongying** [xiaoyifang/goldendict-ng#1267]
> I asked about this feature yesterday because I could not get it working and the comment was deleted after I discovered that I had foolishly used the old generation GoldenDict to test it. Sorry about that. But now I have encountered a real problem.

> Let me re-introduce some background information first. [Diogenes](https://github.com/pjheslin/diogenes) is a popular tool to browse classical texts, and users have been crying for GoldenDict integration for years. I am trying to add that feature by creating a link like `<a href="goldendict://$word">GoldenDict</a>`. But both Firefox and Chrome URI-encode the href, turning `goldendict://οὐετερανός` into `goldendict://%CE%BF%E1%BD%90%CE%B5%CF%84%CE%B5%CF%81%CE%B1%CE%BD%CF%8C%CF%82`. GoldenDict seems unable to handle such URLs and the search term is decoded as `CE�ὐετερανός` (notice that only the first letter is not properly decoded). Am I doing it in the wrong way? Or is it a real issue and I should open one instead? By the way, `xdg-open goldendict://οὐετερανός` works very well.

Anyway, thanks for this extremely useful feature!

_Originally posted by @Crissium in https://github.com/xiaoyifang/goldendict-ng/issues/227#issuecomment-1789883557_

**Comment by shenlebantongying** [comment]
Surprisingly, GD is already able to decode url.

![image](https://github.com/xiaoyifang/goldendict-ng/assets/20123683/145f0d7f-5761-4c9a-a75a-54e7b2a53517)

---

This `goldendict://οὐετερανός` works in Microsoft Word.

https://github.com/xiaoyifang/goldendict-ng/assets/20123683/ef02549f-0023-429f-8f4a-2e2461555757

---

But it becomes something strange from Firefox & Win11's File Explorer.

The URL appears to be auto-encoded on firefox's side.

![image](https://github.com/xiaoyifang/goldendict-ng/assets/20123683/6696307f-0aba-4d0c-9268-8072c51a86a2)

**Comment by shenlebantongying** [comment]
"xdg-open" is a lie that dispatches the URL to actual openers.

For GNOME -> `gio open` -> Works perfectly

<img src="https://github.com/xiaoyifang/goldendict-ng/assets/20123683/3d9b66f9-3364-4f8b-9c0b-b6edf59969ea" width=200>

For KDE -> `kde-open`5 -> ???
<img src="https://github.com/xiaoyifang/goldendict-ng/assets/20123683/e55db948-57a9-4a48-8de2-1a318b85fb82" width=200>

**Comment by shenlebantongying** [comment]
Firefox on Linux works fine.
![Screenshot from 2023-11-01 21-57-43](https://github.com/xiaoyifang/goldendict-ng/assets/20123683/408a484a-6dbe-44d7-8d98-5f1136dd2362)

**Comment by Crissium** [comment]
> Surprisingly, GD is already able to decode url.

Yes, my version is '23.05.03-alpha. on Tue Jun 6 16:10:00 2023' and it is also able to decode URL:

![Screenshot_2023-11-02_09-53-59](https://github.com/xiaoyifang/goldendict-ng/assets/91039086/3116ff37-0ba2-4d7a-b722-18fa23f4e32a)

And this does not work, as expected:

```
gio open goldendict://%CE%BF%E1%BD%90%CE%B5%CF%84%CE%B5%CF%81%CE%B1%CE%BD%CF%8C%CF%82
```
![3](https://github.com/xiaoyifang/goldendict-ng/assets/91039086/406d1f14-2dca-48cc-8e7c-d57e41ce6a46)


Firefox on Linux does not work for me :(

![2](https://github.com/xiaoyifang/goldendict-ng/assets/91039086/3a5f92c3-b502-4285-a8ec-96dfd904be6c)

**Comment by Crissium** [comment]
I rechecked the result of `gio open` and found that the actual search term sent to GoldenDict became `CE%BF%E1%BD%90%CE%B5%CF%84%CE%B5%CF%81%CE%B1%CE%BD%CF%8C%CF%82` (note the missing % at the beginning). Perhaps this is not a bug of GoldenDict then?

**Comment by shenlebantongying** [comment]
I don't have more time to investigate today.
but setting a breakpoint here will yield what's really received

https://github.com/xiaoyifang/goldendict-ng/blob/764fef97e6079eb80be86535bd7417d4aa385a9d/thirdparty/qtsingleapplication/src/qtlocalpeer.cpp#L179

This is the message received  on Win11+firefox

`goldendict://οὐετερανός` -> `uMsg` is utf8

![image](https://github.com/xiaoyifang/goldendict-ng/assets/20123683/d5f71cb4-59ff-42c8-af6e-444271b395b9)

**Comment by shenlebantongying** [comment]
> gio open and found that the actual search term sent to GoldenDict became CE%BF%E1%BD%90%CE%B5%CF%84%CE%B5%CF%81%CE%B1%CE%BD%CF%8C%CF%82 (note the missing % at the beginning). Perhaps this is not a bug of GoldenDict then?

I am not sure. How do u know `gio` sent that message? Only the `goldendict://` part got chopped, and I don't see bug in this code.

https://github.com/xiaoyifang/goldendict-ng/blob/764fef97e6079eb80be86535bd7417d4aa385a9d/src/main.cc#L294-L304

Then the word is processed via QCommandParser, and will later always be passed as QString(internal utf16). Then this word will be passed to QSingleApplication -> converted to utf8 (QString::toUtf8) -> sent to the main instance and converted from utf8 back to QString(utf16).

Some possible reasons:

* Before Goldendict got the word, it might not be utf8 when getting from Firefox? (Windows quirks??)
* QCommandParser? -> Cannot handle certain encoding?

-> Need to save what's QCommandPaser got when getting from Firefox.

* QSinglApplication?

**Comment by shenlebantongying** [comment]
> For KDE -> `kde-open5` -> ??? <img src="https://github.com/xiaoyifang/goldendict-ng/assets/20123683/e55db948-57a9-4a48-8de2-1a318b85fb82" width=200>

This behaviour is this one, `bühler` will be converted into `xn–bhler-kva`??? What??:

> For example, the unencoded URL "http://bühler.example.com/List of applicants.xml" would be sent to the server as "http://xn–bhler-kva.example.com/List%20of%20applicants.xml".

https://doc.qt.io/qt-6/qurl.html#details

**Comment by Crissium** [comment]
> I am not sure. How do u know gio sent that message? Only the goldendict:// part got chopped, and I don't see bug in this code.
> https://github.com/xiaoyifang/goldendict-ng/blob/764fef97e6079eb80be86535bd7417d4aa385a9d/src/main.cc#L294-L304
> Then the word is processed via QCommandParser, and will later always be passed as QString(internal utf16). Then this word will be passed to QSingleApplication -> converted to utf8 (QString::toUtf8) -> sent to the main instance and converted from utf8 back to QString(utf16).

Thanks for the explanation. Unfortunately I cannot build gd at the moment because of incompatible cmake version.

> This behaviour is this one, bühler will be converted into xn–bhler-kva??? What??:

Something interesting:

![1](https://github.com/xiaoyifang/goldendict-ng/assets/91039086/3c388152-bfa6-40cd-a6c4-b88b512503ca)
![2](https://github.com/xiaoyifang/goldendict-ng/assets/91039086/199871d4-1423-4966-8710-104ca14d442a)
![3](https://github.com/xiaoyifang/goldendict-ng/assets/91039086/336c5349-a46f-4988-aeed-2dec883d5791)
![4](https://github.com/xiaoyifang/goldendict-ng/assets/91039086/1c82f50d-a3e2-4756-aac8-acd56b52a6a6)

```javascript
decodeURIComponent('%E4%BD%A0%E5%A5%BD')
'你好'
```

So I think it might not be a problem with gd itself.

**Comment by xiaoyifang** [comment]
I think there are two issues listed in this thread.
1, why % got chopped off.

2, Punycode encoding 
which can be solved by https://doc.qt.io/qt-6/qurl.html#fromAce

**Comment by Resend1298** [comment]
I've also encountered this issue.
`xdg-open goldendict://あ` -> `xn--l8j`
`xdg-open goldendict://あ.` -> `あ.`
`xdg-open goldendict:///あ` -> `/あ`
Punycode decoding seems to work under some conditions, weird.

**Comment by shenlebantongying** [comment]
Although they are called Punycode, url only a subset of it called ACE and qt have built in things to handle it. 

![image](https://github.com/xiaoyifang/goldendict-ng/assets/20123683/cc0a13bd-4e39-47e2-a6b5-0abbff2458d5)

https://doc.qt.io/qt-6/qurl.html#fromAce

**Comment by Resend1298** [comment]
maybe related:
https://bugreports.qt.io/browse/QTBUG-29080

**Comment by shenlebantongying** [comment]
Thanks for your info. I kept reading the doc and couldn't figure out why it didn't work.

I think we can just append then remove a `.com` domain to bypass the restriction :smile:
