### ISSUE TITLE
Search form (left pane, Ctrl + S) is very narrow and not resizeable

### ISSUE THREAD

**Issue by Amr-Ibra** [xiaoyifang/goldendict-ng#1268]
**Describe the bug**

Search form (left pane, Ctrl + S) is very narrow and not resizeable.

**To Reproduce**

1. Go to Search form (Ctrl + S)
2. It is too narrow and not resizeable

**Expected behaviour**

Search form (left pane, Ctrl + S) should not be very narrow and should be resizeable.

**Screenshots**

![goldendict](https://github.com/xiaoyifang/goldendict-ng/assets/45657128/d25011c1-5b4e-4545-bb56-c020ffc9aa8e)

**OS and software versions**

Goldendict-ng 23.09.08 at 2023-10-17T18:43:44
Qt 6.4.2 GCC 13.2.0 debian linux 6.5.0-3-amd64 x86_64-little_endian-lp64
Flags:USE_XAPIAN MAKE_ZIM_SUPPORT USE_ICONV MAKE_CHINESE_CONVERSION_SUPPORT

**Comment by shenlebantongying** [comment]
This is because the right panel and the display area have minimum widths and the window's size is limited, thus there is no space for the left panel.

Just make the window larger so that there is more space for the left panel.

**Comment by Amr-Ibra** [comment]
> Just make the window larger so that there is more space for the left panel.

It was not very obvious to me. It worked. Thanks.

**Comment by shenlebantongying** [comment]
I don't think something needed to be fixed.
