### ISSUE TITLE
[Bug] Failure to index some .dsl dictionaries (UTF16 without BOM)

### ISSUE THREAD

**Issue by Exponent4806** [xiaoyifang/goldendict-ng#1278]
**Describe the bug**
Some .dsl files can be added to the list of dictionaries, but the software fails to index the headwords. So it loads a "ghost" dictionary with no Title and no headwords. 

**To Reproduce**
1. Download a sample of 5 German Dictionaries in .dsl format: 
https://nch.pl/s/6L7r9caNby4n8LJ
3. Try to index those dictionaries
4. GoldenDict shows "0 headwords" and no Title for those dictionaries.

**Affected Dictionaries**

At least 10 dictionaries (English and German). Many of them are made by myself but not all!

**Download:** https://nch.pl/s/6L7r9caNby4n8LJ

**Expected behavior**
All those .dsl dictionaries should work normally. GoldenDict-ng was able to recognize them few months ago. 

**Screenshots**

![image](https://github.com/xiaoyifang/goldendict-ng/assets/121114125/07bc843d-f5a3-4e38-bb36-642e8ca465d4)

![image](https://github.com/xiaoyifang/goldendict-ng/assets/121114125/b58634f2-69a6-4cc2-8200-b6a9593ad11b)

**OS and software versions**
_Goldendict-ng 23.10.01.2799b41c at 2023-11-06T18:24:56
Qt 6.6.0 GCC 13.2.1 20230801 endeavouros linux 6.6.1-arch1-1 x86_64-little_endian-lp64
Flags:USE_XAPIAN MAKE_ZIM_SUPPORT USE_ICONV MAKE_CHINESE_CONVERSION_SUPPORT_

![image](https://github.com/xiaoyifang/goldendict-ng/assets/121114125/c6ba9726-a8cc-4e5d-a1c0-0fa63dd8dd62)

**Additional context**
The .dsl files were working correctly a couple of months ago. Then , I changed from Manjaro OS to EndeavourOS (Arch Linux) and installed the git version from AUR. Suddenly, around 10 .dsl dictionaries are unusable. I presume that the problem lies in the commits of the last couple of months of GD.

I am not sure if the issue can be reproduced in other OSes apart from EndeavourOS. I presume that yes. 

**Could you please try to reproduce this bug ?**

Thanks for your great work! :heart:

**Comment by Exponent4806** [comment]
The bug is also present in the latest "official GoldenDict" (by Abs62) but older versions of GoldenDict can read the .dsl files normally: 

![image](https://github.com/xiaoyifang/goldendict-ng/assets/121114125/23cbc157-c573-4b32-a508-6c63bfb53882)

 > With this portable version (for Windows) works, tested: https://mega.nz/folder/LPB23LLA#1cmW6RcwX6pB6yEvrEcOYQ

---
This observation is thanks to a member of FreeMDict that has a Windows Machine...
https://forum.freemdict.com/t/topic/18498/6

**Comment by shenlebantongying** [comment]
The problem can be narrowed down to failure to recognize [UTF-16 without byte order marks (`U+FEFF`)](https://en.wikipedia.org/wiki/UTF-16#Byte-order_encoding_schemes)

Minimum test files: with and without the UTF-16's BOM [utf-16_BOM_tests.zip](https://github.com/xiaoyifang/goldendict-ng/files/13301793/utf-16_BOM_tests.zip)

The one that has BOM works.

By the way, the `file` command and Kate (KDE's editor) also failed to recognize the UTF-16 file without BOM.
```
> file -bi ./utf-16_with_byte_order_marks.dsl
text/plain; charset=utf-16le
> file -bi ./utf-16_without_byte_order_marks.dsl
application/octet-stream; charset=binary     <--- recognized as binary instead of utf16?
```
![image](https://github.com/xiaoyifang/goldendict-ng/assets/20123683/afced728-2519-466f-af8a-e362fdda0d27)

**Comment by shenlebantongying** [comment]
Temporal workarounds:

* Convert the `.dsl` file to utf8
* Delete the `.dsl` files and rename the `.txt` source file to `.dsl`, the dict author was working around the original GD's limitation around utf8.

<img src="https://github.com/xiaoyifang/goldendict-ng/assets/20123683/a3b6c169-881b-479f-82b5-0fcbcbfbf287" width=500px>

**Comment by Exponent4806** [comment]
Thanks for your kind help @shenlebantongying .    I created the files in UTF16 without BOOM in Kate (Manjaro KDE). I can open the .dsl files normally on Kate in EndeavourOS:

![image](https://github.com/xiaoyifang/goldendict-ng/assets/121114125/e87902f2-51fc-4c4c-bad8-905c3d8df2b2)

However, I tried 4-5 text editors different than Kate and they cannot open the file. Even VSCodium (Visual Studio Code) cannot open it. 

Opening the .txt file and saving it as UTF8 is the simplest solution. However, there is one dictionary in which I only have the .dsl file (without the .txt). There seems to be no solution there :(

Kate opens the .dsl file but it cannot be saved from .dsl into .txt with UTF8. I  tried via terminal with GNU "iconv" to convert from UTF16 to UTF8 and failed.

It seems that the bug is caused by Kate itself. That is quite strange...

Anyway, GoldenDict seems to be working fine. I will close this issue. 

**Many thanks for your great work with GoldenDict...!**

**Comment by shenlebantongying** [comment]
UTF-16 decoding needs to know the byte order.

BOM is necessary for text editors, but DSL dictionaries always start with the string `#NAME`.

We can add an extra round of guessing based on how `#NAME` is encoded when all other guessings fail.

If there is no BOM, then we can check the first few bytes

* `0x 2300 4e00 4100 4d00 4500` -> UTF-16LE
* `0x 0023 004e 0041 004d 0045` -> UTF-16BE

**Comment by xiaoyifang** [comment]
only check the first byte  `2300 `

**Comment by xiaoyifang** [comment]
I afraid next may come UTF32 without bom.
