### ISSUE TITLE
version v23.11.08 can't read dsl dictionaries from jd4gd

### ISSUE THREAD

**Issue by cuongduong73** [xiaoyifang/goldendict-ng#1280]
**Describe the bug**
The goldendict-ng version [v23.11.08](https://github.com/xiaoyifang/goldendict-ng/releases/tag/v23.11.08-BeginningOfWinter.ff83be8a) can't read dictionaries from [jd4gd](https://jd4gd.com/), but the origin version [1.5.0-RC2](https://onboardcloud.dl.sourceforge.net/project/goldendict/early%20access%20builds/GoldenDict-1.5.0-RC2-372-gc3ff15f-Install.exe) do

**To Reproduce**
1. Download dictionary from [jd4gd](https://jd4gd.com), for example: [JMDictplus](https://jd4gd.com/files/JMDictplus.zip)
2. Import to goldendict-ng
3. After the import process finished, the dictionary is empty and doesn't have any index or content.

Please check and fix this issue if possible.

**Comment by xiaoyifang** [comment]
This is a dsl dictionary ,and has the same cause with https://github.com/xiaoyifang/goldendict-ng/issues/1278

**Comment by xiaoyifang** [comment]
try release from https://github.com/xiaoyifang/goldendict-ng/releases/tag/v23.11.09-alpha.b2a8eec2

**Comment by cuongduong73** [comment]
> try release from https://github.com/xiaoyifang/goldendict-ng/releases/tag/v23.11.09-alpha.b2a8eec2
Thank you that release fixed the issue.
