### ISSUE TITLE
[Bug] "libzim" dependency was updated and GD cannot run on Arch Linux 

### ISSUE THREAD

**Issue by Exponent4806** [xiaoyifang/goldendict-ng#1288]
**Describe the bug**
"[libzim](https://archlinux.org/packages/extra/x86_64/libzim/)" dependency was updated from  8.2.1-1 to  9.0.0-1 (Nov. 14th 2023).

I updated the libzim dependency on EndeavourOS (Arch Linux) and afterwards I cannot run GoldenDict-ng. 

I uninstalled the package "goldendict-ng-git" and reinstalled it. It did not work. I guess that libzim 9.0 might be incompatible with the current code on GD..

**To Reproduce**

1. update libzim on Arch Linux: **yay -S libzim**
2. Try to run GoldenDict-ng (git version from AUR repository)
3. The GUI does not appear.

**Expected behavior**
GD should work with the newest "libzim" dependency.

**OS and software versions**
AUR: [goldengict-ng-git](https://aur.archlinux.org/packages/goldendict-ng-git)

![image](https://github.com/xiaoyifang/goldendict-ng/assets/121114125/de374e5c-a039-4e57-9e5e-24dd3a801201)

**Additional context**
 I am a layman in Computer Science (I am a medical Doctor). Sorry if I cannot provide more details, but I would be glad to help as much as possible.

**Thanks for your great work and dedication!**  _Your version of GoldenDict is my favorite software! :smiley:

**Comment by shenlebantongying** [comment]
> The AUR is unsupported, so any packages you install are your responsibility to update, not pacman's. If packages in the official repositories are updated, you will need to rebuild any AUR packages that depend on those libraries. 

https://wiki.archlinux.org/title/Arch_User_Repository#Updating_packages

Arch is KISS distro and AUR has nothing fancy. pacman does not track AUR pacakges' dependency changes. If they are no longer compatible, you need to manually trigger upgrade. Just do `yay -Syu goldendict-ng-git` again.
