### ISSUE TITLE
Installation issue: GoldenDict-ng-v23.11.09-alpha.231120（mac版）

### ISSUE THREAD

**Issue by yshumy** [xiaoyifang/goldendict-ng#1294]
-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               GoldenDict [39547]
Path:                  /Applications/GoldenDict.app/Contents/MacOS/GoldenDict
Identifier:            org.xiaoyifang
Version:               23.11 (???)
Code Type:             X86-64 (Translated)
Parent Process:        launchd [1]
User ID:               501

Date/Time:             2023-11-22 19:42:07.4700 +0800
OS Version:            macOS 12.7 (21G816)
Report Version:        12
Anonymous UUID:        ACE98172-167E-A198-0C40-13044CC98919

Time Awake Since Boot: 2400000 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    Namespace DYLD, Code 1 Library missing
Library not loaded: '@loader_path/../../../../opt/zstd/lib/libzstd.1.dylib'
Referenced from: '/Applications/GoldenDict.app/Contents/Frameworks/libzim.8.dylib'
Reason: tried: '' (no such file), '' (no such file), '' (no such file)
(terminated at launch; ignore backtrace)

Kernel Triage:
VM - pmap_enter failed with resource shortage
VM - pmap_enter failed with resource shortage
VM - pmap_enter failed with resource shortage
VM - pmap_enter failed with resource shortage
VM - pmap_enter failed with resource shortage

Thread 0 Crashed:
0   Rosetta Runtime Routines	       0x1032bf940 ???
1   <translation info unavailable>	       0x103312b8c ???
2   dyld                          	       0x202ea7a72 abort_with_payload_wrapper_internal + 80
3   dyld                          	       0x202ea7aa4 abort_with_payload + 9
4   dyld                          	       0x202e55699 dyld4::halt(char const*) + 615
5   dyld                          	       0x202e515b5 dyld4::prepare(dyld4::APIs&, dyld3::MachOAnalyzer const*) + 3995
6   dyld                          	       0x202e504e4 start + 388

Thread 1:: com.apple.rosetta.exceptionserver
0   runtime                       	    0x7ff7ffbd7944 0x7ff7ffbd3000 + 18756
1   runtime                       	    0x7ff7ffbe53e0 0x7ff7ffbd3000 + 74720
2   runtime                       	    0x7ff7ffbe6e58 0x7ff7ffbd3000 + 81496

Thread 0 crashed with ARM Thread State (64-bit):
    x0: 0x0000000000000006   x1: 0x0000000000000001   x2: 0x00000003096f2150   x3: 0x000000000000008a
    x4: 0x00000003096f1d50   x5: 0x0000000000000000   x6: 0x00007ff8182f4000   x7: 0x000000209c3b8cf8
    x8: 0x00000003096f1d50   x9: 0x0000000000000000  x10: 0x000000000000008a  x11: 0x00000003096f219a
   x12: 0x000000000000008a  x13: 0x00000003096f2150  x14: 0x0000000000000001  x15: 0x0000000000000006
   x16: 0x0000000000000209  x17: 0x0000000000000000  x18: 0x800000010b328b70  x19: 0x00000001032b5000
   x20: 0x00000000000007ff  x21: 0x000000010b32dfa0  x22: 0xffffffffffffffff  x23: 0x00000001032bf914
   x24: 0x0000000202ea7a72  x25: 0x00000001032bf1f4  x26: 0x0000000103312130  x27: 0x0000000000000000
   x28: 0x0000000202e9198e   fp: 0x000000002c000000   lr: 0x0000000103312b8c
    sp: 0x000000010b328b70   pc: 0x00000001032bf940 cpsr: 0x80001000
   far: 0x0000000103312000  esr: 0x56000080  Address size fault

Binary Images:
               0x0 - 0xffffffffffffffff ??? (*) <00000000-0000-0000-0000-000000000000> ???
       0x202e4b000 -        0x202eb6fff dyld (*) <65540238-1367-3f2e-978b-3278e73c124b> /usr/lib/dyld
    0x7ff7ffbd3000 -     0x7ff7ffc02fff runtime (*) <1c03a894-2ec6-3f7f-ae86-0071b1ee57ef> /usr/libexec/rosetta/runtime

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 27
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=1.1G resident=0K(0%) swapped_out_or_unallocated=1.1G(100%)
Writable regions: Total=158.2M written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=158.2M(100%)

                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
Rosetta Arena                     4096K        2 
Rosetta Generic                    804K      198 
Rosetta IndirectBranch              32K        1 
Rosetta JIT                      128.0M        1 
Rosetta Return Stack                20K        2 
Rosetta Thread Context              20K        2 
Stack                             8176K        1 
Stack Guard                       56.0M        1 
VM_ALLOCATE                       13.3M        6 
VM_ALLOCATE (reserved)             612K       33         reserved VM address space (unallocated)
__DATA                            19.2M      278 
__DATA_CONST                      18.5M      182 
__DATA_DIRTY                       485K       85 
__FONT_DATA                          4K        1 
__LINKEDIT                       715.7M       44 
__OBJC_RO                         82.9M        1 
__OBJC_RW                         3200K        1 
__TEXT                           399.4M      293 
__UNICODE                          592K        1 
dyld private memory               1024K        1 
mapped file                        5.5G      417 
===========                     =======  ======= 
TOTAL                              6.9G     1551 
TOTAL, minus reserved VM space     6.9G     1551 

-----------
Full Report
-----------

{"app_name":"GoldenDict","timestamp":"2023-11-22 19:42:07.00 +0800","app_version":"23.11","slice_uuid":"7a3ddaec-d9c6-3c5a-b07f-4de3fb0f7a38","build_version":"","platform":1,"bundleID":"org.xiaoyifang","share_with_app_devs":1,"is_first_party":0,"bug_type":"309","os_version":"macOS 12.7 (21G816)","incident_id":"92A88474-8DF4-4F5C-A209-72023CBE0878","name":"GoldenDict"}
{
  "uptime" : 2400000,
  "procLaunch" : "2023-11-22 19:42:07.3856 +0800",
  "procRole" : "Default",
  "version" : 2,
  "userID" : 501,
  "deployVersion" : 210,
  "modelCode" : "Macmini9,1",
  "procStartAbsTime" : 59952291333238,
  "coalitionID" : 340479,
  "osVersion" : {
    "train" : "macOS 12.7",
    "build" : "21G816",
    "releaseType" : "User"
  },
  "captureTime" : "2023-11-22 19:42:07.4700 +0800",
  "incident" : "92A88474-8DF4-4F5C-A209-72023CBE0878",
  "bug_type" : "309",
  "pid" : 39547,
  "procExitAbsTime" : 59952293352218,
  "translated" : true,
  "cpuType" : "X86-64",
  "procName" : "GoldenDict",
  "procPath" : "\/Applications\/GoldenDict.app\/Contents\/MacOS\/GoldenDict",
  "bundleInfo" : {"CFBundleShortVersionString":"23.11","CFBundleIdentifier":"org.xiaoyifang"},
  "storeInfo" : {"deviceIdentifierForVendor":"96C16DBB-117C-5E17-9023-77CA1BCD7887","thirdParty":true},
  "parentProc" : "launchd",
  "parentPid" : 1,
  "coalitionName" : "org.xiaoyifang",
  "crashReporterKey" : "ACE98172-167E-A198-0C40-13044CC98919",
  "sip" : "enabled",
  "isCorpse" : 1,
  "exception" : {"codes":"0x0000000000000000, 0x0000000000000000","rawCodes":[0,0],"type":"EXC_CRASH","signal":"SIGABRT"},
  "termination" : {"code":1,"flags":518,"namespace":"DYLD","indicator":"Library missing","details":["(terminated at launch; ignore backtrace)"],"reasons":["Library not loaded: '@loader_path\/..\/..\/..\/..\/opt\/zstd\/lib\/libzstd.1.dylib'","Referenced from: '\/Applications\/GoldenDict.app\/Contents\/Frameworks\/libzim.8.dylib'","Reason: tried: '' (no such file), '' (no such file), '' (no such file)"]},
  "ktriageinfo" : "VM - pmap_enter failed with resource shortage\nVM - pmap_enter failed with resource shortage\nVM - pmap_enter failed with resource shortage\nVM - pmap_enter failed with resource shortage\nVM - pmap_enter failed with resource shortage\n",
  "extMods" : {"caller":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"system":{"thread_create":0,"thread_set_state":0,"task_for_pid":27},"targeted":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"warnings":0},
  "faultingThread" : 0,
  "threads" : [{"triggered":true,"id":26494544,"threadState":{"x":[{"value":6},{"value":1},{"value":13043179856},{"value":138},{"value":13043178832},{"value":0},{"value":140703534366720},{"value":140060101880},{"value":13043178832},{"value":0},{"value":138},{"value":13043179930},{"value":138},{"value":13043179856},{"value":1},{"value":6},{"value":521},{"value":0},{"value":9223372041337604976},{"value":4348137472},{"value":2047},{"value":4482850720},{"value":18446744073709551615},{"value":4348180756},{"value":8638855794,"symbolLocation":80,"symbol":"abort_with_payload_wrapper_internal"},{"value":4348178932},{"value":4348518704},{"value":0},{"value":8638765454,"symbolLocation":10,"symbol":"__abort_with_payload"}],"flavor":"ARM_THREAD_STATE64","lr":{"value":4348521356},"cpsr":{"value":2147487744},"fp":{"value":738197504},"sp":{"value":4482829168},"esr":{"value":1442840704,"description":" Address size fault"},"pc":{"value":4348180800,"matchesCrashFrame":1},"far":{"value":4348518400}},"frames":[{"imageOffset":4348180800,"region":"Rosetta Runtime Routines","symbolLocation":10560,"imageIndex":0},{"imageOffset":4348521356,"region":"<translation info unavailable>","imageIndex":0},{"imageOffset":379506,"symbol":"abort_with_payload_wrapper_internal","symbolLocation":80,"imageIndex":1},{"imageOffset":379556,"symbol":"abort_with_payload","symbolLocation":9,"imageIndex":1},{"imageOffset":42649,"symbol":"dyld4::halt(char const*)","symbolLocation":615,"imageIndex":1},{"imageOffset":26037,"symbol":"dyld4::prepare(dyld4::APIs&, dyld3::MachOAnalyzer const*)","symbolLocation":3995,"imageIndex":1},{"imageOffset":21732,"symbol":"start","symbolLocation":388,"imageIndex":1}]},{"id":26494547,"name":"com.apple.rosetta.exceptionserver","frames":[{"imageOffset":18756,"imageIndex":2},{"imageOffset":74720,"imageIndex":2},{"imageOffset":81496,"imageIndex":2}]}],
  "usedImages" : [
  {
    "size" : 0,
    "source" : "A",
    "base" : 0,
    "uuid" : "00000000-0000-0000-0000-000000000000"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 8638476288,
    "size" : 442368,
    "uuid" : "65540238-1367-3f2e-978b-3278e73c124b",
    "path" : "\/usr\/lib\/dyld",
    "name" : "dyld"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 140703124238336,
    "size" : 196608,
    "uuid" : "1c03a894-2ec6-3f7f-ae86-0071b1ee57ef",
    "path" : "\/usr\/libexec\/rosetta\/runtime",
    "name" : "runtime"
  }
],
  "sharedCache" : {
  "base" : 140703420465152,
  "size" : 19331678208,
  "uuid" : "18c0cf72-8655-3222-b471-56a154098595"
},
  "vmSummary" : "ReadOnly portion of Libraries: Total=1.1G resident=0K(0%) swapped_out_or_unallocated=1.1G(100%)\nWritable regions: Total=158.2M written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=158.2M(100%)\n\n                                VIRTUAL   REGION \nREGION TYPE                        SIZE    COUNT (non-coalesced) \n===========                     =======  ======= \nRosetta Arena                     4096K        2 \nRosetta Generic                    804K      198 \nRosetta IndirectBranch              32K        1 \nRosetta JIT                      128.0M        1 \nRosetta Return Stack                20K        2 \nRosetta Thread Context              20K        2 \nStack                             8176K        1 \nStack Guard                       56.0M        1 \nVM_ALLOCATE                       13.3M        6 \nVM_ALLOCATE (reserved)             612K       33         reserved VM address space (unallocated)\n__DATA                            19.2M      278 \n__DATA_CONST                      18.5M      182 \n__DATA_DIRTY                       485K       85 \n__FONT_DATA                          4K        1 \n__LINKEDIT                       715.7M       44 \n__OBJC_RO                         82.9M        1 \n__OBJC_RW                         3200K        1 \n__TEXT                           399.4M      293 \n__UNICODE                          592K        1 \ndyld private memory               1024K        1 \nmapped file                        5.5G      417 \n===========                     =======  ======= \nTOTAL                              6.9G     1551 \nTOTAL, minus reserved VM space     6.9G     1551 \n",
  "legacyInfo" : {
  "threadTriggered" : {

  }
},
  "trialInfo" : {
  "rollouts" : [
    {
      "rolloutId" : "5ffde50ce2aacd000d47a95f",
      "factorPackIds" : {

      },
      "deploymentId" : 240000348
    },
    {
      "rolloutId" : "607844aa04477260f58a8077",
      "factorPackIds" : {
        "SIRI_MORPHUN_ASSETS" : "6103050cbfe6dc472e1c982a"
      },
      "deploymentId" : 240000066
    }
  ],
  "experiments" : [

  ]
}
}

Model: Macmini9,1, BootROM 8422.141.2, proc 8:4:4 processors, 16 GB, SMC 
Graphics: Apple M1, Apple M1, Built-In
Display: VX2880-4K-HDU, 3840 x 2160 (2160p/4K UHD 1 - Ultra High Definition), Main, MirrorOff, Online
Memory Module: LPDDR4
AirPort: Wi-Fi, wl0: Mar 23 2022 19:57:59 version 18.60.27.0.7.8.129 FWID 01-570be953
Bluetooth: Version (null), 0 services, 0 devices, 0 incoming serial ports
Network Service: Ethernet, Ethernet, en0
Network Service: Wi-Fi, AirPort, en1
USB Device: USB31Bus
USB Device: aigo U397
USB Device: USB2.0 HUB
USB Device: Mass Storage Device
USB Device: USB31Bus
USB Device: USB2.0 Hub
USB Device: USB30Bus
USB Device: Keychron K8 Pro
USB Device: Rapoo Gaming Device
Thunderbolt Bus: Mac mini, Apple Inc.
Thunderbolt Bus: Mac mini, Apple Inc.

**Comment by xiaoyifang** [comment]
试下最新版
