### ISSUE TITLE
Dictionary js is loaded twice

### ISSUE THREAD

**Issue by popyoung** [xiaoyifang/goldendict-ng#1295]
起因：剑桥词典的 more example 打不开。
调试后发现目录下js加载了两次，导致click事件重复加载。一次响应展开了 example，第二次响应又关闭了。
我先自己修改下js，防止多次加载。

**Comment by xiaoyifang** [comment]
原则上不会加载2次，是不是有其他词典的影响

**Comment by shenlebantongying** [comment]
It looks like dictionary's problem. Need more info.
