### ISSUE TITLE
Wrong GoldenDict-ng version

### ISSUE THREAD

**Issue by GD-fix** [xiaoyifang/goldendict-ng#1301]
**Describe the bug**
Today updated GD-ng version is  23.09.08 (see the first screenshot), while the last (yesterday uploaded) pre-release version is 23.11.09 (see the second screenshot) and latest release is 23.11.08.

**To Reproduce**
1. Open the [mentioned in the pre-release link ](https://flathub.org/apps/io.github.xiaoyifang.goldendict_ng), click "Install" and open it in Discover (if not did all these yet, otherwise simply update GoldenDict-ng in Discover).
2. Go to 'Discover/Installed'
3. Click on 'GoldenDict-ng'

**Expected behavior**
Because in current pre-release there is the link to source from which GoldenDict-ng was updated in Discover, the versions in pre-release and Discover must be the same.

**Screenshots**
![GD-ng_version](https://github.com/xiaoyifang/goldendict-ng/assets/21008593/a0946d0a-8bf9-4d37-b719-f3ebd9f29f47)
![Current_prerelease](https://github.com/xiaoyifang/goldendict-ng/assets/21008593/b10d118d-b1f1-4227-ac64-86317af768ad)

**OS and software versions**
- OS: OpenSUSE Tumbleweed
- Version up to date

**Comment by shenlebantongying** [comment]
That version number does not really matter. I deleted the `<releases>` from metadata.xml and automated it, but flathub's auto update will stick to the current release version which is before the delectation of it.

It will be fixed automatically when the next release is cut.

You can open GD's help -> about to confirm the version is actually update to data.

Sorry for confusion.

https://github.com/flathub/io.github.xiaoyifang.goldendict_ng/blob/master/io.github.xiaoyifang.goldendict_ng.json#L155

https://github.com/xiaoyifang/goldendict-ng/commit/82d7f1cf76765e301547533cbbf9d6f5e32a356b
