### ISSUE TITLE
GD-ng stopped supporting the /tmp in paths to search for the dictionary files

### ISSUE THREAD

**Issue by GD-fix** [xiaoyifang/goldendict-ng#1306]
**Describe the bug**
When the path contains the "_/tmp_" (or "_/var/tmp_") dictionaries stopped appear in GD-ng nevertheless of this path existing in output "handle path:".
**_According to updated information it doesn't support any subfolder on containing "/" (Root) partition..._**

**To Reproduce**
1. Create the symbolic link in /tmp to dictionaries folder and go to 'Dictionaries/Sources/Files'
2. Change path to _/tmp/{folder}_
3. Click on 'OK'

**Expected behavior**
Because the _/tmp_ (or "_/var/tmp_) path is the only writeable for all users it must remain supported (or must add the "_~/_" support in the path).

**OS and software versions**
- OS: OpenSUSE Tumbleweed
- Version up to date

**Additional context**
On stand-alone (without net) PC Flatpak GD-ng version works by copying from the same but different versions OS (at least) _/var/lib/flatpak/_ folder (without subfolder "repo") and after setting up to GD-ng the next permissions to file system:
![_GD-ng_flatpak_permissions](https://github.com/xiaoyifang/goldendict-ng/assets/21008593/5751e5e9-46eb-4e88-9831-66402dca0422)

**Comment by shenlebantongying** [comment]
I don't know what flatpak does to /tmp yet.

However, based on your description, I think what you really want is path-independent dictionaries grouping.

Maybe you can try auto-grouping by folder or metadata.

https://xiaoyifang.github.io/goldendict-ng/manage_groups/#auto-groups-by-folders

Note that it does modify existing groups, maybe you want to backup or try a few dictionaries for experiments before actually using it.

**Comment by GD-fix** [comment]
You didn't understand, what is needed (and what is the problem itself at all: see the text highlighted in bold in the first message). 
1. There isn't supported any dictionaries path on partition containing Root ("/") even if there is only a symbolic link to folder on another partition. So, in case (of course, unusual) of only one partition using there will not be able to add any dictionary in GD-ng at all. Flatpak itself supports paths on partition containing Root, because GD-ng runs from it...
2. There isn't any problem to keep dictionary grouping across different machines and users: with the same config file it remains the same. There is the problem to keep dictionaries indexing (that may last a lot of days in case of [such dictionary collection](https://booktracker.org/viewtopic.php?t=73067#torrent) for example). There are only 3 variants to solve this problem: **a)** the path to dictionaries folder must have write access to any users (there are only _/tmp_ and _/var/tmp_, how I know), and (1) must be solved for usual cases; **b)** GD-ng must support _~/_ in paths to search for the dictionary files (and how the same nevertheless of different really paths implied by "~"), and (1) must be solved for mentioned unusual case; **c)** the same dictionary must not be re-indexed regardless of path changes to it, and (1) may be not solved. For (a) and (b) variants the path must be the same nevertheless it contains symbolic links to folders or really folders (it's solved in GD-ng unlike the original GD version).

P. S. GD-ng doesn't read dictionaries nevertheless the path to search for the dictionary files are all on non-Root partition and only last symbolic link (on non-Root partition) is to dictionaries folder on Root partition...

**Comment by xiaoyifang** [comment]
https://github.com/flatpak/flatpak/issues/3057

**Comment by GD-fix** [comment]
All the same.
And [crush is the same](https://github.com/xiaoyifang/goldendict-ng/issues/1345) (using rpm version, that supported by gbd):
[gdb.txt](https://github.com/xiaoyifang/goldendict-ng/files/14318754/gdb.txt)

**Comment by GD-fix** [comment]
The problem with crush was solved, but with paths in Flatpak - didn't...

**Comment by shenlebantongying** [comment]
Simply grant Flatpak version of GD with a folder under `/` works for me.

https://askubuntu.com/questions/1086529/how-to-give-a-flatpak-app-access-to-a-directory

The case of `/tmp` will never be fixed. By default, the `/` that a flatpak app sees is not the real `/`, it is a fake `/` that having important paths bind to somewhere else, including `/tmp`.

<img width=400 src="https://github.com/xiaoyifang/goldendict-ng/assets/20123683/93cebadc-9cdb-4914-8432-4da1f27aa8b3">
<img height=200 src="https://github.com/xiaoyifang/goldendict-ng/assets/20123683/fa5510aa-6597-4f0e-93e7-bdfa284dd2f5">

**Comment by shenlebantongying** [comment]
> c) the same dictionary must not be re-indexed regardless of path changes to it

The fix easy, but it will break existing installations. https://github.com/xiaoyifang/goldendict-ng/pull/1446

**Comment by GD-fix** [comment]
Yes, it works (_/tmp_ and _/var/tmp_ both) by adding the needed paths in System Parameters / Applications Permissions:
![GD-ng_flatpak_perm_paths](https://github.com/xiaoyifang/goldendict-ng/assets/21008593/3bf0bfa4-f796-41dd-8838-2a5e14280b4d)
