### ISSUE TITLE
Flatpak version stopped updating

### ISSUE THREAD

**Issue by GD-fix** [xiaoyifang/goldendict-ng#1307]
**Describe the bug**
The version (from "Copy version info" in "About") is:
```
Goldendict-ng 23.11.08.ff83be8 at 2023-11-18T13:04:51
Qt 6.5.3 GCC 12.2.0 org.kde.Platform linux 6.6.2-1-default x86_64-little_endian-lp64
Flags:USE_XAPIAN MAKE_ZIM_SUPPORT USE_ICONV MAKE_CHINESE_CONVERSION_SUPPORT
```
Nevertheless of 4 pre-releases after 2023-11-18 and with link to Flatpak existing, in Discover there aren't any updates (see screenshots).

**Expected behavior**
It's expected that there must be updates as it was previously...

**Screenshots**
![GD-ng_installed](https://github.com/xiaoyifang/goldendict-ng/assets/21008593/df91f19b-8258-42c8-b5b5-1f5e915f07a1)
![GD-ng_updates](https://github.com/xiaoyifang/goldendict-ng/assets/21008593/79fe6e33-0884-4b96-a030-2cc5c604b744)

**OS and software versions**
- OS: OpenSUSE Tumbleweed
- Version up to date

**Comment by shenlebantongying** [comment]
Flatpak only updates with stable releases -> when this page's content changes https://github.com/xiaoyifang/goldendict/releases/latest

https://github.com/flathub/io.github.xiaoyifang.goldendict_ng/blob/master/io.github.xiaoyifang.goldendict_ng.json#L165-L169

**Comment by GD-fix** [comment]
In this case it would be logical, than this link to Flatpak will be only in stable releases, wouldn't it?
