### ISSUE TITLE
Goldendict Ng does not save the last selected dictionary group - Flatpack version

### ISSUE THREAD

**Issue by tea0112** [xiaoyifang/goldendict-ng#1315]
I use the flatpak version of Goldendict Ng, but every time I restart my laptop, the selected group is reset to all.
![image](https://github.com/xiaoyifang/goldendict-ng/assets/35191308/3e65f72c-a1c6-418d-9076-741ab4b7358e)

**Comment by xiaoyifang** [comment]
I do not think it has this function.

**Comment by tea0112** [comment]
> I do not think it has this function.

Is Goldendict-Ng forked from Goldendict right? Though it has this function, I swear.
