### ISSUE TITLE
When goldendict is started through the command line, a notification will pop up ("???" is ready). The notification is fine, but the popup window has lost focus.

### ISSUE THREAD

**Issue by zw963** [xiaoyifang/goldendict-ng#1319]
**描述 bug**

假设有一个词典叫做 local, 我在命令行下通过以下命令来启动它，查询单词 hello

goldendict hello -p local -t

当反复运行多次的时候：

1. 有时候，如果通知没有弹出来，goldendict 不会失去焦点，此时总可以通过简单的 `ESC` 来取消  popup, 这时候没问题。

2. 但是如果偶尔通知弹出来。（我使用 Arch + GNOME 45 wayland), 此时 虽然 popup 也弹出来了，但失去了焦点，此时再按下 `ESC` 根本没反应了，还得 Alt + TAB 切换以下，非常不方便。

**期望的结果**
这个问题在 goldendict 老版本从未出现过，如果没记错，老版本从来不会弹出没啥用处的通知的。

**相关的截图**

![image](https://github.com/xiaoyifang/goldendict-ng/assets/549126/a45bc5e1-90c1-465e-b460-a3c5c0675e1b)

**系统和软件的版本**
Goldendict-ng 23.12.08.6491bc47 at 2023-12-08T12:53:56
Qt 6.6.1 GCC 13.2.1 20230801 arch linux 6.6.5-x64v2-xanmod1-1 x86_64-little_endian-lp64
Flags:USE_XAPIAN MAKE_ZIM_SUPPORT USE_ICONV MAKE_CHINESE_CONVERSION_SUPPORT

**Comment by zw963** [comment]
BTW: this issue only happen when use with `-s` or `-t`.

**Comment by xiaoyifang** [comment]
这个弹窗不像是gd-ng主动弹出来的。可能与系统的配置相关
