### ISSUE TITLE
Browse through headword dialog's words list (up / down  arrorws)

### ISSUE THREAD

**Issue by Eosphorus** [xiaoyifang/goldendict-ng#1323]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Eosphorus** [comment]
It would be cool if one could browse through the headword list via the arrow keys. Meaning: you mark an entry and then use the 'up' or 'down' key to move to next/previous one. Just like in the other panes (search, history, favorites).

**Comment by xiaoyifang** [comment]
various widgets try to steal focus from headword dialog .

When click an item in the headword dialog ,  the dialog will lose the focus to the main window

**Comment by Eosphorus** [comment]
Sadly, this issue is still not solved. Those focus stealing bastards. Kidding.

**Comment by stephenmk** [comment]
As a workaround, I currently export the headword list, convert it to the same XML format that is used by exported favorites lists, and then import the headwords as favorites. You can browse through the favorites list using up/down keys without the program stealing focus away.

**Comment by shenlebantongying** [comment]
Now, it is up/down + enter without changing focus to the main window.
