### ISSUE TITLE
[Feature] Pasting images from GD to Anki should work normally

### ISSUE THREAD

**Issue by Exponent4806** [xiaoyifang/goldendict-ng#1325]
**Problem:**
Some images from GoldenDict cannot be pasted directly into Anki's Editor. I wrote a detailed description with steps to reproduce on Anki forum:

https://forums.ankiweb.net/t/bug-some-images-cannot-be-pasted-into-anki-s-editor/37799

**Describe the solution you'd like**
Users should be able to copy an image within GoldenDict (.zim, dsl, mdx etc) and being able to “paste” the image in Anki's editor.

**Describe alternatives you've considered**
The main developers of Anki tried a solution on their side but failed. They had to reverse their commit. GoldenDict is doing something different with images and the clipboard in comparison with other software programs.

**Additional context**
As this issue has existed for a long time, I have been used to take a screenshot of the image in GoldenDict and then paste into Anki. However, it is time-consuming and the quality of images is partially lost.

_Could it be possible to solve the “compatibility” issue with Anki and the way GD handles images?_

_Thanks again for your great work....!_

**Comment by xiaoyifang** [comment]
what about this
![image](https://github.com/xiaoyifang/goldendict-ng/assets/105986/c2c1d74d-20cb-471a-b78c-a324da7764e5)

copy the image (not the url) and paste to anki

**Comment by Exponent4806** [comment]
> copy the image (not the url) and paste to anki

**That does not work.** Precisely that is the problem that I described in [Anki Forum.](https://forums.ankiweb.net/t/bug-some-images-cannot-be-pasted-into-anki-s-editor/37799)

**Comment by Exponent4806** [comment]
> copy the image (not the url) and paste to anki

One of the most important contributors to Anki ( @abdnh ) suggested a simple solution:

   > Maybe the simplest solution to suggest to the author is to make GoldenDict only write image data to the clipboard, with no HTML.

Source: [Anki Forum](https://forums.ankiweb.net/t/bug-some-images-cannot-be-pasted-into-anki-s-editor/37799/6?u=levitator)

The problem seems to be that GoldenDict adds some HTML to the clipboard and Anki fails to paste those images correctly.

**Comment by xiaoyifang** [comment]
> One of the most important contributors to Anki ( @abdnh ) suggested a method to solve the issue:
> 
> > Maybe the simplest solution to suggest to the author is to make GoldenDict only write image data to the clipboard, with no HTML.


The `copy image...` is what you needed.

**Comment by Exponent4806** [comment]
Please kindly check this 30 seconds video where the problem is shown:
[simplescreenrecorder-2023-12-14_08.24.14.zip](https://github.com/xiaoyifang/goldendict-ng/files/13669969/simplescreenrecorder-2023-12-14_08.24.14.zip)

Of course, this can be considered a "feature request" because this issue does not affects the functionality of GD itself. However, some users of GD need to copy the images into Anki and are affected by that problem...

**Comment by xiaoyifang** [comment]
You can open an image editor , then `Copy image` from gd-ng and copy to ghe editor. If it can work ,then it is anki's issue.
