### ISSUE TITLE
The creating of normal binary releases to avoid third-party developer bugs

### ISSUE THREAD

**Issue by GD-fix** [xiaoyifang/goldendict-ng#1327]
**Describe the bug**
GD-ng doesn't support any dictionaries path on partition containing Root ("/") even if there is only a symbolic link to folder on another partition. So, in case (of course, unusual) of only one partition using there will not be able to add any dictionary in GD-ng at all. [This issue](https://github.com/xiaoyifang/goldendict-ng/issues/1306#issuecomment-1848368354) was labelled as "Flatpak", nevertheless Flatpak itself supports paths on partition containing Root, because GD-ng runs from it...

**To Reproduce**
Steps to reproduce the behavio**u**r(_the form lacks the letter "u"_):
see link above.

**Expected behaviour(_--//--_)**
The compiling of usual binaries with statically linked libraries (for releases only and links to them in releases only, not how is now to Flatpak release in every pre-release). It avoids the need of root privileges for users too.
You may consult with huge number of developers here about how to make it (for example, with author of [this binaries](https://github.com/lightvector/KataGo/releases/tag/v1.13.0): it will be easy for You to find a common language with him, I think; but to make more simple binaries, like [this](https://github.com/pasky/pachi/releases))

**OS and software versions**
- OS: OpenSUSE Tumbleweed
- Version up to date

**Additional context**
Thanks in advance

**Comment by GD-fix** [comment]
[Repository version](https://build.opensuse.org/package/show/home%3Amitdac/goldendict-ng) (not a Flatpak) doesn't find dictionaries too...

**Comment by xiaoyifang** [comment]
What is the the exact version ?

**Comment by GD-fix** [comment]
The Flatpak version, that I launched now again, in Discover is as 23.12.23 and in "About the program" is as 23.12.07.b0086d5 at 2023-12-23T04:18:13. It crushed right now in mentioned manner and had the empty history journal...
The last repository version in Program manager is as 07.12.23 and in "About the program" is as 23.12.07. on Sat Jan 20 05:05:06 2024. It crushed right now in mentioned manner, but had the non-empty history journal...

**Comment by GD-fix** [comment]
The problem with crush was solved, but with paths in Flatpak - didn't.
What about normal binary releases for GNU/Linux too?

**Comment by GD-fix** [comment]
The [problem with paths in Flatpak was solved](https://github.com/xiaoyifang/goldendict-ng/issues/1306).
But I don't close this issue, because for example in my case (with almost the same OpenSUSE Tumbleweed OS versions on stand alone PC and PC with Internet) the copying of Flatpak (_/var/lib/flatpak/_) works, in case of more different systems - may not.

**Comment by shenlebantongying** [comment]
Dealing with differences between different distros and their different versions is a time sucking black hole that never ends.

**Comment by GD-fix** [comment]
I think, that, for example, nor [this developer](https://github.com/lightvector/KataGo/releases), nor [this developer](https://github.com/kobanium/Ray/releases), nor [this developer](https://github.com/pasky/pachi/releases) don't agree with You...
Simply moderate your pride a little and consult about the making a binary releases with statically linked libraries...
