### ISSUE TITLE
Goldendict-ng won't run on Ubuntu,getting FATAL:credentials.cc(126)] Check failed: . : Permission denied (13)

### ISSUE THREAD

**Issue by zyworkshop** [xiaoyifang/goldendict-ng#1328]
qt.webenginecontext: 

GL Type: desktop
Surface Type: OpenGL
Surface Profile: CompatibilityProfile
Surface Version: 4.6
QSG RHI Backend: OpenGL
Using Supported QSG Backend: yes
Using Software Dynamic GL: no
Using Multithreaded OpenGL: yes

Init Parameters:
  *  application-name GoldenDict-ng 
  *  browser-subprocess-path /usr/lib/qt6/libexec/QtWebEngineProcess 
  *  create-default-gl-context  
  *  disable-features ConsolidatedMovementXY,InstalledApp,BackgroundFetch,WebOTP,WebPayments,WebUSB,PictureInPicture 
  *  disable-setuid-sandbox  
  *  disable-speech-api  
  *  enable-features NetworkServiceInProcess,TracingServiceInProcess 
  *  enable-threaded-compositing  
  *  in-process-gpu  
  *  use-gl desktop 

[6941:6941:1218/083235.753335:FATAL:credentials.cc(126)] Check failed: . : Permission denied (13)
Trace/breakpoint trap (core dumped)

**Comment by zyworkshop** [comment]
I just found a workaround: 
sudo sysctl -w kernel.apparmor_restrict_unprivileged_userns=0

**Comment by shenlebantongying** [comment]
This appears to be a bug of Ubuntu + Nvidia.

An alternative work around is `goldendict --no-sandbox`.

https://bugs.launchpad.net/ubuntu/+source/linux-meta-nvidia-5.19/+bug/2017980
