### ISSUE TITLE
 The theme doesn't show some things clearly

### ISSUE THREAD

**Issue by emanuelps2708** [xiaoyifang/goldendict-ng#1330]
**Describe the bug**
Hi, thanks for your software it's amazing and it has a lot of features, I just have a question/issue with the theme, the thing is that some things when I hover or in some settings/features it appears a white background but it doesn't appear text about the setting/feature; it happens in both the dark and light theme. I tried to change the theme and set a custom one but even though I changed it, it hasn't changed.

**Expected behavior**
The white background or color background with the text of the feature/setting in a different color eg(black or blue).

**Screenshots**
![image](https://github.com/xiaoyifang/goldendict-ng/assets/147004033/34c00a5c-8fac-4cf4-a25b-6c852650cd98)
![image](https://github.com/xiaoyifang/goldendict-ng/assets/147004033/ce9ec9a3-2635-4764-a3c8-485f8d8fc5d4)
![WhatsApp Image 2023-12-18 at 21 47 08](https://github.com/xiaoyifang/goldendict-ng/assets/147004033/ca330133-4be8-450f-9290-6132fea41f00)
![WhatsApp Image 2023-12-18 at 21 47 s08](https://github.com/xiaoyifang/goldendict-ng/assets/147004033/bdf0d0c5-e97a-428a-a170-5ff68b8ada66)

- OS: Linux mint 21.2 Cinnamon

**Comment by shenlebantongying** [comment]
GD-ng doesn't modify any Qt theming on Linux.

Try to report this to your current Qt theme's author.
