### ISSUE TITLE
 ctrl+c+c popup doesn't work on Ubuntu 21.10 with firefox, evince, sublime text 

### ISSUE THREAD

**Issue by jasoworld** [xiaoyifang/goldendict-ng#1339]
ctrl+c+c clipboard popup doesn't work on Ubuntu 21.10 (Gnome Shell 40.5) with firefox, evince, sublime text,... but works with chromium, chrome, VS code,...

https://github.com/goldendict/goldendict/issues/1420

I have the same problem with Goldendict-ng on Ubuntu 22.04

**Comment by xiaoyifang** [comment]
wayland?

**Comment by jasoworld** [comment]
yes, ctrl+c+c  works in Debian 12 Firefox but not in Ubuntu 22.04 Firefox.

**Comment by jasoworld** [comment]
Thanks. I have solved the issue when disable wayland.
