### ISSUE TITLE
Screen capture setting is invalid

### ISSUE THREAD

**Issue by bAH7JgbXrMsXEhggm4** [xiaoyifang/goldendict-ng#1342]
系统是 debian 12 更新到最新，软件是按照这里教程编译的最新版本，桌面是 cinnamon

![Screenshot from 2023-12-28 21-45-34](https://github.com/xiaoyifang/goldendict-ng/assets/152476894/05d95087-f3a4-4f49-bcd3-764892591f4f)

按照**上面**这样设置然后重启，选取一个单词后，无论是 ctrl+c,c ，还是按 ctrl + windows键，  都不会弹出翻译界面。

经过几十次实验，发现一个有趣的现象，按照上面这样配置之后，双击选取一个单词的时候聚精会神，在鼠标第一击之后，同时按鼠标左键进行第二击加ctrl加windows键（三者同时按同时松）,可以弹出翻译界面，但这很明显也是一个bug,因为双击的第一击和第二击间隔是如此之短，这样操作很难。并且，当需要翻译是一个句子的时候，就无法这样操作。

------

按照**下面**这样设置然后重启，选取一个单词后，按 ctrl + windows键是失效的不会弹出翻译界面，只有 ctrl+c,c 是生效的可以正常弹出翻译界面。 

![Screenshot from 2023-12-28 21-46-39](https://github.com/xiaoyifang/goldendict-ng/assets/152476894/9d2abf4a-d081-42f3-a405-9c1ab39b14ee)

问题可以复现，实验了好多次都如此
同一个系统环境下这个问题使用原版是没有的

**Comment by shenlebantongying** [comment]
有两个模式

1. 剪切板取词 -> 监控剪切板的变化
1. 选择文本取词 -> 监控 “Selection clipboard”，也就是 选取文本 后自动弹出，有 500ms 的延迟。如果不想让它触发太频繁的话，就添加条件，仅在 Ctrl + Win 按住的情况下才触发。（双击选取可以把延迟设置成 1ms，想要划长单词就调高延迟。）

`选择文本取词`这个翻译可能有点问题，体现不出 Selection clipboard，但是我也不知道怎么翻译。

**Comment by bAH7JgbXrMsXEhggm4** [comment]
>     1. 剪切板取词 -> 监控剪切板的变化
> 
>     2. 选择文本取词 -> 先把 Ctrl 和 Win 按住，然后选取文本。

谢谢回复，弄明白了，ng 版本有3种取词，1. [ 只要复制就翻译] 但是，开启后即使拷贝不需要翻译的内容，也会弹出翻译界面。2. [ 不需要键盘的鼠标划词 ]，划完了设定延迟后出结果，这种误操作也比较容易出现。 3. [ 按键同时划词 ] 延迟后出结果。

我发现，比原版少了一种取词，原版有一种： 划完词，延迟时间之内按键盘，就进行翻译。如果超出延迟时间，再按键盘也不会去翻译。延迟时间是可以自定义的。原版我截了一个图，原版应该是多了下面这种取词方式：

![ogigin-capture2](https://github.com/xiaoyifang/goldendict-ng/assets/152476894/1a15d847-16b3-4d4e-920e-152e4dcbfcea)

**Comment by shenlebantongying** [comment]
> 划完词，延迟时间之内按键盘，就进行翻译。

"先划再按键"和"先按键再划"基本没有区别。为什么要有两套一样的东西呢?😅

**Comment by bAH7JgbXrMsXEhggm4** [comment]
> > 划完词，延迟时间之内按键盘，就进行翻译。
> 
> "先划再按键"和"先按键再划"基本没有区别。为什么要有两套一样的东西呢?😅

有区别的，比如 github 的这个地方，无论是同时 ctrl + shift 还是 ctrl + windows 或者 只按 ctrl,，，先按键再选单词点下鼠标的瞬间就会选定一大片。这种情况应该在网页上其它地方也会出现吧，网页的特性决定的。

如果先选词再按键盘的话，就不会出现这种问题啊。无论是双击选一个单词还是选一条句子。浏览器设计就要考虑到拷贝的需求，先鼠标选择，再按键ctrl+c是常规操作啊。就是这个顺序。

只按 shift 的话，如果之前察完一个单词没有在空白处点下鼠标清除焦点的话，之后又在同一个页面shift按下选另一词，因为 shift特殊性,有可能和之前的焦点连成一片选一些不需要的。如果是先点鼠标再按键的话，每次选择都会清除之前的焦点，不可能误选。

剪贴板取词，每次复制教会去查词。脱离键盘划词取词，编辑个文档时不时就查词了，所以说，这种先选词，再按键，误操作率个人觉得能低一些。

个人见解，不一定有道理。
