### ISSUE TITLE
GD-ng doesn't find the headwords

### ISSUE THREAD

**Issue by GD-fix** [xiaoyifang/goldendict-ng#1346]
**Describe the bug**
It doesn't find many dictionary headwords.

**To Reproduce**
Steps to reproduce the behavio_u_r:
1. Go to dictionary panel
2. Click right on any dictionary
3. Scroll down to headwords and left click

**Affected Dictionaries**
Any normal dictionary (see the second screenshot)

**Expected behavio_u_r**
See the first screenshot

**Screenshots**
The original GD:
![headwords_GD-original](https://github.com/xiaoyifang/goldendict-ng/assets/21008593/2bf42ed8-db56-4868-b27d-980ed1a8cdb0)
The GD-ng:
![headwords_GD-ng](https://github.com/xiaoyifang/goldendict-ng/assets/21008593/45f5c5f4-d6cf-48bb-b550-a3897128f054)

**OS and software versions**
- OS: OpenSUSE Tumbleweed
- Version up to date

**Comment by xiaoyifang** [comment]
I think the headword's order is not the same.

**Comment by GD-fix** [comment]
After applying the non empty and then the empty again filter it finds all headwords and in the same order.
So, I think, it's the same bag as [this "non a high priority"](https://github.com/xiaoyifang/goldendict-ng/issues/1131) one...

**Comment by GD-fix** [comment]
And what is the problem to correct the code, that it will be initially the same, such after filter applying?

**Comment by shenlebantongying** [comment]
Initial order is indeed different, but the headwords are not missing.

**Comment by GD-fix** [comment]
It's all the same (at Linux version at all)...

**Comment by xiaoyifang** [comment]
You may have to let go of this issue :-)

The latest version should have the same headword order with the original goldendict (in the condition that the total headwords count less than 500000).

While dictionaries with >500000 headwords load in batch,the order can not be guaranteed.

**Comment by GD-fix** [comment]
1. In all my dictionaries for testing there are < 50000 (and furthermore 500000)...
2. In original GD for big number headwords dictionaries simply Auto applying feature doesn't applicable...
3. Can it be the user selection (best - in dictionaries headwords window) of the max. headwords number, when the filter auto applying or headwords NOT in batch loading will work (including the "0": wait for all headwords loading nevertheless of them number)?

**Comment by xiaoyifang** [comment]
> 1. In all my dictionaries for testing there are < 50000 (and furthermore 500000)...

Have you tried again.

> 2. In original GD for big number headwords dictionaries simply Auto applying feature doesn't applicable...

This restriction has been removed.  

> 3. Can it be the user selection (best - in dictionaries headwords window) of the max. headwords number, when the filter auto applying or headwords NOT in batch loading will work (including the "0": wait for all headwords loading nevertheless of them number)?

No

**Comment by GD-fix** [comment]
1. In above screenshots there are 10738 headwords...
3. And what is here: https://github.com/xiaoyifang/goldendict-ng/pull/1600 ?

**Comment by xiaoyifang** [comment]
I have not got your idea.

**Comment by GD-fix** [comment]
Correction: we (users at least of Linux) have not got your idea, because the date of the last uploaded here for us is 22.06.24...

**Comment by GD-fix** [comment]
The problem was solved
