### ISSUE TITLE
Script to split sentence into words

### ISSUE THREAD

**Issue by fouda4ever** [xiaoyifang/goldendict-ng#1350]
I'm on windows and I'm learning german, i need a program to split sentence from input line to clickable searchable words or automatically search all words in separate tabs

**Comment by xiaoyifang** [comment]
you can add a program which takes the input and output the tokens 

https://stackoverflow.com/questions/70696987/tokenizing-words-in-german

**Comment by fouda4ever** [comment]
Can you tell me how? i am not a programmer, thanks in advance.

**Comment by xiaoyifang** [comment]
then it will be a little difficult ,  I'll check it later

**Comment by xiaoyifang** [comment]
I think German language is also space seperated , which means you can double click the word to search

**Comment by fouda4ever** [comment]
yes, i realized that.
![GoldenDict_N5NLNq67Is](https://github.com/xiaoyifang/goldendict-ng/assets/86977699/1df99bbd-0625-4bf8-b059-4514c2fd9b12)
but i use google images and google translate programs
![GoldenDict_Bg6oSCKvlf](https://github.com/xiaoyifang/goldendict-ng/assets/86977699/9a436229-eee4-46c0-b09e-7b7004320fbc)
can i configure it to show individual words by default

**Comment by xiaoyifang** [comment]
> can i configure it to show individual words by default

How do you configure the google image,  I think it is the result of google image

**Comment by fouda4ever** [comment]
https://github.com/kanjieater/GoldenDict-Toolbelt

**Comment by xiaoyifang** [comment]
It's the GoldenDict-Toolbelt's resposibility to output the right format.
