### ISSUE TITLE
Middle mouse button response issue

### ISSUE THREAD

**Issue by popyoung** [xiaoyifang/goldendict-ng#1352]
**描述 bug**
在某个链接上点击鼠标中键后没有反应，再次点击鼠标左键将会在后台页面打开该链接

**受影响的词典**
所有词典

**期望的结果**
中键点击后，应该直接在后台打开页面。

**系统和软件的版本**

Goldendict-ng 23.11.08-BeginningOfWinter.20231107.ff83be8a
Qt 6.6.0 Visual C++ Compiler 192930152 windows winnt 10.0.19045 x86_64-little_endian-llp64
Flags:USE_XAPIAN MAKE_ZIM_SUPPORT USE_ICONV MAKE_CHINESE_CONVERSION_SUPPORT no_ffmpeg_player
**额外的信息**

**Comment by xiaoyifang** [comment]
暂时可以用  ctrl+click
