### ISSUE TITLE
Want to improve support for MathML formulas

### ISSUE THREAD

**Issue by YLXDXX** [xiaoyifang/goldendict-ng#1353]
**描述 bug**
对于MathML的公式，有时能正常显示，有时显示有问题：
例如下图，可正常显示
![image](https://github.com/xiaoyifang/goldendict-ng/assets/35033878/dc5bcd78-936b-4da9-9978-234be5c8e55a)

但有时显示异常，如图：
![image](https://github.com/xiaoyifang/goldendict-ng/assets/35033878/0433dd57-ac21-4de3-b008-31a922617a5a)

基本情况是只有图中的理科日常词典有相关词头时，显示异常，当某词头有其它词典时，显示正常。
其它数学词词典其中的某些设置可能让原本没有正常显示的显示正常了，没具体排查。

**期望的结果**
MathML公式应由词典本身来正确渲染。

**原版显示结果**
有无其它词典均显示正常，只不过显示的效果没有本词典正常时好看。

平台  | 信息 
---------|----------
 Linux 
最新版编译，QT6.4.2 
![image](https://github.com/xiaoyifang/goldendict-ng/assets/35033878/e8022acb-3c57-4590-b726-385543e5f992)

**Comment by YLXDXX** [comment]
排查了一下，前面能正常显示是由于加载了 MathJax ，在图中的理科日常词典中引入MathJax后，都能正常显示了
![image](https://github.com/xiaoyifang/goldendict-ng/assets/35033878/ed2c2078-56f6-4224-8024-3b22486dcfd7)



但，还是希望能增强词典软件本身对于MathML公式的渲染能力，现在的渲染能力基本没有，原版的虽然渲染出来没有MathJax的好看，但也可正常观看，原版效果如下图所示
![image](https://github.com/xiaoyifang/goldendict-ng/assets/35033878/b0121610-bdff-48ff-914b-1d161f348776)

**Comment by xiaoyifang** [comment]
原则上浏览器中可以正常显示的，gd-ng都可以显示。
不过相关的js等目前需要词典自己保证。

**Comment by YLXDXX** [comment]
> 原则上浏览器中可以正常显示的，gd-ng都可以显示。

MathML公式，应该是浏览器原生支持的，没有 MathJax 都应该正常显示，不依靠js，但现在的问题是原生有 MathML公式在gd-ng中不依靠 MathJax 的情况下无法正常显示，故，需提升对MathML公式的支持

**Comment by xiaoyifang** [comment]
这个主要依赖qwebengine的支持。暂时没其他办法。

**Comment by shenlebantongying** [comment]
Chromium 的 MathML 支持是去年初 109 版本添加的，现在的 Qt6.6 的 WebEngine 版本号是 112.

问题在于 Chromium 的 MathML 是支持 MathML Core 而不是 MathML 3，前者是后者的子集，所以有一部分公式看起来不对。

https://www.w3.org/TR/mathml-core/

vs

https://www.w3.org/TR/MathML3/

如果使用什么工具生成的 MathML，估计需要找一下有没有专门生成 MathML Core 的。

**Comment by YLXDXX** [comment]
> Qt6.6 的 WebEngine 版本号是 112.

我用的Qt版本较低，6.4.2，可能还没有MathML的支持，等后面升级Qt后再来看看原生的。

现引入MathJax后，基本上满足了要求
