### ISSUE TITLE
Auto audio pronunciation bug in Arch 

### ISSUE THREAD

**Issue by BEST8OY** [xiaoyifang/goldendict-ng#1370]
**Describe the bug**
Auto audio pronunciation bug in Arch linux Xorg with DWM

When "Auto pronunciation in main window" is enabled from preference it also auto pronounce the words in popup mode.

**Expected behavior**
It shouldn't

**OS and software versions**
Goldendict-ng 23.12.07 at 2024-01-17T23:55:55
Qt 6.6.1 GCC 13.2.1 20230801 arch linux 6.7.0-arch3-1 x86_64-little_endian-lp64
Flags:USE_XAPIAN MAKE_ZIM_SUPPORT USE_ICONV MAKE_CHINESE_CONVERSION_SUPPORT

- OS: Arch linux with DWM
- 
**Additional context**
I'm not sure if it's a limitation of DWM or a bug in GD side
Please inform me if you have more information about this.

**Comment by xiaoyifang** [comment]
fixed
