### ISSUE TITLE
Can't show Chinese in program dictionary

### ISSUE THREAD

**Issue by j3rryzh** [xiaoyifang/goldendict-ng#1373]
**Describe the bug**
I wrote a python script following [the document](https://xiaoyifang.github.io/goldendict-ng/howto/how%20to%20add%20a%20program%20as%20dictionary/), but couldn't show Chinese.

The script:

```test.py
print("你好")
```

I got an error while using it in goldendict-ng:

>查询错误：程序返回，退出代码为 1. Traceback (most recent call last): File "D:\test.py", line 1, in <module> print("\u4f60\u597d") File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2032.0_x64__qbz5n2kfra8p0\Lib\encodings\cp1252.py", line 19, in encode return codecs.charmap_encode(input,self.errors,encoding_table)[0] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ UnicodeEncodeError: 'charmap' codec can't encode characters in position 0-1: character maps to <undefined>

**OS and software versions**
- OS: Windows10
- Version Goldendict-ng 24.01.22-LoongYear.20240122.3dddb3be
Qt 6.6.1 Visual C++ Compiler 192930153 windows winnt 10.0.19045 x86_64-little_endian-llp64
Flags:USE_XAPIAN MAKE_ZIM_SUPPORT USE_ICONV MAKE_CHINESE_CONVERSION_SUPPORT no_ffmpeg_player
- I am using Portable mode

**Comment by xiaoyifang** [comment]
I think this is an issue with python encoding.

**Comment by j3rryzh** [comment]
I will close the issue since I find a way to make it works in program dictionary.
