### ISSUE TITLE
Korean characters aren't recognized while search?

### ISSUE THREAD

**Issue by 2o28** [xiaoyifang/goldendict-ng#1378]
When I search for any word written in Korean (ex. 사과, 포도), the written keyword in search box is displayed in italics and there's no result displayed. Registered lexical items in a (Korean) dictionary database are registered normally, but when I search again via that item management window, an actual search isn't possible.

A same kind of bug does not occur when I use the same database with GoldenDict Qt 1.5.0, so I am wondering if it is a problem with the software.

**Affected Dictionaries**
韩国国立国语院韩汉学习词典, etc.

**Screenshots**

**OS and software versions**

Goldendict-ng 24.01.22-LoongYear.20240122.3dddb3be
Qt 6.6.1 Visual C++ Compiler 192930153 windows winnt 10.0.19045 x86_64-little_endian-llp64
Flags:USE_XAPIAN MAKE_ZIM_SUPPORT USE_ICONV MAKE_CHINESE_CONVERSION_SUPPORT no_ffmpeg_player

OS:
Windows 10 Home 22H2

**Additional context**

**Comment by xiaoyifang** [comment]
can you upload the dictionary for analysis?

**Comment by 2o28** [comment]
It's not the dictionary database mentioned in the OP (it's almost 2GB in size; too big to upload), but the problem is common with any database that contains Korean keywords, so I'm posting the other two instead:
https://filebin.net/e7v2ei8k2eaw8bqf

Also, some words in Japanese dictionary aren't searchable (hiragana and katagana recognition itself is fine), can you check this as well?:
![image](https://github.com/xiaoyifang/goldendict-ng/assets/151121335/f290e861-de27-4347-a755-00f80307ece1)

**Comment by xiaoyifang** [comment]
I can not type these words ,can you write the word in this article

**Comment by 2o28** [comment]
사과 or 포도, anything would be ok (respectively responding to 'Apple' and 'Grape', fundamental words)

**Comment by xiaoyifang** [comment]
there is no such word 사과   .


the actual headword is  "포도 1"    and   "  사과 1  "

**Comment by xiaoyifang** [comment]
Is the index from old goldendict? If so ,try reindex them.

**Comment by 2o28** [comment]
Is 'reindexing' referring to that ['File' (On toolbar, the first one) → 'Rescan Files (Ctrl+F5)'] function? If so, it still doesn't fix the problem.

**Comment by xiaoyifang** [comment]
> Is 'reindexing' referring to that ['File' (On toolbar, the first one) → 'Rescan Files (Ctrl+F5)'] function?

right click the on the dictionary in the toolbar and you can find out the corresponding index filename .  remove the index file manually after you quit the gd-ng .

**Comment by 2o28** [comment]
Fixed; thanks. Right-clicked (any) dictionary icon listed in the toolbar, accessed 'dictionary information' to find index/cache folder; Wiped all files in it.
