### ISSUE TITLE
Playing audio will stop loading page and JS execution

### ISSUE THREAD

**Issue by fifv** [xiaoyifang/goldendict-ng#1379]
**Describe the bug**

My dict (see below) uses javascript to `.click()` to play audio, but it will stop loading all following pages/dicts. (seems unrelated to `click` itself, as clicking on a random element is ok, only playing audio has the problem.)

A workaround to this is to listen on `DOMContentLoaded` event to wait page loading finished, but that takes too long to wait long webpages like wikipedia/wiktionary (almost 5 seconds). (this seems to be the built-in audio playing logic, which plays audio after everything has loaded).

**To Reproduce**
1. In any dict, use javascript to trigger sound playing like: `document.querySelector(".pf a.visible")?.click()`
3. Unloaded dict won't show

**Affected Dictionaries**

`The Little Dict` (downloaded from [here](https://github.com/yanyingwang/goldendict)), then modified the `fy.js` that only containes:
`document.querySelector(".pf a")?.click()`

**Expected behavior**
The audio played and page continues loading.

**Screenshots**
Enable js audio play:
![image](https://github.com/xiaoyifang/goldendict-ng/assets/75289510/b04d6b45-a73a-4f38-bb14-d1991147ff92)

Disable js audio play:
![image](https://github.com/xiaoyifang/goldendict-ng/assets/75289510/52a722e5-75d2-4e58-8f4c-39894da4f913)

**OS and software versions**

Goldendict-ng 24.01.22-LoongYear.20240122.3dddb3be
Qt 6.6.1 Visual C++ Compiler 192930153 windows winnt 10.0.22631 x86_64-little_endian-llp64
Flags:USE_XAPIAN MAKE_ZIM_SUPPORT USE_ICONV MAKE_CHINESE_CONVERSION_SUPPORT no_ffmpeg_player

**Comment by xiaoyifang** [comment]
> document.querySelector(".pf a")?.click()

without this line,  when you click the button and play the sound .does it work normally.

**Comment by LakeishaKowalczyk** [comment]
Manual clicks have the same effect

**Comment by xiaoyifang** [comment]
I have not found the dictionary with the link provided above

**Comment by LakeishaKowalczyk** [comment]
try this
https://downloads.freemdict.com/尚未整理/共享2020.5.11/content/0_audio/The little dict/
https://forum.freemdict.com/t/topic/22813
https://forum.freemdict.com/t/topic/9947

Load more dictionaries (dozens) and it's easier to click on
In fact all dictionaries are the same, as long as you click on the pronunciation of any dictionary, the subsequent content of all dictionaries will not be loaded, and JSs will stop running.

**Comment by xiaoyifang** [comment]
The logic flow like this .

1. User click `<a>` in the page , 
2. gd-custom.js will catch the event(the gd-custom.js is created to handle invalid url) and throw an event emitClickedEvent   .
3. there is an url click event `articleview.linkClickedInHtml` been fired in the QWebEngineView ,   then an actual event `linkClicked` has been fired.
4. linkClicked signal connected with `openLink ` which handled the audio download(temporaryly) and play.
5.

**Comment by xiaoyifang** [comment]
> add the following line to gd-custom.js?
> 
> ```
> event.preventDefault();
> ```

checked. Not this reason.

**Comment by xiaoyifang** [comment]
When this issue happens ,QWebEngineView has throw an unsuccesful loadFinishe result. maybe lies in qwebengineview.
```
  connect( webview, &QWebEngineView::loadFinished, this, &ArticleView::loadFinished );
```
the loadResult=false

**Comment by xiaoyifang** [comment]
Guess:

for a normal webview like chrome.   when click the anchor link in the page ,the page will try to load the anchor url in this webview which also stop the previous normal loading.
I guess the behavior here is the default action of webengine view.   


Need find a solution to prevent this default action.

I tested the QWebEngineUrlRequestInterceptor and acceptNavigationRequest ,  the anchor's url can be catched ,and blocked too.
But the webview's loadFinish still with the `result`=false.
