### ISSUE TITLE
"Start with system" not work

### ISSUE THREAD

**Issue by playgithub** [xiaoyifang/goldendict-ng#1395]
### Version
* GoldenDict 24.01.22
* OS archlinux 20204.2.5
* Desktop KDE Plasma 5.27
* Dict 牛津高阶英汉双解词典（简体）第8版

### Problem
* "Start with system" not work

### Others
No problem on Windows 11

**Comment by shenlebantongying** [comment]
You need to if the exec of `~/.config/autostart/goldendict-owned-by-preferences.desktop` is pointing to the current goldendict installation. 

https://github.com/xiaoyifang/goldendict-ng/blob/685b2ec418acd0680f6ad9563407bae7e6629ae5/src/ui/mainwindow.cc#L3140
