### ISSUE TITLE
Missing "Enable index with positional information" option in "Full-text search"

### ISSUE THREAD

**Issue by cmicat** [xiaoyifang/goldendict-ng#1399]
# Describe the bug

In version 23.07.23, there was an "Enable index with positional information" option in "Full-text search", which was introduced in <https://github.com/xiaoyifang/goldendict-ng/issues/870> and <https://github.com/xiaoyifang/goldendict-ng/pull/916>. However, in version v24.01.22, this option was removed. I tried to search phrases using version v24.01.22, and GoldenDict couldn't using "Phrase searches" anymore.

# To Reproduce

1. Edit
2. Preferences
3. Full-text search

# Expected behavior

"Phrase searches" function is available.

# OS and software versions

**with support for positional information: 23.07.23**

Goldendict-ng 23.07.23-GreatHeat.20230722.fbf82af1
Qt 6.5.1 Visual C++ Compiler 192930151windows winnt 10.0.19045 x86_64-little_endian-llp64
Flags:USE_XAPIAN MAKE_ZIM_SUPPORT USE_ICONV MAKE_CHINESE_CONVERSION_SUPPORT

**no support for positional information: 24.01.22**

Goldendict-ng 24.01.22-LoongYear.20240122.3dddb3be
Qt 6.6.1 Visual C++ Compiler 192930153 windows winnt 10.0.19045 x86_64-little_endian-llp64
Flags:USE_XAPIAN MAKE_ZIM_SUPPORT USE_ICONV MAKE_CHINESE_CONVERSION_SUPPORT no_ffmpeg_player

**Comment by xiaoyifang** [comment]
This option has been enable by default now.
