### ISSUE TITLE
Where is  "AppImage: Ubuntu-20.04"?

### ISSUE THREAD

**Issue by GD-fix** [xiaoyifang/goldendict-ng#1400]
**Describe the bug**
Doesn't find:

> Build Details
> 
> AppImage: Ubuntu-20.04

**To Reproduce**
Click on [link](https://github.com/xiaoyifang/goldendict-ng/releases/latest)

**Expected behavior**
Find and download announced AppImage

**Additional context**
Flatpak and rpm (from community) versions [doesn't work a long ago](https://github.com/xiaoyifang/goldendict-ng/issues/1345).

**Comment by atauzki** [comment]
Appimage is deprecated. see #1264
