### ISSUE TITLE
Missing icons in the toolbar after the update of adwaita-icon-theme to 46

### ISSUE THREAD

**Issue by Amr-Ibra** [xiaoyifang/goldendict-ng#1443]
**Describe the bug**
Missing icons in the toolbar after the update of adwaita-icon-theme to 46

**Screenshot**
![missing-icons-goldendict-ng](https://github.com/xiaoyifang/goldendict-ng/assets/45657128/4355592e-a23e-4fc3-b140-b2bd7977d171)

**OS and software versions**
* Goldendict-ng 23.12.08 at 2023-12-27T19:49:44
* Qt 6.4.2 GCC 13.2.0 debian linux 6.6.15-amd64 x86_64-little_endian-lp64
* Flags:USE_XAPIAN MAKE_ZIM_SUPPORT USE_ICONV MAKE_CHINESE_CONVERSION_SUPPORT
* Debian testing
* GNOME desktop environment with adwaita-icon-theme version 46

**Additional context**
GNOME dropped the legacy icons from their adwaita-icon-theme. Its purpose is to provide icons for GNOME's core apps only. Other apps will need to provide their own icons.

**Comment by shenlebantongying** [comment]
But we don't even uses any icons from Theme, all icons are embedded in the executable  :sweat_smile:

Something else is wrong.

**Comment by Amr-Ibra** [comment]
> But we don't even uses any icons from Theme, all icons are embedded in the executable 😅
> Something else is wrong.

Ah, OK, how can I debug that?

**Comment by shenlebantongying** [comment]
TBH, I don't know.

However, all missing icons appear to be `.svg` ones. The ones that are still showing are `.png`.

Maybe you don't have qt6-svg installed? It looks like qt6-svg on Debian is neither a runtime dependency of any other part of Qt nor it is a runtime dependency of Gd-ng package.

**Comment by Amr-Ibra** [comment]
> Maybe you don't have qt6-svg installed? It looks like qt6-svg on Debian is not a runtime dependency for any other part of Qt or the GD-ng package.

Yes, you're right. The icons appear after installing `libqt6svg6`. Thanks.

**Comment by Amr-Ibra** [comment]
This issue can be closed now.
