### ISSUE TITLE
Can't reclaim hard drive space by clearing index cache on Mac M2 (Mac Sonoma OS)?

### ISSUE THREAD

**Issue by christopherball** [xiaoyifang/goldendict-ng#1444]
Recently installed latest version on a Mac M2 using Mac Sonoma OS.  Added too many dictionaries (recursive) and didn't realize how much space the indexing would eat up.  Removing the dictionaries doesn't reclaim disk space, nor does adding them to the ignore list.  

1. What is the exact system file path for where the index files are stored?
2. Other than manually deleting the files, is there a better way to "clear index cache"?

**Comment by christopherball** [comment]
After snooping around more, located `/Users/christopherball/.goldendict/index`.  Presumably these can just be deleted?

**Comment by shenlebantongying** [comment]
> Presumably these can just be deleted?

Yes. Feel free to delete them. 

> Other than manually deleting the files, is there a better way to "clear index cache"?

There is a "Remove invalid index on exit" in Preferences → Advanced.

Maybe that option should be enabled by default. For some reason, it doesn't.
