### ISSUE TITLE
Can't input chinesse character chinese pinyin on goldendict-ng

### ISSUE THREAD

**Issue by nynwadhyhcz8** [xiaoyifang/goldendict-ng#1448]
![Screenshot_20240328_113932](https://github.com/xiaoyifang/goldendict-ng/assets/59760027/88ce8293-4c84-4f5c-ab21-b18af82cf0dd)
![Screenshot_20240328_114429](https://github.com/xiaoyifang/goldendict-ng/assets/59760027/7adee287-c62d-406e-a9cc-8429c156f4a2)
I can only type chinese on browser 就我 please!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by shenlebantongying** [comment]
If ibus only works in browsers, you need to config ibus for qt apps https://wiki.archlinux.org/title/IBus#Integration `QT_IM_MODULE=ibus`
