### ISSUE TITLE
Qt multimedia ffmpeg changes may break
 the backend

### ISSUE THREAD

**Issue by atauzki** [xiaoyifang/goldendict-ng#1451]
On qt 6.7.0 for windows platform, the ffmpeg backed is dynamically linked to ffmpeg, 6.4-6.6 is statically instead. Although the ffmpeg dlls are included in official binaries, windeployqt doesn't install them.

The list of dlls are:
avcodecs-60.dll
avformat-60.dll
avutil-58.dll
swresample-4.dll
swscale-7.dll

That means we should install them manually before windeployqt handle them correctly.

**Comment by xiaoyifang** [comment]
On windows , I would recommend to disable build against ffmpeg ,

`CONFIG+=no_ffmpeg_player`

**Comment by atauzki** [comment]
> On windows , I would recommend to disable build against ffmpeg ,
> 
> `CONFIG+=no_ffmpeg_player`

No, not that case. It's qt's multimedia backend.

**Comment by atauzki** [comment]
![image](https://github.com/xiaoyifang/goldendict-ng/assets/19769843/7023af22-fd7a-416a-8b37-2373b8304a79)
if the dll are missing the ffmpeg backend won't be loaded and no sound with `gdau://` will be played.

and we can just use their binaries.
![image](https://github.com/xiaoyifang/goldendict-ng/assets/19769843/96e1db26-b91e-41f2-9d42-5057da836a42)

**Comment by xiaoyifang** [comment]
> windeployqt doesn't install them.

I believe this is an another windeployqt's bug.

**Comment by xiaoyifang** [comment]
> if the dll are missing the ffmpeg backend won't be loaded and no sound

https://github.com/xiaoyifang/goldendict-ng/blob/staged/.github/scripts/windows-publish.ps1

need to be changed to remedy this change of qt version.

**Comment by atauzki** [comment]
![image](https://github.com/xiaoyifang/goldendict-ng/assets/19769843/c8473ece-336c-4794-8830-856f3e84ae21)
Sorry for the wrong place. the `plugins` in target path should be removed.
