### ISSUE TITLE
Anki Integration URI schemes. When searching French, there are some problem.

### ISSUE THREAD

**Issue by MVVVVK** [xiaoyifang/goldendict-ng#1461]
windows版软件，在使用这个url过程中出现问题了
软件可以正常查阅法语单词，anki也尝试使用在在线词典来看有没有问题，结果是可以正常用的
问题是这样，使用上述url后，出现法语中的û,à,é等单词，跳转到字典上会出现乱码
<img width="502" alt="1" src="https://github.com/xiaoyifang/goldendict-ng/assets/120430862/cba812cc-25da-4d48-ae6a-e2f934c1d4be">
<img width="502" alt="2" src="https://github.com/xiaoyifang/goldendict-ng/assets/120430862/e25af21b-1af7-4665-bc04-d0300e56db32">
<img width="491" alt="3" src="https://github.com/xiaoyifang/goldendict-ng/assets/120430862/6a3b9514-abd9-4057-9655-6b4157241a54">

**Comment by MVVVVK** [comment]
如果我的描述对您来说不够合理详细的话，非常抱歉，我是一名法语专业的学生，不太熟悉这里的规则

**Comment by xiaoyifang** [comment]
你用的gd-ng的版本是哪个，这个问题，应该修改过了。
https://github.com/xiaoyifang/goldendict-ng/pull/1434

**Comment by MVVVVK** [comment]
Goldendict-ng 24.01.22-LoongYear.20240122.3dddb3be
Qt 6.6.1 Visual C++ Compiler 192930153 windows winnt 10.0.19045 x86_64-little_endian-llp64
Flags:USE_XAPIAN MAKE_ZIM_SUPPORT USE_ICONV MAKE_CHINESE_CONVERSION_SUPPORT no_ffmpeg_player

是这个版本

**Comment by xiaoyifang** [comment]
https://github.com/xiaoyifang/goldendict-ng/releases

用这里的版本试一下

**Comment by MVVVVK** [comment]
解决了，感谢！
