### ISSUE TITLE
Does it support word-splitting for Chinese?

### ISSUE THREAD

**Issue by Aulline** [xiaoyifang/goldendict-ng#1466]
First of all, thank you for reviving this great software! 

I have a question: can it split words for Chinese when searching dictionary entries? By this I mean that typing a sentence (for example, "今天天气很好") in the searchbar will return links to individual words in that sentence ("今天", "天气" etc), clicking on which will get the user to the existing dictionary entry for each word. Currently, it either returns nothing or suggests the closest entries available. Abbyy Lingvo does this when the sentence cannot be found in dictionary entries/examples etc.

<details><summary>Details</summary>
<p>

![image](https://github.com/xiaoyifang/goldendict-ng/assets/108539217/374a792c-5656-49f4-beda-2f2ad10c6e20)

![image](https://github.com/xiaoyifang/goldendict-ng/assets/108539217/0efef7da-23d0-4503-a187-6e741e4692c8)

</p>
</details>

**Comment by atauzki** [comment]
https://github.com/fxsjy/jieba
