### ISSUE TITLE
symbol lookup error: goldendict: undefined symbol: _ZN10QAudioSink12stateChangedEN6QAudio5StateE, version Qt_6

### ISSUE THREAD

**Issue by wengyk** [xiaoyifang/goldendict-ng#1473]
**描述 bug：**

终端启动goldendic命令，有如下错误提示：
goldendict: symbol lookup error: goldendict: undefined symbol: _ZN10QAudioSink12stateChangedEN6QAudio5StateE, version Qt_6
软件无法启动。

**goldendict-ng版本：**
goldendict-ng安装自Arch Linuxcn，版本为：archlinuxcn/goldendict-ng-git 24.02.16.r5372.cb37a91d-1

**系统：**
OS: Arch Linux x86_64
Kernel: 6.6.26-1-lts
DE: Plasma 6.0.3

**Comment by shenlebantongying** [comment]
See the linked issuse.
