### ISSUE TITLE
Package for linux ubuntu

### ISSUE THREAD

**Issue by arnoulfos** [xiaoyifang/goldendict-ng#1474]
Hi could you compile a package for.Linux Ubuntu thanks

**Comment by shenlebantongying** [comment]
ubuntu package https://packages.ubuntu.com/noble/goldendict-ng

flathub https://flathub.org/apps/io.github.xiaoyifang.goldendict_ng

guide to build from source https://xiaoyifang.github.io/goldendict-ng/howto/build_from_source/

**Comment by arnoulfos** [comment]
Great, thanks a lot!!!

Apr 17, 2024 19:25:40 shenleban tongying ***@***.***>:

**Comment by arnoulfos** [comment]
I managed to install it, thank you for the great work that you made to improve goldendict!

Apr 17, 2024 19:31:24 Arnoulfos ***@***.***>:
