### ISSUE TITLE
支持名词动词形容词变形

### ISSUE THREAD

**Issue by playgithub** [xiaoyifang/goldendict-ng#1478]
**Is your feature request related to a problem? Please describe.**
名词有单复数，形容词有比较级最高级，动词有过去式过去分词
当形式变化时，常常查不到，而且时常遇到

**Describe the solution you'd like**
如果可以自动使用单词的原始形式查询，会方便很多

**Describe alternatives you've considered**
这个python库可以自动转换各种单词变形，准确率很高
[A clear and concise description of any alternative solutions or features you've considered.](https://github.com/FinNLP/en-inflectors)

**Additional context**
可以考虑移植，或直接调用

**Comment by shenlebantongying** [comment]
Wildcard matching does pretty much what you want. For example, search `match*` will search everything that starts with `match` which includes `matching` and `matched`.

https://xiaoyifang.github.io/goldendict-ng/ui_toolbar/#wildcard-matching

**Comment by playgithub** [comment]
> Wildcard matching does pretty much what you want.

No, I mean search by "Ctrl+C, C", for example, the word there is "apples", but Oxford Dict V8 doesn't contain "apples" but "apple", so I have to manually edit it from "apples" to "apple" to see the translations. If it can convert "apples" to "apple" automatically when "apples" can't be found, then it can save a lot of attention and time relatively, because select a word and press "Ctrl+C, C" is fixed key strokes.

**Comment by z-gong** [comment]
All you need is turning on the morphology
![image](https://github.com/xiaoyifang/goldendict-ng/assets/379616/8a0d6118-d554-4f05-871c-fdb92131f8f7)
![image](https://github.com/xiaoyifang/goldendict-ng/assets/379616/50a67e02-a7c5-410e-84b3-ec06176dc3ac)

**Comment by playgithub** [comment]
> All you need is turning on the morphology
Great!
I've tested it with hunspell dicts at https://github.com/titoBouzout/Dictionaries for a while, it works quite well.
Thans very much

**Comment by playgithub** [comment]
With morphology dicts "English (American)" and "English (British)" at https://github.com/titoBouzout/Dictionaries,
it can't find the word "goes".

**Comment by playgithub** [comment]
It shows that each of "morphology dictionary" and "en-inflectors" has its own advances.
For example,

### Case that "morphology dictionary" wins

Word: suspiciousness

For "morphology dictionary", it converts "suspiciousness" to "suspicious" as expected.
For "en-inflectors" codes as below, the output is still suspiciousness, but the offline dict could find it.
```typescript
import { Inflectors } from "en-inflectors";
let instance = new Inflectors("suspiciousness");
let v = instance.conjugate("VBP");
console.log(v);
```

### Case that "en-inflectors" wins

Word: arisen

For "morphology dictionary", it can't convert "arisen" to "arise" as expected.
For "en-inflectors" codes as below, the output is "arise" as expected.
```typescript
import { Inflectors } from "en-inflectors";
let instance = new Inflectors("arisen");
let v = instance.conjugate("VBP");
console.log(v);
```

**Comment by shenlebantongying** [comment]
It seems possible to inject a custom script's return into GD's search completion list.

I don't know how to use `npm`, so I used `deno` and added this program to GD's program as "Prefix match"

```
import { Inflectors } from "npm:en-inflectors";
const word = Deno.args[0];
let instance = new Inflectors(word);
console.log(instance.conjugate("VBP"));
console.log(instance.conjugate("VBD"));
```

Then add it as `deno run /home/slbtty/Desktop/endef/endef.js %GDWORD%` and set type as "Prefix match"

![image](https://github.com/xiaoyifang/goldendict-ng/assets/20123683/6bebce32-c0dc-4958-ab04-7c015cfe213f)

Then 

![image](https://github.com/xiaoyifang/goldendict-ng/assets/20123683/4e4debb9-23e1-475b-bcbc-70262ec93c29)

---

I think we can enhance this feature, so that the word results returned from custom programs will also be used as search keywords (like search `arisen` will also search `arise`).

(The "Prefix matches" needs a name change, it is too obscure and doesn't convey what it really does.)

**Comment by playgithub** [comment]
As it's matching a string as prefix for a completion list, "Prefix matches" is proper this way.

**Comment by shenlebantongying** [comment]
And there is a fix:

Just mark arisen is a stem of arise.
```
arisen st:arise
```

GD's original author ikm/dragonroot uploaded a hunspell dict with those irrgular forms' stem marked :sweat_smile::sweat_smile::sweat_smile:  

https://sourceforge.net/projects/goldendict/files/better%20morphologies/1.0/

**Comment by playgithub** [comment]
> GD's original author ikm/dragonroot uploaded a hunspell dict with those irrgular forms' stem marked 😅😅😅
> 
> https://sourceforge.net/projects/goldendict/files/better%20morphologies/1.0/

Absolutely better for me, thanks very much.
