### ISSUE TITLE
Roaming under C drive Appdata will take up a lot of space

### ISSUE THREAD

**Issue by Nalanzhan** [xiaoyifang/goldendict-ng#1479]
查看电脑发现C:\Users\AN\AppData\Roaming\GoldenDict占据了30G的空间；未来可能会不断增加。

目前每天都会使用Goldendict，查几十个单词及以上（没有具体统计过），加载了20+个词典

**期望的结果**
想了解是为什么？可以如何不影响软件使用的情况下解决该问题

**相关的截图**
设置如下，然后使用了anki功能，其他设置保持默认设置，没有更改。目前已经删除了历史记录和收藏词条，但没有存储情况。
![image](https://github.com/xiaoyifang/goldendict-ng/assets/57355364/d0cd4d8e-2b28-40c1-8a96-cd256c380a31)
![image](https://github.com/xiaoyifang/goldendict-ng/assets/57355364/a8fe045d-3122-4199-914a-5a2fdb45e0ba)

占据空间如下
![image](https://github.com/xiaoyifang/goldendict-ng/assets/57355364/14fa2c95-e313-48f8-8132-6e7db585b318)
**Window 11**

Goldendict-ng 24.01.22-LoongYear.20240122.3dddb3be
Qt 6.6.1 Visual C++ Compiler 192930153 windows winnt 10.0.22631 x86_64-little_endian-llp64

- OS: [e.g. Windows10,  Fedora37]

平台  | 信息 
---------|----------
 Windows |  _将位于配置文件夹中（可以通过菜单  **help->配置文件夹** 打开）crash文件夹里面的dmp文件上传到此处_
 Macos | 将macos自带的crashpad的log粘贴到此处 
 Linux | gdb crash 堆栈信息

**Comment by czz404** [comment]
正常应该主要是index文件夹（索引）会占用比较大的空间，和你说的那些设置没什么关系
在意这个就用便携模式呗
直接goldendict文件夹放到非系统盘，然后新建portable文件夹变为便携模式，就一点c盘空间都不占了
参考：https://xiaoyifang.github.io/goldendict-ng/topic_portablemode/

当然，根源上解决还是精简词典数量，以及不建立所有词典的全文索引之类的

**Comment by Nalanzhan** [comment]
> 正常应该主要是index文件夹（索引）会占用比较大的空间，和你说的那些设置没什么关系 在意这个就用便携模式呗 直接goldendict文件夹放到非系统盘，然后新建portable文件夹变为便携模式，就一点c盘空间都不占了 参考：https://xiaoyifang.github.io/goldendict-ng/topic_portablemode/
> 
> 当然，根源上解决还是精简词典数量，以及不建立所有词典的全文索引之类的

谢谢！问题已经解决了！
