### ISSUE TITLE
Do you have plans for the Microsoft Powertoys plugin?

### ISSUE THREAD

**Issue by ubless607** [xiaoyifang/goldendict-ng#1480]
Do you have plans for the Microsoft Powertoys plugin?

**Comment by xiaoyifang** [comment]
How?
Can you give a detail explanation?

**Comment by ubless607** [comment]
Microsoft PowerToys run is a quick launcher (Spotlight in Mac)
There is an ongoing discussion for the dictionary plugin. I think GoldenDict might be a good approach to the solution.
Check https://github.com/microsoft/PowerToys/issues/3309.

**Comment by xiaoyifang** [comment]
> Microsoft PowerToys run is a quick launcher

IMO，  this is a requirement for powertoys.
