### ISSUE TITLE
unify the appearance of headword for different dictionary formats

### ISSUE THREAD

**Issue by z-gong** [xiaoyifang/goldendict-ng#1483]
Currently, different dictionary formats have similar but not identical appearance. An apparent difference is the headword. For DSL and Stardict formats, the headword is displayed before article; Whereas for MDX format, the headword is not displayed.

E.g. when I search for the word `appear` in a DSL format, the headword is displayed as
```
<div class="dsl_headwords"><p>appear</p></div>
```
For StarDict Format, the headword is displayed as
```
<h3 class="sdct_headwords">appear</h3>
```
But for MDX format, the headword is not included in the article

**The headword tells me exactly which word is displayed. This information is especially important when morphology or synonym is turned on.**

Do you think it makes sense to unify the appearance of headwords? If so, I could contribute a pull request.

**Comment by shenlebantongying** [comment]
> Whereas for MDX format, the headword is not displayed.

Aren't MDX dicts usually display headwords by themselves? Adding extra headword display will create unnecessary duplications. I am not sure exactly what you want to change.

**Comment by z-gong** [comment]
> Aren't MDX dicts usually display headwords by themselves?

Not always. Some visual dictionaries made of images do not display headword. When morphology or synonyms is turned on, it can be difficult to know which word is matched.

> Adding extra headword display will create unnecessary duplications.

If the MDX already displays headword, the extra headword can be hidden with the CSS associated with this MDX or with `article-style.css`. But if the MDX does not display headword, then the "extra" headword generated by Goldendict can be useful.

> I am not sure exactly what you want to change.

Similar to DSL and Stardict format, add a headword section at the beginning of the definition article.

**Comment by shenlebantongying** [comment]
> Not always. Some visual dictionaries made of images do not display headword. 

Ok, I didn't think about this.

> Do you think it makes sense to unify the appearance of headwords?

The default style of various different formats are very different. Unifying them is probably not easy. I think adding a new hidden `mdx_headwords` is good enough.

Feel free to add related code.
