### ISSUE TITLE
Latest release marked as a trojan

### ISSUE THREAD

**Issue by darlopvil** [xiaoyifang/goldendict-ng#1503]
By AVG while downloading the .exe file. Never before happened this to me.

![trojan](https://github.com/xiaoyifang/goldendict-ng/assets/60988792/0261544a-3ed1-477c-95a8-cf8afb7c8a62)

**Comment by shenlebantongying** [comment]
First, I didn't inject malicious staff :sweat_smile::sweat_smile:

The artifacts are built and published entirely through GitHub, this is the log

https://github.com/xiaoyifang/goldendict-ng/actions/runs/8958959871/job/24603791069

There is nothing we can do. None of the many open-source software can buy certificates and do code singing binaries.

https://github.com/search?q=Windows+trojan&type=issues

**Comment by shenlebantongying** [comment]
Not actionable on our side. Though, we need help to remove binary winlibs to improve transparency. https://github.com/xiaoyifang/goldendict-ng/issues/555
