### ISSUE TITLE
The dictionary expansion button in the upper right corner has moved to the middle!

### ISSUE THREAD

**Issue by yshumy** [xiaoyifang/goldendict-ng#1504]
这样（Mac版）：
<img width="343" alt="截屏2024-05-06 04 22 46" src="https://github.com/xiaoyifang/goldendict-ng/assets/103359913/cfecf098-4986-438b-9f97-f3d94fc1509e">

**Comment by xiaoyifang** [comment]
粗略估计，qt在mac上的bug

**Comment by shenlebantongying** [comment]
Not fixable on our side.
