### ISSUE TITLE
6.7.0-GoldenDict.exe_windows-2019_20240505 interface settings do not enable dark mode and are invalid

### ISSUE THREAD

**Issue by sunboy0523** [xiaoyifang/goldendict-ng#1506]
![image](https://github.com/xiaoyifang/goldendict-ng/assets/63040375/87f1d4bf-f1e7-4ede-8d94-4cc8b2082bdc)

**Comment by shenlebantongying** [comment]
https://www.qt.io/blog/dark-mode-on-windows-11-with-qt-6.5

Qt's theme now has a built-in dark theme and will sync with Windows' dark appearance setting.

**Comment by sunboy0523** [comment]
> https://www.qt.io/blog/dark-mode-on-windows-11-with-qt-6.5
> 
> Qt's theme now has a built-in dark theme and will sync with Windows' dark appearance setting.

Thanks a lot. How can i turn off the built-in dark theme? Thanks

**Comment by shenlebantongying** [comment]
The workaround is adding a parameter `goldendict.exe -platform windows:darkmode=1` or switching back to Qt6.6 version.

https://doc.qt.io/qt-6/qguiapplication.html#platform-specific-arguments

**Comment by sunboy0523** [comment]
> Workarounds:
> 
> * adding a parameter `goldendict.exe -platform windows:darkmode=1`
> * Turn off Windows's system dark theme 😅
> * switching back to Qt6.6 version
> 
> https://doc.qt.io/qt-6/qguiapplication.html#platform-specific-arguments

Thanks very much

**Comment by Leon406** [comment]
`adding a parameter goldendict.exe -platform windows:darkmode=1` 
This solution still has some problem


![dropdown](https://github.com/xiaoyifang/goldendict-ng/assets/26186607/e4557b01-b78c-451b-abf0-832b7c1055c8)

you can change dll  (in directory plugins\styles) to previous version  ( qwindowsvistastyle.dll)

 
[qwindowsvistastyle.zip](https://github.com/xiaoyifang/goldendict-ng/files/15282322/qwindowsvistastyle.zip)

**Comment by shenlebantongying** [comment]
Does anyone still have access to Windows10?

I want to know if Qt's new dark theme also works on Windows10.

If it works, I wants to simply remove the old dark theme, and rework the dark mode into 3 options -> "Follow system" / "Enable" / "Disable".
