### ISSUE TITLE
Garbled characters appear in the latest Mac version 24.05.05

### ISSUE THREAD

**Issue by yshumy** [xiaoyifang/goldendict-ng#1507]
全部字典名称和部分内容变成乱码，这样：
<img width="289" alt="截屏2024-05-07 23 33 48" src="https://github.com/xiaoyifang/goldendict-ng/assets/103359913/36d7a287-06f7-422f-989c-3257cc2ea00e">

**Comment by shenlebantongying** [comment]
I cannot reproduce this.

Can you try maybe deleting caches, then reindex?

`Help -> Configuration folder` then delete the `index`

If this works, what was your original version before upgrading?

**Comment by yshumy** [comment]
> I cannot reproduce this.
> 
> Can you try maybe deleting caches, then reindex?
> 
> `Help -> Configuration folder` then delete the `index`
> 
> If this works, what was your original version before upgrading?

谢谢。重启后恢复正常。
