### ISSUE TITLE
Does the Mac version no longer support Mac 12?

### ISSUE THREAD

**Issue by yshumy** [xiaoyifang/goldendict-ng#1510]
<img width="329" alt="截屏2024-05-11 01 33 06" src="https://github.com/xiaoyifang/goldendict-ng/assets/103359913/ae970386-fdd4-4ffd-bb0b-6ab81177c1af">

**Comment by shenlebantongying** [comment]
My bad. I didn't set the deployment target version when switching to CMake.

It is supported according to https://developer.apple.com/support/xcode

Can you test this build? It should support macOS 12

https://github.com/shenlebantongying/goldendict-ng/releases/tag/v24.05.13-alpha.a9abc776
