### ISSUE TITLE
Crash on start while goldendict-ng indexing dictionary

### ISSUE THREAD

**Issue by sammynguyen2409** [xiaoyifang/goldendict-ng#1517]
**Describe the bug**
Start up normally and proceed on indexing several dictionary and then not responding cursor and crash.
**To Reproduce**
1. Start goldendict-ng
2. And wait till crash

**Affected Dictionaries**

If certain dictionaries don't work, list their names and types.

If possible, please attach the dictionary files or provide a downloadable link. (GitHub allows uploading 25MiB zip file as attachment)

**Expected behavior**
Not to crash

**Screenshots**
<img width="402" alt="image" src="https://github.com/xiaoyifang/goldendict-ng/assets/33772550/ed7b6851-2b3f-4a2b-92a4-b16f80b93538">

**OS and software versions**
Windows 11 and latest stable version on this exact day issue is posted (because i cannot run the program)

**Additional context**

Platform | Context

[GoldenDict.exe.3384.zip](https://github.com/xiaoyifang/goldendict-ng/files/15343140/GoldenDict.exe.3384.zip)

**Comment by xiaoyifang** [comment]
what is the gd-ng version?

**Comment by sammynguyen2409** [comment]
[6.6.3-GoldenDict-ng-Installer.exe](https://github.com/xiaoyifang/goldendict-ng/releases/download/v24.05.05-LiXia.ecd1138c/6.6.3-GoldenDict-ng-Installer.exe)
117 MB
Since i cant check inside the program, this is the one i downloaded yesterday
thank you

**Comment by xiaoyifang** [comment]
upload the dmp file (the file location is in the crash folder in the configuration folder) and the corresponding gd-ng version.

**Comment by shenlebantongying** [comment]
Need the crash file.
