### ISSUE TITLE
Cannot restore window by clicking the system tray icon

### ISSUE THREAD

**Issue by Kruegerrr** [xiaoyifang/goldendict-ng#1518]
**Describe the bug**
The main window of Goldendict-ng cannot be restored by single-clicking the icon in the system tray.

**To Reproduce**
1. Go to Edit -> Preferences -> Interface, confirm both 'Enable system tray icon' and 'Close to system tray' are enabled.
2. Click on the close button, Goldendict-ng should now be closed to the system tray.
3. Click the Goldendict icon in the system tray.
4. The window frame of Goldendict-ng disappears after a flash.

**Expected behavior**
The Goldendict-ng window should be restored after clicking the icon in the system tray. Note that the window can still be restored by right clicking the icon and then clicking on 'Show Main Window'.

**OS and software versions**

Goldendict-ng 24.05.05 at 2024-05-12T15:31:50Z
Qt 6.7.0 GCC 14.1.1 20240507 arch linux 6.8.9-arch1-2 x86_64-little_endian-lp64
Flags: MAKE_ZIM_SUPPORT USE_ICONV MAKE_CHINESE_CONVERSION_SUPPORT

Operating System: Arch Linux 
KDE Plasma Version: 6.0.4
KDE Frameworks Version: 6.1.0
Qt Version: 6.7.0
Kernel Version: 6.8.9-arch1-2 (64-bit)
Graphics Platform: Wayland

**Comment by shenlebantongying** [comment]
I cannot produce this, it works fine on my machine :sweat_smile:


https://github.com/xiaoyifang/goldendict-ng/assets/20123683/6eaf35d6-79a1-45cd-b1e2-456e85e358ce

**Comment by puchu** [comment]
same problem for me too

clicking on the tray icon doesnt retore the window, it seems its shown for a second and hidden again
console output of the app is:

> Current state: false false false false
> Current state: true false true false

**Comment by shenlebantongying** [comment]
I reproduced it with https://github.com/ubuntu/gnome-shell-extension-appindicator

Not sure why it may or may not happen.

**Comment by puchu** [comment]
> same problem for me too
> 
> clicking on the tray icon doesnt retore the window console output of the app is:
> 
> > Current state: false false false false
> > Current state: true false true false

based on the output, it seems to call MainWindow::toggleMainWindow two times

**Comment by shenlebantongying** [comment]
You are right, 

adding a true to here, like `toggleMainWindow( true );`, should "fix" the problem.

https://github.com/xiaoyifang/goldendict-ng/blob/e2e1ca2d49b939e89a12104a2e9c90875a7d50ea/src/ui/mainwindow.cc#L2996

---

I suspect the root problem is that we connected `&QSystemTrayIcon::activated` to `&MainWindow::trayIconActivated` twice?

The `updateTrayIcon` also called connect.

https://github.com/xiaoyifang/goldendict-ng/blob/e2e1ca2d49b939e89a12104a2e9c90875a7d50ea/src/ui/mainwindow.cc#L865-L874

We can add `Qt::UniqueConnection` to avoid duplication.

---

Or we clean up the legacy, revise old code to make them cleaner.

**Comment by puchu** [comment]
this patch also fixes the problem, there are to connects for trayIconActivated

```
diff --git a/src/ui/mainwindow.cc b/src/ui/mainwindow.cc
index a430dca9..f7bdedf3 100644
--- a/src/ui/mainwindow.cc
+++ b/src/ui/mainwindow.cc
@@ -868,7 +868,7 @@ MainWindow::MainWindow( Config::Class & cfg_ ):
     trayIcon->setContextMenu( &trayIconMenu );
     trayIcon->show();
 
-    connect( trayIcon, &QSystemTrayIcon::activated, this, &MainWindow::trayIconActivated );
+    //connect( trayIcon, &QSystemTrayIcon::activated, this, &MainWindow::trayIconActivated );
   }
 
   updateTrayIcon();
```

**Comment by puchu** [comment]
actually here:

https://github.com/xiaoyifang/goldendict-ng/blob/e2e1ca2d49b939e89a12104a2e9c90875a7d50ea/src/ui/mainwindow.cc#L871

https://github.com/xiaoyifang/goldendict-ng/blob/e2e1ca2d49b939e89a12104a2e9c90875a7d50ea/src/ui/mainwindow.cc#L1403

**Comment by shenlebantongying** [comment]
https://github.com/xiaoyifang/goldendict-ng/pull/1535 should be the correct fix.

Note that `QSystemTrayIcon::Trigger` is platform-dependent. On KDE, it is a single click, while on GNOME with [AppIndicator and KStatusNotifierItem Support](https://extensions.gnome.org/extension/615/appindicator-support/), it is a double click.
