### ISSUE TITLE
'Auto apply' dementia in dictionary headwords

### ISSUE THREAD

**Issue by Eosphorus** [xiaoyifang/goldendict-ng#1519]
![asterisk](https://github.com/xiaoyifang/goldendict-ng/assets/8929191/80cab892-2bbf-4ce8-b00c-0a060ed0688c)

Why is it that

1. GD doesn't remember the settings in the 'Dictionary headwords' list
2. with some dictionaries you can't even select 'Auto apply', it's ghosted, non-selectable - seems to be inconsistent

**Comment by Eosphorus** [comment]
Doesn't seem to be an issue for others or I do misunderstand something here. Somebody enlighten me.
Thanks.

**Comment by xiaoyifang** [comment]
> 2\. with some dictionaries you can't even select 'Auto apply',

disabled when headwords > 150000

https://github.com/xiaoyifang/goldendict-ng/blame/2f82ea7e55d795c54baebdd7e7760e8457d51f4b/dictheadwords.cc#L117

**Comment by Eosphorus** [comment]
Oh, I see. Thanks.
