### ISSUE TITLE
Godendict ng on android

### ISSUE THREAD

**Issue by arnoulfos** [xiaoyifang/goldendict-ng#1522]
Is there any plan to port android-ng to android ?thanks in advance

**Comment by shenlebantongying** [comment]
no,

maybe this can help to create it https://github.com/xiaoyifang/goldendict-ng/issues/905

**Comment by KonstantinDjairo** [comment]
> Is there any plan to port android-ng to android ?thanks in advance

i recommend using DictTango if you want to use your goldendict dictionaries on android, the interface is beautiful and it's really easy to use.
