### ISSUE TITLE
After the latest roll of Arch Linux, the scanning functionality no longer works.

### ISSUE THREAD

**Issue by zw963** [xiaoyifang/goldendict-ng#1529]
**描述 bug**

GNOME 46 + Wayland.

在最近的升级以前, 点开托盘邮件, 打开 Scanning 功能的话(前面✅选上),  使用 okular 阅读文本 pdf 时, 高亮选择一段文本时, 会自动弹出窗口, 使用自己指定的引擎翻译 `选择的文本`.

但是现在没有任何反应了, 同样的情况在 Firefox (GTK 应用程序) 下面也不工作.

**额外的信息**

goldendict-git 这个包也无法安装了(注意, 没有 ng), 提示错误:

```sh
 ╰─ $ 127  pacman -S goldendict-git
resolving dependencies...
warning: cannot resolve "libicuuc.so=74-64", a dependency of "qt5-webkit"
warning: cannot resolve "libicui18n.so=74-64", a dependency of "qt5-webkit"
warning: cannot resolve "qt5-webkit", a dependency of "goldendict-git"
:: The following package cannot be upgraded due to unresolvable dependencies:
      goldendict-git

:: Do you want to skip the above package for this upgrade? [y/N]
```

不知道是否跟此有关.

**Comment by shenlebantongying** [comment]
Duplicate of https://github.com/xiaoyifang/goldendict-ng/issues/741

**Comment by xiaoyifang** [comment]
> ```shell
> warning: cannot resolve "libicuuc.so=74-64", a dependency of "qt5-webkit"
> warning: cannot resolve "libicui18n.so=74-64", a dependency of "qt5-webkit"
> ```

从上面的日志看，这个是 不是goldendict-ng的版本，是基于webkit的原goldendict版本

**Comment by zw963** [comment]
> Duplicate of #741
> 
> Wayland doesn't want inactive apps to read clipboards.

嘿， 我不确定是这个问题， 因为时间不符，这个 issue 创建时间比出现这个问题早得多， 在那个时间之后， 我肯定用过 goldendict-ng 以及 goldendict-git, 两者都工作的， 直到最近的升级才不工作。

**Comment by zw963** [comment]
好像可以了，是因为从 goldendict 切换过来，配置文件不兼容缘故，没有打开 scanning option 选项。
