### ISSUE TITLE
save state of UI

### ISSUE THREAD

**Issue by KonstantinDjairo** [xiaoyifang/goldendict-ng#1532]
when i open goldendict-ng , i have to manually disable the favorites bar, dictionary bar, drag the bar to another place and so on

this is kinda tedious since goldendict-ng doesn't "remember" the position of the elements.
maybe it could write the position into its config file, would be nice

![image](https://github.com/xiaoyifang/goldendict-ng/assets/53496273/6dde8282-22b4-4e55-949b-9bcdd79568fb)

**Comment by shenlebantongying** [comment]
Currently, window state restoring is solely done via `QMainWindow::save/restoreState`
https://github.com/xiaoyifang/goldendict-ng/blob/e2e1ca2d49b939e89a12104a2e9c90875a7d50ea/src/ui/mainwindow.cc#L1258-L1262

It could be a bug,

or we didn't call it correctly https://doc.qt.io/qt-6/qmainwindow.html#restoreDockWidget https://doc.qt.io/qt-5/qmainwindow.html#restoreDockWidget

**Comment by KonstantinDjairo** [comment]
does it writes the state to a file? that could help, and would be cool when migrating your configuration to another pc
