### ISSUE TITLE
Can you solve the white edge problem of transparent images in dark mode, as shown in the figure:

### ISSUE THREAD

**Issue by yshumy** [xiaoyifang/goldendict-ng#1533]
<img width="347" alt="截屏2024-05-27 15 24 30" src="https://github.com/xiaoyifang/goldendict-ng/assets/103359913/206df29a-851b-4598-89ff-3dfed3d0d491">

**Comment by shenlebantongying** [comment]
https://github.com/xiaoyifang/goldendict-ng/issues/1490#issuecomment-2092357556

**Comment by xiaoyifang** [comment]
词典制作问题。
