### ISSUE TITLE
Why not use JavaScript to manipulate links instead of Regex?

### ISSUE THREAD

**Issue by shenlebantongying** [xiaoyifang/goldendict-ng#1537]
All the code below is reinventing DOM APIs, like finding all <audio> tags etc.

I think reimplementing them in JS could makes things easier, faster and more reliable.

* Nobody understands regex, but everyone understands JS.
* More reliable. Verifying correctness of regex is hard, while the browser's API is truly battle tested. The current code is questionable if meeting not so well-formed HTML, like this PR trying to fix https://github.com/goldendict/goldendict/pull/1695
* Speed? The browser will parse the HTML anyway, but in an insanely optimized way.
* Loading speed? The browser can show the result immediately, instead of waiting PCRE to parses all the text.

https://github.com/xiaoyifang/goldendict-ng/blob/05d9a398a0a32adfdc3c6d29815e5ad2631cb2f7/src/dict/mdx.cc#L879 https://github.com/xiaoyifang/goldendict-ng/blob/05d9a398a0a32adfdc3c6d29815e5ad2631cb2f7/src/common/globalregex.cc#L27-L67

I find all the code in https://github.com/xiaoyifang/goldendict-ng/pull/1536 is questionable 😅

**Comment by shenlebantongying** [comment]
It seems possible to run JS before any image requests 

https://developer.mozilla.org/en-US/docs/Web/API/Document/DOMContentLoaded_event

**Comment by xiaoyifang** [comment]
JS is easier to run into problem.
When we do the regex in the code ,it is only limited to the dictionary .
while writing the logic with the js ,it is applied to all the dictionaries and it can easily meet performance issue without carefully thinking.

**Comment by shenlebantongying** [comment]
Ok. After some trials, I failed to find a way to replace `img`'s `src` with something else before the loading of the original `src`. 😅

**Comment by KonstantinDjairo** [comment]
JS breaks everything , the less JS the better
