### ISSUE TITLE
When using The little dict dictionary to query certain words, enter the word and press Enter. Some words have sounds and some words have no sounds.

### ISSUE THREAD

**Issue by zw963** [xiaoyifang/goldendict-ng#1540]
**描述 bug**

**复现 bug 的步骤**

打开 goldendict ng 界面，如下面截图，然后（1）位置输入 `professional`, 然后回车。

![image](https://github.com/xiaoyifang/goldendict-ng/assets/549126/c9918d99-33ac-4449-9e79-c07d352e1835)

** 期望的结果**
期望看到翻译的同时，同时会发出这个单词的读音.

** 实际的结果**
而实际上，按下回车后，并没有发出声音，必须鼠标移动到上面截图 (2) 发音图标位置，才会发音。

为什么我说这可能是 bug 呢？ 因为如果换个单词，例如： `hello`, 完全同样的操作，回车就会立即发出声音。请看截图：

![image](https://github.com/xiaoyifang/goldendict-ng/assets/549126/923c32a8-95fb-4835-aba7-beb026255bc7)

因为我经常通过查询 `professional` 来时测试辞典是否工作，所以我相当确认，同样的问题在 goldendict 上是没有的，直到最近 goldendict 不可用了，切换到 ng 之后，又发现这个问题。

相关选项也是开启状态 （看截图）

![image](https://github.com/xiaoyifang/goldendict-ng/assets/549126/24008942-04bd-4289-875d-b4056e9fca0c)

**受影响的词典**
（The little dict) 

**相关的截图**

**系统和软件的版本**

Goldendict-ng 24.05.13.e6a2be83 at 2024-05-29T22:05:12Z
Qt 6.7.1 GCC 14.1.1 20240522 arch linux 6.9.2-arch1-1 x86_64-little_endian-lp64
Flags: MAKE_ZIM_SUPPORT USE_ICONV MAKE_CHINESE_CONVERSION_SUPPORT

- OS: Arch linux

**Comment by zw963** [comment]
我刚刚尝试删除了所有配置文件，仅仅导入 The little dict, 重试了一下，问题依旧，所以，这应该不是配置文件的问题。

谢谢。

**Comment by xiaoyifang** [comment]
改为第三方的播放引擎看一下
![image](https://github.com/xiaoyifang/goldendict-ng/assets/105986/39fc4202-d707-493a-b2d7-57da451106b8)

**Comment by zw963** [comment]
你好, 刚刚试了一下:

1.  改为第三方播放器 mpv, 还是翻译 professional, 鼠标 hover 可以播放, 但是从命令行还是不播放.
2.  我使用 arch linux 的包管理器安装, 当前安装的版本 git hash 基于最新的 master, 应该已经包含了最新的修复.

 ╰─ $ 1  pacman -Q |grep goldendict-ng-git
goldendict-ng-git 24.02.16.r5447.4ac44e9a-1

所以, 结论是, 貌似还是不工作.

你觉得有没有可能跟这个问题有关?

https://bbs.archlinux.org/viewtopic.php?id=295776

问题已经提出,但是一直没有人回复.

**Comment by xiaoyifang** [comment]
不是很确定，因为你的是有的单词正常发音，有的不能发音，可能跟单词的音频格式有关系，记得这本little dict词典用的是spx格式的音频。

也可能是系统中的qt的版本比较低，qtmultimedia的模块还没有集成ffmpeg的后端。

你可以采用第三方播放引擎  ffmpeg中的 ffplay试一下。

**Comment by zw963** [comment]
> 你可以采用第三方播放引擎 ffmpeg中的 ffplay试一下。

一样的结果, 鼠标 hover 播放, 但是仅仅输入回车不播放.

**Comment by shenlebantongying** [comment]
Duplicate of https://github.com/xiaoyifang/goldendict-ng/issues/1738
