### ISSUE TITLE
Favorite list

### ISSUE THREAD

**Issue by Alrazzouq** [xiaoyifang/goldendict-ng#1545]
It is a good idea to arrange the favorite list to the newest at the top.

**Comment by KonstantinDjairo** [comment]
dragging a favorite to the top and rearranging would be cool, yeah

**Comment by Alrazzouq** [comment]
I use this method. But I have do that for each word I added to favorite list. The history list is sorted by "newest at the top". It is better to sort favorite list the same.

**Comment by xiaoyifang** [comment]
I have to make sure that this requirement is needed for most of the people.

**Comment by Alrazzouq** [comment]
Could you add an option to customise sorting either "ascending or descending".

**Comment by shenlebantongying** [comment]
>  sorting either "ascending or descending"

There is no concept of ordering to begin with. Currently, "Favorite" is just a tree that lets users reorder, an unsorted thing by nature.

If you mean add new ones to top, it is unlikely.

Think of browser's bookmarks. No browser vendors will ever implement an option that changes insert from append to prepend.

Properly enhancing "favorite" needs better ideas than just "add an extra option".

**Comment by prismriverrr** [comment]
I also hope that words can be added to top of favorites list by default, so that if there are many saved words, I don't need to scroll to see the most recently added ones.
