### ISSUE TITLE
When running goldendict from command line, not focus the opened window and move it to the top.

### ISSUE THREAD

**Issue by zw963** [xiaoyifang/goldendict-ng#1546]
**Describe the bug**
e.g. run command like this:

```sh
$: goldendict --group-name=local professional
```

The window of goldendict is opened, but it behind the current terminal window.

What i expected is, it will active the goldendict and move it into front instead, as it did when use old webkit version goldendict 

**OS and software versions**

Goldendict-ng 24.05.13.e6a2be83 at 2024-05-29T22:05:12Z
Qt 6.7.1 GCC 14.1.1 20240522 arch linux 6.9.2-arch1-1 x86_64-little_endian-lp64
Flags: MAKE_ZIM_SUPPORT USE_ICONV MAKE_CHINESE_CONVERSION_SUPPORT

- OS: Arch Linux
- Version

**Comment by shenlebantongying** [comment]
GNOME46 + Wayland.

**Comment by xiaoyifang** [comment]
![image](https://github.com/user-attachments/assets/0c943475-94b0-4fa4-9022-786784845417)

这个选项试下

**Comment by shenlebantongying** [comment]
Cannot reproduce 

> it did when use old webkit version goldendict

That's because you are using older version of GNOME.
