### ISSUE TITLE
When i added below code to Program tab in Dictionaries, i got an error like that ;

### ISSUE THREAD

**Issue by xiaoyifang** [xiaoyifang/goldendict-ng#1547]
When i added below code to Program tab in Dictionaries, i got an error like that ; 

**program:** trans -e google -s fr -t en -show-original y -show-original-phonetics n -show-translation y -no-ansi -show-translation-phonetics n -show-prompt-message n -show-languages y -show-original-dictionary n -show-dictionary n -show-alternatives n %GDWORD%

**error code:** Query error: The program has returned exit code 255.

i am using fedora 39. when i used Ubuntu repo, i did not got any error, but i changed my repo to fedora, i am getting eror nowadays, thanks for help, regards. 

PS: i installed translate-shell program in link; https://github.com/soimort/translate-shell

![image](https://github.com/xiaoyifang/goldendict-ng/assets/112494004/7a00d412-92c9-433d-a699-f7780972c835)

_Originally posted by @mehmet-ercan in https://github.com/xiaoyifang/goldendict-ng/discussions/1542_

**Comment by xiaoyifang** [comment]
https://github.com/soimort/translate-shell/issues/352

**Comment by shenlebantongying** [comment]
I don't see him posting version info. If @mehmet-ercan uses the flatpak version, these step are needed https://github.com/flathub/io.github.xiaoyifang.goldendict_ng/issues/1#issuecomment-1656071332

I think we need a new section in doc to document how to work with the idiosyncrasies of flatpak.

**Comment by shenlebantongying** [comment]
I don't think this GD's problem. I tested yesterday, there is no issue.

https://github.com/xiaoyifang/goldendict-ng/pull/1592/files#diff-35035312d0b073534ef7563c4611724cad2d5fb6e9822c07136ba363c401a4d2R23
