### ISSUE TITLE
Windows, Clion build error.

### ISSUE THREAD

**Issue by xiaoyifang** [xiaoyifang/goldendict-ng#1551]
**Describe the bug**
load Clion ,the IDE will report cmake error

```
CMake Error at CMakeLists.txt:220 (add_dependencies):
  The dependency target "goldendict-ng_lrelease" of target "goldendict" does
  not exist.

```

on Windows.

**Comment by shenlebantongying** [comment]
Can you check if `goldendict-ng_lrelease` exists in the target list?

<img src="https://github.com/xiaoyifang/goldendict-ng/assets/20123683/a093ad95-fe4a-4f8d-9371-c32beb77925d" width=400px>

I am using Qt6.7 and things works fine. The `goldendict-ng_lrelease` is added by [qt_add_translations -> qt_add_lrelease](https://doc.qt.io/qt-6/qtlinguist-cmake-qt-add-lrelease.html).

You can also try Clion -> Tools -> CMake -> Reset Cache and Reload Project.

**Comment by xiaoyifang** [comment]
![image](https://github.com/xiaoyifang/goldendict-ng/assets/105986/9d930aa2-30ec-4884-a783-30808551c1b0)

Should has some relation with `USE_ALTERNATIVE_NAME`

**Comment by xiaoyifang** [comment]
![image](https://github.com/xiaoyifang/goldendict-ng/assets/105986/f0d00b82-ebaf-408d-959a-873ae808cd20)
