### ISSUE TITLE
custom qt style support ,There should be no such use case any more. 

### ISSUE THREAD

**Issue by xiaoyifang** [xiaoyifang/goldendict-ng#1572]
https://github.com/xiaoyifang/goldendict-ng/blob/1dafa5cb16db5552bdf154fb3ae02b8e9a65562e/mainwindow.cc#L1071-L1090

![image](https://github.com/xiaoyifang/goldendict-ng/assets/105986/9cecc413-db3a-40a2-bbfe-0c4283d7508b)

custom qt style does not work well when applied dark mode.    Such a feature is too specific and rare.

**Comment by shenlebantongying** [comment]
+1

It does get mentioned twice, however the use case mentioned is superseded by the UI language setting that we already have.
https://github.com/search?q=repo%3Agoldendict%2Fgoldendict+currentGroup&type=issues
