### ISSUE TITLE
Some dictionaries have a double quote in their stylesheet link.

### ISSUE THREAD

**Issue by cuongha0701** [xiaoyifang/goldendict-ng#1585]
**Describe the bug**
Some dictionaries cannot load css because of double quote

**Affected Dictionaries**
Stardict format converted from Apple dictonary

**Expected behavior**
Remove the double quote in stylesheet link, and everything works again.

**Screenshots**
![Screenshot_20240615_095930](https://github.com/xiaoyifang/goldendict-ng/assets/34791382/176b6f06-28b8-48de-9637-d8dd4c661451)

**OS and software versions**
KDE Plasma 6.0.5
Goldendict-ng 24.05.13.4ac44e9a at 2024-06-14T21:18:58Z
Qt 6.7.1 GCC 14.1.1 20240522 arch linux 6.9.4-arch1-1 x86_64-little_endian-lp64
Flags: MAKE_ZIM_SUPPORT USE_ICONV MAKE_CHINESE_CONVERSION_SUPPORT

**Comment by shenlebantongying** [comment]
> Stardict format converted from Apple dictonary

Attach this dict or provide a download link

**Comment by shenlebantongying** [comment]
I don't think this related code is wrong.

https://github.com/xiaoyifang/goldendict-ng/blob/65e51b2313eaa5af6cf048eb7f0552ef07ac24f3/src/dict/stardict.cc#L459-L464

https://regex101.com/r/gVtCyO/1

>  Remove the double quote in stylesheet link, and everything works again.

Upload or provide a download link for this dict. The content before replacement might be malformed.

**Comment by cuongha0701** [comment]
> I don't think this related code is wrong.
> 
> https://github.com/xiaoyifang/goldendict-ng/blob/65e51b2313eaa5af6cf048eb7f0552ef07ac24f3/src/dict/stardict.cc#L459-L464
> 
> https://regex101.com/r/gVtCyO/1
> 
> > Remove the double quote in stylesheet link, and everything works again.
> 
> Upload or provide a download link for this dict. The content before replacement might be malformed.


@shenlebantongying
Here you are: [OxfordThesaurusofEnglish.zip](https://github.com/user-attachments/files/15845684/OxfordThesaurusofEnglish.zip)

**Comment by shenlebantongying** [comment]
Seems a combination of 

* QRegularExpression::InvertedGreedinessOption
* https://github.com/xiaoyifang/goldendict-ng/pull/1562

InvertedGreedinessOption converts `*` to `*?` and `?` to `??`.

```
With InvertedGreedinessOption:
(<\s*link\s+?[^>]*href\s*?=\s*["']*)(?!(?:data|https?|ftp):)   < correct
(<\s*link\s+?[^>]*href\s*?=\s*["']?)(?!(?:data|https?|ftp):)   < error as in this issue
(<\s*link\s+?[^>]*href\s*?=\s*["']??)(?!(?:data|https?|ftp):)  < correct, because `??` converted back to `?` by InvertedGreedinessOption
```

**Comment by xiaoyifang** [comment]
remove  QRegularExpression::InvertedGreedinessOption  seems ok.

![image](https://github.com/xiaoyifang/goldendict-ng/assets/105986/f1b14002-11af-4761-9aab-296b6548b4e0)

**Comment by shenlebantongying** [comment]
There are performance implications

InvertedGreedinessOption or Ungreedy only needs 96 steps
<img width=400px src=https://github.com/xiaoyifang/goldendict-ng/assets/20123683/ed438b82-729f-48fa-9625-7def00f30011>

while cancel this option needs 114 steps

<img width=400px src=https://github.com/xiaoyifang/goldendict-ng/assets/20123683/e464cd4b-02e3-446a-ba89-b43770d5b67a)>

I think changing the single `?` to `??` is better fix.

**Comment by xiaoyifang** [comment]
the syntax `??` is not easy to understand

**Comment by shenlebantongying** [comment]
I agree that `InvertedGreedinessOption` is 💩💩 that shouldn't exist.

For performance, I have no opinion. Making the code reliable first is ok to me too. Maybe I can revise all regex for performance later.
