### ISSUE TITLE
Font customisation

### ISSUE THREAD

**Issue by Alrazzouq** [xiaoyifang/goldendict-ng#1596]
Can we customise the font of display results of all dictinories?

**Comment by xiaoyifang** [comment]
This only happens when  the dictionary has not appoint the font .
![image](https://github.com/xiaoyifang/goldendict-ng/assets/105986/cb259891-4360-4842-801d-36165c7b66bd)

**Comment by Alrazzouq** [comment]
I think It is a good idea to force all dictionaries to display a spesific font type and size.

**Comment by xiaoyifang** [comment]
Not a good idea for dictionary markers.

**Comment by shenlebantongying** [comment]
Simply use `important!` to override any font choices.

https://xiaoyifang.github.io/goldendict-ng/topic_userstyle/
https://developer.mozilla.org/docs/Web/CSS/important

```
body {
  font: "whatever" !important;
}
```
