### ISSUE TITLE
Using javascript to automatically jump to search words will load all dictionaries

### ISSUE THREAD

**Issue by pk49800** [xiaoyifang/goldendict-ng#1609]
**描述 bug**
为了节省空间和减少重复的内容，没有把自制词典中的词条内带有的idioms单独提取出来，想通过@@@LINK=entry#anchor的方式来访问这些内容，但是mdict本身并不支持，故使用javascript的window.location=word#anchor的方法来实现在页面加载时自动跳转到目标词条的锚点处。这样做虽然实现了功能但是会自动查询并显示所有未激活的词典。

**受影响的词典**
测试词典:
[test.zip](https://github.com/user-attachments/files/15942213/test.zip)

**复现 bug 的步骤**
把我提供的测试词典加入到一个分组，只激活分组中的该词典，查询 take that! 。除了会缓慢跳转到目标词头take的锚点处，还会连带查询分组内的所有词典。如果分组内还有网络搜索词典，控制台还会报错。

**期望的结果**
只显示本词典的查询内容。

**相关的截图**
![截屏2024-06-22 20 43 40](https://github.com/xiaoyifang/goldendict-ng/assets/36910388/dc6b02b1-5fe4-4639-a061-c8099204daa0)

**系统和软件的版本**

复制 & 粘贴 `帮助` -> `关于` -> `复制版本信息` 到这里

- OS: MacOS Ventura 13.6
- Version : 24.05.05.ecd1138c at 2024-05-05T14:29:32Z

**Comment by xiaoyifang** [comment]
用  bword:entry#archor  的链接的方式试一下的方式试一下，
上述未测试。

**Comment by pk49800** [comment]
> 用 bword:entry#archor 的链接的方式试一下的方式试一下， `<a href="bword:entry#archor" >xxx</a>` 上述未测试。

经测试无法自动跳转或者通过点击跳转

**Comment by xiaoyifang** [comment]
`entry://xxxx#anchor   ` 其中xxxx是另一个词头，  这个好像是mdx中跨词头跳转用的。

**Comment by pk49800** [comment]
> `entry://xxxx#anchor ` 其中xxxx是另一个词头， 这个好像是mdx中跨词头跳转用的。

我就是用这种方式跳转的，但是有个问题。如果不是手动点击超链接的方式跳转而是用javascript来控制跳转，就是window.location.href='entry://xxxx#anchor'的方式来实现的话，它跳转后还会显示其他分组的查询结果，我的本意是使用javascript或者其他方式自动跳转后仅返回同一本词典的查询结果。

**Comment by xiaoyifang** [comment]
> window.location.href='entry://xxxx#anchor'的方式来实现的话，

不建议js的方式处理。  如果你想用js跳转，目前估计没有通用的方式。

**Comment by pk49800** [comment]
那没办法了，只好手动点击跳转或者把内容提取成单独的词条
