### ISSUE TITLE
Pronunciation becomes very slow

### ISSUE THREAD

**Issue by playgithub** [xiaoyifang/goldendict-ng#1612]
**描述 bug**
发音变得很慢

**复现 bug 的步骤**
1. 打开某词典 '牛津高阶8简体'
2. 查单词，点击 '喇叭'发音
3. 发音变得很慢，至少0.5倍数，以前正常

**受影响的词典**
牛津高阶8简体

**期望的结果**
正常发音

**系统和软件的版本**

- OS: Arch Linux
- Goldendict-ng 24.05.05 at 2024-06-24T04:17:30Z
Qt 6.7.1 GCC 14.1.1 20240522 arch linux 6.9.6-arch1-1 x86_64-little_endian-lp64
Flags: MAKE_ZIM_SUPPORT USE_ICONV MAKE_CHINESE_CONVERSION_SUPPORT

**额外的信息**

Menu / Edit / Preferences / Audio / Playback / Use internal player
选FFmpeg / Qt Multimedia都一样

**Comment by xiaoyifang** [comment]
音频保存到本地，然后播放一下看看。

**Comment by playgithub** [comment]
> 音频保存到本地，然后播放一下看看。

正常

**Comment by xiaoyifang** [comment]
内部播放声音的时候，没有额外控制速度。
建议你从几个方面先排查下：
1，发音是词典发出的，还是gd-ng发出的。  gd-ng工具栏上的发音按钮正常吗。有的词典会自己通过js发音。
2，排除其他词典影响。禁用其他词典，比如建个分组，分组里面只有这个词典，发音是否正常。

**Comment by playgithub** [comment]
> 内部播放声音的时候，没有额外控制速度。 建议你从几个方面先排查下： 1，发音是词典发出的，还是gd-ng发出的。 gd-ng工具栏上的发音按钮正常吗。有的词典会自己通过js发音。 2，排除其他词典影响。禁用其他词典，比如建个分组，分组里面只有这个词典，发音是否正常。

最近Qt等升级了，然后goldendict-ng运行不了，然后重新编译，然后就出现这个问题了。
以前都正常的，碰到运行不了，重新编译安装，然后一切正常，这次就发音变慢了。

**Comment by playgithub** [comment]
> 音频保存到本地，然后播放一下看看。

用VLC播放正常，用ffplay播放出现同样的问题（非常慢）

**Comment by xiaoyifang** [comment]
> 用VLC播放正常，用ffplay播放出现同样的问题（非常慢）

如果是这样，可能是ffplay的问题，可以提给ffmpeg先看下。

**Comment by playgithub** [comment]
Bug reported
https://trac.ffmpeg.org/ticket/11078

**Comment by playgithub** [comment]
Solved by using `mplayer` as the external audio player.
