### ISSUE TITLE
Ctrl+F page Search does not work in popup dialog on macos

### ISSUE THREAD

**Issue by xiaoyifang** [xiaoyifang/goldendict-ng#1616]
**Describe the bug**
Ctrl+F page Search does not work in popup dialog on macos

 ~seems introduced by https://github.com/xiaoyifang/goldendict-ng/commit/57a5c526208d04b63381e5ff8d4319c2bb179a1f~

This bug maybe has existed for a long time.

ps.
works on Windows.

**Comment by xiaoyifang** [comment]
@shenlebantongying  can you help to check this when available?

**Comment by shenlebantongying** [comment]
likely a Duplicate of https://github.com/xiaoyifang/goldendict-ng/issues/1007

`Qt::popup` has implicit behaviours on macOS

**Comment by xiaoyifang** [comment]
> edit: revert [57a5c52](https://github.com/xiaoyifang/goldendict-ng/commit/57a5c526208d04b63381e5ff8d4319c2bb179a1f) does not fix the problem.

I noticed.

**Comment by xiaoyifang** [comment]
There is a comprosied solution to solve this(on Macos).
On the above situation, Ctrl+F does not work in popup,and the shortcut was sent to the mainwindow actually.
When MainWindows detect the CTRL+F and found that itself is not actived and the popup existed, then forward the trigger to the popup
