### ISSUE TITLE
Freezes and crashes at closing several tabs

### ISSUE THREAD

**Issue by darlopvil** [xiaoyifang/goldendict-ng#1622]
**Describe the bug**
If several tabs are opened and want to close all of them at once, GD freezes and so it happens to the PC. That is the case, that you cannot use anything. Task administrator shows countless processes increasing incessantly. RAM and CPU collapse. In a desperate action to not get things worse, had to manually terminate the GD main process.

**Expected behavior**
Fix this as it was before. Using several tabs is as essential as breathing air.

**Screenshots**
Because the PC was unusable, had to take a shot with my phone:
![gd](https://github.com/xiaoyifang/goldendict-ng/assets/60988792/0cd8a76e-b1a2-4a93-a5ef-2f69b8a370d8)

**OS and software versions**

Goldendict-ng 24.05.13-alpha.20240628.9ef50e80
Qt 6.6.3 Visual C++ Compiler 192930154 windows winnt 10.0.19045 x86_64-little_endian-llp64
Flags: MAKE_ZIM_SUPPORT USE_ICONV MAKE_CHINESE_CONVERSION_SUPPORT NO_TTS_SUPPORT no_ffmpeg_player

- OS: Windows 10 x64 bits
- Version 22H2

**Comment by xiaoyifang** [comment]
Have you enabled the full text feature?

**Comment by darlopvil** [comment]
Hello,

You mean this?

![imagen](https://github.com/xiaoyifang/goldendict-ng/assets/60988792/90c1c368-9194-47fc-b9d9-19f8ab29392b)

**Comment by xiaoyifang** [comment]
yes, 

Can you  try to disable this and reproduce the crash again.

**Comment by darlopvil** [comment]
Did it and happened again. The number of processes escalated quickly to over 1.000 and then the PC almost crashed😰

**Comment by xiaoyifang** [comment]
![image](https://github.com/xiaoyifang/goldendict-ng/assets/105986/92414975-7344-47eb-b8b7-e6701c7d256c)

which one has caused the crash?  Can not reproduce on my side? need more information

**Comment by xiaoyifang** [comment]
suspected changes:
https://github.com/xiaoyifang/goldendict-ng/blob/3a46dd290b995f7a0040bbe590ef26b4794a68fe/src/ui/mainwindow.cc

**Comment by xiaoyifang** [comment]
try this
https://github.com/xiaoyifang/goldendict-ng/releases/tag/v24.05.13-alpha.ed222859

**Comment by darlopvil** [comment]
It works!!!! Thank you so much!! 
🤝🤝🙏🙏🙏
