### ISSUE TITLE
GoldenDict's clipboard translation feature doesn't work in Brave browser

### ISSUE THREAD

**Issue by EsuRt** [xiaoyifang/goldendict-ng#1624]
**描述 bug**
GoldenDict的剪贴板翻译快捷键设置为Ctrl+C，Ctrl+C后，在Brave浏览器中选择单词并使用快捷键，会出现翻译上一个单词的情况，并且导致无法复制当前单词的情况。这个情况在其他浏览器或软件中没有出现。

**复现 bug 的步骤**
1. GoldenDict的剪贴板翻译快捷键设置为Ctrl+C，Ctrl+C。
2. 在Brave浏览器中选择单词并使用快捷键。
3. 弹出的翻译窗口显示的是上一个被复制单词的翻译词条。

**受影响的词典**
无

**期望的结果**
弹出的翻译窗口显示的是当前被复制单词的翻译词条。

**相关的截图**

https://github.com/xiaoyifang/goldendict-ng/assets/15177069/58777e7d-6639-430c-bf74-55bc36255789

**系统和软件的版本**

- OS: Windows10 22H2
- Goldendict-ng 24.05.05-LiXia.20240505.ecd1138c
- Qt 6.7.0 Visual C++ Compiler 192930154 windows winnt 10.0.19045 x86_64-little_endian-llp64
- Flags: MAKE_ZIM_SUPPORT USE_ICONV MAKE_CHINESE_CONVERSION_SUPPORT NO_TTS_SUPPORT no_ffmpeg_player

**Comment by xiaoyifang** [comment]
以右键-管理员模式运行gd-ng看下。

**Comment by EsuRt** [comment]
> 以右键-管理员模式运行gd-ng看下。

Windows 10上管理员权限运行正常没问题，Windows 11上非管理员也没问题。
