### ISSUE TITLE
Package collision with goldendict

### ISSUE THREAD

**Issue by TheNicker** [xiaoyifang/goldendict-ng#1627]
I've created a package for void linux and there are colliding names with the original goldendit project
Suggesting to change target name and library paths for this fork to resolve this issue

**Comment by shenlebantongying** [comment]
Add `-DUSE_ALTERNATIVE_NAME=ON` to cmake. https://github.com/xiaoyifang/goldendict-ng/blob/ddb9203e3425a9762fb1d56666c201adf13cc325/CMakeLists.txt#L20
