### ISSUE TITLE
Can someone share me a screenshot of Arabic(or any RTL language)  browser ui interface ,like chrome or firefox?

### ISSUE THREAD

**Issue by xiaoyifang** [xiaoyifang/goldendict-ng#1632]
Can someone share me a screenshot of Arabic(or any RTL language)  browser ui interface ,like chrome or firefox?

I want to check the layout of Forward/Back button in the browser.

**Comment by shenlebantongying** [comment]
The left/right relationship of forward/backward is unchanged, but the position of the forward/backward combo is moved to another side of the topbar.

Arabic:
![image](https://github.com/xiaoyifang/goldendict-ng/assets/20123683/19096746-b2e2-420a-ae55-abba78d65b98)

Normal:
![image](https://github.com/xiaoyifang/goldendict-ng/assets/20123683/d12337be-7a15-402e-b3d3-a48c1e7bd464)

**Comment by xiaoyifang** [comment]
https://github.com/xiaoyifang/goldendict-ng/blob/2053511856a9b7c591f26ad927601fe985ee2997/src/ui/mainwindow.cc#L880-L884

then I think this piece of code can be removed.

**Comment by shenlebantongying** [comment]
Actually, no. I checked it again the backward is on the right side after switching to Arabic language.

https://ux.stackexchange.com/questions/55127/do-arabic-web-browsers-have-the-back-forward-buttons-reversed

**Comment by shenlebantongying** [comment]
In the current GD, this piece of code won't be triggered on Linux in anyway.

The whole app level layout direction is never set. No idea what the "auto" means (using `LC_ALL=ar` doesn't work and setting the language doesn't work). https://doc.qt.io/qt-6/qguiapplication.html#layoutDirection-prop

https://github.com/xiaoyifang/goldendict-ng/blob/2053511856a9b7c591f26ad927601fe985ee2997/src/ui/mainwindow.cc#L880-L884

---

Unrelated, but force setting RTL via `qApp->setLayoutDirection(RTL)` looks like this :sweat_smile: 

<img width="400px" src="https://github.com/xiaoyifang/goldendict-ng/assets/20123683/d0dadfbb-4666-4083-b5b3-ffd575de6781">

**Comment by xiaoyifang** [comment]
> I checked it again, the backward is on the right side after switching to Arabic language (but they look the same. I said, "left/right relationship of forward/backward is unchanged" because they still look like `<- ->` rather than `-> <-` 😅 ).

the above code will make the button appear as -> <- .
which should be  controlled by layout direction.

If layout is concerned,all the buttons should rearranged. 

Based on above ,the code is still nonsense.

**Comment by xiaoyifang** [comment]
> Unrelated, but force setting RTL via `qApp->setLayoutDirection(RTL)` looks like this 😅

what about qApp->setLayoutDirection(Auto) and then change the interface language to arabic

**Comment by shenlebantongying** [comment]
> Based on above ,the code is still nonsense.

The code is needed when it triggers because buttons will be added from right to left if the whole app is RTL layout as shown in the forced layout screenshot https://github.com/xiaoyifang/goldendict-ng/issues/1632#issuecomment-2208110215

However, I don't find a way to trigger the whole application RTL layout.

> what about qApp->setLayoutDirection(Auto) and then change the interface language to arabic/persian

On Linux, the layout doesn't change to RTL (which is what browsers do) as Qt's doc says.

I don't know exactly what the "application language" means.

**Comment by xiaoyifang** [comment]
> The code is needed when it triggers because buttons will be added from right to left if the whole app is RTL layout as shown in the forced layout screenshot [#1632 (comment)](https://github.com/xiaoyifang/goldendict-ng/issues/1632#issuecomment-2208110215) . Don't remove it.

got your idea

**Comment by xiaoyifang** [comment]
![image](https://github.com/xiaoyifang/goldendict-ng/assets/105986/5bbad85f-ff1f-4116-8041-89b7e9e4674f)
the screen seems mirrored.  I has a little doubt that ,the Forward/Back button will be mirrored too.(which do not need to set the image explictly).
