### ISSUE TITLE
Goldendict defaults to filename for short name dictionaries

### ISSUE THREAD

**Issue by epistularum** [xiaoyifang/goldendict-ng#1636]
When the dictionary name is 4 characters or shorter, goldendict refuses to display the name and instead uses the file name.

![image](https://github.com/xiaoyifang/goldendict-ng/assets/34507493/cc76854c-4ebd-4c5c-bb3b-43405e8117c9)

**Comment by xiaoyifang** [comment]
After fix, the dictionary should be reindexed.
