### ISSUE TITLE
argos-translate cli does not work inside goldendict-ng

### ISSUE THREAD

**Issue by franzmondlichtmann** [xiaoyifang/goldendict-ng#1648]
**Describe the bug**
Under programs in GoldenDict-ng I added:
`argos-translate "%GDWORD%" -f es -t de`
This gives me the error (freely translated): Program exited with error code 255.

`argos-translate "Test" -f es -t de`  (gives me the german translation Prüfung, if I use it in the cli)

You maybe know argos translate, its a very good offline translator similar to deepl in power and very fast
https://github.com/argosopentech/argos-translate
It has this badly documented cli interface, but you can get help with `argos-translate --help`

Newest updated arch distro (EndevourOS, which is basically arch with a calamares installer)

**Comment by shenlebantongying** [comment]
> error code 255.

flatpak version need this https://xiaoyifang.github.io/goldendict-ng/topic_flatpak/#add-external-programs

**Comment by franzmondlichtmann** [comment]
I don't use the flatpak version.
I installed the latest, arch package `goldendict-ng-git`
Also, I have conda activated on bash. Maybe its a conda problem?

**Comment by shenlebantongying** [comment]
> Maybe its a conda problem?

Maybe? Previously, there was error code 255 because the command doesn't exist in the flatpak version.

The `pip` in your shell could be many things(conda's, system's, or other pythons, like https://xkcd.com/1987/ 😅.)

You probably need sth like <https://conda.io/projects/conda/en/latest/commands/run.html> if the thing is inside conda.

**Comment by franzmondlichtmann** [comment]
Its inside conda base, I should have clarified that

**Comment by franzmondlichtmann** [comment]
`conda run argos-translate "test" -f es -t de`
This works in the bash cli

`conda run argos-translate "%GDWORD%" -f es -t de`
does not work in goldendict-ng

**Comment by shenlebantongying** [comment]
I think you also need to ensure conda is in the path, maybe just hardcode it in GD?

**Comment by franzmondlichtmann** [comment]
```
laptop02@laptop02-pc ~> echo $PATH                                                                                                                                     (base) 
/home/laptop02/miniconda3/bin /home/laptop02/miniconda3/condabin /usr/local/bin /usr/bin /usr/local/sbin /var/lib/flatpak/exports/bin /usr/bin/site_perl /usr/bin/vendor_perl /usr/bin/core_perl
```

**Comment by franzmondlichtmann** [comment]
![image](https://github.com/xiaoyifang/goldendict-ng/assets/105480088/000d6bec-493a-449d-81c5-3957d48cd772)
![image](https://github.com/xiaoyifang/goldendict-ng/assets/105480088/778d3176-5d67-4dc0-b8e1-8aa75a6472d0)
Sadly in german

**Comment by franzmondlichtmann** [comment]
Btw. argos-translate takes several seconds to produce an translation output, could it be a timeout on goldendict-ng's side?

**Comment by franzmondlichtmann** [comment]
For whatever reason, it did not work with conda run, I had to give the full path instead `/home/laptop02/miniconda3/bin/argos-translate` "test" -f es -t de 
Luckily that worked
