### ISSUE TITLE
Add Deepl API support please

### ISSUE THREAD

**Issue by franzmondlichtmann** [xiaoyifang/goldendict-ng#1649]
**Is your feature request related to a problem? Please describe.**
I have free Deepl API (yes you have to register via credit card, but you effectively never reach the limit of 500.000 words per month, also you don't get charged when you're over the limit)

**Describe the solution you'd like**
Please implement the Deepl API or consider giving an easy solution to integrate outside APIs.
Best would be, if you can choose sorce and target language with two seperate drop down menus.
I know its a lot to ask.

**Describe alternatives you've considered**
Deepl CLI does work, but its inofficial and needs to be set up seperately: https://github.com/kojix2/deepl-cli

**Comment by xiaoyifang** [comment]
add deepl as program dictionary.

**Comment by franzmondlichtmann** [comment]
I found it. I must have missed it.
[Deepl Integration](https://pypi.org/project/deepl/#:~:text=python3%20%2Dm%20deepl%20%2D%2Dauth%2Dkey%3DYOUR_AUTH_KEY%20text%20%2D%2Dto%3DDE%20%22Text%20to%20be%20translated.%22)
