### ISSUE TITLE
Can you share goldendict-ng dev environment information?

### ISSUE THREAD

**Issue by TAbdiukov** [xiaoyifang/goldendict-ng#1662]
**Is your feature request related to a problem? Please describe.**

I wanted to improve goldendict-ng. I know how to develop in C++ but I have no experience with Qt Creator. 

I tried to install Qt Creator... 2 times, and I can never get it working properly. Either some packages are missing, or it keeps saying it needs to download 50GB+. So, it frustrates me.

Furthermore, Qt Creator and their website is very frustrating, because they constantly direct the user to paid option, whereas they offer free Community option.

On [wiki](https://xiaoyifang.github.io/goldendict-ng/developer/) , it just says 
"""
Install Qt and QtCreator
(On Linux, install dependencies)
"""

But I think some information is required.

**Describe the solution you'd like**

Can you share a VM image for goldendict-ng development OR a step-by-step guide with what packages need to be installed?

**Describe alternatives you've considered**

* Installing all packages hat make sense - I always get 2-3 packages missing
* Developing without being able to test (without Qt and Qt creator) - obviously wouldn't work

**Comment by xiaoyifang** [comment]
qtcreator

Package selections
[x]qt6.XX

[x]MSVC2019 /GCC

[x]Qt5 Compatible Module

[*]Additional

[x]Qt Image formats
Qt MultiMedia
Qt Positioning
Qt speech
Qt webchannel
Qt webengine

**Comment by TAbdiukov** [comment]
Thanks for your fast response! Maybe it can be a good idea to ask this information to documentation?

**Comment by shenlebantongying** [comment]
For sure, you are welcomed to tell what's trouble did you met on building goldendict so that we can some more doc.

**Comment by TAbdiukov** [comment]
Currently: no matter what I do, I get this error,

![image](https://github.com/xiaoyifang/goldendict-ng/assets/18607514/cc0f5abb-2ddf-492a-b132-b47764ba3c4a)

My installed packages,

![image](https://github.com/xiaoyifang/goldendict-ng/assets/18607514/244d1672-8839-45b6-9ed1-ae5f4e4fb56e)

![image](https://github.com/xiaoyifang/goldendict-ng/assets/18607514/fea3822b-bdd0-402b-9474-bd9bdbcbb3eb)

![image](https://github.com/xiaoyifang/goldendict-ng/assets/18607514/f3ae4204-568a-4f70-80f1-7d43d73279ab)

![image](https://github.com/xiaoyifang/goldendict-ng/assets/18607514/953ad537-749f-48bb-8386-cf704f51b7d5)


I previously tried to use QT 6.7.2, but I experience the same result...

**Comment by shenlebantongying** [comment]
The webengine doesn't support MinGW. You need to set what QtCreator called "kits" and change the current one's to MSVC.

I don't install the MinGW, so it is already MSVC.

![image](https://github.com/xiaoyifang/goldendict-ng/assets/20123683/542cb4cc-0aa5-415f-ae65-21d6335e62e6)

![image](https://github.com/xiaoyifang/goldendict-ng/assets/20123683/0531b3f0-dd6e-4d54-b688-2c6033130a4e)

(No worries, C++ project is full of land mines and foot guns 😅)

**Comment by shenlebantongying** [comment]
Sadly, the default build is currently broken, you need to manually copy a missing dll from `winlibs`.

At the same time, vcpkg build cost lots of time.

**Comment by TAbdiukov** [comment]
OK. More debugging hell :D

This is if I open `CMakeLists.txt`

![image](https://github.com/xiaoyifang/goldendict-ng/assets/18607514/9d1159dc-7521-4f2b-b3e7-f07b3832cfd2)

This is if I open `goldendict.pro`

![image](https://github.com/xiaoyifang/goldendict-ng/assets/18607514/21ee5afc-1909-4672-af05-357c354f317b)

(this file exists, so I'm not sure why such error occurs)

**Comment by shenlebantongying** [comment]
> This is if I open CMakeLists.txt

You can either initialize git submodules or `-DWITH_EPWING_SUPPORT=OFF` for now

**Comment by shenlebantongying** [comment]
My screenshot is misleading, the config options need to modify list view

![image](https://github.com/xiaoyifang/goldendict-ng/assets/20123683/c10ba04d-cde4-4e45-a3a2-9cf8298ef474)

**Comment by TAbdiukov** [comment]
This is the first run I had,
![image](https://github.com/xiaoyifang/goldendict-ng/assets/18607514/eb7d87f2-658c-480c-96c3-3c14bf58ff69)
![image](https://github.com/xiaoyifang/goldendict-ng/assets/18607514/6230ea54-862d-474a-8c68-e7884a176d71)
![image](https://github.com/xiaoyifang/goldendict-ng/assets/18607514/c6a93d07-3980-42ea-b7c0-84f2ca65f006)
![image](https://github.com/xiaoyifang/goldendict-ng/assets/18607514/320ab250-05a3-4a44-afd8-b05965f658e6)

**Comment by shenlebantongying** [comment]
Two options

1. Add Qt's lib folder into `PATH`

In GD only:

![image](https://github.com/xiaoyifang/goldendict-ng/assets/20123683/94af7914-870a-405e-903d-1a75003693e1)


2. Run this target,

(As of right now, it has a bug, needs to copy a dll manually to beside goldendict.exe)

![image](https://github.com/xiaoyifang/goldendict-ng/assets/20123683/5a99fe45-472c-4d64-98ee-68394bea3b31)

**Comment by TAbdiukov** [comment]
Thanks! I now got it to work, so I hope all this information in one place can help create the developer documentation 😄
