### ISSUE TITLE
[macOS] The close button (❌) is not working as expected, it should actually "hide', as all the Apple's apps do. 

### ISSUE THREAD

**Issue by zt-c** [xiaoyifang/goldendict-ng#1731]
**Describe the bug**

According to the behavior of Apple's app's, the red cross should actually "hide" rather than kill the app, when this window/tab is the only window/tab for one application.

一般来说mac上面的UI逻辑是，对于只有一个页面/窗口的app，点关闭实际上是hide，并不真正kill这个process。

（比如试一下系统自带的notes，hide(cmd-h)和点❌效果是一样的，再点一下notes图标都是秒开，说明实际上并没有关）

**Comment by zt-c** [comment]
Another convenient example is "Activity Monitor", close(cmd+w) and hide(cmd+h) has exactly the same result. They both hide rather than kill the app. 

`close` only means close the window on macOS UI, which means `hide` the window if it is the only one, and we can easily get the window back without reloading all the data.

**Comment by zt-c** [comment]
> The red button means "close this window" not "close this app." Whether the app quits after the window is closed depends on the context of the app and whether the developer thinks closing the app is the right thing to do.

And the hotkey to "Hide the main window" should also make it "hide" rather than "minimize"(current behavior).

**Comment by zt-c** [comment]
Well...I think the behavior for the red button should be: 

* If the active tab is not the last one, close the tab. 
* If the active tab is the only one, we don't need to close any tab but just hide the window. 

This is the most intuitive behavior in macOS. We don't need to close all tabs. Does this make more sense and be easier for us to implement?

I am asking because its behavior is super unexpected when we use the "cmd+w"(red button), and users always need to think about "this is the GoldenDict-ng app, remember to use 'cmd+h' for this specific app" while using it.

**Comment by shenlebantongying** [comment]
Maybe I am biased because I have lots of open source software with poor macOS support and they all just close when red button clicked.

Googling shows that there are also lots of people of complaining the opposite, the red button is a duplication of the yellow button https://www.google.com/search?q=macOS+red+button+quit

Perhaps just ignore the red button, and consistently uses Ctrl+Q to quit and Ctrl+H for hiding for all apps.

**Comment by zt-c** [comment]
Make sense, most open-source applications would not add specific support for macOS's HCI design. 

As for the difference between the yellow and the red buttons: 
The red button is "Cmd+W" which is meant to close a tab. 
The yellow button will not close any tabs but will make the window into the "minimize zone' in the dock. 

Maybe you are right about not many people being familiar with both macOS and QT - if I knew QT, I would have already fixed it...

**Comment by shenlebantongying** [comment]
Is this correct behavior?

+ red button -> close all tabs then minimize
+ Actually quit actions are click Menu -> App name -> "Quit" and Cmd+Q and Right click dock icon -> Quit 
+ yellow button -> minimize only

Credit: I see what this PR does and knows what to do right after 😅 https://github.com/keepassxreboot/keepassxc/pull/583
