### ISSUE TITLE
Write version into the registry

### ISSUE THREAD

**Issue by gotounix** [xiaoyifang/goldendict-ng#1744]
While using `winget` manage software, winget can't get goldendict-ng's version.

So while using `winget upgrade --all` to upgrade software will reinstall goldendict-ng again.

https://github.com/goldendict/goldendict/issues/1677

https://github.com/microsoft/winget-cli/issues/3854

**Comment by shenlebantongying** [comment]
Add something like
```
WriteRegStr/DeleteRegValue HKLM `Software\Microsoft\Windows\CurrentVersion\Uninstall\@CPACK_PACKAGE_INSTALL_REGISTRY_KEY@" DisplayVersion "${VERSION}"
```

to

CPACK_NSIS_EXTRA_INSTALL_COMMANDS / CPACK_NSIS_EXTRA_UNINSTALL_COMMANDS

should fix the problem.

**Comment by xiaoyifang** [comment]
Is the registry the only way to provide the version information to winget?

**Comment by xiaoyifang** [comment]
I think winget as a package manager tool which handle its package seperately 。
Does Winget have a centralized place to store ,manage all the packages including the version information.

**Comment by gotounix** [comment]
@xiaoyifang [Windows Package Manager Community Repository](https://github.com/microsoft/winget-pkgs) is the place to store all packages's information.
But while using Winget to upgrade your package, it only get the current installed version from registry.

**Comment by shenlebantongying** [comment]
This seems already fixed after we switched to CPack.

The newest version from https://github.com/xiaoyifang/goldendict-ng/releases shows these:

<img width="500px" src="https://github.com/user-attachments/assets/327bc3d7-db50-4b4e-bc6c-0a08151af410">

The registry path is `Computer\HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall\GoldenDict-ng`

The NSIS template used by Cpack already did it for us 😅 

https://github.com/Kitware/CMake/blob/3bf4bcba114380924ab829da2099a1ceb5a231c6/Modules/Internal/CPack/NSIS.template.in#L669-L670

**Comment by shenlebantongying** [comment]
> Is the registry the only way to provide the version information to winget?
> I think winget as a package manager tool which handle its package seperately 。
> Does Winget have a centralized place to store ,manage all the packages including the version information.

winget has to deal with Windows's existing legacy. It can upgrade software that isn't installed with winget. I think they have no choice but to continue using the registry for eternity.

**Comment by gotounix** [comment]
There are some many releases named `24.05.13`, I don't know how to add this version to winget-pkgs.
Is it possible to use minor version numbers to mark alpha versions instead of using a series of random characters?

**Comment by shenlebantongying** [comment]
Maybe just don't package alpha versions? Some of them are just for testing 😅

I plan to cut a release within this month after qt6.7.3 is released. What do you think about this schedule @xiaoyifang? 

https://wiki.qt.io/Qt_6.7_Release

**Comment by xiaoyifang** [comment]
> I plan to cut a release within this month after qt6.7.3 is released. What do you think about this schedule

Does goldendict-ng have some dependencies on qt6.7.3?
If not,  we do not have to wait the release of qt6.7.3

**Comment by shenlebantongying** [comment]
This problem should be fixed now. @gotounix Do you want to update the winget-pkg's goldendict-ng's version? I think we can add it to download page.

**Comment by gotounix** [comment]
@xiaoyifang Why would you modify the Assets file after a version has been released? It causes the SHA-256 hash to change, preventing the submission/use of the winget repository. Shouldn't the correct approach be to release a new version to fix the error?

**Comment by shenlebantongying** [comment]
😅My bad. I triggered build again because I thought something was wrong with uploading (a few files were seems missing).

They won't be changed anymore.
