### ISSUE TITLE
flatpak 24.09.03 Question

### ISSUE THREAD

**Issue by gcqmkm02** [xiaoyifang/goldendict-ng#1749]
在ubuntu24.04 flatpak的goldendict-ng执行以后都building fulltext-index。
有很多sept. 07 08:54:23 uoc kernel: page dumped because: fuse: trying to steal weird page

**Comment by xiaoyifang** [comment]
> 在ubuntu24.04 flatpak的goldendict-ng执行以后都building fulltext-index。

take a screenshot 

> 有很多sept. 07 08:54:23 uoc kernel: page dumped because: fuse: trying to steal weird page

https://github.com/trapexit/mergerfs/issues/401

**Comment by gcqmkm02** [comment]
https://imgur.com/a/XTBNVo9

好像我辞典太多了，所以应该等40分钟才行。现在已经没有building也没有page dumped. 我不用mergerfs，也不知道是什么。

想问你们怎么调试，以后哪里有好看的style.css。谢谢

**Comment by xiaoyifang** [comment]
> 都building fulltext-index。

只是 checking ,不是building。

可能的话，你从源码build看看。

**Comment by shenlebantongying** [comment]
The message is from kernel level. No idea what to fix. Reopen if it causes actual problems.
