### ISSUE TITLE
mac dmg crash, libicudata bundle problem

### ISSUE THREAD

**Issue by xiaoyifang** [xiaoyifang/goldendict-ng#1761]
Translated Report (Full Report Below)
Process: GoldenDict-ng [55311]
Path: /Applications/GoldenDict-ng.app/Contents/MacOS/GoldenDict-ng
Identifier: org.xiaoyifang
Version: 24.05.13 (???)
Code Type: ARM-64 (Native)
Parent Process: launchd [1]
User ID: 501

Date/Time: 2024-09-10 10:46:33.8286 +0800
OS Version: macOS 14.6.1 (23G93)
Report Version: 12
Anonymous UUID: C2DD2621-B847-3EF3-D9C8-C276BD52EE14

Sleep/Wake UUID: AB52A89C-CB70-424D-909F-4221E182A393

Time Awake Since Boot: 140000 seconds
Time Since Wake: 935 seconds

System Integrity Protection: enabled

Crashed Thread: 0

Exception Type: EXC_CRASH (SIGABRT)
Exception Codes: 0x0000000000000000, 0x0000000000000000

Termination Reason: Namespace DYLD, Code 1 Library missing
Library not loaded: @loader_path/libicudata.74.dylib
Referenced from: /Applications/GoldenDict-ng.app/Contents/Frameworks/libicui18n.74.dylib
Reason: tried: ‘/Applications/GoldenDict-ng.app/Contents/Frameworks/libicudata.74.dylib’ (no such file)Library not loaded: @loader_path/libicudata.74.dylib
Referenced from: <970EB52F-1E1F-3ACF-9FF9-92999DD585E1> /Applications/GoldenDict-ng.app/Contents/Frameworks/libicuuc.74.dylib
Reason: tried: ‘/Applications/GoldenDict-ng.app/Contents/Frameworks/libicudata.74.dylib’ (no such file)

**Comment by xiaoyifang** [comment]
the libicu*  should be imported by libzim . This dependency issue happens many time before ,  I used to manually handle the file to fix this.


Now we moved to CMake ,does this work https://zhuanlan.zhihu.com/p/115180323?from_voters_page=true

**Comment by shenlebantongying** [comment]
> Now we moved to CMake ,does this work https://zhuanlan.zhihu.com/p/115180323?from_voters_page=true

TBH, I don't know 😅. Currently, we depend on windeployqt & macdepoloyqt to achieve the same purpose.
