### ISSUE TITLE
Flatpak version doesn't start at all

### ISSUE THREAD

**Issue by GD-fix** [xiaoyifang/goldendict-ng#1776]
**Describe the bug**

**To Reproduce**
# flatpak install flathub io.github.xiaoyifang.goldendict_ng
Looking for matches…
Skipping: io.github.xiaoyifang.goldendict_ng/x86_64/stable is already installed
# flatpak run io.github.xiaoyifang.goldendict_ng
bwrap: execvp goldendict: No such file or directory

**OS and software versions**

- OS: OpenSUSE Tumbleweed
- Version up to date
![GD-ng_not_start](https://github.com/user-attachments/assets/4f870911-ed50-4413-9720-85c60619ad68)

**Comment by shenlebantongying** [comment]
Cannot reproduce, it works for me. I think this is your local setup's problem. Have you tried anything? Like google the error message, try install, `flatpak repair`.... Btw, [copying /var/lib/flatpak](https://github.com/xiaoyifang/goldendict-ng/issues/1327#issuecomment-2143378174) will certainly cause problems

**Comment by GD-fix** [comment]
What is .... Btw?

**Comment by shenlebantongying** [comment]
"By the way" https://www.collinsdictionary.com/dictionary/english/by-the-way

**Comment by GD-fix** [comment]
I had deleted via Discover old installation and had installed via Command prompt. After that the first time it was run, the second - not: https://github.com/xiaoyifang/goldendict-ng/issues/1779
After uninstalling and installing it didn't run at first time too...
