### ISSUE TITLE
Doesn't work a dictionary edition

### ISSUE THREAD

**Issue by GD-fix** [xiaoyifang/goldendict-ng#1780]
**Describe the bug**
"Edit the dictionary" (or something the same - it's my own translation from Russian to English) doesn't start anything (it some seconds loads the CPU, but without any console output).

**To Reproduce**
0. "Behaviour", not a behavior: edit the blank, please...
1. Go to 'dictionaries panel'
2. Click right on any editable dictionary
3. Scroll down on context menu to 'Edit the dictionary' and left click

**Affected Dictionaries**
Any editable

**Expected behavior**
0. "Behaviour", not a behavior: edit the blank, please...
May be it's better to use some external editor, that will be chosen in Parameters?

**OS and software versions**
- OS: OpenSUSE Tumbleweed
- Version up to date

**Comment by xiaoyifang** [comment]
> 3\. Scroll down on context menu to 'Edit the dictionary' and left click

provide a screenshot

**Comment by GD-fix** [comment]
![GD-ng_dic_edit](https://github.com/user-attachments/assets/f0941569-9e91-40e1-aa19-7b50521e332c)
With the rpm version (24.02.16 at 2024-05-05T04:12:48Z) it's the same...

**Comment by shenlebantongying** [comment]
It is an undocumented hidden feature of the original GD https://github.com/search?q=repo%3Agoldendict%2Fgoldendict%20editDictionaryCommandLine&type=code

Whatever the code tried to do in the past, it is nonsense now.

We should just delete related code.
