### ISSUE TITLE
Feature request: make the name of the dictionary selectable

### ISSUE THREAD

**Issue by AnabasisXu** [xiaoyifang/goldendict-ng#1781]
Sometimes I need to copy the of the dictionary title together with the explanation it gives. But it turns out that the dictionary title cannot be selected: click on the dictionary title in the result will only toggle whether the result is collapsed. 

So I have to click the dictionary information, and copy the dictionary name there. 

Would be great if the dictionary title is straightforwardly selectable.

**Comment by shenlebantongying** [comment]
I honestly not sure is this a feature or bug. Both original GD and us for some reason overrides `user-select`

* https://github.com/search?q=repo%3Agoldendict%2Fgoldendict%20user-select&type=code
* https://github.com/search?q=repo%3Axiaoyifang%2Fgoldendict-ng+user-select&type=commits&p=1

**Comment by shenlebantongying** [comment]
I think "title not selectable just like a button" is a feature 😅.

But you can override this by putting 

```css
* {
	user-select: auto !important;
}
```

into article-style.css  -> https://xiaoyifang.github.io/goldendict-ng/topic_userstyle/

**Comment by AnabasisXu** [comment]
Adding the above css to article-style.css did not make the dictionary name selectable. 

But thanks anyway.
