### ISSUE TITLE
tarball for linux (amd64)

### ISSUE THREAD

**Issue by KonstantinDjairo** [xiaoyifang/goldendict-ng#1782]
i developed a way to generate fully portable tarball with goldendict-ng and its required libraries, it can be shipped in the same way as firefox and other bigger softwares, i think it's somehow better than using an appimage, which was done in the past.

what do you think about it? it'd be useful so that people wouldn't rely on flatpak

**Comment by shenlebantongying** [comment]
> what do you think about it?

I think it likely contains bugs that are hard/impossible to predict and phantom. For example, [supporting popular IME like ibus/fcitx](https://github.com/xiaoyifang/goldendict-ng/issues/795) is a good starting bug. Testing on Nvidia card could be a bonus.

“Fully portable” is insanely hard and time-consuming to fix. People has been working on various solutions of “Fully portable” for decades, and both chromium and Qt are pretty complex. Flakpak/Snap (somewhat a lightweight VM) is currently the most reliable approach to do such thing, despite their sandbox model sometimes causes problems. 

Anyway, feel free to
* Send PR that have a script to auto product it 
* Or just show code
* Or attach such binary to prove that it works 
* Or show proof that it works on at least one or two popular systems such as ubuntu22.04 & 24.04, debian stable, fedora, openSUSE...
  * (and special distros like cutting edge systems like arch/nix/guix/gentoo, or esoteric libc systems like void/alphine)

**Comment by shenlebantongying** [comment]
Good read about the fragmentation of Linux distros https://gitlab.com/probono/platformissues

Practical question:

Why Appimage blocks lots' libraries and what to do with them for creating “fully portable” whatever? https://github.com/AppImageCommunity/pkg2appimage/blob/master/excludelist

**Comment by KonstantinDjairo** [comment]
proof that it runs at least in void linux:

![](https://matrix.eientei.org/_matrix/media/v3/download/lvx.red/ICPhhcjkNwBehgrccGkDkXaF?allow_redirect=true)

now i need to test it on ubuntu/fedora, but i think it will run just fine, since void was a hard candidate
