### ISSUE TITLE
Feature request: Using source files with reference syntax in DSL format

### ISSUE THREAD

**Issue by samvan11** [xiaoyifang/goldendict-ng#1786]
Hello,

I want to make a dsl glossary that has multiple pdf files zipped as a single source file. The syntax [s]example.pdf[/s] allows opening the pdf in the zip with the default external program. What I want to do is displaying some clickable, explanatory text to the file instead of the file name.

The syntax [ref target="source item"displayed text[/ref] does this for text, but it doesn't support files.

So, the syntax [ref target="[s]example.pdf[/s]"chapter 1[/ref] doesn't work. The link gets broken.

It would be nice if using [s][/s] inside [ref target=" "[/ref] were possible. That could also be used for masking images with clickable text which might be useful when there are a lot of images in an article and displaying them all at once is overkill.

Another option could be introducing a new syntax like below:

[s target="file's name"]displayed text[/s]

**Comment by shenlebantongying** [comment]
This feature already exists.
In DSL, you can use,
```
[url target="file://./asd.pdf"] text [/url]
or
[url target="file:///asd.pdf"] text [/url]
```
for a folder like this
```
.
├── a.dsl
└── asd.pdf
```
.

This is a hidden feature. For relative path in `file://` will be automatically converted to relative to `a.dsl`. Note that triple slashes `file:///filename`  or relative path `file://./filename` is needed to trick QUrl to think that the link is localfile.

https://github.com/xiaoyifang/goldendict-ng/blob/58f346f23e9e5ce196c4177a686dcf6c8d50493c/src/dict/dsl.cc#L866-L882

---

For reference, tag `[s]` is not for links but rather for images/videos/sounds.

In GD, it falls back to be a text link, so it feel like a link

https://github.com/xiaoyifang/goldendict-ng/blob/58f346f23e9e5ce196c4177a686dcf6c8d50493c/src/dict/dsl.cc#L854-L864

---

References (in Russian): 

Tag [s] -> https://lingvoboard.ru/store/html/DSLReference_HTML/index.html?page=tag_mm.html#s

Tag [url] ->https://lingvoboard.ru/store/html/DSLReference_HTML/tag_links.html#url
