### ISSUE TITLE
I can't rerun the GD-ng without restarting the OS

### ISSUE THREAD

**Issue by GD-fix** [xiaoyifang/goldendict-ng#1798]
The beginning:
https://github.com/xiaoyifang/goldendict-ng/issues/1779#issuecomment-2380862006
Of course, the `flatpak ps` doesn't printout anything and the tray icon is not still there (I start on this PC GD-ng from console and after GD-ng exiting I close the console, _by the way, it would be nice to add the application exitting/quitting button on the Navigation panel_).
Restarting the user session doesn't matter: only after restarting the OS I can start the application.

**Comment by shenlebantongying** [comment]
You have to figure out the difference between 1st and 2nd run without restarting. The info provided doesn't tell anything about what to fix.

**Comment by GD-fix** [comment]
You forgot to mention what specific additional information You need...

**Comment by shenlebantongying** [comment]
How do anyone suppose to know what's wrong with almost no info provided.

No, I don't want to read your message about who is responsible again.

And, No, open source does not imply free user support.

So what's wrong?

I don't know, you tell me.
