### ISSUE TITLE
Stop scrolling on QT 6.4 MacOS

### ISSUE THREAD

**Issue by itkind** [xiaoyifang/goldendict-ng#180]
When scrolling large entries, you can't stop the scroll by just touching the trackpad, you need to touch and scroll to the opposite direction to stop the scroll very bouncy, you can also scroll over the first entry. Is it possible to repair it? 
![Image on 2022-10-26 02 11 28 PM](https://user-images.githubusercontent.com/22380863/198022789-3b41162f-e70f-4339-b25f-fc2bcc67d043.jpg)

**Comment by xiaoyifang** [comment]
I have no macos ,so I have no idea what it is.
can you give me a record screen video to show the steps.

**Comment by itkind** [comment]
On the video you will only see a scrolling window. My point is: how do you stop a scroll with a trackpad? On mac you put 2 fingers on the trackpad. But in GD the scroll doesn't stop immediately, it just slows down and then it stops.

**Comment by xiaoyifang** [comment]
I have no macos to test this issue ,maybe wait for other's help

**Comment by xiaoyifang** [comment]
maybe related to this https://bugreports.qt.io/browse/QTBUG-47697

**Comment by shenlebantongying** [comment]
The "empty area" above the page (NSScrollViewRubberbanding) is mac's feature.

There is a hack to disable it globally

https://discussions.apple.com/thread/253588608


It is written in chrome's code. I don't know what can we do. Qt web engine does't expose those low-level details.

https://github.com/chromium/chromium/blob/77dbba30e477c1455627aa4749670613763d0357/content/browser/theme_helper_mac.mm#L61

---

> scrolling large entries, you can't stop the scroll by just touching the trackpad, you need to touch and scroll in the opposite direction to stop the scroll very bouncy

I also think this is mac's feature.

You can either scroll slower or disable the "Use inertia when scrolling".

https://support.apple.com/en-ca/guide/mac-help/unac899/mac

I don't understand. Isn't all "native" macOS apps works like this??

**Comment by itkind** [comment]
The issue is that when in scroll, putting the fingers down on the trackpad doesn't stop the scroll.

**Comment by xiaoyifang** [comment]
https://bugreports.qt.io/browse/QTBUG-67716

https://github.com/qutebrowser/qutebrowser/issues/7810#issuecomment-1662960610

**Comment by shenlebantongying** [comment]
Fixed by https://github.com/qt/qtwebengine/commit/2d2e7bd6f13456acd217eb1b18c6dd6b48cf0c0c (and maybe https://github.com/xiaoyifang/goldendict-ng/pull/1421 😅)
