### ISSUE TITLE
Selected word immediately closes itself on Mac

### ISSUE THREAD

**Issue by sonerfromnurland** [xiaoyifang/goldendict-ng#1803]
I have updated golden dict 23 to 24.09.0.316ec900 and I encountered the following issue.
There was no any issue with 23 but the latest released version yields this issue.
When I press 4 times Cmd+C it shows but why? Only two times Cmd+C was enough in its old version.
The os is Mac os sonoma. But the issue also appears in monterey.

![2024-10-07 09 47 11](https://github.com/user-attachments/assets/1cb73923-b5b3-44f2-9735-cf7de14d0bcf)

**Comment by shenlebantongying** [comment]
This should include a fix https://github.com/xiaoyifang/goldendict-ng/releases/tag/v24.11.0-alpha.44992766

Though, there is another bug on macOS Sequoia (15). If mainwindow is visible, the showing up of scanpopup will bring maindinwow to front. No idea how to fix it.
