### ISSUE TITLE
change 'Enable Scanning'   to another more accurate tooltip ?

### ISSUE THREAD

**Issue by xiaoyifang** [xiaoyifang/goldendict-ng#1808]
![image](https://github.com/user-attachments/assets/626d26e1-f4b5-48ac-98f5-4957d8513049)

this button seems only used in the following cases:
1, clipboard
2, popup
3, combine with Ctrl+C+C
Do you have any idea? @shenlebantongying

**Comment by shenlebantongying** [comment]
How about change the tooltip to `Enable clipboard tracking for scan popup.`.

---

There was a rant about the term of "popup" http://goldendict.org/forum/viewtopic.php?f=6&t=1740 😅

**Comment by xiaoyifang** [comment]
what about restricted the button to clipboard only. and change the tooltip to "Enable Clipboard monitoring"(or tracking)

**Comment by shenlebantongying** [comment]
> change the tooltip to "Enable Clipboard monitoring"(or tracking)

+1

Let's just change it to `Toggle clipboard monitoring.` as scanpopup may not be involved at all. (`Toggle` as suggested  by that rant from 10 years ago 😅.)

Longer version:

```
Toggle clipboard monitoring. Copied text will be sent to either a scan popup or the main window.
```

**Comment by shenlebantongying** [comment]
How about just drop the `scan` part and call it `popup window` instead.

```
Toggle clipboard monitoring. Copied text will be sent to either a popup window or the main window.
```

**Comment by xiaoyifang** [comment]
agree.
