### ISSUE TITLE
Add kabyle language on Crowdin

### ISSUE THREAD

**Issue by BoFFire** [xiaoyifang/goldendict-ng#1823]
Hello,
Please add Kabyle `kab` language on Crowdin so that we will be able to translate goldendict-ng.

Thank you.

**Comment by xiaoyifang** [comment]
https://crowdin.com/editor/goldendict-ng/93/en-kab?view=comfortable&filter=basic&value=0

**Comment by BoFFire** [comment]
Thank you @xiaoyifang Xie xie
