### ISSUE TITLE
Flatpak version audio output device is inconsistent with the native system

### ISSUE THREAD

**Issue by fanguohao** [xiaoyifang/goldendict-ng#1824]
**描述 bug**
flatpak 版本音频输出设备与本机设置不一致， 具体表现为：只能输出到line out 有线设备，蓝牙设备无法获得音频输出。

**环境**
ubuntu 22.04
goldendict 版本 24.09.13

**复现 bug 的步骤**
1. 打开软件
2. 连接蓝牙耳机 和有线设备，本机系统切换到蓝牙设备为输出
3. 点击任意单词发音，蓝牙设备无音频输出，有线设备输出音频。（其他flatpak 软件不存在此问题，如spotify音频输出与本机保持一致）

**推测**
内部绑定了单一输出设备，没有进行动态判断。

**Comment by xiaoyifang** [comment]
1, 切换输出后。  退出gd-ng,重新打开，是否正常。
2, 更改下音频的播放引擎，   （内）外置的是否正常。
![image](https://github.com/user-attachments/assets/edc08e6f-16b6-4852-96d3-bbce78dbb26b)

**Comment by fanguohao** [comment]
感谢！在内部切换到Qt multimedia 音频恢复正常～

通过pulseauido 查看发现，选中ffmpeg， 音频输出设备不受系统接管
