### ISSUE TITLE
Mac search line out of focus after hitting enter

### ISSUE THREAD

**Issue by itkind** [xiaoyifang/goldendict-ng#185]
QT 6.4 on M1 Mac GD is out of focus after typing anything and hit enter (without clicking in the search pane). The result is that you can't continue to type inside the search line without clicking somewhere. Also cmd+L or ctrl+L doesn't jump to search line until you click somewhere.  The ideal is any typing focuses the search line (which is the normal behaviour unless you hit enter).

**Comment by itkind** [comment]
The issue is resolved with the latest alpha.

**Comment by itkind** [comment]
In the latest alpha the same problem happens after opening a new tab, typing something and hitting enter. Or after opening any application and returning to GD.

**Comment by xiaoyifang** [comment]
seems like the gd application has lost the focus.

**Comment by itkind** [comment]
> seems like the gd application has lost the focus. do not use QT 6.4 version for now, this version has reported with many bugs.

cmd+f still works in that state

**Comment by xiaoyifang** [comment]
can not reproduced on macos using virtual machine.

**Comment by itkind** [comment]
should I post this into the main GD repository?

**Comment by xiaoyifang** [comment]
I am sure if this problem exists in the original version as well。

Have you tried the other qt version dmg ? such as qt6.3.2

**Comment by itkind** [comment]
QT 6.3.2 doesn't have this issue.

**Comment by itkind** [comment]
Since you don't publish assets based on QT 6.3.2 anymore, this issue within 6.4.3 is not resolved.

**Comment by xiaoyifang** [comment]
any relation with 2f4db6c34f9b73459666e7bbfb8235925cd1ebf2?

**Comment by xiaoyifang** [comment]
Do you have your search line docker opened.
![image](https://user-images.githubusercontent.com/105986/232430518-95eed40d-6cfd-4105-ab4b-04f495ddcd96.png)

When the docker is not opened , does the issue  exist?

**Comment by itkind** [comment]
It works now! THANK YOU!!!!! ❤️❤️❤️
