### ISSUE TITLE
Homebrew上传需要签名Homebrew submission need signature

### ISSUE THREAD

**Issue by whitewatercn** [xiaoyifang/goldendict-ng#1855]
**Is your feature request related to a problem? Please describe.**

我尝试给Homebrew提交软件，macOS 需要软件签名，如果作者可以搞定签名的话我再上传arm版
I tried to submit software to Homebrew, macOS version requires software signature,  if the author can get the signature, I will upload the arm version

https://github.com/Homebrew/homebrew-cask/pull/189332

**Comment by shenlebantongying** [comment]
The type of code signing required by homebrew needs to pay Apple 99 USD per year, which is unlikely to happen.

https://github.com/xiaoyifang/goldendict-ng/issues/1141#issuecomment-2106340197

**Comment by whitewatercn** [comment]
可惜，那就先不传了
