### ISSUE TITLE
Can't input Korean and Japanese on Mint Linux

### ISSUE THREAD

**Issue by su-jang** [xiaoyifang/goldendict-ng#1865]
### Discussed in https://github.com/xiaoyifang/goldendict-ng/discussions/1864

<div type='discussions-op-text'>

<sup>Originally posted by **su-jang** October 25, 2024</sup>
Both the latest Mint Linux and Goldendict-NG. I cannot input Korean and Japanese letters using UIM input method. I am using UIM-Byeoru for Korean and uim-mozc for Japanese input. Switching input method to iBus resolved this issue, but the iBus input method is very unstable for Korean and Japanese input and I cannot use it for daily use. Any advice would be very appreciated. Thank you.</div>

**Comment by shenlebantongying** [comment]
Does UIM work on other qt apps? If you are using Wayland, does it work on XWaland apps?

**Comment by su-jang** [comment]
Downloaded a qt app, FeatherPad, for test, and I could input Korean and Japanese letters without problem.
I can confirm that I can input Korean and Japanese GoldenDict-661dd4d-x86_64.AppImage, unstable though. Unfortunately this AppImage GoldenDict does not accept  EPWING dictionaries.
I do not know about Wayland. Thank you for your concern.

**Comment by su-jang** [comment]
Here's a screenshot of AppImage and FeatherPad with Korean and Japanese input.
![스크린샷, 2024-10-26 06-40-33](https://github.com/user-attachments/assets/e1d6e53f-3114-4442-a4d9-a3fdf3b947c7)

**Comment by shenlebantongying** [comment]
Sadly, it seems UIM doesn't support Qt6 at all https://github.com/search?q=repo%3Auim%2Fuim+qt6&type=issues

Maybe use something better than IBus, e.g., Fcitx5.

**Comment by su-jang** [comment]
Thank you.
