### ISSUE TITLE
Audio on Qt 6.7.3

### ISSUE THREAD

**Issue by abc16361** [xiaoyifang/goldendict-ng#1868]
**Describe the bug**
After upgrading to v.Qt6.7.3, clicking words on pages and History gives a very unclear, hoarse sound, but speaker buttons on the page work fine. This behavior was tested only on GoldenDict-ng-24.11.0-Qt6.7.3-Windows.7z packages / Win 11. 

![audio_qt673](https://github.com/user-attachments/assets/7db078dd-789b-458d-980a-f1cd444de192)

**Comment by shenlebantongying** [comment]
I suspect Qt bumped major FFmpeg version in its minor release, and this issue kicks in 

https://github.com/xiaoyifang/goldendict-ng/issues/1738

Qt6.6.3 version should work fot these audios.

**Comment by kumiko42** [comment]
The Qt6.7.3 version on macOS 14 also arbitrarily makes explosive noises even at the lowest volume setting.
