### ISSUE TITLE
Running on an unrooted Termux

### ISSUE THREAD

**Issue by b9Joker108** [xiaoyifang/goldendict-ng#1874]
**Is your feature request related to a problem? Please describe.**
I searched throughout Discussions and Issues and I could find no mention of Termux.

**Describe the solution you'd like**
I would really like to use this project in my unrooted Termux host environment and/or one of my proot chroots. But, ideally on the host environment.

**Describe alternatives you've considered**
Instructions for installing on Termux.

**Additional context**
Maybe assistance with potentially making a package for the Termux repository.

**Comment by shenlebantongying** [comment]
>  Instructions for installing on Termux.

If you succeed, related PR welcomed.

>  Maybe assistance with potentially making a package for the Termux repository.

There are various dependencies missing in Termux's repo. Don't think it is possible without heroic effort.
