### ISSUE TITLE
Code style, explicit `==0` and `==nullptr` ?

### ISSUE THREAD

**Issue by shenlebantongying** [xiaoyifang/goldendict-ng#1910]
I think implicit checking pointer null is fine, because it is super popular

```
Object * a;
if(a){}
```

---

However, I feel

```
int a;
if(!a){}
```

is super confusing.

It needs 3 steps

1. needs to know the type of `a` is int (or question is the code to check if `a` is null)
2. know 0 means false
3. Thus, `!a` means `a!=0`

---

This clang-tidy check --> `readability-implicit-bool-conversion` https://clang.llvm.org/extra/clang-tidy/checks/readability/implicit-bool-conversion.html

I want to disable `AllowPointerConditions` and mass convert `AllowIntegerConditions` part so that IDEs stop warns this very widespread thing.

Note that clang-tidy cannot distinguish flag check and will introduce `if ((x & FLAG) != 0)` :sweat_smile: 

https://clang.llvm.org/extra/clang-tidy/checks/readability/implicit-bool-conversion.html

Related discussion of another project https://github.com/libsdl-org/SDL/issues/7214

@xiaoyifang good?

**Comment by xiaoyifang** [comment]
how much codes have been affected by this?

**Comment by shenlebantongying** [comment]
This much :sweat_smile: 

* Just make int -> bool explicit
* pointer -> bool is untouched

https://github.com/xiaoyifang/goldendict-ng/pull/1913

I think we should disable `AllowPointerConditions` in any case because it is too common in both this codebase and other places.

**Comment by xiaoyifang** [comment]
Too much code changed. but it seems ok.
Though I would prefer a much gental way, fix them when the related PR has touched them.

`if(pointer)` syntax seems used more widely.

**Comment by shenlebantongying** [comment]
I will disable some unrealistic warnings in `.clang-tidy` later.
