### ISSUE TITLE
Forced Alignment

### ISSUE THREAD

**Issue by samvan11** [xiaoyifang/goldendict-ng#1929]
Hello,

RTL scripts are normally right-aligned, but when there are multiple lines of different scripts that are supposed to be paired vertically, having different alignments makes them look scattered. In the original version of GD, the default alignmet is left which makes it more suitable for such content.

Original vs NG

![gd1](https://github.com/user-attachments/assets/896ce0de-8d39-442f-bf7b-05707e8b0b91)

![gd2](https://github.com/user-attachments/assets/f1b9d9fd-26f7-4933-bea3-4c691aed3118)

Is there a way to force alignment for specific dictionaries in GoldenDict-ng? If not, it would be nice to have one.

**Comment by xiaoyifang** [comment]
> Is there a way to force alignment for specific dictionaries in GoldenDict-ng? If not, it would be nice to have one.

align the text based on Language is a feature of modern web browser.   old goldendict has done it wrong.

One way to confirm this result is save the article and open it in Chrome and check the result.

**Comment by xiaoyifang** [comment]
> applied only to a single dictionary (say, test.dsl)?

right click on the dictionary in the web view. and choose `inspect element` .  You should see a unique container(div) id which identify this dictionary.  restrict the css to this specific container id.

**Comment by shenlebantongying** [comment]
Descendant combinator ` ` and Universal selector `*` will apply to all children.

```
#gdfrom-63bf4a4a3ac85f14824bebf2d47127bc * {
   text-align: left;
}
```

**Comment by shenlebantongying** [comment]
Ok.

If someone want to implement a reasonable "switch page direction" like Firefox, PR welcomed. I have little idea about the RTL languages.
