### ISSUE TITLE
`WordFinder::updateResults` invokes intensive case folding every second?

### ISSUE THREAD

**Issue by shenlebantongying** [xiaoyifang/goldendict-ng#1943]
I was playing the XCode's Instruments.app and find that `WordFinder::updateResults` is potentially slowing down searching. 

The data is recorded for a running debug build GD and do a few word searches.

There is a ~1.5s region marked as "hang" and it turns out to be all case folding.

I am not sure, but the code says `updateResults` which contains the `foldCase` appears to be called every 1s.

https://github.com/xiaoyifang/goldendict-ng/blob/453948155a2df5ce4bbe989eab60c05f6ae6dbd1/src/wordfinder.cc#L23-L26

P1: a region of 1.5s marked as hang, with mostly case folding

<img width="1493" src="https://github.com/user-attachments/assets/4ecf3304-f850-42c0-8d91-8fa234796a4f">

P2: No idea why would the computer switch CPU core (they are in the main thread).

But in this 1.5s, CPU core 4's result in backtrace form

<img width="1448" src="https://github.com/user-attachments/assets/ad854d31-c7c7-47d9-b0d1-3ef260ffa76a">

CPU core 6's result in flamegrahe
<img width="1680"  src="https://github.com/user-attachments/assets/5552f17f-7233-4e91-af67-1183d90db8e7">

---

Above measurement could be heavily affected by the fact that my computer was doing lots of staff at that time, hence got marked as hang.

Though, I can consistently observe it may range from 0.1~0.5sec in the main thread (No idea why main thread would be named as "CrBrowserMain" btw).
<img width="1574"  src="https://github.com/user-attachments/assets/21c7d484-b7c9-47ee-a468-6f9d44e04570">

---

Also btw, the findMatches appears to be doing duplicated folding?
<img width="1240"  src="https://github.com/user-attachments/assets/e424b4bd-f7d0-4043-9512-2fc40146cc82">

**Comment by shenlebantongying** [comment]
Question, for a 1000 to 2500 cases `switch` statement, would it be faster if it gets loaded as a hash map?

**Comment by xiaoyifang** [comment]
> Question, for a 1000 to 2500 cases `switch` statement, would it be faster if it gets loaded as a hash map? 

Not necessary , a little over design.  Readability is also an important factor

**Comment by shenlebantongying** [comment]
QChar::toCaseFolded cannot be used -> https://github.com/xiaoyifang/goldendict-ng/pull/1945#discussion_r1839081300
