### ISSUE TITLE
Feature request: Allow the use to uncheck the Recursive option of the "content" path in portable mode

### ISSUE THREAD

**Issue by AnabasisXu** [xiaoyifang/goldendict-ng#1957]
Please add a feature to allow the reader to uncheck the `Recursive` option of `content` folder in the `Dictionaries--Sources--Files--PATH`. 

Currently, one can add any folder and uncheck them, but any dictionary in the `content` folder will be scanned and added in portable mode, because the `Recursive` option is checked by default and can not be unchecked in portable mode,.

I know that a workaround is to create a new folder such as "content1" under the `GoldenDict` folder, and then add sub folders there to the PATH so that you can check/uncheck the `Recursive` option. But that would means that I need to move all my dictionaries out and redo the indexing...

![image](https://github.com/user-attachments/assets/ee13248e-2c75-434d-9f9e-884aa2e508c8)

**Comment by xiaoyifang** [comment]
as designed. 

maybe you should not use portable mode.   delete the portable folder alongside with the content folder.
