### ISSUE TITLE
Extension-less audio links are not added to `PronounceEngine` -> `dictAudioMap` causing some audio not auto played

### ISSUE THREAD

**Issue by shenlebantongying** [xiaoyifang/goldendict-ng#1962]
Sample dict file -> .lsa from https://sourceforge.net/projects/goldendict/files/dictionary%20content/1.1/

The code executed to [line 27](https://github.com/xiaoyifang/goldendict-ng/blob/bb87c55b1a3725f8f11f242c534373d8585b25e2/src/pronounceengine.cc#L27)

The isAudioUrl returns false.

<img width="1294" src="https://github.com/user-attachments/assets/a4329af8-9eb6-4a41-9b41-30f270248410">

I think for `gdau` links, it should unconditionally return true without doing the `Filetype::isNameOfSound`

https://github.com/xiaoyifang/goldendict-ng/blob/bb87c55b1a3725f8f11f242c534373d8585b25e2/src/common/utils.hh#L262-L263

Observed bug: Pronounce button not active and auto pronounce doesn't work.

**Comment by xiaoyifang** [comment]
> I think for `gdau` links, it should unconditionally return true without doing the `Filetype::isNameOfSound`

yes,   I agree.
