### ISSUE TITLE
GoldenDict didn't work properly on StarDict format.

### ISSUE THREAD

**Issue by cuongha0701** [xiaoyifang/goldendict-ng#1979]
**Describe the bug**
Only the headword shows up

**Affected Dictionaries**
StarDict format: [OxfordThesaurusofEnglish.zip](https://github.com/user-attachments/files/17856375/OxfordThesaurusofEnglish.zip)

**Screenshots**
![image](https://github.com/user-attachments/assets/11fb64a2-0dd1-461a-978e-d203cd1f89f8)

**OS and software versions**
Goldendict-ng 24.11.0.5b70a7e0 at 2024-11-21T21:18:20Z
Qt 6.8.0 GCC 14.2.1 20240910 arch linux 6.11.9-arch1-1 x86_64-little_endian-lp64
Flags: MAKE_ZIM_SUPPORT MAKE_CHINESE_CONVERSION_SUPPORT NO_TTS_SUPPORT no_ffmpeg_player

**Comment by xiaoyifang** [comment]
introduced with recent commits.  @shenlebantongying 
https://github.com/xiaoyifang/goldendict-ng/releases/tag/v24.11.0-alpha.5b70a7e0  this version has this bug.
the previous  is ol.
https://github.com/xiaoyifang/goldendict-ng/releases/tag/v24.11.0-alpha.bb87c55b

**Comment by xiaoyifang** [comment]
should be introduced by this https://github.com/xiaoyifang/goldendict-ng/pull/1966

I guess the  `version` field should not be deleted.

**Comment by shenlebantongying** [comment]
I have found the issue, I will fix it soon.
