### ISSUE TITLE
Wrong execution order of `<script>` tag without `src` and `defer`

### ISSUE THREAD

**Issue by yshumy** [xiaoyifang/goldendict-ng#1984]
我有一个包含 JavaScript Source File 的词典在最新版上不能用了。

**Comment by shenlebantongying** [comment]
Need more info.

**Comment by yshumy** [comment]
> 需要更多信息。

[词根词缀.zip](https://github.com/user-attachments/files/17897711/default.zip)

**Comment by shenlebantongying** [comment]
This is related to https://github.com/xiaoyifang/goldendict-ng/commit/939e78633165c1cb1908ece5448139d8bea49b41#

Not every `<script>` tag got the `defer`.

The `<script>` block executed before the deferred `jsmind.js`.

<img width="800" src="https://github.com/user-attachments/assets/9a059bf7-74de-4a0e-a248-e44227ac4ad0">
b0aed1R1001

**Comment by xiaoyifang** [comment]
https://github.com/xiaoyifang/goldendict-ng/issues/1379

**Comment by xiaoyifang** [comment]
maybe should wrap around the `<script>` content on   document.ready event.
```
<script>
$(function(){

[content]
});
</script>
```

**Comment by shenlebantongying** [comment]
We can just use the standardized methods

```
<script>
addEventListener("DOMContentLoaded", (event) => {


});
</script>
```

This makes the execution after `DOMContentLoaded` clear.

**Comment by shenlebantongying** [comment]
We can just use standardized stuffs.
```js
function gd_onReady(func) {
  if (document.readyState !== 'loading') {  
    func();
  } else {
    document.addEventListener('DOMContentLoaded', func);
  }
}
```

```html
<script>
gd_onReady(()=> {
  [content]
})
</script>

```

**Comment by yshumy** [comment]
> 我们可以只使用标准化的东西。
> 
> ```js
> // new gd build-in
> function gd_onReady(func) {
>   if (document.readyState !== 'loading') {  
>     func();
>   } else {
>     document.addEventListener('DOMContentLoaded', func);
>   }
> }
> ```
> 
> ```
> <script>
> gd_onReady(()=> {
>   [content]
> })
> </script>
> ```

以前这个词典可以正常使用的，就是最近升级后不能用了。
