### ISSUE TITLE
morphology not working properly

### ISSUE THREAD

**Issue by czz404** [xiaoyifang/goldendict-ng#1998]
**描述 bug**
相同构词法文件
v24.09.1-Release.241104.ca9dd133 测试正常
Daily build v24.11.0-a1b3d76f 测试不正常

**复现 bug 的步骤**
1. 随便搜个拼写错误的词
2. ![upgit_tmp_1732634257638701.png](https://s2.loli.net/2024/11/26/38RDZ7NGMLFOesX.png)

**受影响的词典**

https://www.lanzout.com/iOlZ92gdkyvc?pwd=bk5y

**系统和软件的版本**

Goldendict-ng 24.11.0.a1b3d76 at 2024-11-26T07:46:32Z
Qt 6.7.2 MSVC 194234433 windows winnt 10.0.22631 x86_64-little_endian-llp64
Flags: MAKE_ZIM_SUPPORT EPWING_SUPPORT MAKE_CHINESE_CONVERSION_SUPPORT no_ffmpeg_player

- OS: [Windows11]
- Version [23H2]

**Comment by shenlebantongying** [comment]
Can u share the Hunspell file?

> https://www.lanzout.com/iOlZ92gdkyvc?pwd=bk5y

It has a password.

**Comment by czz404** [comment]
> Can u share the Hunspell file?
> 
> > https://www.lanzout.com/iOlZ92gdkyvc?pwd=bk5y
> 
> It has a password.

sorry , it is bk5y
I tried to upload the zip file directly but failed, so I had to use the network disk.

**Comment by shenlebantongying** [comment]
Thanks for your report, the feedback is really valuable.

I have found the issue.
