### ISSUE TITLE
Request GoldenDict-Ng Android

### ISSUE THREAD

**Issue by zenfas** [xiaoyifang/goldendict-ng#2010]
Dear @xiaoyifang,

Do you have any plan to port GoldenDict-Ng to Android? 

P/S: From Android 14, orginal GoldenDict Android was gone, longtime no update from author.

**Comment by zenfas** [comment]
Official from Goldendict [http://goldendict.mobi/free.php ](url)

**Comment by shenlebantongying** [comment]
Sadly for this endeavor, I don't think this project have enough resource (Android development experience and human time).

Though personally, I wish to achieve https://github.com/xiaoyifang/goldendict-ng/issues/905 to enable development of alternative frontends.
