### ISSUE TITLE
Why isn’t Chinese characters with expanded I supported?

### ISSUE THREAD

**Issue by asgsdbrseg** [xiaoyifang/goldendict-ng#2011]
![image](https://github.com/user-attachments/assets/76df43ef-70f6-4259-ab58-8173986ae6ea)
我确认我的词典里有
![image](https://github.com/user-attachments/assets/d80f95f3-323f-42b8-9d28-69b992508381)

**Comment by xiaoyifang** [comment]
确认  
![image](https://github.com/user-attachments/assets/69e25872-4289-4574-9ca0-aca4d1340b59)
  是词头吗，有词典链接吗

**Comment by asgsdbrseg** [comment]
是一个纯图片词典，里面包含GHI的区块，结构是一样的，GH都没事，只有I不行。
mdd比较大，不知道txt够不够测试
![image](https://github.com/user-attachments/assets/72694dc8-bbcd-4bf1-b2a0-037d9978f88f)
![image](https://github.com/user-attachments/assets/9d9b975d-efe3-4fd2-b615-2dd7e14b0884)
![image](https://github.com/user-attachments/assets/7803c8f2-3ba9-4a33-a97c-db235c73ed31)

[CJK-G2022一改单.txt](https://github.com/user-attachments/files/18050941/CJK-G2022.txt)

**Comment by asgsdbrseg** [comment]
显然不是pua，是cjk

**Comment by asgsdbrseg** [comment]
而且字符的属性不是词典软件需要关注的地方，只要返回输入值的查询结果即可。深蓝、无限、mdict都没有这种问题，我认为gd做了本分之外的事。

**Comment by asgsdbrseg** [comment]
抱歉，你复制出来的符号是「�」（U+FFFD），不是扩I的汉字。
「𮯰」（U+2EBF0），这里提供正确字符，供你测试。

**Comment by xiaoyifang** [comment]
I think this is the BMP bug reintroduced some long days ago.

```
// When convert non-BMP characters to wstring,the ending char maybe \0 .This method remove the tailing \0 from the wstring
// as \0 is sensitive in the index.  This method will be only used with index related operations like store/query.
```

character U+2EBF0 has an ending zero ,which will cause confusion to the index file.

The method `removeTrailingZero` has failed to remove the ending zero byte..  maybe return QByteArray ?

**Comment by asgsdbrseg** [comment]
排查出根源是件值得高兴的事，期待更新。

**Comment by asgsdbrseg** [comment]
可能不是\0的问题，不仅U+2EBF0，整个扩I，U+2EBF0——U+2EE5D都不能查询。

**Comment by xiaoyifang** [comment]
> U+2EBF0——U+2EE5D都不能查询。

能不能帮忙将这个范围的字做个词典，后续用于测试。

**Comment by xiaoyifang** [comment]
> 可能不是\0的问题，不仅U+2EBF0，整个扩I，U+2EBF0——U+2EE5D都不能查询。

有道理，后续继续排查下

**Comment by xiaoyifang** [comment]
test dictionary
[testdict.zip](https://github.com/user-attachments/files/18098925/testdict.zip)

**Comment by xiaoyifang** [comment]
用最新版试下，之前这本词典生成的索引，可以先清除下。

**Comment by asgsdbrseg** [comment]
新版重建索引后仍然查不到
![image](https://github.com/user-attachments/assets/7b097e28-ca7b-4121-a859-4c7debc8af7b)
![image](https://github.com/user-attachments/assets/0cdacb79-1a2c-41e8-a9e2-b57c6f41073d)

**Comment by xiaoyifang** [comment]
> 新版重建索引后仍然查不到

这步是如何操作的

**Comment by asgsdbrseg** [comment]
打开配置文件夹，退出gd，删除index文件夹，打开gd

**Comment by xiaoyifang** [comment]
> 打开配置文件夹，退出gd，删除index文件夹，打开gd

词典能私发给我，测试下吗，我用上面的 testdict.zip里面的词典，测试是正常的。
yifang.xiao@gmail.com

**Comment by asgsdbrseg** [comment]
毫无疑问，视频没有问题，但我测试你上传的文件，依然无法工作。
![image](https://github.com/user-attachments/assets/66978655-2ca1-435b-a464-28516754d6bc)
版本信息是
Goldendict-ng 24.11.0.853700a at 2024-12-04T05:47:02Z
Qt 6.7.2 MSVC 194234433 windows winnt 10.0.22631 x86_64-little_endian-llp64
Flags: MAKE_ZIM_SUPPORT EPWING_SUPPORT MAKE_CHINESE_CONVERSION_SUPPORT no_ffmpeg_player
这是我使用的词典 
[CJK-G2022一改单.zip](https://github.com/user-attachments/files/18121402/CJK-G2022.zip)

**Comment by xiaoyifang** [comment]
Goldendict-ng 24.11.0.853700a at 2024-12-04T05:47:02Z  版本不对。
用最新的版本。
