### ISSUE TITLE
Add “Import as List” on the Fav page

### ISSUE THREAD

**Issue by doubanb** [xiaoyifang/goldendict-ng#2015]
Currently,There only have the "Export to List“ on the Fav Page.
 
![Screenshot 2024-12-11 180121](https://github.com/user-attachments/assets/170f20ec-1cf7-495e-bb76-67c00460a563)

默认的"Import”是XML格式，虽然也能以TXT格式导入，但每次都要多点几下。
![image](https://github.com/user-attachments/assets/df139bb3-99b3-4579-a1d5-f8b820cccb83)

而且XML格式编辑起来比较麻烦
尽管它支持文件夹格式
![image](https://github.com/user-attachments/assets/fd801b0a-0c05-4470-b84c-d1b155f8dd31)

但有时候想导入Fav Page
不想导入History Page 

因为在History Page 导入新的内容会清空历史
但是想保留又暂时不想备份
权衡了一下
只能选择导入Fav Page

最近历史记录总莫名消失
但我觉得能随时保存到本地也不错
可以创建多个TXT文档
划为不同的分类
按需编辑与导入

**Comment by xiaoyifang** [comment]
没大明白你的诉求？
是要导入的时候默认文本格式的吗，

**Comment by doubanb** [comment]
> 没大明白你的诉求？ 是要导入的时候默认文本格式的吗，

是的

**Comment by xiaoyifang** [comment]
不知道，需要导入的时候默认xml格式的人有多少，需求有点特定。

**Comment by doubanb** [comment]
> 不知道，需要导入的时候默认xml格式的人有多少，需求有点特定。

emmm... 或者让导出的历史记录直接拖动进来？

https://github.com/user-attachments/assets/028ecd45-9d89-4a30-9793-f1fdba2c50c3


感觉这样更通用一些。
