### ISSUE TITLE
Spanish dict "es-en" bookname detected as Icelandic

### ISSUE THREAD

**Issue by ilius** [xiaoyifang/goldendict-ng#2019]
**描述 bug**

Bookname "A Spanish-English Dictionary (Granada University, Spain), 14.4 (es-en)" is detected as Icelanding-English.

"es" is code for Spanish. I looked it up in source code:
```
src/langcoder.cc:  { "es", { "es", "spa", 0, "Spanish" } },
src/language.cc:  addEntry( "es", "Spanish", QCoreApplication::translate( "Language", "Spanish" ) );
```

![Screenshot from 2024-12-13 06-30-55](https://github.com/user-attachments/assets/6180c4b9-07c5-46c5-a0fc-fb0eb58c51e4)

- OS: Ubuntu 24.04.1
- Version: a5337770da7573e4f1c2549dda10b0bdcaebbcbb built from source

**Comment by ilius** [comment]
I pulled, removed build dir and built and ran again.
But still shows Icelandic.

**Comment by shenlebantongying** [comment]
The language info is written to the index file, so you have to delete the previous index files of that dictionary.

**Comment by ilius** [comment]
Ah OK.
It's fixed.
