### ISSUE TITLE
[TODO] Scanpopup on macOS bugs

### ISSUE THREAD

**Issue by shenlebantongying** [xiaoyifang/goldendict-ng#219]
1.

On macOS, qt won't know the clipboard changed without an active window, thus scan popup doesn't track clipboard changes (unless set the popup to be always shown).

2. 

Mouse hover actually works on mac. It is almost like Linux' selection.

https://user-images.githubusercontent.com/20123683/203171016-b4205c52-fd2e-4396-aab2-e03bf46a72ae.mov

But newer mac needs explicitly grant the permission

Also we never call this method, lol

https://github.com/xiaoyifang/goldendict/blob/4a129005df5eafc8de4dc9c09e30b6faf6017000/macmouseover.hh#L25

**Comment by xiaoyifang** [comment]
> On macOS, qt won't know the clipboard changed without an active window, thus scan popup doesn't track clipboard changes.

or this function can be enabled only when popup in pinned  on top

**Comment by shenlebantongying** [comment]
That means there is some way to keep a floating window open in a corner and obtain changes

**Comment by xiaoyifang** [comment]
is this issue related to https://github.com/goldendict/goldendict/issues/1333

**Comment by shenlebantongying** [comment]
`⌘+C+C` is implemented using Carbon API which was introduced much earlier than the "Accessibility" setting window.

In official apple documents, there seems to have absolutely no mention of the relationship between them.

However, in macOS 13.0.1, the "Accessibility" isn't needed to use `⌘+C+C`. I have no idea why they need to do that.

**Comment by shenlebantongying** [comment]
Actually I was wrong. I grant my IDE with everything and goldendict started via IDE seems to inherit every permission, thus I got no problems.

On newest macOS, `⌘+C+C` will trigger this. Yes, this permission must be granted to use `⌘+C+C`.

<img width="466" alt="Screenshot 2022-12-09 at 9 28 16 AM" src="https://user-images.githubusercontent.com/20123683/206724281-464a37fb-f660-46fb-9020-de3698afe34c.png">

**Comment by shenlebantongying** [comment]
Also, this one is related: https://github.com/xiaoyifang/goldendict/issues/124

Without this permission, GD seems to trap ⌘+C and blocks the normal copy.

**Comment by shenlebantongying** [comment]
The proper solution should be detecting this permission and don't register global hotkeys if the permission isn't granted.

like this:
https://stackoverflow.com/a/53617674/12494649

**Comment by shenlebantongying** [comment]
1. is fixed.

Let's track 2. at https://github.com/xiaoyifang/goldendict-ng/issues/219
