### ISSUE TITLE
源文件更新请求 以及 QT 界面字体渲染改善

### ISSUE THREAD

**Issue by ryanlo713** [xiaoyifang/goldendict-ng#315]
之前在官方库请求过支持XDXF最新标准（[详细点我](https://github.com/goldendict/goldendict/issues/1600)），并得到跟进。

-----

我使用的版本是`GoldenDict-QT6-Windows.22.12.24-alpha.230113.e184162d`

由于所用的屏幕分辨率还是相当高的，这些奇怪的毛刺很难让人不在意；这里给出对比图：

![image](https://user-images.githubusercontent.com/12672523/213498185-cb954a91-bf9e-48bd-9cba-83ed627e4bc2.png)

与官方 QT 5 比较：

![image](https://user-images.githubusercontent.com/12672523/213498645-52a24088-cf8e-413e-80f6-87e271da4da3.png)

辞典正文渲染还是正常的（毕竟是Chrome内核），但主界面基本上都是这画风

![image](https://user-images.githubusercontent.com/12672523/213498068-f13fe047-c55d-48fd-b226-bc0bf942cacb.png)

**Comment by xiaoyifang** [comment]
> 之前在官方库请求过支持XDXF最新标准（[详细点我](https://github.com/goldendict/goldendict/issues/1600)），并得到跟进

https://github.com/xiaoyifang/goldendict/pull/322


界面渲染问题，估计是windows本身的问题。

**Comment by xiaoyifang** [comment]
https://blog.csdn.net/ayang1986/article/details/96484482

**Comment by xiaoyifang** [comment]
https://stackoverflow.com/questions/6746276/how-to-enable-anti-aliasing-on-qlabel#:~:text=You%20can%20set%20the%20Antialisasing%20attribute%20in%20the,QFont%20f%20%28%22Times%22%2C%2050%29%3B%20f.setStyleStrategy%20%28QFont%3A%3APreferAntialias%29%3B%20ui-%3Elabel-%3EsetFont%20%28f%29%3B
