### ISSUE TITLE
Goldendict Qt 6 related bug

### ISSUE THREAD

**Issue by xiaoyifang** [xiaoyifang/goldendict-ng#342]
| Qt Version  | Bug |note
| ------------- | ------------- |---------
|6.2.3|critical bug,https://bugreports.qt.io/browse/QTBUG-101724|
| 6.3.1  | [http bug](https://bugreports.qt.io/browse/QTBUG-106573)  |
| 6.4.0 | the qmutlimedia is not copied to target by windeployqt https://bugreports.qt.io/browse/QTBUG-105984 |
| 6.4.1  | font size is unnormally larger,  ffmpeg bug https://bugreports.qt.io/browse/QTBUG-108383 |
| 6.4.2  | ffmpeg bug https://bugreports.qt.io/browse/QTBUG-108383 ,this bug extended two release versions|
|6.5.0|https://bugreports.qt.io/browse/QTBUG-112889    devtool|
|6.5.1|https://github.com/xiaoyifang/goldendict-ng/issues/854| this bug only occured in qt6.5.1 on macos, A deeper reason may be caused by qt and goldendict together.
|6.6.0-beta1,6.6.0-beta2| crash mysteriously,the webengine can not render properly on Windows,https://bugreports.qt.io/browse/QTBUG-115369?filter=-2|suppose to be fixed in 6.6.0 RC|
|6.4+|https://bugreports.qt.io/browse/QTBUG-115074  https://github.com/xiaoyifang/goldendict-ng/issues/1016  ||
|6.7.0|https://bugreports.qt.io/browse/QTBUG-120191 https://github.com/xiaoyifang/goldendict-ng/issues/1372||

**Comment by shenlebantongying** [comment]
6.5 is planned to be released at 2023-03-30

If those problems got solved, I think we can shake off Qt5 (and possibly fully migrate to CMake?).

https://wiki.qt.io/Qt_6.5_Release

**Comment by xiaoyifang** [comment]
if qt6.5 has proved its value,this can be considered.

**Comment by shawkynasr** [comment]
6.5.1 will release 23-05, I hope it will be stable version of QT.

**Comment by shenlebantongying** [comment]
I think we have to keep qmake/qt5 support until the release of KDE 6.

Not having the KDE's theme is too shocking for Linux users, especially the "stable distro" users.

(However, this is considered as progression by rolling distros fans like arch/gentoo :sweat_smile:)
