### ISSUE TITLE
深色模式下查词时，闪现白色背景色 (White flash in dark reader mode)

### ISSUE THREAD

**Issue by opiater** [xiaoyifang/goldendict-ng#357]
版本信息：
Goldendict 23.02.07-alpha.230225.da004ee9
macos darwin 19.6.0 Qt 6.4.2 x86_64-little_endian-lp64
Clang 13.0.0 (clang-1300.0.29.30)
Flags: MAKE_ZIM_SUPPORT MAKE_CHINESE_CONVERSION_SUPPORT

也就是说，未完全加载完前，会显示软件界面更下层的白色底色。
新增加的内置深色模式总体效果很好，不过这个闪现白底色的问题比较影响观感。

**Comment by xiaoyifang** [comment]
@shenlebantongying can you check on this?
Is this related with the following code
https://github.com/xiaoyifang/goldendict/blob/eb1206945bab3b91fe8cf811a5c42fe82383ab63/article_maker.cc#L164-L166

**Comment by opiater** [comment]
闪现白色背景的问题在更新版本中依然存在。

Goldendict 23.02.07-alpha.230309.37e3df05
macos darwin 19.6.0 Qt 6.4.2 x86_64-little_endian-lp64
Clang 13.0.0 (clang-1300.0.29.30)
Flags: MAKE_ZIM_SUPPORT MAKE_CHINESE_CONVERSION_SUPPORT

**Comment by xiaoyifang** [comment]
会不会是词典本身里面设置了白色背景

**Comment by opiater** [comment]
> 会不会是词典本身里面设置了白色背景

没有，也检查了配置文件夹里的qt-style.css和所用“附加样式”的article-style.css，没有或删除背景设置后，依然闪现白色背景。
你和其他用户没有这个问题吗？

**Comment by shenlebantongying** [comment]
It looks like we should also set background via https://doc.qt.io/qt-6/qwebenginepage.html#backgroundColor-prop

**Comment by xiaoyifang** [comment]
seems the cause of this issue.

**Comment by xiaoyifang** [comment]
I began to suspect that the white background flash is not caused by `dark reader mode`.
This issue is only more significant in `dark reader mode`

**Comment by xiaoyifang** [comment]
https://github.com/qutebrowser/qutebrowser/issues/2912
https://stackoverflow.com/questions/43150506/opacity-not-working-with-qwebengineview-and-translucent-background

**Comment by shenlebantongying** [comment]
I think the changes in the PR above is unrelated. Articleview.cc is a `QFrame` while the doc that I linked is a `QWebEnginePage`. This is yet another confusing "same method name but used for different class". 

The setBackground should be used with`ArticleWebPage`.

Sadly, I tried and it does not work. Only the initial background is changed, and the white flash still exist.

**Comment by shenlebantongying** [comment]
I think I figured out the actual problem, but I don't have a fix.

It is unrelated to Qt.

The white flash comes from Chromium when opening a new page. You can open chrome then find a slow website, then click the refresh, you will get similar white flash (but most websites are white, so it is not obvious).

When a search is initiated by a user, the code will end up at `ArticleView::showDefinition`

https://github.com/xiaoyifang/goldendict/blob/fa06c85d6d617e07e7e7a40d529db2392f5c0bd5/articleview.cc#L405-L406

This req's url will be `gdloCokup://something` and will be loaded later like open a new webpage in chrome.

Here the "white flash" happens! It is the embedded chromium that shows white when open a new page.

Googling those things will show related solutions:
* dark website refresh white flash
* black website white flash`
* chromium white flash open new page
* chromium white flash black website

Also see https://github.com/darkreader/darkreader/issues/3811

(A "fix" if we cannot figure out something else: hide the ArticleView before loading a new page and show it up after the page is loaded.)

**Comment by xiaoyifang** [comment]
![image](https://user-images.githubusercontent.com/105986/225564110-128a0420-e1c1-40f2-8871-ca2bfdef9cd0.png)

this extension can be installed in the chrome to enable the dark reader mode

**Comment by xiaoyifang** [comment]
> I think the changes in the PR above is unrelated. Articleview.cc is a `QFrame`

I think you have pointed the right place . I will try again to set this QFrame translucent.

**Comment by shenlebantongying** [comment]
Chrome with the Dark Reader extension doesn't solve the "white flash". Using a light theme, chrome will have the same kind of white flash. So there is no solution within chromium.

The QWebEnginePage.setBackground() only changes the initial background, and it does not affect the Chromium's background when loading a page.

So, I think hide when the article view when the page loading is the best fix.

Another potential fix is to change `gdlookup://url` to `gdlookup://a_fixed_domain.org/word` to trick the chromium to think we are still on the same domain.

**Comment by xiaoyifang** [comment]
https://bugreports.qt.io/browse/QTBUG-67434

**Comment by xiaoyifang** [comment]
#957

**Comment by Canvis-Me** [comment]
这个和深色模式没关系，只要背景不是白的就会闪一下白色，比如`文章显示风格`换为`经典`也是会闪白色。

**Comment by seth-js** [comment]
Any update to this? Having the same issue as #957.

**Comment by xiaoyifang** [comment]
use the latest pre-release version .  the possibility of white-flash has been reduced.

**Comment by seth-js** [comment]
That fixed the issue for me. Thank you.
