### ISSUE TITLE
feature request:add parameter control to dark reader

### ISSUE THREAD

**Issue by xiaoyifang** [xiaoyifang/goldendict-ng#388]
>希望可以在 Interface → Dark Reader Mode 打钩下面添加上具体参数的调整，
brightness: [100] 鼠标悬浮时显示 tip: 0-100. Default: 100
contrast: [90] 0-100. Default: 90
grayscale: [30] 0-100. Default: 30
sepia: [10] 0-100. Default: 10

**Comment by shenlebantongying** [comment]
Check out related code at `MainWindow::editPreferences`

It updates multiple components' states in multiple styles.

We should refactor this part by defining an interface with a single method `reconfigure(Config::Preferences *p)`, then move state updating code into corresponding components.

Then we can implement this feature without bloating the `mainwindow.cc` and the code will be very clean.

Sample state updating code that should be moved to their class' `reconfigure()`:

https://github.com/xiaoyifang/goldendict/blob/4008e47625f08fefef40d011d2c297fad06d85cf/mainwindow.cc#L2236-L2240
https://github.com/xiaoyifang/goldendict/blob/4008e47625f08fefef40d011d2c297fad06d85cf/mainwindow.cc#L2243-L2249
https://github.com/xiaoyifang/goldendict/blob/4008e47625f08fefef40d011d2c297fad06d85cf/mainwindow.cc#L2269-L2278

**Comment by xiaoyifang** [comment]
https://xiaoyifang.github.io/goldendict-ng/topic_userstyle/
