### ISSUE TITLE
Take up a lot of memory

### ISSUE THREAD

**Issue by actforjason** [xiaoyifang/goldendict-ng#430]
四部词典查询一个词，内存有400MB左右
![image](https://user-images.githubusercontent.com/57058325/228255712-5938c618-ff49-407d-92f1-0df02ae99ffe.png)

版本：6.4.3-GoldenDict-v23.02.07-alpha-Installer.exe

**Comment by xiaoyifang** [comment]
有没有对比  比如其他同类词典占用多少  400M在心理预期内  内置的相当于Chrome浏览器  本身占内存比较多

**Comment by actforjason** [comment]
原版的以及欧路词典大概在100mb左右

**Comment by xiaoyifang** [comment]
如果内存不是持续增加 且不释放。这个内存应该是正常的

**Comment by xiaoyifang** [comment]
如果后续有问题可以再打开
