### ISSUE TITLE
Scrolling issue in latest relesae

### ISSUE THREAD

**Issue by BEST8OY** [xiaoyifang/goldendict-ng#447]
**Describe the bug**
![GoldenDict_8p86toZ9Ht](https://user-images.githubusercontent.com/70865987/229529125-7a4c6c3c-4e66-4e9f-bf60-0a3adba77672.gif)

**To Reproduce**
Try scrolling with scrollbar with fast speed.

**Expected behavior**
I don't know what to expect but it should not be like this!

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Edge
 - Version: 111

**Comment by xiaoyifang** [comment]
https://github.com/xiaoyifang/goldendict/issues/420

**Comment by xiaoyifang** [comment]
I can be sure that it is a side effect of contain-intrinsic-size

**Comment by xiaoyifang** [comment]
change the contain-intrinsic-size to height and add `auto `
This should reduce some inconvenience . After the page scrolled into view ,the height should be remembered.
