### ISSUE TITLE
0410latest version

### ISSUE THREAD

**Issue by catsalt** [xiaoyifang/goldendict-ng#464]
1, 在历史面板里面,不能使用键盘上下键;

2, 反应慢; 不知道啥原因, 372的版本很轻快;

**Comment by xiaoyifang** [comment]
> 1, 在历史面板里面,不能使用键盘上下键;

是个问题，后续调查下。

> 反应慢; 不知道啥原因, 372的版本很轻快;

具体一下，什么操作，另外版本用的哪个，当前操作系统，词典数量等信息。

**Comment by xiaoyifang** [comment]
> 1, 在历史面板里面,不能使用键盘上下键;

处理了

**Comment by catsalt** [comment]
这个版本, 能用上下键; 同时也比较快了; 上个版本肯定哪里问题

**Comment by catsalt** [comment]
大佬，现在goldenDic 有没有可能集成 自然语言，（win11已经可以提供多种自然人声）。
如果可以的话，是否例句也可以点击发音？
我在freeMdict 论坛发现不少词典的例句都可以使用微软提供的在线语言进行人声发音。
例如牛津高阶，韦氏高阶，剑桥高阶 之完美版。
但是如果词典软件本身就可以的话，那么就方便多了。

盼复。
祝你一切顺利！

________________________________
发件人: xiaoyifang ***@***.***>
发送时间: 2023年5月3日 0:10
收件人: xiaoyifang/goldendict-ng ***@***.***>
抄送: Qin ***@***.***>; Author ***@***.***>
主题: Re: [xiaoyifang/goldendict-ng] 0410latest version (Issue #464)


Closed #464<https://github.com/xiaoyifang/goldendict-ng/issues/464> as completed.

―

**Comment by xiaoyifang** [comment]
单词发音，参考如下
![Image](https://github.com/user-attachments/assets/1880d560-efb2-42c1-81f5-afb1ba8bf245)

至于例句，没法区分哪些是例句。暂时实现不了

**Comment by catsalt** [comment]
按照图片方式设置了，但是没有声音，为啥呢。版本25.04 qt6.7.2



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2025年04月16日 10:08 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [xiaoyifang/goldendict-ng] 0410latest version (Issue #464) |

单词发音，参考如下
image.png (view on web)

至于例句，没法区分哪些是例句。暂时实现不了

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***>

xiaoyifang left a comment (xiaoyifang/goldendict-ng#464)

单词发音，参考如下
image.png (view on web)

至于例句，没法区分哪些是例句。暂时实现不了

**Comment by xiaoyifang** [comment]
https://github.com/rany2/edge-tts

安装了吗

**Comment by catsalt** [comment]
已经解决。请忽略上一个问题~无法停止的问题。



---- Replied Message ----
| From | ***@***.***> |
| Date | 04/16/2025 13:31 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [xiaoyifang/goldendict-ng] 0410latest version (Issue #464) |

Bot detected the issue body's language is not English, translate it automatically.

It's done. But there is a problem. Sometimes I copy a large paragraph and start reading it directly, not knowing how to stop.

--- The original email of the reply ---
| Sender | @.> |
| Date | April 16, 2025 10:52 |
| Recipient | @.> |
| Cc to | @.>@.> |
| Topic | Re: [xiaoyifang/goldendict-ng] 0410latest version (Issue #464) |

https://github.com/rany2/edge-tts

Is it installed

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: @.***>

xiaoyifang left a comment (#464)

https://github.com/rany2/edge-tts

Is it installed

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: @.***>

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***>

github-actions[bot] left a comment (xiaoyifang/goldendict-ng#464)

Bot detected the issue body's language is not English, translate it automatically.

It's done. But there is a problem. Sometimes I copy a large paragraph and start reading it directly, not knowing how to stop.

--- The original email of the reply ---
| Sender | @.> |
| Date | April 16, 2025 10:52 |
| Recipient | @.> |
| Cc to | @.>@.> |
| Topic | Re: [xiaoyifang/goldendict-ng] 0410latest version (Issue #464) |

https://github.com/rany2/edge-tts

Is it installed

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: @.***>

xiaoyifang left a comment (#464)

https://github.com/rany2/edge-tts

Is it installed

**Comment by xiaoyifang** [comment]
https://xiaoyifang.github.io/goldendict-ng/ui_shortcuts/#:~:text=Ctrl%2BShift%2BS,current%20playing%20sound

**Comment by catsalt** [comment]
你好, 一个新的问题, 插上耳机,仍然从扬声器输出;


版本 Windows 11 家庭中文版
版本号 24H2
安装日期 ‎2025/‎4/‎26
操作系统版本 26100.3775
体验 Windows 功能体验包 1000.26100.66.0


Version: 25.05.0.2a2b0e1 at 2025-04-04T02:59:24Z
Qt 6.7.2 MSVC 194334808
windows winnt 10.0.26100 x86_64-little_endian-llp64
Flags: ZIM EPWING OPENCC 


ADOBE au 开始也一样, 但是 它有个选项, 始终选择系统默认输入,输出; 就ok啦.
这版的字典, 必须手动禁用扬声器才可以!


谢谢!


---- Replied Message ----
| From | ***@***.***> |
| Date | 4/16/2025 15:51 |
| To | ***@***.***> |
| Cc | ***@***.***>,
***@***.***> |
| Subject | Re: [xiaoyifang/goldendict-ng] 0410latest version (Issue #464) |

https://xiaoyifang.github.io/goldendict-ng/ui_shortcuts/#:~:text=Ctrl%2BShift%2BS,current%20playing%20sound

Ctrl+Shift+S

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***>

xiaoyifang left a comment (xiaoyifang/goldendict-ng#464)

https://xiaoyifang.github.io/goldendict-ng/ui_shortcuts/#:~:text=Ctrl%2BShift%2BS,current%20playing%20sound

Ctrl+Shift+S

**Comment by catsalt** [comment]
已经找到原因了。



---- Replied Message ----
| From | ***@***.***> |
| Date | 05/10/2025 11:36 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [xiaoyifang/goldendict-ng] 0410latest version (Issue #464) |
github-actions[bot] left a comment (xiaoyifang/goldendict-ng#464)

Bot detected the issue body's language is not English, translate it automatically.

Hello, a new question, plug in the headphones and still output from the speaker;

Version Windows 11 Home Chinese Version
Version number 24H2
Installation date ‎2025/4/‎26
Operating system version 26100.3775
Experience Windows Feature Experience Pack 1000.26100.66.0

Version: 25.05.0.2a2b0e1 at 2025-04-04T02:59:24Z
Qt 6.7.2 MSVC 194334808
windows winnt 10.0.26100 x86_64-little_endian-llp64
Flags: ZIM EPWING OPENCC

The same is true at the beginning of ADOBE au, but it has an option, always select the system default input and output; it's OK.
This version of the dictionary must be disabled manually!

Thanks!

--- Replied Message ---
| From | @.> |
| Date | 4/16/2025 15:51 |
| To | @.> |
| Cc | @.>,
@.> |
| Subject | Re: [xiaoyifang/goldendict-ng] 0410latest version (Issue #464) |

https://xiaoyifang.github.io/goldendict-ng/ui_shortcuts/#:~:text=Ctrl%2BShift%2BS, current%20playing%20sound

Ctrl+Shift+S

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: @.***>

xiaoyifang left a comment (#464)

https://xiaoyifang.github.io/goldendict-ng/ui_shortcuts/#:~:text=Ctrl%2BShift%2BS, current%20playing%20sound

Ctrl+Shift+S

**Comment by catsalt** [comment]
大佬，请问你的微信或者QQ，多少啊。



---- Replied Message ----
| From | ***@***.***> |
| Date | 04/16/2025 15:51 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [xiaoyifang/goldendict-ng] 0410latest version (Issue #464) |

https://xiaoyifang.github.io/goldendict-ng/ui_shortcuts/#:~:text=Ctrl%2BShift%2BS,current%20playing%20sound

Ctrl+Shift+S

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***>

xiaoyifang left a comment (xiaoyifang/goldendict-ng#464)

https://xiaoyifang.github.io/goldendict-ng/ui_shortcuts/#:~:text=Ctrl%2BShift%2BS,current%20playing%20sound

Ctrl+Shift+S

**Comment by monowovo** [comment]
有一种方案，鼠标位置，(快捷键)开始朗读，然后到句号暂停。(快捷键)继续。



> 单词发音，参考如下
> ![Image](https://github.com/user-attachments/assets/1880d560-efb2-42c1-81f5-afb1ba8bf245)
> 
> 至于例句，没法区分哪些是例句。暂时实现不了
