### ISSUE TITLE
Maç Silicon support natively

### ISSUE THREAD

**Issue by sonerfromnurland** [xiaoyifang/goldendict-ng#467]
I sold my MacBook and bought a windows pc for the sake of use this dictionary app. You have developed it well. However, I wonder whether it works natively in Silicon macs? Or using rosalin? If not, do you have any plan (when) to release it with native Silicon support? If there is no plan, I will go on postponing plans to buy a new Mac.

**Comment by xiaoyifang** [comment]
> I sold my MacBook and bought a windows pc for the sake of use this dictionary app.

You donot have to sold your macbook.

in the release page,  there are builds for macos. try some of the them.

As for the native builds for Silicon support .  You can use the code to build on your computer by yourself. the build instruction is easy to follow.   

Or wait until Septeber when GitHUB release a new host runner for M1

**Comment by xiaoyifang** [comment]
Is the universal package of goldendict can work natively on you M1?
