### ISSUE TITLE
The possiblity to remove/change FsEncoding class's encode/decode methods

### ISSUE THREAD

**Issue by xiaoyifang** [xiaoyifang/goldendict-ng#468]
this class file is used to convert string from/to localBit8()  and string/QString/wstring.
I think use a consistent string form such as QString or std;;string should be enough.

> [QByteArray](https://doc.qt.io/qt-6.2/qbytearray.html) QString::toLocal8Bit() const
> Returns the local 8-bit representation of the string as a [QByteArray](https://doc.qt.io/qt-6.2/qbytearray.html). The returned byte array is undefined if the string contains characters not supported by the local 8-bit encoding.
> 
> On Unix systems this is equivalen to [toUtf8](https://doc.qt.io/qt-6.2/qstring.html#toUtf8)(), on Windows the systems current code page is being used.
> 
> If this string contains any characters that cannot be encoded in the locale, the returned byte array is undefined. Those characters may be suppressed or replaced by another.

**Comment by shenlebantongying** [comment]
The existence of `FsEncoding` come from the unwillingness of using `QFile/QDir`.

If we just use `QFile/QDir` everywhere, then we can probably just delete `FsEncoding`?

https://github.com/goldendict/goldendict/issues/30

We are passing paths via string
https://github.com/xiaoyifang/goldendict/blob/54a4a052a5a09dbb6994b4eb58ef2196545be450/mdx.hh#L15-L17

and we are using QFile anyway
https://github.com/xiaoyifang/goldendict/blob/54a4a052a5a09dbb6994b4eb58ef2196545be450/mdx.cc#L502

or we can use c++17's `<filesystem>`?

**Comment by shenlebantongying** [comment]
In fact, we can also delete `ufile.cc`. I see no reason to maintain some file opening utilities. Just reuse Qt's code.

https://github.com/xiaoyifang/goldendict/blob/54a4a052a5a09dbb6994b4eb58ef2196545be450/ufile.cc

We should redo this PR, and replace file handling with QFile/QDir instead of reinventing wheels.

https://github.com/goldendict/goldendict/pull/48/files

**Comment by xiaoyifang** [comment]
agreed

**Comment by shenlebantongying** [comment]
There are static `QFile::encodeName` `QFile::decodeName`. Maybe we can alias FsEncoding to them for now?

**Comment by xiaoyifang** [comment]
When you use QFile, QFileInfo, and QDir to access the file system
191 <https://codebrowser.dev/qt5/qtbase/src/corelib/io/qfile.cpp.html#191> with
Qt, you can use Unicode file names. On Unix, these file
192 <https://codebrowser.dev/qt5/qtbase/src/corelib/io/qfile.cpp.html#192>
names
are converted to an 8-bit encoding. If you want to use
193 standard C++ APIs (\c <cstdio> or \c <iostream>) or
194 platform-specific APIs to access files instead of QFile, you can
195 use the encodeName() and decodeName() functions to convert
196 between Unicode file names and 8-bit file names.

shenleban tongying ***@***.***> 于2023年4月13日周四 11:10写道：

**Comment by shenlebantongying** [comment]
I think a workable path starts from here:

https://github.com/xiaoyifang/goldendict/blob/84151878f6d6c0d86bc35b6c3f4e964310a1e0cd/dictionary.hh#L267

* First convert this std::string to QString
* When we further refactor the code by opening files via QFile, there will be no neeed to converting between std::string & QString.
* Remove more code :)

**Comment by xiaoyifang** [comment]
the aim is to avoid too much non-neccessary converting and limit the changed code lines.

**Comment by shenlebantongying** [comment]
On windows

Add `qDebug()<< str <<  str.toUtf8().data() << str.toLocal8Bit().data();` to

https://github.com/xiaoyifang/goldendict/blob/034c878e91f341da1f800ab4d5dddfebefa5054b/fsencoding.cc#L30-L37

will yield:

1. `F:\\desktop\\😎whaرحبًا你好\\Oxford Advanced Learner's Dictionary, 9th Ed\\Oxford Advanced Learner's Dictionary, 9th Ed.mdx`
2. `F:\desktop\😎whaرحبًا你好\Oxford Advanced Learner's Dictionary, 9th Ed\Oxford Advanced Learner's Dictionary, 9th Ed.mdx`
3. `F:\desktop\??wha???????\Oxford Advanced Learner's Dictionary, 9th Ed\Oxford Advanced Learner's Dictionary, 9th Ed.mdx`

This `encode` on windows will in fact keep the code untouched (1->2)😅

The `QFile::encode` will actually encode the string to ASCII (1->3), thus QFile is not a direct mapping.

Does `toLocal8Bit()` on Unix make any sence?

**Comment by shenlebantongying** [comment]
https://doc.qt.io/qt-6/qstring.html#toLocal8Bit

> On Unix systems this is equivalent to [toUtf8](https://doc.qt.io/qt-6/qstring.html#toUtf8)(), on Windows the systems current code page is being used.

https://github.com/xiaoyifang/goldendict/blob/034c878e91f341da1f800ab4d5dddfebefa5054b/fsencoding.cc#L30-L37

This piece of code prevent the `on Windows the systems current code page is being used` from happening, and on Unix, the code is just `toUtf8()`. The `data()` return `char*` so here is also a implicit conversion `char* -> string`

So this piece of code is equal to

```
string encode( QString const & str ) { return str.toStdString(); }
```
💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩

**Comment by shenlebantongying** [comment]
The decode is the same story:

https://github.com/xiaoyifang/goldendict/blob/034c878e91f341da1f800ab4d5dddfebefa5054b/fsencoding.cc#L48-L55

https://doc.qt.io/qt-6/qstring.html#fromLocal8Bit

> On Unix systems this is equivalent to [fromUtf8](https://doc.qt.io/qt-6/qstring.html#fromUtf8)(), on Windows the systems current code page is being used.

This code should be equal to 

```
QString decode( const char * str ) {
    return QString::fromUtf8( str );
};
```
💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩

**Comment by xiaoyifang** [comment]
many laughs.



> * `F:\\desktop\\😎whaرحبًا你好\\Oxford Advanced Learner's Dictionary, 9th Ed\\Oxford Advanced Learner's Dictionary, 9th Ed.mdx`
> * `F:\desktop\😎whaرحبًا你好\Oxford Advanced Learner's Dictionary, 9th Ed\Oxford Advanced Learner's Dictionary, 9th Ed.mdx`
> * `F:\desktop\??wha???????\Oxford Advanced Learner's Dictionary, 9th Ed\Oxford Advanced Learner's Dictionary, 9th Ed.mdx`

Now ,I'm a bit curious whether file can open the the 3 form(fopen ) in the above as it acclaimed

**Comment by xiaoyifang** [comment]
or we just replace them all with QString /QFile ,to eliminate all these problems.

**Comment by xiaoyifang** [comment]
> > fopen can open the the 3rd form in the above as it claimed in QFile::encode's method
> 
> I don't think so.

gd internal does not use `FILE` much ,only two places use FILE class.  
I think QFile::encode should be used together with FILE,without using FILE ,there is no need to use QFile::encode/decode.

**Comment by shenlebantongying** [comment]
It looks like in the past, they did migrate from `FILE` to `QFile`.

https://github.com/xiaoyifang/goldendict/commit/becc74c730d350e06cc58cea3396a4e4ce82c3bf

The `file.cc` is just a wrapper over `QFile` but with `std::string` as paramater.

The ancient code (before 1st commit) contains a hack that use a buffer to write large chunk of data at once.

Questions:

1.) Is this hack still relevant to today’s computer?
2.) Is it still relevant after switching from `FILE` to `QFile`? 
3.) (Will it slow down IO due to 1 & 2?)

**Comment by xiaoyifang** [comment]
> contains a hack that use a buffer to write large chunk of data at once.

where is this hack?

**Comment by xiaoyifang** [comment]
https://github.com/qt/qtbase/blob/9618427ee5a42e1d120fa475aa6e2408a738915a/src/corelib/io/qfiledevice.cpp#L15-L24

set this MACRO should be enough ,the default buffersize is 16384

**Comment by shenlebantongying** [comment]
`QFile` has a similar 16 KiB buffer:

https://github.com/qt/qtbase/blob/aea92807be2567c4212b96ae67de7137075ba4ee/src/corelib/io/qfiledevice.cpp#L16

https://github.com/qt/qtbase/blob/aea92807be2567c4212b96ae67de7137075ba4ee/src/corelib/io/qfiledevice.cpp#L503-L532

The comment line from GD's original author and `QFile` read like the same. So they know exactly the same and proceed to implement the same thing.

See those two comment  :sweat_smile: :sweat_smile: :sweat_smile:

![image](https://user-images.githubusercontent.com/20123683/231973669-da342310-3817-42c1-9946-fc0bfc8a1e86.png)

**Comment by xiaoyifang** [comment]
> So, we remove this hack. It should be irreverent when GD did the `FILE` ⇾ `QFile` migration. What do u think?

I agree  with this.  the default buffersize should be ok.

**Comment by xiaoyifang** [comment]
rename the template method?
