### ISSUE TITLE
Should this repository has a new name?

### ISSUE THREAD

**Issue by xiaoyifang** [xiaoyifang/goldendict-ng#489]
some users have pointed out the confusions they encountered.Should this repo has a different name?
If it is neccessary ,plz provide a name for choosing.

**Comment by shenlebantongying** [comment]
Yes, like

* [paperless](https://github.com/the-paperless-project/paperless#important-news-about-the-future-of-this-project) -> [paperless-ng](https://github.com/jonaswinkler/paperless-ng#archive-notice) -> [paperless-ngx](https://github.com/paperless-ngx/paperless-ngx)
* Shadowsocks -> ShadowssocksX -> ???? -> ShadowsocksX-NG https://github.com/shadowsocks
* Gosling Emacs -> GNU Emacs -> Lucid Emacs -> XEmacs
* GCC -> EGCS (Enhanced GNU Compiler System) (today's GCC was developed by EGCS people)

Forks replacing the original project happens all the time.

Time to go `goldendict-ng` and rewrite the slogan to `Next generation goldendict` :flags: :hot_face: 



https://github.com/search?q=next+generation+NG&type=repositories 

GitHub do have name redirects, but there are other consequences.

https://docs.github.com/en/repositories/creating-and-managing-repositories/renaming-a-repository
> In addition to redirecting web traffic, all git clone, git fetch, or git push operations targeting the previous location will continue to function as if made on the new location.

**Comment by xiaoyifang** [comment]
GoldendictX
XGoldenDict
GoldenDict-ng

sound all ok.

**Comment by xiaoyifang** [comment]
which one is your favorite name @shenlebantongying ?
We can decide by ourselve.

**Comment by xiaoyifang** [comment]
XGoldenDict    neXt generation GoldenDict?

**Comment by xiaoyifang** [comment]
how to disconnect with the official repo and keep all the commit history and change a repo name at the same time.
![image](https://user-images.githubusercontent.com/105986/232264073-a150dcb1-62b8-459c-aee3-8e10d65914df.png)

**Comment by data-man** [comment]
After so many excellent changes, only PlatinumDict is the best name.

**Comment by xiaoyifang** [comment]
I'm afraid not too non-english native person can write the `Platinum` word correctly in the first place

**Comment by shenlebantongying** [comment]
I think `goldendict-ng` is the better. We should keep the `goldendict` part and clarify the situation -> next generation :)

> how to disconnect with the official repo and keep all the commit history and change a repo name

You can file a github ticket / ask github support. Usually within a few weeks the fork relationship will be detached.

**Comment by data-man** [comment]
https://stackoverflow.com/questions/29326767/unfork-a-github-fork-without-deleting/41486339#41486339

**Comment by shenlebantongying** [comment]
> https://stackoverflow.com/questions/29326767/unfork-a-github-fork-without-deleting/41486339#41486339

That method will lose all stars :sweat_smile: File a github ticket is slower but safe.

**Comment by xiaoyifang** [comment]
![image](https://user-images.githubusercontent.com/105986/232264764-b431baed-7a64-4f64-bc9d-43b98dc92a0e.png)

done .

**Comment by data-man** [comment]
> will lose all stars

Losing 510 stars isn't the biggest problem. :)

**Comment by xiaoyifang** [comment]
After the rename ,I think we really can do some extravagant actions now.

**Comment by data-man** [comment]
> github do not have tool to start a poll

You can create a poll in Discussions.

**Comment by xiaoyifang** [comment]
goldendict-ng sounds ok. before a better name came . this should be the choosen one.

---

**Comment by Memory383** [comment]
**Name suggestions:**  
- GoldenDict Silver
- GoldenDict NextGen
- GoldenDict Zenit
