### ISSUE TITLE
Dark theme

### ISSUE THREAD

**Issue by catsalt** [xiaoyifang/goldendict-ng#493]
黑暗模式下,  
词典选取之后的 标记框建议加亮色, 否则不容易看出来;
词义解释的这个框当中, 每部词典的分界色, 也建议增亮;
  .gddictname {
      background-image: initial;
      background-color: rgb(75 75 75);
  }

**Comment by xiaoyifang** [comment]
有点灰，也不是很清楚。

**Comment by xiaoyifang** [comment]
https://github.com/xiaoyifang/goldendict/issues/388

**Comment by catsalt** [comment]
嗯, 你看着办嘛.  我本来想改的, 又不知道在哪里保存.

**Comment by xiaoyifang** [comment]
后续看下

**Comment by xiaoyifang** [comment]
https://alvarotrigo.com/blog/css-highlight-text/#:~:text=To%20Highlight%20text%20in%20HTML%20you%20have%20to,examples%20in%20this%20article%20follow%20the%20following%20structure%3A

喜欢哪个，下次在暗黑的模式下尝试一下。

https://user-images.githubusercontent.com/105986/232283688-65ed0919-701d-42e2-a71b-5ce414a3b052.mp4

**Comment by xiaoyifang** [comment]
![image](https://user-images.githubusercontent.com/105986/233123945-0497cf49-c367-4155-9d9b-6f2a69834d71.png)
