### ISSUE TITLE
Add an ability to micro-adjust the goldendict's behaviour

### ISSUE THREAD

**Issue by xiaoyifang** [xiaoyifang/goldendict-ng#496]
**Is your feature request related to a problem? Please describe.**
Provide a common way to fine tune certain behaviour of goldendict.
Such as 
- provide custom dictionary name,  https://github.com/xiaoyifang/goldendict/issues/309
- enable/disable single dictionary's fulltext  (from-community)
- auto group funcationality  https://github.com/xiaoyifang/goldendict/issues/483
- etc.

While doing all the above ,  the dictionary itself should be kept intact.
All these requirements have a common  point that they are not in frequent daily use .  The scenario would be set a one time and never have to modify it again.

**Describe the solution you'd like**
I'd like a metadata.txt file abut with the dictionary files.
It has a structure like this
```
name: "new dictionary name"
category: group1, group2 ,group3, "group 4"
fulltext: false   
#this is comment
```
each field hold one line, and seperated with colon
comment start with `#`
list values seperated with comma
string with can be enclosed with double quote.

**Comment by shenlebantongying** [comment]
I think disabling "Full text index" is a less used feature (Only needed for hardcore users with 100+ dictionaries).

How about

``` toml
# metadata.toml
fulltextindex = false
```
?

**Comment by xiaoyifang** [comment]
If it is easier to implementation without too much effort .    I think it worth a shot.
If take too much work ,  I think the requirement can hold for a time to mature.

**Comment by shenlebantongying** [comment]
Implemented as `metadata.toml`, though there are certainly some space for improvements.
