### ISSUE TITLE
fulltext engine refactor steps

### ISSUE THREAD

**Issue by xiaoyifang** [xiaoyifang/goldendict-ng#497]
**Is your feature request related to a problem? Please describe.**

As the creation of the official fulltext speed is about 3M/s ,  while xapian based fulltext can achieve 30M/s disk write speed.
I would recommend or alter the current processing of fulltext process.

And after clean the code ,it wil offer a more accurate and simple analysis to current dictionary read lock strategy.

Currently the fulltext creation and normal search use the same lock (inner share the same file lock).  I think it can be seperate and make real parallel lock .

**Describe the solution you'd like**

- [x]  remove the old fulltext creation ,maybe at the same time ,  keep a branch used to hold the old-logic and offer the old-fulltext as an alternative but no more features will be added/maintained  for a while.   https://github.com/xiaoyifang/goldendict-ng/issues/616

- [x] introduce a lock-free strategy or at least between normal index creation and fulltext index creation.
This can be done for certain dictionary formats first ,as different dictionary format has different popularity.https://github.com/xiaoyifang/goldendict-ng/pull/759

- [x]  add it to cmake @shenlebantongying

**Comment by shenlebantongying** [comment]
- [ ] let me add it to cmake :sweat_smile:

**Comment by xiaoyifang** [comment]
I create a vcpkg you can use on Windows
```
vcpkg install xapian:windows-x64-release
```
etc
