### ISSUE TITLE
Folder structure rearranged to have a more clean viewport

### ISSUE THREAD

**Issue by xiaoyifang** [xiaoyifang/goldendict-ng#503]
**Is your feature request related to a problem? Please describe.**
Currently nearly all the source file is in the root folder

**Describe the solution you'd like**

Maybe need to take some suggestive idea from other opensource project 
I'd like a folder structure like this:

Example(implementation can be different):

- dictionary
  - mdx
  - stardict
  - etc
- doc
- guideline
- index
- base
- core
- ui
- locale
- etc

**Comment by shenlebantongying** [comment]
I think within `src`

There are only ~280 files.

The big ones are Dictionaries parsers and UI related.

The rest are not that much. We don't have to divide the rest. Just put them directly under src/ for simplicity.

```
src/
  ui/
  dicts/
  main.cc
  other files
```

We also need a file naming plan:

Right now, we have 2 styles of file names `article_maker.cc` and `audioplayerfactory.cc`

We have both `.cpp` and `.cc` :sweat_smile: Unified into `.cpp` if move all files?

**Comment by xiaoyifang** [comment]
> We have both `.cpp` and `.cc` 😅 Unified into `.cpp` if move all files?

most of the existed files are `.cc`

**Comment by shenlebantongying** [comment]
Should we do it now? Move files will chop the history from some poor git clients, but git blame still works.

Move as early as possible?

**Comment by shenlebantongying** [comment]
We should use wildcard matching for simplicity:

qmake do support wildcard path matching:
https://doc.qt.io/qt-5/qmake-function-reference.html#files-pattern-recursive-false

We have those submodules that can be conditional compiled:

![image](https://user-images.githubusercontent.com/20123683/232413331-0ccf7473-e10c-436a-a769-a6d34f4a564d.png)

If we move all reverent file in to their owner folder:

```
src/
  chinese/
    chinese.cc
  epwing/
    epwing.cc
    epwing.ui
  ui/
    scanpopup.ui
    dialog.cc
    panel.cc
  dicts/
    dictionary.cc
    stardict.cc
  main.cc
  wstring.cc
  other files
```

We can write build rules as

```
SOURCES = src/*.cc
HEADERS = src/*.h

CONFIG( epwing ) {
    SOURCES = src/epwing/epwing.cc
    HEADERS = src/epwing/epwing.h
}
```

Thus, remove the need to modify build scripts when add new files.

**Comment by xiaoyifang** [comment]
Then all the future-added extended features should in a seperate folder to avoid been added to the *.cc accidently.

I think this can wait .

**Comment by shenlebantongying** [comment]
Ok, we continue to use explicit names.
