### ISSUE TITLE
boost startup speed 

### ISSUE THREAD

**Issue by xiaoyifang** [xiaoyifang/goldendict-ng#504]
**Is your feature request related to a problem? Please describe.**
when startup ,the goldendict went through some checks and indexing

**Describe the solution you'd like**
what about to delay the dictionary check ,or check in an unobstructive way.

While checking,the goldendict can still work 

This is a difficult task at first though , maybe can be scheduled for later investigation

----

Suspected reasons:
When has too many dictionaries ,  at startup ,goldendict did too much check , verify index, create index if not exist etc.
This may has some space for improvement.

**Comment by shenlebantongying** [comment]
How about we replace the `QSingleApplication` with a maintained one https://github.com/itay-grudev/SingleApplication first

**Comment by xiaoyifang** [comment]
I think it is the same.
Does the SingleApplication has offer some advantage over the one we use?

**Comment by shenlebantongying** [comment]
At least SingleApplication has a doc that explain how it works https://itay-grudev.github.io/SingleApplication/index.html

Deciphering how QtSingleApplication cost time :sweat_smile:

**Comment by xiaoyifang** [comment]
![image](https://user-images.githubusercontent.com/105986/232301982-4bda81a0-2c63-45c1-84b0-43e538bc90f6.png)

they are both from qtsingleapplication .
The singleapplication only offered qt6 support which our version supports too.

**Comment by shenlebantongying** [comment]
Difference:

`SingleApplication` use a `QSharedMemory` to check if an instance already exists.

`QSingleApplication` use `QLockFile` (Because it used to be part of Qt, it uses private APIs rather than public ones :sweat_smile: Someday it may break.)

Similarity:

They both use `QLocalServer` to communicate, the primary instance will set it up, and new instances will try to send messages to it.

Both are 1k~2k lines of code.

**Comment by xiaoyifang** [comment]
They are both derived from qt-solutions/qtsingleapplication.cpp at master ·
qtproject/qt-solutions · GitHub
<https://github.com/qtproject/qt-solutions/blob/master/qtsingleapplication/src/qtsingleapplication.cpp>

QSingleApplication use a self implementation of QtLockFile   maybe can be
replaced with the following
QLockFile Class | Qt Core 6.5.0 <https://doc.qt.io/qt-6/qlockfile.html>

shenleban tongying ***@***.***> 于2023年4月17日周一 11:15写道：

**Comment by shenlebantongying** [comment]
SharedMemoery on macOS has some restrictions, we cannot use SingleApplication before https://github.com/itay-grudev/SingleApplication/issues/136 is closed
