### ISSUE TITLE
wstring=>QString=>wstring again

### ISSUE THREAD

**Issue by xiaoyifang** [xiaoyifang/goldendict-ng#506]
**Is your feature request related to a problem? Please describe.**
there are also many string format changing from one string type to another.
This is one of the them,
https://github.com/xiaoyifang/goldendict/blob/59327959a81aab1253cd64f363dfd2b43f83c234/config.cc#L209

![image](https://user-images.githubusercontent.com/105986/232288853-3f307f70-5943-4ae5-aa87-2077ef053a07.png)

**Describe the solution you'd like**
have a unique string type in the goldendict and avoid all the unnecessary string type conversions.
Apart from dictionary parsing,indexing which may involve char*(string,qbytearry), all other places I think should use QString(or u32string) as a unique string type.

- [x] wstring_qt.cc  #507
- [x] ~utf8.cc encode/decode method ,performance compared to Qt builtin encode/decode.~
- [x] remove unnecessary string conversion,   can be split into many small commits/PRs ,seems a large work.
- [x] Folding::removeWhiteAndPunct optimization https://github.com/xiaoyifang/goldendict-ng/pull/606

----
method toWString
https://github.com/xiaoyifang/goldendict-ng/blob/3ff6b6a8eeda63a635d143ce7677f974708948c3/wstring_qt.cc#L11-L24

The above implementation was introduced in eaa62e69a0d579f968f355792477f708783642dd  to fix CJK character index issue.The fix is ok ,but as toWString() is used in too many places, the affected range is too wide. Actually only two parts of the code places need this fix.  
- when write word to index (index file is \0 sensitive , one more \0 character will make index can not work as expected)
- when query word from the index,the queryed word need this method.

All other places  can be simply replaced with toStd32String().More over,the `toWString()` will cause misunderstanding and confusion when compared to QString toStd32String .Make the further improvement difficult.

One possible defect is that when used in web page, CJK characters may not be displayed correctly.  

------------------

**Comment by shenlebantongying** [comment]
> Apart from dictionary parsing

From dictionary file to parsers to article maker, we use a lot of QString().arg() for templating. 

Include `{fmt}` ⇾ `std::format` should boost the speed without complicating the code. We only need the core feature, we can just include the 4 files into our build.

https://github.com/fmtlib/fmt

**Comment by xiaoyifang** [comment]
can be an extra option to choose

**Comment by xiaoyifang** [comment]
Are there some efficient string conversion library out there @shenlebantongying 
eg, u32string<=>string

**Comment by shenlebantongying** [comment]
We can abandon Qt5 and use this https://doc.qt.io/qt-6/qstringconverter.html :sweat_smile: 

`QString` is utf16.

With `QStringConverter`, the middle step converting to utf16/QString is gone

I have not look at the code, but I think they use ICU internally?

![image](https://user-images.githubusercontent.com/20123683/232357295-a3611c12-5b8d-4be9-9800-4fa09c1dff19.png)

**Comment by xiaoyifang** [comment]
Qt6 is still not perfect right now ,Qt5 maybe need to stay a little longer .
