### ISSUE TITLE
remove gdappstyle 

### ISSUE THREAD

**Issue by xiaoyifang** [xiaoyifang/goldendict-ng#516]
**Is your feature request related to a problem? Please describe.**
gdappstyle does not work seamlessly with qss.With the darkmode introduced ,even qss is used less and less.
Currently gdappstyle has not been used any more in goldendict-ng 

https://bugreports.qt.io/browse/QTBUG-103326
**Describe the solution you'd like**

**Comment by shenlebantongying** [comment]
Can we use this to avoid accidentally working on the same issue?

![image](https://user-images.githubusercontent.com/20123683/232556036-700a6e40-4666-4e7e-8c43-e53f83c720f1.png)

**Comment by xiaoyifang** [comment]
sure
