### ISSUE TITLE
Automated translation service. Crowdin?

### ISSUE THREAD

**Issue by shenlebantongying** [xiaoyifang/goldendict-ng#521]
See those projects using an automated translation services:

Mastodon (Crowdin) https://crowdin.com/project/mastodon
Transmission (Transfix) https://github.com/transmission/transmission/blob/main/docs/Translating.md
KDE zh-CN (Crowdin) https://crowdin.com/project/kdeorg/zh-CN
LinuxMint (launchpad) https://translations.launchpad.net/linuxmint/latest/+lang/zh_CN

We should consider one too, because learn to use git, qt translator, and send PR is overwhelming for none-programmers.

There are many choices, and they are all free for open source projects (Free labor to  enriching their translation memory database :sweat_smile:)

Crowdin is the best. You can try to log in via Github/Google and translate some Mastodon's strings. The experience is very smooth.

There is qt ts file support.

https://store.crowdin.com/qtts

And you can set up auto sync per day or per week.

https://support.crowdin.com/github-integration/

**Comment by shenlebantongying** [comment]
You have to submit a request:

https://crowdin.com/page/open-source-project-setup-request

**Comment by xiaoyifang** [comment]
crowdin seems promising .
GoldenDict already has some translations.  how to keep certains files or items in the file unchanged by crowdin.

**Comment by shenlebantongying** [comment]
It says it will import existing ones. 

:sweat_smile: If this kind of basic feature not implemented, they should have bankrupted already.

![image](https://user-images.githubusercontent.com/20123683/232658068-13eea14c-994b-4b0e-b2ff-ddcfe91f5067.png)

**Comment by xiaoyifang** [comment]
Most ts files I have not updated .   will crowdin automatically add new entries to the ts file. 
such as extract ts entries from source code and add the new translate entry to the ts file.

**Comment by xiaoyifang** [comment]
I'll take a more close look later

**Comment by shenlebantongying** [comment]
I think they only access the ts file, read it and update it. Not sure about the details.

**Comment by xiaoyifang** [comment]
> You have to submit a request:
> 
> https://crowdin.com/page/open-source-project-setup-request

submitted

**Comment by xiaoyifang** [comment]
https://crowdin.com/project/goldendict-ng/invite?h=e4371e8287ee215c870a25003720b3401673859
@shenlebantongying

**Comment by shenlebantongying** [comment]
Add me as admin? :sweat_smile:

**Comment by xiaoyifang** [comment]
done, 

configuration issue,I'm just asking the crowdin team for help.
![image](https://user-images.githubusercontent.com/105986/232689688-b3dc6970-9eaa-4df9-b5d5-f3482f415ded.png)

**Comment by WanderMax** [comment]
joined, configuration seems not right. all raw ts files in each language folder.

**Comment by xiaoyifang** [comment]
@WanderMax  are you robot or a real person?

**Comment by WanderMax** [comment]
I just upload the existing zh_CN.ts file to update current translation. You can see that I am the translator of some projects in crowdin.

**Comment by xiaoyifang** [comment]
Welcome

**Comment by xiaoyifang** [comment]
I roughly checked the translated ts file .Wonderful work!

**Comment by xiaoyifang** [comment]
https://github.com/xiaoyifang/goldendict-ng/commit/6de7f442e8c8023badca7530b99253bcccff7db4
too many unfinished entry items,   I think I need to reset some commits
