### ISSUE TITLE
The implementation of Ctrl+C+C, rewrite? or not?

### ISSUE THREAD

**Issue by xiaoyifang** [xiaoyifang/goldendict-ng#522]
**Is your feature request related to a problem? Please describe.**
on macos or Windows, there are some cases this global hot key will affect the system Copy(Ctrl+C) function.

**Describe the solution you'd like**
What about to use a new way to implement this ,  Last time I tried it in PR https://github.com/xiaoyifang/goldendict-ng/pull/139
Users reported that it can not work all time and I just revert the PR.

Pros:

The disadvantage of this implementation is that ,the first hotkey combination must be Ctrl+C ,the second key can be left for user to choose.

The pros:

It monitor clipboard changes and does not need to intecepte global system Copy shortcut.

**Describe alternatives you've considered**
I have not test wholely ,it is definitely a breakage to the previous GoldenDict behaviour.

Found:
A disadvantage of use clipboard to simulate Ctrl+C+C is that sometime the second Ctrl+C will not trigger clipboard changes.

---------------------

What about reduce ctrl+c+c to a simple combine key such as `Ctrl+D`    which means to translate the word in the clipboard.

Users will still have to press `Ctrl+C` or `Ctrl+X` to copy the text to clipboard ,then press `Ctrl+D` to trigger clipboard translation.
By this way, the system's global hotkey will not be affected .

**Comment by shenlebantongying** [comment]
So after clipboard changes, we detect if user pressed another button with in a short time?

> Users reported that it can not work all time

Are macOS users reported that?

**Comment by xiaoyifang** [comment]
https://forum.freemdict.com/t/topic/11495/1482?u=xiaoyifang

maybe not a break ,seems conflict with CTRL+C , even without enable Scan popup in  Tray.   
8e4c3263413766c6a15263cf4d9b48f11c26d79d
c24f57975ec944bcc6ad5f688c6fbefaaf0fd514
371fb66bdfe450af7def7056aeb25320a2446d23

**Comment by tophf** [comment]
ABBYY Lingvo's implementation of Ctrl-CC doesn't interfere with apps in Windows, so I guess it's possible to implement it correctly, but it probably requires a hook dll to detect the exact sequence of holding the modifier Ctrl while pressing `C` twice.
