### ISSUE TITLE
Some suspected language translations which I have not found with the file name as Language .

### ISSUE THREAD

**Issue by xiaoyifang** [xiaoyifang/goldendict-ng#530]
**Is your feature request related to a problem? Please describe.**
some translation files in folder `locale`
[ay_WI.ts](https://github.com/xiaoyifang/goldendict-ng/blob/staged/locale/ay_WI.ts)   (ay_BO in crowdin)
[be_BY@latin.ts](https://github.com/xiaoyifang/goldendict-ng/blob/staged/locale/be_BY%40latin.ts)
[eo_EO.ts](https://github.com/xiaoyifang/goldendict-ng/blob/staged/locale/eo_EO.ts)  https://simple.wikipedia.org/wiki/Esperanto    (eo_UY in crowdin)
[ie_001.ts](https://github.com/xiaoyifang/goldendict-ng/blob/staged/locale/ie_001.ts)   add custom mapping in crowdin
[jb_JB.ts](https://github.com/xiaoyifang/goldendict-ng/blob/staged/locale/jb_JB.ts)  introduced in 7df235b1188c441042e569c1a611d9fae71327ac  (NEW in crowdin   jbo_EN)
~[qt_es.ts](https://github.com/xiaoyifang/goldendict-ng/blob/staged/locale/qt_es.ts)
[qt_it.ts](https://github.com/xiaoyifang/goldendict-ng/blob/staged/locale/qt_it.ts)
[qt_lt.ts](https://github.com/xiaoyifang/goldendict-ng/blob/staged/locale/qt_lt.ts)~
[qu_WI.ts](https://github.com/xiaoyifang/goldendict-ng/blob/staged/locale/qu_WI.ts)  qu-PE in crowdin
[sr_SR.ts](https://github.com/xiaoyifang/goldendict-ng/blob/staged/locale/sr_SR.ts)      sr-SP in crowdin

 I have not found with these Language online.

**Describe the solution you'd like**
Remove them or update with a correct language code

**Comment by shenlebantongying** [comment]
`qu_WI.ts`

This is the only place where this code is used on the entire internet.

This madness come from this: We use different flags :sweat_smile: :sweat_smile: 

https://github.com/goldendict/goldendict/commit/987f0e0876862b299d05a325e3e462e40c438049

![image](https://user-images.githubusercontent.com/20123683/232851136-e9b7d67c-45ad-4c51-ac0c-db5bcfa6ac6a.png)


`qu_WI.ts` can be just `qu.ts`.

We should stop displaying flags for language, and adjust the language parser to accept just format like `qu.ts`

**Comment by xiaoyifang** [comment]
> `qu_WI.ts` can be just `qu.ts` (Quechua).

from the commit log ,I think that ,   qu_WI.ts is used as Wiphala  language 
qu in https://developer.crowdin.com/language-codes/ seems refer to 
![image](https://user-images.githubusercontent.com/105986/232928815-b44a48f9-1e6e-4b16-bb0d-26c3fe737e73.png)

Then quesion, which locale ts file is used with Bolivia ?

If the above  Wiphala and Bolivia both use the same language with no difference,I think we can replaced qu_WI to qu
and support Bolivia at the same time?

As we are using Crowdin to do all the translation .   This is highly needed .
https://github.com/goldendict/goldendict/issues/1330

**Comment by xiaoyifang** [comment]
> ie_001.ts

https://en.wikipedia.org/wiki/Interlingue

17aea140d3de4a1a7ba73b03af9d7a5d3fe5bb01

**Comment by shenlebantongying** [comment]
> Then quesion, which locale ts file is used with Bolivia ?

Bolivia is a South American country, they generally use Spanish & Portuguese.  (They were colonies of Spain, there is no native languages :)

We should just remove the flags as https://github.com/goldendict/goldendict/issues/1330

Crowdin seems to be able to add custom languages: 

https://support.crowdin.com/changing-target-languages/

**Comment by WanderMax** [comment]
main language support is in top priority. for users in Bolivia, they can choose Spanish or Portuguese in language setting.

**Comment by xiaoyifang** [comment]
> Crowdin seems to be able to add custom languages:
> 
> https://support.crowdin.com/changing-target-languages/

I think the mapping only change filenames,  not the content.

**Comment by xiaoyifang** [comment]
> Crowdin seems to be able to add custom languages:
> 
> https://support.crowdin.com/changing-target-languages/

I think the mapping only change filenames,  not the content.

**Comment by xiaoyifang** [comment]
the content of be_BY@latin.ts seems it is Polish(detect with google translate)?

**Comment by shenlebantongying** [comment]
It is Belarusian but in Latin Script 

Belarusian can be written in Latin Script(ABCDE) or Cyrillic script (THe one used in russian).

The content is the same, just different alphabets :sweat_smile: 

However, Latin script is rarely used. https://www.reddit.com/r/belarus/comments/qy8o5e/belarusians_it_it_true_that_the_belarusian/

**Comment by xiaoyifang** [comment]
> However, Latin script is rarely used. https://www.reddit.com/r/belarus/comments/qy8o5e/belarusians_it_it_true_that_the_belarusian/

Seems crowdin does not support belarusian latin ,  we can remove it for now.

**Comment by xiaoyifang** [comment]
> https://developer.crowdin.com/language-codes/
> 
> We have to stop displaying flags for language, and adjust the language parser to accept just format like `qu.ts`.

I prefer use locale ,  the code in the above language is too specific and only used in Crowdin.

> 1. Via API, the endpoint [List Supported Languages](https://developer.crowdin.com/api/v2/?q=api#operation/api.languages.getMany). In response, you'll see all locales.
> 
> 
> 
> 2. Or the second workaround, you can check them by downloading translations. You should go to the File Settings-> Resulting file after translations export -> put the needed placeholder -> download the file with translation. In this way, you can check which locale will be used:
![image](https://user-images.githubusercontent.com/105986/233009972-f839de0d-96df-401c-925b-575e32e0b83f.png)

**Comment by shenlebantongying** [comment]
> I prefer use locale , the code in the above language is too specific and only used in Crowdin.

What do u mean by "locale"? We don't use "locale" as in C's locale to set interface languages? We just load a specific .qm file?

**Comment by xiaoyifang** [comment]
> > I prefer use locale , the code in the above language is too specific and only used in Crowdin.
> 
> What do u mean by "locale"? We don't use "locale" as in C's locale to set interface languages? We just load a specific .qm file?

It has no relation with the system locale.
I mean the locale Crowdin used internally ,  %locale_with_underscore%  ,  Crowdin also use this variable to generate ts files.
![image](https://user-images.githubusercontent.com/105986/233012914-cb17bc1b-fc28-4150-8c5c-22a33968861c.png)

**Comment by shenlebantongying** [comment]
This make senses. Some languages do have variants based on regions.

**Comment by shenlebantongying** [comment]
Curious, what's the default region associated with `qu`?

**Comment by xiaoyifang** [comment]
then we use this zh_CN as an unique identifier to load the translation file,not need to use substring again.

**Comment by xiaoyifang** [comment]
> Curious, what's the default region associated with `qu`?

qu-PE

**Comment by xiaoyifang** [comment]
> If the file doesn't exist, we just don't load any translation?
> 
> If someone demands, we can add more `lang_region` variants?

Crowdin will translate some entries but not all of them. based on the existing crowdin database.
![image](https://user-images.githubusercontent.com/105986/233036977-7db2ae46-2d8f-401b-bc9d-70f37fe73135.png)

Add a new language maybe result with this .not translated ,I'm still trying to figure out the process.

**Comment by shenlebantongying** [comment]
> Crowdin will translate some entries but not all of them. based on the existing crowdin database.

We can just add a link on README.md 

Someone will translate them. 

![image](https://user-images.githubusercontent.com/20123683/233039483-e2f0a7df-6b75-45f5-8d86-6f375cc4c18c.png)

https://github.com/transmission/transmission/blob/main/docs/Translating.md

**Comment by xiaoyifang** [comment]
great ,this is a way.   They can join the crowdin's project .

**Comment by Carmina16** [comment]
`ie_001` is a correct code. It should be probably added manually in Crowdin.

**Comment by Carmina16** [comment]
Please do not use `QLocale::name` for anything. Qt5+ has a new mechanism for loading translations which can handle any locale names (not the limited set of `QLocale`) and can use user language preferences (and not the dumb `LANG` variable).

**Comment by xiaoyifang** [comment]
> `ie_001` is a correct code. It should be probably added manually in Crowdin.

I have found no ie_001 in the Crowdin ,  this file can be kept in gd-ng for a  while. Later can be put in the Crowdin for help of translation . maybe with some documents to guild the users to help .

**Comment by xiaoyifang** [comment]
[all-configured-mapping.zip](https://github.com/xiaoyifang/goldendict-ng/files/11279392/all-configured-mapping.zip)
: all the configured languages mapping with locale 

Just focus on these two fields, and use underscore _ in locale field
![image](https://user-images.githubusercontent.com/105986/233246275-2baf51e1-74d1-4341-bfb5-2024032d8fb9.png)

**Comment by Carmina16** [comment]
> https://doc.qt.io/qt-5/qtranslator.html#load

Yes, please use the version that takes a `Locale` object instead of string. It is more advanced.

**Comment by Carmina16** [comment]
Here you are:
```
            {
                "id": "ie",
                "name": "Interlingue",
                "editorCode": "ie",
                "twoLettersCode": "ie",
                "threeLettersCode": "ile",
                "locale": "ie_001",
                "androidCode": "ie",
                "osxCode": "ie.lproj",
                "osxLocale": "ie",
                "pluralCategoryNames": [
                    "one",
                    "other"
                ],
                "pluralRules": "(n != 1)",
                "pluralExamples": [
                    "1",
                    "0, 2-999; 1.2, 2.07..."
                ],
                "textDirection": "ltr",
                "dialectOf": null
            },
```

**Comment by xiaoyifang** [comment]
> Interlingue

where do you get this,I have not found the language `Interlingue` in crowdin

**Comment by Carmina16** [comment]
It's not there by default. You can add it to the project.

**Comment by xiaoyifang** [comment]
Yes ,I noticed the custom mapping.    But the content still need to be translated by manual.
