### ISSUE TITLE
increase the height of last displayed dictionary

### ISSUE THREAD

**Issue by xiaoyifang** [xiaoyifang/goldendict-ng#536]
**Is your feature request related to a problem? Please describe.**
![image](https://user-images.githubusercontent.com/105986/232979200-4513d1f8-ff93-4063-87ca-2dc5e642e48e.png)

If the last dictionary has too few text, the display is not well.

**Describe the solution you'd like**
Add a `min-height` to the last dictionary

**Comment by shenlebantongying** [comment]
Why not add an empty div instead `<div style="height:400px;"></div>`.

If the style has an edge (modern & lingoes blue), the last one will have weird space. 

![image](https://user-images.githubusercontent.com/20123683/233187047-8a50af3b-66c7-4be8-8d08-1b0a18d83242.png)

vs

![image](https://user-images.githubusercontent.com/20123683/233187397-eace78ef-4deb-4f3f-ad8d-f7cb770a67b5.png)

**Comment by xiaoyifang** [comment]
> Add an empty div `<div style="height:400px;"></div>` is better.

Your way is better.
