### ISSUE TITLE
 Avoid using flags to represent languages

### ISSUE THREAD

**Issue by xiaoyifang** [xiaoyifang/goldendict-ng#537]
> Disabling/deprecating the flag icons is contrary to an old inclination toward icons everywhere of two core GoldenDict developers (now sadly inactive): #12

I'm not going to remove icon everywhere, although I do against overuse icons. As [GNOME human interface guidelines says](https://developer.gnome.org/hig/stable/icons-and-artwork.html.en):
> Therefore, only use icons whose meaning is commonly recognized. If a commonly recognized icon is not available, it might be better to use a text label instead. 

The point here is only about removing flag icons for representing languages - exactly as what Google and Microsoft do:
![image](https://user-images.githubusercontent.com/2216902/102368084-6370d680-3fb2-11eb-889f-df76ad577312.png)
![image](https://user-images.githubusercontent.com/2216902/102368208-83a09580-3fb2-11eb-83aa-4fd83787d3dd.png)

Besides, I believe text in languages people use is more identifiable than flags.

> Not necessarily. Finding all flags in one compatibly-licensed icon set is not unimaginable.

Indeed we can just grab from Noto Emoji. Will not be forever but takes too much time. If you're really interested, are you willing to grab flags & rename them?

_Originally posted by @xcffl in https://github.com/goldendict/goldendict/issues/1330#issuecomment-746467121_

**Comment by xiaoyifang** [comment]
#530

**Comment by shenlebantongying** [comment]
Hard problem: how do we distinguish those two:

zh_CN
zh_TW

Current languages code only contains `zh` part

https://github.com/xiaoyifang/goldendict-ng/blob/8bbf7838bc9ebf548c717870792792b74798a07b/src/language.cc#L235

We have to create a new file with mapping of:

```
zh_CN -> tr("Simplified Chinese")
zh_TW -> tr("Simplified Chinese")
```

**Comment by michaelbeijer** [comment]
Agree, text is better than flags. 

Incidentally, the same goes for Dutch:

Dutch(nl_NL) = standard Dutch, used in the Netherlands
Dutch(nl_BE) = Belgian Dutch (sometimes referred to as ‘Flemish’)

**Comment by xiaoyifang** [comment]
> Problem: how do we distinguish those two:
> 
> zh_CN zh_TW
> 
> We just display `Chinese(zh_CN)` and `Chinese(zh_TW)`?

It uses other method to keep these two languages can be loaded correctly.

zh_CN= Chinese Simplified 
zh_TW=Chinese Traditional

**Comment by shenlebantongying** [comment]
> zh_CN= Chinese Simplified
zh_TW=Chinese Traditional

I thought about his, but other languages are problems:

Without backgrounds, we cannot figure out other languages' variant names

like @michaelbeijer mentioned

> Dutch(nl_NL) = standard Dutch, used in the Netherlands
 Dutch(nl_BE) = Belgian Dutch (sometimes referred to as ‘Flemish’)

:sweat_smile: how do we suppose to know nl_NL is "standard dutch"

**Comment by xiaoyifang** [comment]
![image](https://user-images.githubusercontent.com/105986/233041620-bdd65049-f02a-4889-9fbc-c90c169c2d9e.png)
This is what crowdin offers

**Comment by michaelbeijer** [comment]
A good place to look for lists of the various language codes is to see how the developers of CAT tools (translation software) deal with it. For example have a look at these lists:

- https://gateway.sdl.com/servlet/fileField?retURL=%2Fapex%2FCommunityKnowledge%3FarticleName%3D000001154&entityId=ka54X000000oYYdQAM&field=Attachment1__Body__s (a very good one this: SDL TMS Language Support.xlsx)
- https://help.xtm.cloud/en/xtm-cloud/13.1/en/language-codes.html
- https://docs.memoq.com/9-7/en/Things/things-supported-languages.html
- https://docs.memoq.com/current/en/Things/things-supported-languages.html?highlight=supported%20language

**Comment by xiaoyifang** [comment]
https://github.com/xiaoyifang/goldendict-ng/issues/530#issuecomment-1515639539
