### ISSUE TITLE
what's the function of blank.png used in gd

### ISSUE THREAD

**Issue by xiaoyifang** [xiaoyifang/goldendict-ng#552]
as title

**Comment by shenlebantongying** [comment]
It is hack to put an `<img>` within `<span>`.

If the span is empty, it doesn't have size thus cannot use css `background-img`

![image](https://user-images.githubusercontent.com/20123683/233321576-85880c9f-3d69-4810-99b1-4cdd42379886.png)


![image](https://user-images.githubusercontent.com/20123683/233321257-b2a2ef77-b8d2-4b2a-bc1a-5d87c0b96b84.png)

He is either genius or on meth to come up this hack :sweat_smile:

**Comment by xiaoyifang** [comment]
`display:inline-block`
