### ISSUE TITLE
remove winlibs and use vcpkg instead

### ISSUE THREAD

**Issue by xiaoyifang** [xiaoyifang/goldendict-ng#555]
**Is your feature request related to a problem? Please describe.**
Currently the packages in winlibs are mostly taken from vcpkg build packages.

**Describe the solution you'd like**

use vcpkg and qmake /cmake together .  
Maybe need change the github action script at the same time.

Steps:

- [x] create a seperate repository to backup the winlibs https://github.com/xiaoyifang/goldendict-winlibs

- [x] remove eb.lib from winlibs and use submodule eb

- [x] use cmake to build qt6 based goldendict 
- [x] integrete vcpkg with cmake
vcpkg has better support for cmake

- [x] new features will stop to add to qt5 if it cost extra work.

**Comment by xiaoyifang** [comment]
this can be postpone after cmake adaption which is qt6.

**Comment by xiaoyifang** [comment]
vcpkg and cmake can be used together ,
Currently ,all the dependencies in the winlibs folder  can be found in the vcpkg

**Comment by shenlebantongying** [comment]
ffmpeg needs hours to build :sweat_smile: :sweat_smile: 

vcpkg is developing a GitHub caches feature that uses GitHub caches. Maybe this feature does not work for now. We can also make a new workflow that dedicates to building a cache for all dependencies and drop them into the current winlibs. Personal free GitHub has 10 GiB space for caches.

https://learn.microsoft.com/en-us/vcpkg/consume/binary-caching-github-actions-cache

https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows

**Comment by xiaoyifang** [comment]
> ffmpeg needs hours to build 😅 😅

ffmpeg does not needed anymore when qt>6.5(?).   or do not build with ffmpeg enabled on Windows

**Comment by shenlebantongying** [comment]
TODO for future PRs

- [ ] add breakpad for windows
- [ ] how to disable building of debug packages for CI?

**Comment by shenlebantongying** [comment]
To make breakpad optional, combine these:

* https://learn.microsoft.com/en-us/vcpkg/concepts/manifest-mode#example-features-in-project-manifests
* https://learn.microsoft.com/en-us/vcpkg/users/buildsystems/cmake-integration#vcpkg_manifest_features

**Comment by shenlebantongying** [comment]
The vcpkg bundled in GitHub actions runners update every time the runner image updates.

This means vcpkg packages will be updated weekly. 

Update frequency -> https://github.com/search?q=repo%3Aactions%2Frunner-images+Windows+Server+2022&type=pullrequests

The initial full build needs maybe 30 mins. https://github.com/shenlebantongying/goldendict-ng/actions/runs/9824674216/job/27123911938 .

I suppose that even if the vcpkg updates, the old caches are still useable if the library isn't updated? 

Worest case senario: one super long build to create caches every week 😅

**Comment by shenlebantongying** [comment]
I consider this is finished. Let's just keep the winlibs just for now, just for PR check.
