### ISSUE TITLE
Does the set locale still needed?

### ISSUE THREAD

**Issue by xiaoyifang** [xiaoyifang/goldendict-ng#559]
https://github.com/xiaoyifang/goldendict-ng/blob/a8c898192f531d29a5a07198aa3b6dab8f8cc7a8/src/main.cc#L215-L217
Seems these lines were introduced to correct commandline charmap issue.

As we have use a different way to parse command line option .Does these lines still needed?
And it seems to affect the system language detection logic

**Comment by xiaoyifang** [comment]
https://github.com/xiaoyifang/goldendict-ng/issues/530#issuecomment-1514360678

**Comment by shenlebantongying** [comment]
Obligatory link before talking Unix's locale https://github.com/mpv-player/mpv/commit/1e70e82baa9193f6f027338b0fab0f5078971fbe

---

The line was added for `argv` parsing https://github.com/goldendict/goldendict/commit/720c95dd22972650cc22cde20794dc9423821855 , but we have moved to `QCommandLineParser` which should have taken care of those things for us. 

I think it can be removed.

**Comment by xiaoyifang** [comment]
this can be fixed in the PR of language icon issue

**Comment by shenlebantongying** [comment]
Qt4:

![image](https://user-images.githubusercontent.com/20123683/233638314-061ac968-9c11-46c0-8482-3e937b2d5ee5.png)

The fix no long works because in Qt6, the `QString::fromLocal8Bit` just default to utf8 on Unix :sweat_smile: 

https://doc.qt.io/qt-6/qstring.html#fromLocal8Bit

**Comment by xiaoyifang** [comment]
Can you file a PR to remove this?

shenleban tongying ***@***.***> 于2023年4月21日周五 20:45写道：
