### ISSUE TITLE
Arm64EC Compile

### ISSUE THREAD

**Issue by huangyinhaow** [xiaoyifang/goldendict-ng#561]
According to Microsoft:

> Arm64EC (“Emulation Compatible”) enables you to build new native apps or incrementally transition existing x64 apps to take advantage of the native speed and performance possible with Arm-powered devices, including better power consumption, battery life, and accelerated AI & ML workloads.
> Arm64EC is a new application binary interface (ABI) for apps running on Arm devices with Windows 11. **It is a Windows 11 feature that requires the use of the Windows 11 SDK** and is not available on Windows 10 on Arm.
> [Link](https://learn.microsoft.com/en-us/windows/arm/arm64ec)

Compiling to Arm64EC is [probably trivial](https://learn.microsoft.com/en-us/windows/arm/arm64ec-build), because _if your app relies on existing dependencies or plugins that don't yet support Arm, you can start to rebuild parts of your app as Arm64EC to gain the benefits of native performance_.

You can compile to an Arm64EC target on an x64 device. https://github.com/xiaoyifang/goldendict-ng/issues/444

I don't know much about C and C++, I hope you can give it a try. THANKS 🙏!

**Comment by xiaoyifang** [comment]
Currently has no resource to compile on Arm64EC ,  need help.

**Comment by huangyinhaow** [comment]
> Currently has no resource to compile on Arm64EC ,  need help.

Oh, sorry to misunderstand you, Arm64EC is not a processor architecture, it is just a special program compilation method, the program compiled by this method can use both arm64ec library and x64 library , the advantage of this is that when you find that part of your program cannot be compiled for arm64, you have room for compromise.

**Comment by huangyinhaow** [comment]
> Currently has no resource to compile on Arm64EC ,  need help.

Oh, sorry to misunderstand you, Arm64EC is not a processor architecture, it is just a special program compilation method, the program compiled by this method can use both arm64ec library and x64 library , the advantage of this is that when you find that part of your program cannot be compiled for arm64, you have room for compromise.

**Comment by xiaoyifang** [comment]
Does github action support this kind of compilation now ?

**Comment by huangyinhaow** [comment]
> Does github action support this kind of compilation now ?

Yes, you can do this on an x64 device.

**Comment by xiaoyifang** [comment]
close as not planned

**Comment by shenlebantongying** [comment]
For extra context, Qt's ARM windows support is still technical preview

![image](https://github.com/xiaoyifang/goldendict-ng/assets/20123683/0a38806e-202d-45f8-bf6f-92f60eb5db7d)
