### ISSUE TITLE
StarDict synonym links broken with &

### ISSUE THREAD

**Issue by homocomputeris** [xiaoyifang/goldendict-ng#567]
**Describe the bug**
Links in StarDict dictionaries lead to `&` or similar strings, not the works they are supposed to link.

**To Reproduce**
0. Get a StarDict dictionary with links, e.g. by converting kaikki.org dumps to StarDict using Pyglossary.
1. Open a word with synonym links
2. Hover over the link
3. See something like `&`
4. Click on the link
5. Something like `&`, `m&`, `fl&` opens instead of the synonym.

**Expected behavior**

**Screenshots**
<img width="517" alt="Screenshot 2023-04-22 at 15 11 00" src="https://user-images.githubusercontent.com/7422433/233787269-4d72774a-d10d-4e31-b621-e7651ee23e41.png">
<img width="675" alt="Screenshot 2023-04-22 at 15 12 31" src="https://user-images.githubusercontent.com/7422433/233787271-06ed2901-5545-4db3-b38b-acfcb23f4691.png">

**Desktop (please complete the following information):**
 - OS: macos 13.3
 - Browser Fifefox
 - Version

> Goldendict 23.04.03-alpha.230421.a8c89819
> macos darwin 22.4.0 Qt 6.4.3 x86_64-little_endian-lp64
> Clang 14.0.0 (clang-1400.0.29.202)
> Flags: USE_XAPIAN  MAKE_ZIM_SUPPORT MAKE_CHINESE_CONVERSION_SUPPORT

**Additional context**
Links work in GoldenDict for Android, so I'd assume this is not the StarDict dictionary issue.

**Comment by xiaoyifang** [comment]
can you help to save the html and upload the html here
![image](https://user-images.githubusercontent.com/105986/233788567-6a1c5972-2a09-45a0-9c42-258550fc4e1b.png)

**Comment by homocomputeris** [comment]
The HTML from File - Save article:

```html
<!DOCTYPE html><html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8"><script type="text/javascript" src="qrc:///scripts/jquery-3.6.0.slim.min.js"></script><script> var $_$=$.noConflict(); </script><script type="text/javascript" src="qrc:///scripts/gd-custom.js"></script><script type="text/javascript" src="qrc:///scripts/iframeResizer.min.js"></script><script type="text/javascript" src="qrc:///qtwebchannel/qwebchannel.js"></script>
    <script>
     $_$(document).ready( function ($){ 
         console.log("webchannel ready..."); 
         new QWebChannel(qt.webChannelTransport, function(channel) { 
             window.articleview = channel.objects.articleview; 
       }); 
     }); 
    </script>
    <link href="qrc:///article-style.css" media="all" rel="stylesheet" type="text/css"><link href="qrc:///article-style-print.css" media="print" rel="stylesheet" type="text/css"><title>fleka</title><link rel="icon" type="image/png" href="qrc:///flags/rs.png">

<script type="text/javascript">
     function tr(key) {
            var tr_map = {
                "Expand article": "Expand article", "Collapse article": "Collapse article"
            };
            return tr_map[key] || '';
        }
</script>
<script type="text/javascript" src="qrc:///scripts/gd-builtin.js"></script></head><body> <div class="gdarticle  gdactivearticle " id="gdfrom-6f8051c77dfbfd1b8b9be2c44709d85d" onclick="gdMakeArticleActive( '6f8051c77dfbfd1b8b9be2c44709d85d' );" oncontextmenu="gdMakeArticleActive( '6f8051c77dfbfd1b8b9be2c44709d85d' );"><div class="gddictname" onclick="gdExpandArticle('6f8051c77dfbfd1b8b9be2c44709d85d');" id="gddictname-6f8051c77dfbfd1b8b9be2c44709d85d" title="">
                      <span class="gddicticon"><img src="gico://6f8051c77dfbfd1b8b9be2c44709d85d/dicticon.png"></span>
                      <span class="gdfromprefix">From </span>
                      <span class="gddicttitle">Wiktionary (Sr-En)</span>
                      <span class="collapse_expand_area"><img class="gdcollapseicon" id="expandicon-6f8051c77dfbfd1b8b9be2c44709d85d" title="Collapse article"></span>
                     </div><div class="gddictnamebodyseparator"></div><div class="gdarticlebody gdlangfrom-sr" lang="en" style="display:inline" id="gdarticlefrom-6f8051c77dfbfd1b8b9be2c44709d85d"><h3 class="sdct_headwords">fleka</h3><div class="sdct_h"><div><div class="pronunciations"><font color="gray">/flêka/</font> (ipa)</div><div class="pos"><font color="green">noun</font></div>spot, smear, blot<div>Synonyms: <a href="m%26amp%3B.html#x211;lja">mȑlja</a>, <a href="fl%26amp%3B.html#x205;k">flȅk</a></div><br><div>Etymology: From German Fleck.</div></div></div>
                     
                     
                     <h3 class="sdct_headwords">flȅka</h3><div class="sdct_h"><div><div class="pronunciations"><font color="gray">/flêka/</font> (ipa)</div><div class="pos"><font color="green">noun</font></div>spot, smear, blot<div>Synonyms: <a href="m%26amp%3B.html#x211;lja">mȑlja</a>, <a href="fl%26amp%3B.html#x205;k">flȅk</a></div><br><div>Etymology: From German Fleck.</div></div></div>
                     
                     
                     <h3 class="sdct_headwords">flȅka</h3><div class="sdct_h"><div><div class="pronunciations"><font color="gray">/flêka/</font> (ipa)</div><div class="pos"><font color="green">noun</font></div>spot, smear, blot<div>Synonyms: <a href="%26amp%3B.html#x43C;&amp;#x440;&amp;#x30F;&amp;#x459;&amp;#x430;">мр̏ља</a>, <a href="%26amp%3B.html#x444;&amp;#x43B;&amp;#x435;&amp;#x30F;&amp;#x43A;">фле̏к</a></div><br><div>Etymology: From German Fleck.</div></div></div>
                     
                     
                     </div></div><div class="empty-space"></div></body></html>
```

**Comment by xiaoyifang** [comment]
```
<a href="m%26amp%3B.html#x211;lja">mȑlja</a>
```

`ȑ` has been encoded as html `&#x211;`.  The correct way should be encoded as url .

need further investigation to find out where does it come from.

**Comment by xiaoyifang** [comment]
> Get a StarDict dictionary with links, e.g. by converting kaikki.org dumps to StarDict using Pyglossary

can you provide a stardict dictionary or a more detailed step how to use the kaikki.org dumps.

**Comment by homocomputeris** [comment]
> > Get a StarDict dictionary with links, e.g. by converting kaikki.org dumps to StarDict using Pyglossary
> 
> can you provide a stardict dictionary or a more detailed step how to use the kaikki.org dumps.

Sure:
1. Install https://github.com/ilius/pyglossary, and its deps: lxml, beautifulsoup.
2. Download, e.g. https://kaikki.org/dictionary/Serbo-Croatian/all-senses/kaikki_dot_org-dictionary-SerboCroatian-all-senses.json
3. Run
```shell
pyglossary --read-format=Wiktextract --write-format=Stardict --utf8-check --source-lang=sr --target-lang=en --name='Wiktionary (Sr-En)' kaikki_dot_org-dictionary-SerboCroatian-all-senses.json "Wiktionary (Sr-En)"
```
4. It will produce 4 stardict files:

> Wiktionary (Sr-En).dict.dz 
> Wiktionary (Sr-En).ifo
> Wiktionary (Sr-En).idx     
> Wiktionary (Sr-En).syn

5. Add them to GD

**Comment by xiaoyifang** [comment]
https://ports.macports.org/port/stardict/
Does stardict support this dictionary's link?

**Comment by homocomputeris** [comment]
Unfortunately, Stardict is unusable on mac:

> Error: Processing of port stardict failed

From binary:

![Screenshot 2023-04-24 at 18 47 18](https://user-images.githubusercontent.com/7422433/234062886-8f3349c6-c3bd-4baf-b754-0f489cb78282.png)

Sorry, I have no other OS available.

**Comment by xiaoyifang** [comment]
I still struggle to install a pyglossary ,may take some time .

**Comment by homocomputeris** [comment]
> I still struggle to install a pyglossary ,may take some time .

I can share the dictionary, although it's about 50 MB. Will it be fine?

**Comment by xiaoyifang** [comment]
Yes ,you are very kind.  you can share me with a private link if you do not want to expose this dictionary.

**Comment by homocomputeris** [comment]
You can get them from the repo: https://github.com/homocomputeris/wiktionary-stardict

**Comment by homocomputeris** [comment]
Maybe @ilius will be able to help to clarify whether it's an issue with StarDict format, Pyglossary conversion, or GoldenDict.

Because in a different piece of software, I get this (although, for example, in GD android it works fine):
<img width="733" alt="Screenshot 2023-04-25 at 14 12 50" src="https://user-images.githubusercontent.com/7422433/234272813-9d005329-6adb-4f72-a4e2-9e444937ce0a.png">
<img width="730" alt="Screenshot 2023-04-25 at 14 12 59" src="https://user-images.githubusercontent.com/7422433/234272816-e1b244d1-34ec-429a-b4fb-aa2bb8052df6.png">

**Comment by xiaoyifang** [comment]
Do you mean AyanDict also does not support this kind of link?

**Comment by homocomputeris** [comment]
> Do you mean AyanDict also does not support this kind of link?

Yes, it looks like it.

**Comment by homocomputeris** [comment]
However, the exact same dictionary works fine in GoldenDict for:

https://user-images.githubusercontent.com/7422433/234284525-f1951b14-8d1c-4b56-868c-2816f75932b5.mp4

I will open an issue in the Pyglossary tracker.

**Comment by ilius** [comment]
I can add a flag to disable or enable the quiting in pyglossary.

But I'm still not sure about the default behavior.

On one hand, href value is a URL, and the path part of URLs should be encoded/quoted, kinda like when you paste a unicode link in your browser.

On the other hand, I think most dictionaries that read StarDict do not unquote the word link. So from the user's perspetive it's probably better not to quote it.

**Comment by homocomputeris** [comment]
In my opinion, the default behaviour should address forward compatibility and the state of the art. 

- If most of modern dictionary software is completely fine with full-unicode (as is modern Web, I believe, where the encoding problem has almost disappeared), then dictionaries themselves should target this modern software and have everything in UTF. 
- For backwards compatibility there may be an explicit flag, for those who prefer older software.

**Comment by ilius** [comment]
I just tested a quoted unicode link with AyanDict and seems to work fine:

(from Latin-to-English, 501-word sample)

```
#72 >> X

<div><div class="pronunciations"><font color="gray">/ks/</font> (other)</div><div class="pos"><font color="green">num</font></div>ten; decem.<div class="categories">Categories: Latin cardinal numbers (source: w)</div><div>Related: <a href="bword://&#x2169;">Ⅹ</a>, <a href="bword://&#x2179;">ⅹ</a></div><br><div>Etymology: Borrowed from Ancient Greek Χ (Kh, “chi”), which represented /ks/ in the dialects of most of the Greek mainland and Euboea.</div></div>
```

I'm not sure the quoting is to blame here.
You sure the wiktextract json file is not the problem?

PS: I realized the quoting in pyglossary is done with lxml library and disabling would be very hacky is possible.

**Comment by homocomputeris** [comment]
> You sure the wiktextract json file is not the problem?

I've encountered it in converted JMdict too

<img width="384" alt="Screenshot 2023-04-26 at 00 19 54" src="https://user-images.githubusercontent.com/7422433/234416781-66bfa05d-508c-44ee-83bd-76cd2033a470.png">

**Comment by ilius** [comment]
I think we are talking about 2 different issues here.

1- Unquoting the link in GoldenDict.

2- Possibly problematic links in kaikki json, like `<a href="m%26amp%3B.html#x211;lja">mȑlja</a>`

```python
In [3]: from urllib.parse import unquote
In [4]: unquote("m%26amp%3B.html#x211;lja")
Out[4]: 'm&amp;.html#x211;lja'
```

**Comment by xiaoyifang** [comment]
` <a href="bword://&#x2179;">ⅹ</a>`
the word `ⅹ` is encoded as html entity which is fine in html content, but as bword is a link ,  encode as url should be expected.
But considering that bword is a custom scheme protocol , this html encoding can be handled if is already be widely used.

**Comment by ilius** [comment]
Okay, correcttion: 2 problems:

1- Unquoting the link in GoldenDict or other apps.
2- AyanDict combining 2 separate links (html is correct) which is entirely different problem.

The html generated by pyglossary seems fine: (prettified it here)
```
<div>
	<div class="pronunciations">
		<font color="gray">/flêka/</font> (ipa)
	</div>
	<div class="pos">
		<font color="green">noun</font>
	</div>spot, smear, blot<div>Synonyms: <a href="bword://m&#x211;lja">mȑlja</a>, <a href="bword://fl&#x205;k">flȅk</a>
	</div><br>
	<div>Etymology: From German Fleck.</div>
</div>
```

**Comment by ilius** [comment]
But where did `<a href="m%26amp%3B.html#x211;lja">mȑlja</a>` come from?
This is a confusing issue! :D

**Comment by xiaoyifang** [comment]
> But where did `<a href="m%26amp%3B.html#x211;lja">mȑlja</a>` come from? This is a confusing issue! :D

this is goldendict's doing .   fixed in above commit.

**Comment by ilius** [comment]
Got it.
Fixed it in AyanDict:
https://github.com/ilius/ayandict/commit/a60103db8cfbf8417876fb6556e47d6b723ef65c

**Comment by ilius** [comment]
BTW, do you handle link targets with space in them?

**Comment by xiaoyifang** [comment]
> do you handle link targets with space in them?

yes

**Comment by xiaoyifang** [comment]
![image](https://user-images.githubusercontent.com/105986/234740101-d8e64064-d5c6-48d4-bd98-65bd11399ab4.png)

plz use the latest release.

**Comment by homocomputeris** [comment]
It works, thanks a lot!
