### ISSUE TITLE
GoldenDict fails to initialize on Manjaro KDE

### ISSUE THREAD

**Issue by ApprobationBW** [xiaoyifang/goldendict-ng#571]
**Describe the bug**
GoldenDict cannot be launched anymore on my Manjaro KDE (Stable).

I use normally 3 Virtual Desktops called: 1, 2, 3.

I only use GD on "Virtual Desktop 3" and have a windows rule forcing to only launch there.

I changed the name of virtual desktop "3" to "Goldendict".

Then, tried to launch the software and it does not launch at all. I tried uninstalling the software and re-installing it. Nothing works !

**Comment by xiaoyifang** [comment]
> I only use GD on "Virtual Desktop 3" and have a windows rule forcing to only launch there.
> 
> I changed the name of virtual desktop "3" to "Goldendict".

Seems it stop to work after you change the virtual desktop ,  sounds more likely a KDE bug.

**Comment by Memory383** [comment]
[gd_log.txt](https://github.com/xiaoyifang/goldendict-ng/files/11309650/gd_log.txt)

I will re-install Manjaro KDE (fresh install). 

I cannot live without GoldenDict ! I will let you know if the issue persists on a fresh installation of Manjaro KDE.

**Comment by Memory383** [comment]
I will close this issue because it is related mainly to KDE. If someone changes the name of a virtual desktop, GoldenDict-ng might fail to work.

**Comment by xiaoyifang** [comment]
what happens to other application which is also binded to a virutal desktop?

**Comment by Memory383** [comment]
What happens to other application which is also binded to a virtual KDE desktop?

Anki works perfectly after changing the desktop name. **Only GoldenDict fails to initialize**.

It might be a problem with GD code and KDE. I will reopen this to see if someone else can reproduce.

**Comment by ApprobationBW** [comment]
This error never happened again. It should be closed. It was probably an issue with KDE and/or Manjaro.
