### ISSUE TITLE
Html::unescape method refactor

### ISSUE THREAD

**Issue by xiaoyifang** [xiaoyifang/goldendict-ng#579]
https://github.com/xiaoyifang/goldendict-ng/blob/a82ce2a86f4f374b9b752706fe35709376b8e94e/src/dict/gls.cc#L560

~the second parameter `true` is used to strip html from the description.   As we have already support html in the description .
The second parameter can be removed. (There are also several other places in the code).~

And the second parameter can be rename to `stripHtml` to have a better and clear meaning(reverse meaning).

One more bug found here.
https://github.com/xiaoyifang/goldendict-ng/blob/367aac43bf0074b34a9b2e3372e9d5a9736aa87b/htmlescape.cc#L157-L160
![image](https://user-images.githubusercontent.com/105986/234448924-aa217ec2-bef5-4ee0-b2c6-d659a3fc10cf.png)

**Comment by shenlebantongying** [comment]
bool parameter is a known confusing thing, and sadly this codebase uses it a lot.

If we refactor this kind of code, we probably should consider those suggestions:

https://google.github.io/styleguide/cppguide.html#Function_Argument_Comments
![image](https://user-images.githubusercontent.com/20123683/234473445-57458a01-49d0-48dc-8b9a-7438804ae7a4.png)

https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#i4-make-interfaces-precisely-and-strongly-typed

![image](https://user-images.githubusercontent.com/20123683/234474267-4e993f0c-6545-4ef8-9b9a-219e75e897d8.png)



```
enum class htmlescape{
    stripHtml,
    saveFormat,
}

string unescapeUtf9(str, htmlescape::stripHtml)

or split it into two method:

unescapeUtf8(str)
unescapeUtf8WithHTMLStripped(str)
```

**Comment by xiaoyifang** [comment]
I think both `enum` and `two method` are ok.

`unescapeUtf8`  accept string ->string
`unescape` accept QString-> return QString

these two method can have the same name and overload.

**Comment by shenlebantongying** [comment]
After actually looked at the code, I think splitting into 
```
QString stripHTMLtags(str)
QString unescape(str)
```
is more elegant.

Just compose them to get original behaviors:

* `unescape(str,saveFormat=false)` -> `unescape(stripHTMLtags(str))`
* `unescape(str,saveFormat=true)` -> `unescape(str)`

**Comment by xiaoyifang** [comment]
> One more bug found here.

https://github.com/xiaoyifang/goldendict-ng/pull/585
