### ISSUE TITLE
List issues fixed in this repo while not in official repo

### ISSUE THREAD

**Issue by xiaoyifang** [xiaoyifang/goldendict-ng#587]
Note: Not updated since early 2023.

Only include the long unsolved issues which are in the official repository .

Not include new bugs been fixed 
Not include features added.

description  | issues | possible PR or commits
---------|----------|----------
Perfect Dark theme everywhere | https://github.com/goldendict/goldendict/issues/1536 https://github.com/goldendict/goldendict/issues/1142 https://github.com/goldendict/goldendict/issues/679 https://github.com/goldendict/goldendict/issues/1295 https://github.com/goldendict/goldendict/issues/1278  https://github.com/goldendict/goldendict/issues/719  | notes: https://github.com/xiaoyifang/goldendict-ng/issues/271 https://github.com/xiaoyifang/goldendict-ng/issues/339 PRs:  https://github.com/xiaoyifang/goldendict-ng/pull/272 https://github.com/xiaoyifang/goldendict-ng/pull/345
URL schema handler like `goldendict://word` | https://github.com/goldendict/goldendict/issues/735 https://github.com/goldendict/goldendict/issues/1139 https://github.com/goldendict/goldendict/issues/1139 https://github.com/goldendict/goldendict/issues/1280 https://github.com/goldendict/goldendict/pull/1632 |  https://github.com/xiaoyifang/goldendict-ng/pull/227
"Close To Tray" on macOS does not work | https://github.com/goldendict/goldendict/issues/1356 | PR: https://github.com/xiaoyifang/goldendict-ng/pull/301 notes: https://github.com/xiaoyifang/goldendict-ng/issues/300
cmake build | https://github.com/goldendict/goldendict/pull/1515 |  https://github.com/xiaoyifang/goldendict-ng/pull/218
toggle scanpopup | https://github.com/goldendict/goldendict/pull/965 | https://github.com/xiaoyifang/goldendict-ng/pull/525
forvo replacement, lingualibre | https://github.com/goldendict/goldendict/issues/1610 https://github.com/goldendict/goldendict/issues/57 | https://github.com/xiaoyifang/goldendict-ng/pull/268 design: https://github.com/xiaoyifang/goldendict-ng/issues/263
enable highdpi settings and replace the png with svg .| highdpi request https://github.com/goldendict/goldendict/issues/549 https://github.com/goldendict/goldendict/issues/531 https://github.com/goldendict/goldendict/issues/812 https://github.com/goldendict/goldendict/issues/985 https://github.com/goldendict/goldendict/issues/1327| commit history search `highdpi`
webkit issue|https://github.com/goldendict/goldendict/issues/1121 https://github.com/goldendict/goldendict/issues/1143 https://github.com/goldendict/goldendict/issues/1370 https://github.com/goldendict/goldendict/issues/795 https://github.com/goldendict/goldendict/issues/1435 https://github.com/goldendict/goldendict/issues/1565|
epwing issue|https://github.com/goldendict/goldendict/issues/1196 | reference to the content of epwing dictionary is supported
rtl bi-languages support| https://github.com/goldendict/goldendict/issues/1150| https://github.com/xiaoyifang/goldendict-ng/commit/b23e57d08cd2fbebca19a5d490db0f4d49c1f7e9
Good CLI interface with support for qt related argv like `--style fusion` | https://github.com/goldendict/goldendict/issues/1226 https://github.com/goldendict/goldendict/issues/911 https://github.com/goldendict/goldendict/issues/1623 | https://github.com/xiaoyifang/goldendict-ng/pull/452
epwing synonym|https://github.com/goldendict/goldendict/issues/1551|
website dictionary height issue|https://github.com/goldendict/goldendict/issues/1448| https://github.com/xiaoyifang/goldendict-ng/commit/349ac86d47e1e1d6174a138b837705d0da39f9f5
session collapse |https://github.com/goldendict/goldendict/issues/1630|  the implementation is a little different ,but has the essence  https://github.com/xiaoyifang/goldendict-ng/pull/488
zim parsing|https://github.com/goldendict/goldendict/issues/1472| https://github.com/xiaoyifang/goldendict-ng/commit/92e2708faef33dba35af0f52d8524af27a808280 this should also has further commits.   
epwing render|https://github.com/goldendict/goldendict/issues/1244|https://github.com/xiaoyifang/goldendict-ng/pull/617
custom font |https://github.com/goldendict/goldendict/issues/1093|![image](https://user-images.githubusercontent.com/105986/235301351-46589809-5dc8-4f2b-b924-61d6cdc09ccb.png) in the preference ,add a font to customize the dictionary font
language flag|https://github.com/goldendict/goldendict/issues/1330|https://github.com/xiaoyifang/goldendict-ng/pull/604
focus popup|https://github.com/goldendict/goldendict/issues/310|https://github.com/xiaoyifang/goldendict-ng/pull/387
fulltext performance|https://github.com/goldendict/goldendict/issues/1596 https://github.com/goldendict/goldendict/issues/1242| use xapian instead
recursive mutex lock|https://github.com/goldendict/goldendict/issues/1590| use non-recursive mutex
QTextHtmlParser warnings|https://github.com/goldendict/goldendict/issues/1578|https://github.com/xiaoyifang/goldendict-ng/commit/2263dfc8dace1c875ef739e0eddd5dd68bf1d978
import txt favorite |https://github.com/goldendict/goldendict/issues/1537|
zim issue|https://github.com/goldendict/goldendict/issues/1599 https://github.com/goldendict/goldendict/issues/1596 https://github.com/goldendict/goldendict/issues/1644| a 8GB zim will take less than one minute to finish  https://github.com/xiaoyifang/goldendict-ng/pull/725
custom metadata|https://github.com/goldendict/goldendict/issues/274|https://github.com/xiaoyifang/goldendict-ng/pull/613 https://github.com/xiaoyifang/goldendict-ng/pull/722
dsl encoding issue|https://github.com/goldendict/goldendict/issues/1203#issuecomment-539617199 https://github.com/goldendict/goldendict/issues/1388|https://github.com/xiaoyifang/goldendict-ng/pull/830

**Comment by shenlebantongying** [comment]
I will just close this to remove it from issue list. It is still pinned.
