### ISSUE TITLE
can not start immediately after quit old goldendict

### ISSUE THREAD

**Issue by xiaoyifang** [xiaoyifang/goldendict-ng#599]
**Describe the bug**

After quit the offical gd version ,this repo's goldendict can not start and will crash when starting.

**To Reproduce**
- start the official version of gd ,version 
![image](https://user-images.githubusercontent.com/105986/235047237-60065806-3c59-4c21-852f-bb0f77758ae7.png)
- when the fulltext creation is beginning , quit the gd.
- the webengine goldendict of this repo can not start and will crash

**Desktop (please complete the following information):**
 - OS: Windows
 - latest version

**Additional context**
Maybe related with singleapplication strategy.

**Comment by xiaoyifang** [comment]
![image](https://user-images.githubusercontent.com/105986/235049251-e475888b-4f07-4d1a-8067-6dd65ec9e2a4.png)
manual delete the above file can solve this issue.
Can you help to check @shenlebantongying

**Comment by shenlebantongying** [comment]
Not sure why, but it works for me normally.

https://user-images.githubusercontent.com/20123683/235053900-79f2ee1a-e4e1-4c0e-b7ce-75b870f828ba.mp4

**Comment by xiaoyifang** [comment]
In rare cases , If goldendict crashed without delete the locked file.
What will happen next time, are there any possible solution to overcome this?
Such as detect if the file really locked by an active goldendict process?

**Comment by shenlebantongying** [comment]
The lock file contains the process ID and timestamp

QLockFile will check that info to know if a happened before.

```
> cat /tmp/qtsingleapp-Golden-86bf-3e8-gdlockfile
113918
goldendict
archlinux
083be8a9490344d18100ce38ac518364
b5bbc14d-5621-43ae-a4d8-83c0c965222d
```

https://doc.qt.io/qt-6/qlockfile.html#details

> If the process holding the lock crashes, the lock file stays on disk and can prevent any other process from accessing the shared resource, ever. For this reason, QLockFile tries to detect such a "stale" lock file, based on the process ID written into the file. To cover the situation that the process ID got reused meanwhile, the current process name is compared to the name of the process that corresponds to the process ID from the lock file. If the process names differ, the lock file is considered stale. Additionally, the last modification time of the lock file (30s by default, for the use case of a short-lived operation) is taken into account. If the lock file is found to be stale, it will be deleted.

**Comment by xiaoyifang** [comment]
> 30s by default,

We use    ` lockFile->setStaleLockTime(0);`,so this default behavior is not guarranted.

From the description above, as we use different lockfile name , so theoretically ,gd-ng should not conflict with gd.

**Comment by shenlebantongying** [comment]
I tested with 

```
kill --signal SIGILL ${GD's pid}
```

and manually created illegal access to simulate a crash.

And the lock file is ok in both cases

**Comment by xiaoyifang** [comment]
Ok,  then this issue will put into further investigation.

After issue #578

**Comment by xiaoyifang** [comment]
I think `Socket name ` maybe also need to  be changed .  
In this case , I guess the process is likey this:

1. quit the old goldendict,  
1. the qlocalserver failed to close the connection on socketname.
3. start the new goldendict ,
4. receive message `bringtofront`
5. failed ,because no application is running.

**Comment by xiaoyifang** [comment]
https://github.com/xiaoyifang/goldendict-ng/pull/653 can somehow solve this issue.

A little defect .   Goldendict-ng has to start two times before it can successful launched
