### ISSUE TITLE
schedule to remove default fulltext creation logic and only keep xapian

### ISSUE THREAD

**Issue by xiaoyifang** [xiaoyifang/goldendict-ng#616]
**Is your feature request related to a problem? Please describe.**
I'd like this to be happen after libzim is imported instead of use the self-implemented parsing of zim dictionary.

By that time, we can skip zim's fulltext creation if zim has already built-with fulltext .This will save a lot of time and disk space.

**Describe the solution you'd like**

https://github.com/xiaoyifang/goldendict-ng/releases/tag/v23.05.01-WuYi.230501.6c8b0c1c
will be the last release version to support both xapian fulltext and origianl fulltext.
From this release on ,  the original fulltext creation logic will be removed .

**Comment by shenlebantongying** [comment]
I have turned on xapian for aur, and the binary size increased only `0.13Mib` with the new toml.hpp.

![image](https://user-images.githubusercontent.com/20123683/235303947-f6a9740d-79a5-4cc3-a758-c3a83b4741a9.png)

**Comment by xiaoyifang** [comment]
https://github.com/xiaoyifang/goldendict-ng/releases/tag/v23.05.01-WuYi.230501.6c8b0c1c
will be the last release version to support both xapian fulltext and origianl fulltext.
From this release on ,  the original fulltext creation logic will be removed .
