### ISSUE TITLE
add a `how to` about the method to  contribute to the international translation 

### ISSUE THREAD

**Issue by xiaoyifang** [xiaoyifang/goldendict-ng#619]
We can just add a link on README.md and a short description. 

Someone will translate them. 

https://github.com/transmission/transmission/blob/main/docs/Translating.md

![image](https://user-images.githubusercontent.com/20123683/233039483-e2f0a7df-6b75-45f5-8d86-6f375cc4c18c.png)

_Originally posted by @shenlebantongying in https://github.com/xiaoyifang/goldendict-ng/issues/530#issuecomment-1514457654_

**Comment by xiaoyifang** [comment]
Is this issue has been solved?
This is a document about translation process.

**Comment by shenlebantongying** [comment]
I don't feel it is needed, just click the crowdin and click the language, then follow the lead of crowdin. For translators, the interface is pretty simple.

**Comment by xiaoyifang** [comment]
ok. this can do
