### ISSUE TITLE
Some dictionaries have the problem of cutting off half a letter on the left

### ISSUE THREAD

**Issue by ffffffff01** [xiaoyifang/goldendict-ng#646]
大佬您好，发现一个问题。如图，版本是最新的wuyi版for Windows，有一部分词典无法完全显示，左边被切掉半个字母。

![image](https://user-images.githubusercontent.com/105986/236137491-8df8efb3-f239-495a-9930-1b6acd5aee46.png)

**Comment by xiaoyifang** [comment]
只有这个版本有问题吗，之前的版本是否正常。  会是词典本身的css的问题吗？

**Comment by ffffffff01** [comment]
> 只有这个版本有问题吗，之前的版本是否正常。 会是词典本身的css的问题吗？
> 
> 保存成html，然后浏览器打开看下。

谢谢回复。

1. 我之前一直用很老版本的goldendict, 没有问题。
2. 我一共用了10本左右词典，其中有2-3本在wuyi版中出现最左边被切掉一点的问题。所以并不是所有的词典都有问题。
3. 我保存为html, 用浏览器打开，没有问题，截图在下面。可以看到这本词典左边紧贴，在这种情况下好像就会被切掉。
![goldendict2](https://user-images.githubusercontent.com/83349722/236211630-ba53a8d4-0868-44e5-a8e7-5c73b0753a75.png)

**Comment by xiaoyifang** [comment]
软件没有特别处理，比较像是词典的自定义样式造成的。

有没有自定义过样式之类的。
另外单独分组这个词典也是同样的问题吗。

**Comment by xiaoyifang** [comment]
能共享下词典看下吗  可以私发我

**Comment by ffffffff01** [comment]
> 
没问题，我已经打包分享。谢谢！
链接: https://pan.baidu.com/s/1AXGhdv3ONkMKOJhOeU1_kw 
提取码: ncdk

**Comment by xiaoyifang** [comment]
收到了。

**Comment by xiaoyifang** [comment]
![image](https://user-images.githubusercontent.com/105986/236603200-eea476c3-3777-4403-ba87-0b44034fe854.png)

**Comment by xiaoyifang** [comment]
另外与  content-visibility  也有一定的关系，后续看下如何处理。

**Comment by ffffffff01** [comment]
> ![image](https://user-images.githubusercontent.com/105986/236603200-eea476c3-3777-4403-ba87-0b44034fe854.png)

去掉后 问题解决 多谢大佬！

**Comment by xiaoyifang** [comment]
后续的新发布的版本中也可以尝试用现代模式的样式尝试下。
![image](https://user-images.githubusercontent.com/105986/236671508-47bc959b-b524-445d-b180-f7f5057090e9.png)

**Comment by ffffffff01** [comment]
> 后续的新发布的版本中也可以尝试用现代模式的样式尝试下。 ![image](https://user-images.githubusercontent.com/105986/236671508-47bc959b-b524-445d-b180-f7f5057090e9.png)

好的，等新版本发布后试试！Thank you!

**Comment by xiaoyifang** [comment]
![image](https://user-images.githubusercontent.com/105986/236717803-71de8fa0-d174-441e-8c91-5078946b5e13.png)
现代样式下的例子
https://github.com/xiaoyifang/goldendict-ng/releases/tag/v23.05.03-alpha.230507.d8ec2b5d

**Comment by ffffffff01** [comment]
> ![image](https://user-images.githubusercontent.com/105986/236717803-71de8fa0-d174-441e-8c91-5078946b5e13.png) 现代样式下的样子 https://github.com/xiaoyifang/goldendict-ng/releases/tag/v23.05.03-alpha.230507.d8ec2b5d

嗯嗯，试了这个版本+现代样式，不改css也没问题了
