### ISSUE TITLE
Regression:  failure to load a website (Leipzig Corpora)

### ISSUE THREAD

**Issue by Memory383** [xiaoyifang/goldendict-ng#649]
**Describe the bug**
After an update in the last 2-3 weeks, a website stopped working correctly. It was working correctly during several months.

**To Reproduce**
1= Add the following dictionary in GD:
https://corpora.uni-leipzig.de/de/res?corpusId=deu_news_2022&word=%GDWORD%

2. Compare the results in GoldenDict with the website using the web browser:
https://corpora.uni-leipzig.de/de/res?corpusId=deu_news_2022&word

Example words in German:
**Arbeit**
**arbeiten**

**Expected behavior**
The results should be the same on GD and Browser.

**Screenshots**
![image](https://user-images.githubusercontent.com/121114125/236321509-f8312644-cd7d-485c-8e7d-6357624ed2a0.png)

**Desktop (please complete the following information):**
 - OS: Manjaro Linux Unstable
![image](https://user-images.githubusercontent.com/121114125/236330052-ce4eccfc-27c8-4940-992f-26095e1077c4.png)
 - Browser: Firefox
 
 Goldendict 23.04.03-alpha.6bbb4d99 on Sun Apr 30 11:23:59 2023
manjaro linux 6.1.27-2-MANJARO Qt 6.5.0 x86_64-little_endian-lp64
GCC 12.2.1 20230201
Flags: USE_XAPIAN  MAKE_ZIM_SUPPORT MAKE_CHINESE_CONVERSION_SUPPORT

**Comment by xiaoyifang** [comment]
the website on goldendict can not always have the same result as browser due to website's cors policy.
