### ISSUE TITLE
Dark mode follow the system's

### ISSUE THREAD

**Issue by courrier1** [xiaoyifang/goldendict-ng#687]
Make an option for the app to follow Windows' dark mode, it's a little bothersome to manually switch every time the dark/light mode is on.

**Comment by courrier1** [comment]
bump

**Comment by loyukfai** [comment]
Ditto

**Comment by xuangeyouneihan** [comment]
So will this be added to the software?

**Comment by xuangeyouneihan** [comment]
bump

**Comment by shenlebantongying** [comment]
Duplicate of https://github.com/xiaoyifang/goldendict-ng/issues/1561
