### ISSUE TITLE
Letter "f" to Beta Letter

### ISSUE THREAD

**Issue by Ducanh210** [xiaoyifang/goldendict-ng#692]
Hi guys. There is a bug which convert the letter "f" to Beta letter like the image below. Please help me to fix this, very tks. 
![image_2023-05-15_192311295](https://github.com/xiaoyifang/goldendict-ng/assets/108744075/4e31f95f-6c7d-4810-a790-dc7da6b7dfab)
![2023-05-15](https://github.com/xiaoyifang/goldendict-ng/assets/108744075/fbeeab74-b32a-44ed-9f01-b65cba718aa1)

**Comment by xiaoyifang** [comment]
I can not input that letter ,can you paste the word here?
Have you enabled some transliteration?

**Comment by Ducanh210** [comment]
ϐinancial and financial 
About transliteration, I just download the installer, then install and use like normal.

**Comment by Ducanh210** [comment]
Oh, if the word start with uppercase F, like Financial, it still work. However, when the word start with f like financial, it comes to ϐinancial.

**Comment by xiaoyifang** [comment]
can not reproduce the issue.

**Comment by Ducanh210** [comment]
I'm sad to hear that. Anyway, tks for your pork. My laptop has 4k resolution and you has saved me with this version.

**Comment by xiaoyifang** [comment]
you can copy the `financial` in the pdf and paste it to other text editor and check the result.
Is it still `financial `?

**Comment by xiaoyifang** [comment]
then I think it is a issue of pdf

**Comment by Ducanh210** [comment]
Like you said, the problem is the pdf file. I have just downloaded adobe pdf reader. This time when I double click the word "financial", only "inancial" is in black. I tried to take all the word but then I could not paste it anywhere or use popup window.

**Comment by Ducanh210** [comment]
Tks for your support. Really love your fork. Wish you the best.
