### ISSUE TITLE
Regarding the naming standards of tags/installer/zip names

### ISSUE THREAD

**Issue by hu3rror** [xiaoyifang/goldendict-ng#701]
Hello,

I wanna make a manifest for goldendict-ng to [Scoop](https://scoop.sh/).

[Scoop ](https://scoop.sh/)is a package manager software for Windows that can implement downloading and installing various repositories in a workflow. But because the current binary installation packages of goldendict-ng are not unified in naming, I have to use complex and unstable regular expressions to match the binary download name, which makes maintenance very difficult.

Therefore I have a suggestion, I hope the tags and file names can be as unified as possible.

For example, releases tags can consider using `v23.05.01-20230501` directly, that is, `version number+date`, instead of `GoldenDict-ng-v23.05.01-WuYi.230501.6c8b0c1c`. In this way, I can match the latest version update more accurately when using Scoop for version checking.

Secondly, the `6.4.3-GoldenDict.exe_windows-2022_20230501.zip` file, after unzipping the root directory is a folder named `GoldenDict-Windows.6c8b0c1c-045928`. I hope this folder name can be simpler, for example `GoldenDict-Windows`. This can avoid `6c8b0c1c-045928` like useless word groups, and can better implement the process of uncompressing.

What do you think about this? 😊

**Comment by xiaoyifang** [comment]
> `v23.05.01-20230501`

this is not sufficient,  sometimes  I have to make several tag and release in a day.   what about `v23.05.01-WuYi.230501.6c8b0c1c`?

> Secondly, the 6.4.3-GoldenDict.exe_windows-2022_20230501.zip file, after unzipping the root directory is a folder named GoldenDict-Windows.6c8b0c1c-045928. I hope this folder name can be simpler, for example GoldenDict-Windows. 


I'll check about this, do you only care about the Windows package name?

**Comment by xiaoyifang** [comment]
currently 
`GoldenDict-ng-v23.05.01-WuYi.230501.6c8b0c1c`  is release name
`v23.05.01-WuYi.230501.6c8b0c1c` is tagname

**Comment by xiaoyifang** [comment]
`https://github.com/xiaoyifang/goldendict-ng/releases/download/v23.05.01-WuYi.230501.6c8b0c1c/6.4.3-GoldenDict-ng-v23.05.01-WuYi-Installer.exe`

what about this 
```
https://github.com/xiaoyifang/goldendict-ng/releases/download/v23.05.01-WuYi.230501.6c8b0c1c/6.4.3-GoldenDict-ng-Installer.exe
```
