### ISSUE TITLE
Hitting the download button when prompted for an update doesn't help.

### ISSUE THREAD

**Issue by 12vpn** [xiaoyifang/goldendict-ng#718]
Goldendict会提示更新，但是我点击下载按钮时什么也没有发生，还是需要到Github上手动下载更新。
Goldendict版本：
Goldendict 
windows winnt 10.0.22624 Qt 6.4.3 x86_64-little_endian-llp64
Visual C++ Compiler: 192930148
Flags: USE_XAPIAN  MAKE_ZIM_SUPPORT USE_ICONV MAKE_CHINESE_CONVERSION_SUPPORT
Windows版本：
Windows 11 Pro 22H2

**Comment by xiaoyifang** [comment]
点击下载的时候，应该会打开下载页面。是需要自己下载。
