### ISSUE TITLE
The entire chain of "Input Phase" is because when using clipboard, the word's ending punctunation will be automatically removed.

### ISSUE THREAD

**Issue by shenlebantongying** [xiaoyifang/goldendict-ng#726]
This is confusing since last year when I check out the code for the first time. Sometimes, the `InputPhase` got used, and sometimes just pass the `word`.

The `ArticleView` has 3 versions of `showDefination` which will propagate to mainwindow/scanpopup which also have 3 versions of `showTranslationFor`

![image](https://github.com/xiaoyifang/goldendict-ng/assets/20123683/ffd05c97-2580-4378-bcd4-a20202460f1b)

(Unrelated but there is something amazing here:

* The `struct inputPhase` is in `Config`
* The `sanitizeInputPhrase()` is in `Preferences`

Mainly because of laziness. "I have no idea where to put this, so I just put it under `Config`".)

---

The "inputPhase" is invented because `Preferences::sanitizeInputPhrase` (why the hell `sanitizeInputPhrase` is under `Preferences` :sweat_smile:) calls `trimWhitespaceOrPunct` which removes Punct at the word end.

Then you get this weird thing: the User selected `Assoc.` and becomes `Assoc` in the translate box, then the article shows both `Assoc.` and `Assoc`.

The amazing `struct inputPhase` is just a pair with `Word without Punct` and `Punct that got removed`.

![image](https://github.com/xiaoyifang/goldendict-ng/assets/20123683/90393a9b-e5ab-4832-87bc-3f1c8302fe42)

---

The PR that invents "inputphase" https://github.com/goldendict/goldendict/pull/1389/files 

The problem that the PR tries to cover (not fix) https://github.com/goldendict/goldendict/issues/1350

A similar problem that PR tries https://github.com/goldendict/goldendict/issues/1375

**Comment by xiaoyifang** [comment]
> Then you get this weird thing: the User selected `Assoc.` and becomes `Assoc` in the translate box, then the article shows both `Assoc.` and `Assoc`.

![image](https://github.com/xiaoyifang/goldendict-ng/assets/105986/665bbe89-a812-47fb-ae36-b4bb668287b2)

**Comment by shenlebantongying** [comment]
A funny result:

Because of the invention of "InputPhase", he doesn't know what to pass.

So he passed an "InputPhase" plus an empty string :sweat_smile: 

![image](https://github.com/xiaoyifang/goldendict-ng/assets/20123683/0ce95db8-765a-4822-92e8-4c9aff728939)

![image](https://github.com/xiaoyifang/goldendict-ng/assets/20123683/c159b6ec-8890-4503-8941-0cf492838c4a)

**Comment by xiaoyifang** [comment]
I also do not like so much versions of showdefinition ,  maybe later can find a way to refactor them.

**Comment by shenlebantongying** [comment]
> Does the result has something to do with this

I think they are unrelated. I don't enable it.

---

The "InputPhase" seems mostly used with clipboard changing. But the abstraction is leaky. In a few places, the `InputPhrase::fromPhase` is used, but it is just `word` plus an `empty string`, they are probably unnecessary.

---

Possible alternatives:

1.) Stop being too smart, don't trim punct automatically. (The new `ignore punct when searching` seems better).
2.) Unify the "showDefinition" and get rid of `inputPhase`. Always pass the `word` as the only source of truth that the user typed or copied. Then only check the existence of punct right before querying the word. If punct exists, then show the results from both with and without punct (the current behaviour, but simpler. Also the translateBox won't show trimed word which might be confusing).
