### ISSUE TITLE
rpm packaging

### ISSUE THREAD

**Issue by shenlebantongying** [xiaoyifang/goldendict-ng#729]
Sample RPM to build with qmake/qt5 + qmake/qt6: https://build.opensuse.org/package/view_file/Education/goldendict-ng/goldendict-ng.spec

Help wanted.

**Comment by topazus** [comment]
@shenlebantongying Hello, I am interested in packaging this into Fedora. Actually, I have made the [tomlplusplus dependency](https://src.fedoraproject.org/rpms/tomlplusplus) into fedora not logn ago. There are some third-party libraries that should be avoided, using the corresponding system dependencies is suggested. Maybe, we can add options (OFF by default), like`USE_SYSTEM_FMT` and `USE_SYSTEM_TOMLPLUSPLUS` or others, to enable or disable the possibility of building against these dependecies.
For toml++, 
https://github.com/xiaoyifang/goldendict-ng/blob/4b8c87a30db920646ca80728b6b2c0ab790168d1/src/metadata.cc#L1-L4
```bash
❯ rpm -ql tomlplusplus-devel 
/usr/include/toml++
/usr/include/toml++/impl
/usr/include/toml++/impl/array.h
/usr/include/toml++/impl/array.inl
/usr/include/toml++/impl/at_path.h
/usr/include/toml++/impl/at_path.inl
/usr/include/toml++/impl/date_time.h
/usr/include/toml++/impl/formatter.h
/usr/include/toml++/impl/formatter.inl
/usr/include/toml++/impl/forward_declarations.h
/usr/include/toml++/impl/header_end.h
/usr/include/toml++/impl/header_start.h
/usr/include/toml++/impl/json_formatter.h
/usr/include/toml++/impl/json_formatter.inl
/usr/include/toml++/impl/key.h
/usr/include/toml++/impl/make_node.h
/usr/include/toml++/impl/node.h
/usr/include/toml++/impl/node.inl
/usr/include/toml++/impl/node_view.h
/usr/include/toml++/impl/parse_error.h
/usr/include/toml++/impl/parse_result.h
/usr/include/toml++/impl/parser.h
/usr/include/toml++/impl/parser.inl
/usr/include/toml++/impl/path.h
/usr/include/toml++/impl/path.inl
/usr/include/toml++/impl/preprocessor.h
/usr/include/toml++/impl/print_to_stream.h
/usr/include/toml++/impl/print_to_stream.inl
/usr/include/toml++/impl/simd.h
/usr/include/toml++/impl/source_region.h
/usr/include/toml++/impl/std_except.h
/usr/include/toml++/impl/std_initializer_list.h
/usr/include/toml++/impl/std_map.h
/usr/include/toml++/impl/std_new.h
/usr/include/toml++/impl/std_optional.h
/usr/include/toml++/impl/std_string.h
/usr/include/toml++/impl/std_string.inl
/usr/include/toml++/impl/std_utility.h
/usr/include/toml++/impl/std_variant.h
/usr/include/toml++/impl/std_vector.h
/usr/include/toml++/impl/table.h
/usr/include/toml++/impl/table.inl
/usr/include/toml++/impl/toml_formatter.h
/usr/include/toml++/impl/toml_formatter.inl
/usr/include/toml++/impl/unicode.h
/usr/include/toml++/impl/unicode.inl
/usr/include/toml++/impl/unicode_autogenerated.h
/usr/include/toml++/impl/value.h
/usr/include/toml++/impl/version.h
/usr/include/toml++/impl/yaml_formatter.h
/usr/include/toml++/impl/yaml_formatter.inl
/usr/include/toml++/toml.h
/usr/lib64/cmake/tomlplusplus
/usr/lib64/cmake/tomlplusplus/tomlplusplusConfig.cmake
/usr/lib64/cmake/tomlplusplus/tomlplusplusConfigVersion.cmake
/usr/lib64/libtomlplusplus.so
/usr/lib64/pkgconfig/tomlplusplus.pc
``` 

It seemed that qtsingleapplication is also one of the dependencies.The similar dependencies also have been packaged for fedora, but they are built against qt4 or qt5.

ref: https://packages.fedoraproject.org/pkgs/qtsingleapplication/
https://packages.fedoraproject.org/pkgs/tomlplusplus/
https://docs.fedoraproject.org/en-US/packaging-guidelines/#bundling

**Comment by shenlebantongying** [comment]
I can add an option to use system toml.

The qtsingleapplication cannot.

**Comment by topazus** [comment]
Okay, I could mark the qtsingleapplication lib as bundled dependency. So, what do you think of the fmt library, I see the fmt lib has been updated to 10.0.0, in this #717 . But I have tried goldendict-ng with system fmt lib of 9.1.0 version, it could build and work. And, what about [simple-eb](https://github.com/xiaoyifang/simple-eb)?

**Comment by shenlebantongying** [comment]
> And, what about [simple-eb](https://github.com/xiaoyifang/simple-eb)?

@xiaoyifang knows more about eb.

Right now, the simple-eb is used only for windows build.

On linux, https://packages.fedoraproject.org/pkgs/eb/ is used.

**Comment by xiaoyifang** [comment]
when packaging rpm , will qmake be used or cmake?

**Comment by shenlebantongying** [comment]
qmake?

Before the next qt release at the end of this year, we can use qmake at the moment?

---

@topazus Can you try the `CONFIG+=use_system_toml CONFIG+=use_system_fmt` in the PR works on fedora?

**Comment by topazus** [comment]
> when packaging rpm , will qmake be used or cmake?

I would prefer cmake.

**Comment by shenlebantongying** [comment]
Then I will double-check the CMake build, and ship it to Fedora as first official CMake build :)

**Comment by topazus** [comment]
I have a question about the github tags. The curent tag names, like https://github.com/xiaoyifang/goldendict-ng/releases/tag/v23.06.01-ChildrenDay.230531.e771a65f , is too long and not standard. Could you set it to normal versioning, like v1.0.0, or just v23.06.01 when the new release is published later?

**Comment by shenlebantongying** [comment]
The CMake build uses simple-eb (aka /thirdparty/eb/).

**Comment by shenlebantongying** [comment]
I think the CMake build is ready to use.

The flags are different, but by default, all features will be turned on. 

The PR added `-DUSE_SYSTEM_FMT=ON -DUSE_SYSTEM_TOML=ON` to use the system's fmt & toml.

---

The CMake build uses simple-eb (aka `/thirdparty/eb/`)

**Comment by shenlebantongying** [comment]
@xiaoyifang I think we should just use `simple-eb` as a static library.

Separately packing a library and installing a `.so` file that only we use is a major pain.

**Comment by shenlebantongying** [comment]
@topazus We can use CMake. Defaults options will enable all features.

Add those options `-DUSE_SYSTEM_FMT=ON -DUSE_SYSTEM_TOML=ON` to use system fmt & toml.

the `theirdparty/eb` is not used at all. https://packages.fedoraproject.org/pkgs/eb/ is needed.

**Comment by xiaoyifang** [comment]
a new release package and tag have been made.
https://github.com/xiaoyifang/goldendict-ng/releases/tag/v23.06.01

**Comment by aaly11** [comment]
Привет. Интерфейс программы при сборке её с помощью _cmake_ остаётся не локализованным, не смотря на то, что файлы локализации установлены. Вопрос, почему?
[Ссылка](https://build.opensuse.org/package/show/home:AndnoVember:LXQt:Qt6/goldendict-ng) на проект из Open Build Service.
Для 15.5 программа собрана с помощью **qmake** (есть ограничение на версию cmake >= 3.25).
Для openSUSE Tumbleweed с помощью **cmake**.
Также были собраны библиотеки [libzim](https://build.opensuse.org/package/show/home:AndnoVember:LXQt:Qt6/libzim) и [tomlplusplus](https://build.opensuse.org/package/show/home:AndnoVember:LXQt:Qt6/tomlplusplus).

**Comment by shenlebantongying** [comment]
@aaly11

I think the `%dir` only includes the folder and not the content. Due to the `%dir`, the -lang package generated is empty.
 
http://ftp.rpm.org/max-rpm/s1-rpm-inside-files-list-directives.html#S3-RPM-INSIDE-DIR-DIRECTIVE

![image](https://github.com/xiaoyifang/goldendict-ng/assets/20123683/7b5478d9-cf8b-4108-a639-0f21c3c43b15)

**Comment by shenlebantongying** [comment]
@aaly11 I can confirm that it is a CMake build bug. It appears that all generated .qm files are not getting recognized.

Something wrong around here: https://github.com/xiaoyifang/goldendict-ng/blob/87e20912147fe660d458568d3bccbea6836545db/CMakeLists.txt#L167-L176

**Comment by shenlebantongying** [comment]
The root problem is that `QCoreApplication::applicationDirPath()` is not giving `/usr/share/goldendict` in cmake build.

**Comment by topazus** [comment]
Sorry for the a bit late response. There are several issues about goldendict-ng Fedora packaging.

1.
> If the conflict could be avoided (i.e. by renaming the binary and data directories) that would be preferred. This would support a scenario in which a user may decide to install both variants of the package.
That would fulfill the "As a general rule, Fedora packages must NOT contain any usage of the Conflicts: field." part of the packaging guidelines.

2.
> goldendict-ng.x86_64: W: unused-direct-shlib-dependency /usr/bin/goldendict /lib64/libfmt.so.9

Ref: https://bugzilla.redhat.com/show_bug.cgi?id=2213078#c7

**Comment by shenlebantongying** [comment]
1. Not changing binary name & resource name has a few benefits :)

https://github.com/xiaoyifang/goldendict-ng/issues/690

**Comment by shenlebantongying** [comment]
The problem now is that the upstream reviewer appears to be missing for some reason.

I don't think further actions need to be done on our side.

**Comment by shenlebantongying** [comment]
My wording was bad. The document says RPATH will be cleared when doing `cmake install`, but this is not what we observed, which looks like "`cmake install` will add this RPATH to the binary."

https://gitlab.kitware.com/cmake/community/-/wikis/doc/cmake/RPATH-handling#default-rpath-settings

> By default if you don't change any RPATH related settings, CMake will
link the executables and shared libraries with full RPATH to all used
libraries in the build tree. When installing, it will clear the RPATH of
these targets so they are installed with an empty RPATH.

---

My current suspicion is `qt_standard_project_setup`, which modifies a few rpath-related things. It overrides the default behaviour.

https://github.com/xiaoyifang/goldendict-ng/blob/b6420c87f7c6aa23a9aad2cf44800568862d0107/CMakeLists.txt#L51

Not sure why would Qt do that. Linux distros clearly against it https://fedoraproject.org/wiki/Changes/Broken_RPATH_will_fail_rpmbuild

https://doc.qt.io/qt-6/qt-standard-project-setup.html
>  On platforms that support RPATH (other than Apple platforms), two values are appended to the CMAKE_INSTALL_RPATH variable by this command. $ORIGIN is appended so that libraries will find other libraries they depend on in the same directory as themselves. $ORIGIN/<reldir> is also appended, where <reldir> is the relative path from CMAKE_INSTALL_BINDIR to CMAKE_INSTALL_LIBDIR.

---

I think we can avoid qt_standard_project_setup for now.

**Comment by topazus** [comment]
@shenlebantongying Thanks for the explanation on this, I will set `-DCMAKE_SKIP_RPATH=ON` to deal with the rpath issue at the moment. Btw, The goldendict-ng package will be available in Fedora. https://src.fedoraproject.org/rpms/goldendict-ng
