### ISSUE TITLE
Longman DOCE 5th Ed(En-En) dictionary, example sentences are blank

### ISSUE THREAD

**Issue by binglius** [xiaoyifang/goldendict-ng#733]
**描述 bug**

**复现 bug 的步骤**
 用词典 'Longman DOCE 5th Ed(En-En)' 查询任何单词，例句显示空白。

**受影响的词典**
如果某本词典有问题，列出词典的名称和类型。
Longman DOCE 5th Ed(En-En)

如果有可能，上传词典的文件或提供下载的链接。（GitHub 可以上传 25MiB 以下的 zip 文件）
太大，无法上传。

**期望的结果**
如果没有 bug，期望的结果是什么。
以前的旧版本没有问题。

**相关的截图**
![image](https://github.com/xiaoyifang/goldendict-ng/assets/115341131/ba3e5086-6a20-4ddc-99c9-4e6cb9aad5ad)

**系统和软件的版本**

复制 & 粘贴 `帮助` -> `关于` -> `复制版本信息` 到这里

- OS: Gentoo
- Version Latest

**额外的信息**

**Comment by shenlebantongying** [comment]
有几本 DSL 格式的字典的例句是 “optional part”，可以点击那个加号，或者 从 advanced -> expand optional part

![image](https://github.com/xiaoyifang/goldendict-ng/assets/20123683/c39736f9-e3b7-4a8f-a90c-d797627a3b57)

**Comment by binglius** [comment]
谢谢，原来是新特性，刚下了个 LDOCE6, 好像 mdx 词典也有类似的问题，启用这个选项就可以了。

但是还有个问题，好像最新版本（可能好久以前的版本就这样了，我有段时间没更新了），从托盘点击 Goldendict 白屏，右键点show main window　就没有问题。

![image](https://github.com/xiaoyifang/goldendict-ng/assets/115341131/729023f3-be22-453e-b7b7-0f5e613b6415)

**Comment by shenlebantongying** [comment]
> 原来是新特性

不算是新特性，十年前就有了，只是几乎没有词典用而已。

> 但是还有个问题，好像最新版本（可能好久以前的版本就这样了，我有段时间没更新了），从托盘点击 Goldendict 白屏，右键点show main window　就没有问题。

在 xfce 下复现不出来，你先升级一下把，

![Peek 2023-05-21 05-03](https://github.com/xiaoyifang/goldendict-ng/assets/20123683/042d92c1-dc22-4f32-be8a-afe914380bbd)

**Comment by binglius** [comment]
已经是最新版本了，我再看看。这个影响也不大。

**Comment by binglius** [comment]
问题解决了，应该是配置和以前的不兼容了（我的配置目录可能有好多年了），删掉配置目录重新配置一下就可以了。
