### ISSUE TITLE
Latest favorites get added to the top of the Favorites section.

### ISSUE THREAD

**Issue by BEST8OY** [xiaoyifang/goldendict-ng#742]
**Is your feature request related to a problem? Please describe.**
UX wise new favorites are better to get added to the top not to the bottom.

**Comment by xiaoyifang** [comment]
Are there some standards about this?

**Comment by BEST8OY** [comment]
Well not a standard but I think if you see your recent favorites on top it's better than scrolling to bottom every time (on GD relaunching)
And I think it's better for learning new words if you see your recent favorites on the top because sometime you just forget to scroll down to the bottom.

**Comment by xiaoyifang** [comment]
This is a designed behavior .Close for now .
Can be reopened when have a more clear solution.
