### ISSUE TITLE
Can you support macOS offline dictionary? 

### ISSUE THREAD

**Issue by arpir** [xiaoyifang/goldendict-ng#763]
Apple OSX's built-in Dictionary (.dictionary dirs), OSX system carries the authority and high quality of the dictionary, no doubt about it.

**Comment by arpir** [comment]
https://vercel.autoptr.top/gdocr/wiki/GoldenDict-Supported-Dictionary-Formats/,like this versions.

**Comment by xiaoyifang** [comment]
not in plan right now.

**Comment by shenlebantongying** [comment]
You can just use pyglossary to convert form "Apple binary" to any HTML based formats like slob2

https://github.com/ilius/pyglossary

Just copy file out from
```
/System/Library/AssetsV2/com_apple_MobileAsset_DictionaryServices_dictionaryOSX/8cb788a59ce1dee551adf0e18b07d9bd29d377cd.asset/AssetData/Oxford American Writer's Thesaurus.dictionary
```
To somewhere else, then
```
pyglossary folder_of_your_choice/the_dict_file_that_you_copied.dictionary a_output_name_you_want --read-format=AppleDictBin --write-format=Aard2Slob
```

(and fix every errors)

The apple's "new oxford dictionary" that I converted to slob https://pixeldrain.com/u/7RtvbShq (file will be gone after 60 days)

<img width="1356" alt="Screenshot 2023-05-30 at 3 24 47 AM" src="https://github.com/xiaoyifang/goldendict-ng/assets/20123683/52c91727-2725-41e5-9671-743d1d5fdc42">

**Comment by arpir** [comment]
> 您可以使用 pyglossary 将「Apple binary」转换为任何基于 HTML 的格式，例如 slob2
> 
> https://github.com/ilius/pyglossary
> 
> 只需`.dictionary`从中复制文件
> 
> ```
> /System/Library/AssetsV2/com_apple_MobileAsset_DictionaryServices_dictionaryOSX/8cb788a59ce1dee551adf0e18b07d9bd29d377cd.asset/AssetData/Oxford American Writer's Thesaurus.dictionary
> ```
> 
> 那就去别的地方
> 
> ```
> pyglossary folder_of_your_choice/the_dict_file_that_you_copied.dictionary a_output_name_you_want --read-format=AppleDictBin --write-format=Aard2Slob
> ```
> 
> （并修复所有错误）
> 
> 示例：从 Apple 的「新牛津词典」转换而来的 slob dict：
> 
> https://pixeldrain.com/u/7RtvbShq（文件将在 60 天后消失）
> 
> <img alt="屏幕截图 2023-05-30 3 24 47 AM" width="1356" src="https://user-images.githubusercontent.com/20123683/241880175-52c91727-2725-41e5-9671-743d1d5fdc42.png">
 
Thank you very much, I think this worked for me.
