### ISSUE TITLE
translatebox's dropdown doesn't show if the toolbar is floating

### ISSUE THREAD

**Issue by shenlebantongying** [xiaoyifang/goldendict-ng#771]
**Describe the bug**

Edge case bug:

![image](https://github.com/xiaoyifang/goldendict-ng/assets/20123683/6c713eba-2e38-4204-8959-9f64ffceb909)

**To Reproduce**
1. Drag the toolbar out
2. Type a word
3. The dropdown exists but with wrong geometry

**Context**

Original GD's bug? the geometry calculation is wrong when dragged out.

https://github.com/goldendict/goldendict/blob/dea2f7cb65aa4205c1f5c4648b1d0c1ad9cf20eb/translatebox.cc#L287

**Comment by xiaoyifang** [comment]
I think it can be rewrite with https://doc.qt.io/qt-5/qcompleter.html#details

**Comment by xiaoyifang** [comment]
Which platform? Have not reproduced this on Windows.

**Comment by shenlebantongying** [comment]
On Linux, both X11 & Wayland.
