### ISSUE TITLE
undefined reference to symbol 'soxr_process'

### ISSUE THREAD

**Issue by Fahad-Alsaidi** [xiaoyifang/goldendict-ng#777]
**Describe the bug**
when I try to compile goldendict-ng I got an error in linking stage says:
```
 linking goldendict
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/11/../../../x86_64-linux-gnu/libswresample.a(soxr_resample.o): undefined reference to symbol 'soxr_process'
/usr/bin/ld: /usr/lib/x86_64-linux-gnu/libsoxr.so.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make: *** [Makefile:811: goldendict] Error 1
```
my system details:
Operating System: KDE neon 5.27
KDE Plasma Version: 5.27.4
KDE Frameworks Version: 5.105.0
Qt Version: 5.15.9
Kernel Version: 5.19.0-41-generic (64-bit)
Graphics Platform: X11

is this a bug or my system is broken somehow?

**Comment by shenlebantongying** [comment]
I think `KDE neon 5.27` is based on Ubuntu 22.04, and the CI is using `ubuntu-latest` which is also ubuntu 22.04 

https://github.com/xiaoyifang/goldendict-ng/blob/3ffdbe007995027e0f68d5b218b89b0368e29877/.github/workflows/ubuntu-PR-check.yml#L28

Not sure why it doesn't work on your machine.

You can disable ffmpeg if you don't need pronunciation via ffmpeg "CONFIG+=no_ffmpeg_player"

**Comment by Fahad-Alsaidi** [comment]
@shenlebantongying Thanks for the hint. I disabled ffmpeg_player and it works fine.

**Comment by xiaoyifang** [comment]
intall `libsoxr`?
