### ISSUE TITLE
scroll bar keeps jumping up & down

### ISSUE THREAD

**Issue by Fahad-Alsaidi** [xiaoyifang/goldendict-ng#780]
**Describe the bug**
scroll bar keeps jumping up & down when you have many dicts, please the screen recording
https://github.com/xiaoyifang/goldendict-ng/assets/1632566/b70906de-9b2f-46e8-851e-381d34fe861e

**OS and software versions**
- OS: 
Operating System: Kubuntu 22.04
KDE Plasma Version: 5.24.7
KDE Frameworks Version: 5.92.0
Qt Version: 5.15.3
Kernel Version: 5.15.0-72-generic (64-bit)

- goldendict-ng version: 
Goldendict 23.05.03-alpha.a7213a1c on Thu May 25 21:58:38 2023
ubuntu linux 5.15.0-72-generic Qt 5.15.3 x86_64-little_endian-lp64
GCC 11.3.0
Flags: USE_XAPIAN

**Comment by xiaoyifang** [comment]
the same as https://github.com/xiaoyifang/goldendict-ng/issues/420

it is actually a new  chrome feature  ,maybe need further adjustment

**Comment by Fahad-Alsaidi** [comment]
When a new feature confuses users, it should be revised. What fits browser maybe does not fit other application. However, thank you for your great work on goldendict-ng.

**Comment by xiaoyifang** [comment]
> When a new feature confuses users, it should be revised. What fits browser maybe does not fit other application

Goldendict has actually embedded with a chrome engine.  this `[contain-intrinsic-size](https://developer.mozilla.org/en-US/docs/Web/CSS/contain-intrinsic-size)` feature has really boost page render speed ,   so I just leave it there.

When a better solution comes ,I'll replace it.

**Comment by Fahad-Alsaidi** [comment]
ok. If I want to disable it in my pc. is there any custom css?

**Comment by xiaoyifang** [comment]
https://github.com/xiaoyifang/goldendict-ng/blob/c7d3829eb76c00728cb87148f9192e20c3268f76/src/stylesheets/article-style.css#L90-L91


use custom style and try to remove these two lines.

**Comment by Fahad-Alsaidi** [comment]
Great thanks, 
one more question where I put my custom article-style.css I mean the folder under linux system.

**Comment by xiaoyifang** [comment]
http://goldendict.org/wiki/index.php/FAQ

**Comment by xiaoyifang** [comment]
https://xiaoyifang.github.io/goldendict-ng/topic_userstyle/
