### ISSUE TITLE
slob format's `slobdict_headword` shouldn't exist?

### ISSUE THREAD

**Issue by shenlebantongying** [xiaoyifang/goldendict-ng#783]
Like mdict/zim, slob is also a html format.

Download any dictionary from slob's website https://aarddict.org/

There will be a double head:

![image](https://github.com/xiaoyifang/goldendict-ng/assets/20123683/e40108e1-c2dc-4256-9f7d-5086fddb98dc)

This is the official slob reader's display 

![image](https://github.com/xiaoyifang/goldendict-ng/assets/20123683/6919ce6c-5fa5-4f2d-bab8-4c4c426d2e88)

**Comment by xiaoyifang** [comment]
![image](https://github.com/xiaoyifang/goldendict-ng/assets/105986/47ec4bd0-03cf-483a-83bb-dc57c8dca74f)

A simple fix is to set this css class `display:none`
