### ISSUE TITLE
How can I change the article window background color?

### ISSUE THREAD

**Issue by digitalsimulator** [xiaoyifang/goldendict-ng#806]
I use Dark Deep Add-on Style. Everything is fine except for the color of the article window. It's not dark enough for me, it's gray. Option Dark Reader Mode just adds a brown tint. How can I change the article window background color (and also font color)?

**Comment by shenlebantongying** [comment]
> I use Dark Deep Add-on Style. 

Not sure which one you are using, but you can just change the color value of `gdarticlebody` inside the `.css` file.

> Option Dark Reader Mode just adds a brown tint.

You can remove the custom article-style.css, then turn on Dark Reader mode, it will automatically invert the colour.

However, there is no way to adjust the dark reader's parameters yet. https://github.com/xiaoyifang/goldendict-ng/issues/388

**Comment by digitalsimulator** [comment]
> Not sure which one you are using, but you can just change the color value of gdarticlebody or body inside the .css file.

Thanks for your reply.
I use goldendict-ng 23.05.03-alpha for Linux and article-style.css files which came with it. I changed the color value of **gdarticle** in the "ARTICLE BOXES "  section and this is exactly what I needed. Can I change the font size in the same way?

**Comment by shenlebantongying** [comment]
> Can I change the font size in the same way?

Yes, you can, but you need to learn some CSS selector and set [font:](https://developer.mozilla.org/en-US/docs/Web/CSS/font)

Why not just press "Zoom in" :sweat_smile: 

![image](https://github.com/xiaoyifang/goldendict-ng/assets/20123683/7c43be0a-1b52-4f29-8f78-0054285939f1)

**Comment by digitalsimulator** [comment]
Yes, indeed. I didn't notice it. Thank you.

**Comment by xiaoyifang** [comment]
https://xiaoyifang.github.io/goldendict-ng/topic_userstyle/
