### ISSUE TITLE
DSL format need BOM to recongize utf-8 file

### ISSUE THREAD

**Issue by shenlebantongying** [xiaoyifang/goldendict-ng#809]
Original GD's limitation:

https://github.com/goldendict/goldendict/issues/1203#issuecomment-539617199

The original GD refuse to load the utf8 file without BOM.

related https://github.com/goldendict/goldendict/issues/1388

---

It will load on the -ng version but doesn't display correctly:

![image](https://github.com/xiaoyifang/goldendict-ng/assets/20123683/5f53c869-d556-4e7c-8313-49a7636c366c)

Sample: utf8 dicts -> with BOM & without BOM.
[dsl_sample.zip](https://github.com/xiaoyifang/goldendict-ng/files/11645150/dsl_sample.zip)

Sample problematic DSL file in the wild: https://github.com/open-dsl-dict/wikidict-dsl-zh/blob/master/data/en-zh_wikidict.dsl

**Comment by xiaoyifang** [comment]
any suggestion?

if no bom presented ,read as utf-8 as default?

**Comment by xiaoyifang** [comment]
*[QTextCodec](https://codebrowser.dev/qt5/qtbase/src/corelib/codecs/qtextcodec.h.html#QTextCodec)::codecForUtfText

**Comment by xiaoyifang** [comment]
![image](https://github.com/xiaoyifang/goldendict-ng/assets/105986/d289d5c7-bc0b-4743-b9c0-18988d3e3146)
