### ISSUE TITLE
Start to system tray option is not working in system start up

### ISSUE THREAD

**Issue by BEST8OY** [xiaoyifang/goldendict-ng#810]
**Describe the bug**
Start to system tray option is not working and doesn't minimize GD to tray when system Startup and it maximize GD in Startup.

**To Reproduce**
Enable both 'Start to system' tray and 'Start with system' option.
Restart your system.
It now should start minimized but it's maximized instead.

**Expected behavior**
It should be minimized to system tray when system boot up.

**OS and software versions**

- OS: Windows 11
- Goldendict 23.06.01
windows winnt 10.0.22621 Qt 6.4.3 x86_64-little_endian-llp64
Visual C++ Compiler: 192930148
Flags: USE_XAPIAN  MAKE_ZIM_SUPPORT USE_ICONV MAKE_CHINESE_CONVERSION_SUPPORT

**Additional context**
It only happens in system start up and if you close GD and execute it manually it open minimized in system tray.

**Comment by xiaoyifang** [comment]
can not  reproduced.

**Comment by BEST8OY** [comment]
![image](https://github.com/xiaoyifang/goldendict-ng/assets/70865987/0edc5ff5-87c9-4668-a97e-626976b5780b)
So I checked my startup applications and I have to GD (don't know why?)
Anyway, I disabled one of them and it got fixed.
I close the issue as I think it might be a problem which only I have.

**Comment by xiaoyifang** [comment]
Can you see the path of the two application?

**Comment by BEST8OY** [comment]
> Can you check the path of the two application?

They both had the same path.
I deleted the second one from startup apps list with this application.
One of them was GoldenDict and the other as you can see in this image is GoldenDict-ng which is the one I kept.
But before deleting it from the list I checked, and they both were in the same path.
![image](https://github.com/xiaoyifang/goldendict-ng/assets/70865987/12c16448-8974-416d-9eec-d2661e94c8a9)

**Comment by xiaoyifang** [comment]
I guess I know the reason:
the two entries both start `goldendict.exe`
The first one start to the tray (As expected).
When the second goldendict.exe try to run ,  it detect the application already started.  so it bring the existed application to front(As expected).
