### ISSUE TITLE
stardict format doesn't recongize xdxf (aka type x) correctly

### ISSUE THREAD

**Issue by shenlebantongying** [xiaoyifang/goldendict-ng#811]
`mueller7.tar.bz2` from: https://build.opensuse.org/package/show/openSUSE%3AFactory/stardict-dic-enru-mueller7

Originally reported at https://build.opensuse.org/request/show/1087963?notification_id=41005850

It should be recognized as xdxf (sdct_x) embedded in stardict.

This only happens in Qt6.

Qt5 version is not affected.

![image](https://github.com/xiaoyifang/goldendict-ng/assets/20123683/0ed66a47-0670-4f68-bfa7-85beb167f671)

**Comment by shenlebantongying** [comment]
Not the cause, but we will hit this line with message:

```
Xdxf2html error, xml parse failed: Entity 'nbsp' not declared. at 1,1
```

https://github.com/xiaoyifang/goldendict-ng/blob/87358f73c65861867517cf402b1281853175f8df/src/dict/xdxf2html.cc#LL131C43-L131C43

**Comment by shenlebantongying** [comment]
It turns out to be Qt's fault:

Qt changed the `QDomDocument::setContent` while they are source-level compatible :sweat_smile:

They should have changed the name so that outdated usage will fail to compile.

![image](https://github.com/xiaoyifang/goldendict-ng/assets/20123683/d4b7aeb6-47ce-454f-aaf0-33b5bbeabcae)

Workaround is temporarily to use Qt5.

**Comment by shenlebantongying** [comment]
The problem likely came from Qt's API changes.

The bug only happens with Qt6.

Switch back to Qt5, and the problem will be gone.

![image](https://github.com/xiaoyifang/goldendict-ng/assets/20123683/e762d931-6ac0-4406-b686-054b5f1b4e1b)

**Comment by shenlebantongying** [comment]
I think Qt changed related API and make the XML parser more strict, the `&nbsp` will be rejected.

![image](https://github.com/xiaoyifang/goldendict-ng/assets/20123683/4f180856-769d-453f-87c2-ff30b5c328a4)

**Comment by xiaoyifang** [comment]
QDomDocument is used to parse XML ,    in the above situation ,html parse
is needed.

This is not the first time QDomDocument has caused trouble.
https://github.com/xiaoyifang/goldendict-ng/issues/657
https://github.com/xiaoyifang/goldendict-ng/pull/659

shenleban tongying ***@***.***> 于2023年6月4日周日 19:04写道：
