### ISSUE TITLE
Lingvo dictionaries does not display correctly

### ISSUE THREAD

**Issue by xiaoyifang** [xiaoyifang/goldendict-ng#821]
> 1. UI: Articles are terrible comparing to previous: all translations in 1 line - no line breaks, colors are terrible, background often becomes white - not yellow. Menus and settings not in KDE style - previously was.
> 
> ### Current:
> ![image](https://user-images.githubusercontent.com/3843657/243187466-029a2201-62e9-4903-88ef-82c6db5511bb.png)

mentioned in this issue https://github.com/goldendict/goldendict/issues/1650

**Comment by shenlebantongying** [comment]
The lingvo dict is already fixed.

It can be downloaded http://download.huzheng.org/lingvo/

However, it costs time to update the one in the distro.

The original GD will suffer the same problem when they upgrade to Qt6.

![image](https://github.com/xiaoyifang/goldendict-ng/assets/20123683/8a13dda3-307e-414a-8855-32378daf3d5f)

**Comment by shenlebantongying** [comment]
@vedgy Go fix the thing. GD doesn't even generate the correct XML. The working of stardict's xdxf2html is pure luck.

https://github.com/xiaoyifang/goldendict-ng/pull/812
