### ISSUE TITLE
[feature] add more compression method to dsl dictionary

### ISSUE THREAD

**Issue by xiaoyifang** [xiaoyifang/goldendict-ng#832]
**Is your feature request related to a problem? Please describe.**
apart from `dsl.dz`
what about `dsl.tar.gz`
`dsl.gz`   ,  `dsl.tar` etc.

**Comment by shenlebantongying** [comment]
Not sure if this is useful because `.dz` is `gzip/.gz` but with an index table to support random access, which is not the goal of other compression methods.
