### ISSUE TITLE
[Bug] Zim dictionaries are re-indexed at every startup

### ISSUE THREAD

**Issue by ApprobationBW** [xiaoyifang/goldendict-ng#860]
**Describe the bug**
At every startup of GoldenDict-ng, the zim dictionaries are re-indexed as if they were new. This bug appeared a few days ago and it is time-consuming.

This issue causes GoldenDict to very slow at startup when someone has several .zim dictionaries.

**To Reproduce**
1. Add a few .zim dictionaries (e.g. German Wiktionary)
2. Start GoldenDict
4. We can see a window showing that the .zim files are reindexed at every startup

**Expected behavior**
.zim files should be indexed once and forever like other formats.

**Screenshots**
![grafik](https://github.com/xiaoyifang/goldendict-ng/assets/121114125/4e9b9678-121f-4bac-91ce-58062c0d2a52)

**OS and software versions**
- OS: Manjaro Linux—latest Unstable- (Arch Linux)
-  GD Installed via AUR package

Goldendict 23.06.02-alpha.4fc21074 on Sat Jun 3 17:53:00 2023
manjaro linux 6.1.33-1-MANJARO Qt 6.5.1 x86_64-little_endian-lp64
GCC 13.1.1 20230429
Flags: USE_XAPIAN  MAKE_ZIM_SUPPORT MAKE_CHINESE_CONVERSION_SUPPORT

**Comment by xiaoyifang** [comment]
This part of reindex logic has not changed.

It only reindex when it detect the zim file is newer than the indexed file or indexed file is corrupted

**Comment by xiaoyifang** [comment]
This part of reindex logic has not changed.

It only reindex when it detect the zim file is newer than the indexed file or indexed file is corrupted

**Comment by ApprobationBW** [comment]
The issue was solved after deleting all the config folder.

**Comment by xiaoyifang** [comment]
> The issue was solved after deleting all the config folder.

This is weird ,  maybe need further check

**Comment by shahram7** [comment]
I have same problem but i have just babylon BGL and Stardict dictionaries. 
By every start it begins to index and the app get closed immediately

**Comment by xiaoyifang** [comment]
fulltext indexing?

**Comment by shahram7** [comment]
> fulltext indexing?

yes and it get closed immediately. even when it doesn't get closed at start up it is going to get closed when I click on a word in history.
(history comes from my goldendict 1.5.0 last gen)

**Comment by xiaoyifang** [comment]
> it get closed immediately.

I do not get it , do you mean it disappeared .?

**Comment by shahram7** [comment]
> > it get closed immediately.
> 
> I do not get it , do you mean status text disappeared .?

no the main window of goldendict-ng get closed

**Comment by xiaoyifang** [comment]
> > > it get closed immediately.
> > 
> > 
> > I do not get it , do you mean status text disappeared .?
> 
> no the main window of goldendict-ng get closed

seems a bug ,need more information . you can open a new issue ticket
