### ISSUE TITLE
qtimer is not released.

### ISSUE THREAD

**Issue by xiaoyifang** [xiaoyifang/goldendict-ng#861]
**Describe the bug**
-fsanitizer=address
```
set (CMAKE_CXX_FLAGS_DEBUG "${CMAKE_CXX_FLAGS_DEBUG} -fno-omit-frame-pointer -fsanitize=address")
set (CMAKE_LINKER_FLAGS_DEBUG "${CMAKE_LINKER_FLAGS_DEBUG} -fno-omit-frame-pointer -fsanitize=address ")
```
showed the result
![图片](https://github.com/xiaoyifang/goldendict-ng/assets/105986/9c724176-8a9a-498c-9597-fa33115472dc)

**Comment by xiaoyifang** [comment]
@shenlebantongying  can you help to check this

**Comment by shenlebantongying** [comment]
This should silence the sanitizer:
```
   connect(timerThread,&QThread::finished,timer,&QObject::deleteLater);
```

**Comment by xiaoyifang** [comment]
I think it is better to release the memory by timer's host ,but not the thread.

```
new QTimer(this)?
```

**Comment by shenlebantongying** [comment]
>  better to release the memory by timer's host ,but not the thread

Make sense, but I cannot get `new QTimer(this)` to work. Setting the parent to `this` will lead to crashes https://github.com/xiaoyifang/goldendict-ng/pull/266

[moveToThread -> The object cannot be moved if it has a parent.](https://doc.qt.io/qt-6/qobject.html#moveToThread)

Also, the connect deleteLater is a pattern.

Make a worker obj (QTimer) -> Push it to thread (moveToThread) -> connect to deleteLater

![image](https://github.com/xiaoyifang/goldendict-ng/assets/20123683/4edcc078-53b0-41c4-9860-d4d5065f954a)https://doc.qt.io/qt-6/qthread.html#details

**Comment by xiaoyifang** [comment]
I got it ,  the qtimer must be release after workThread.
