### ISSUE TITLE
Not removal of ARM support

### ISSUE THREAD

**Issue by sonerfromnurland** [xiaoyifang/goldendict-ng#862]
Could you kindly consider **not removal of ARM(Apple Silicon) support?** Your homebrew builds are for Intel processors. Using Intel apps on Mac computers require to use rosetta as intermediary(intel to ARM  simulator). This kind of usage brings about more battery consumption. That's why most people don't want to use Rosetta.

**Comment by xiaoyifang** [comment]
You can continue to use arm version   using the following release
https://github.com/xiaoyifang/goldendict-ng/releases?q=wuyi&expanded=true
