### ISSUE TITLE
This part of config code seems too old to be useful

### ISSUE THREAD

**Issue by xiaoyifang** [xiaoyifang/goldendict-ng#865]
https://github.com/xiaoyifang/goldendict-ng/blob/16f853b68b5c648fd42baeeb35158162539079a6/src/config.cc#L485-L515

**Comment by shenlebantongying** [comment]
+1

Just delete these codes.

`StarDict\dic` is just a demo without real value.

http://www.huzheng.org/stardict/

StarDict doesn't bundle `WyabdcRealPeopleTTS`, and manual installation is needed anyway.

http://www.huzheng.org/stardict/

![image](https://github.com/xiaoyifang/goldendict-ng/assets/20123683/8b4d1fc9-e484-4796-9e0d-46f7d9a39288)
