### ISSUE TITLE
zim dicts don't have icon

### ISSUE THREAD

**Issue by shenlebantongying** [xiaoyifang/goldendict-ng#872]
Original GD's only loads a default one.

![image](https://github.com/xiaoyifang/goldendict-ng/assets/20123683/7470d04f-0487-4ece-818b-4d3bda5ea1c3)

https://github.com/xiaoyifang/goldendict-ng/blob/0b36b846cea191b1b751ffd106e5b69ef34a7899/src/dict/zim.cc#L273-L290

zim's icon, called "Illustration" is a 48x48 png file (the related code allows other sizes, but 48x48 is guaranteed to exist).

It should be obtained via `Archive::getIllustrationItem`

https://github.com/openzim/libzim/blob/d87ff0d0d80d251ce976d34bac96ffc53c04bfe4/include/zim/archive.h#L197

# Affected Dicts in the wild

I think anything downloaded from 

https://library.kiwix.org

should have an icon

**Comment by xiaoyifang** [comment]
> It should be obtained via `Archive::getIllustrationItem`

Only display default icon ,if can not obtained via the above method.

**Comment by shenlebantongying** [comment]
Why are there two types of icons `dictionaryNativeIcon` `dictionaryIcon` :sweat_smile: 

The `getNativeIcon` is only used in dictionaryBar

https://github.com/search?q=repo%3Agoldendict%2Fgoldendict%20getNativeIcon&type=code

And based on the comment, the `getNativeIcon` should not be used in dictionaryBar. The square `dictionaryIcon` should be used instead.

<img src="https://github.com/xiaoyifang/goldendict-ng/assets/20123683/6bcce228-488d-433e-b584-bec698413632" width="400"> 

---

They are always the same :sweat_smile: 

![image](https://github.com/xiaoyifang/goldendict-ng/assets/20123683/687a4f85-d2a2-492e-94a4-f9633c793bd2)

We should eliminate `dictionaryNativeIcon` & `getNativeIcon()`.
