### ISSUE TITLE
Use `ubuntu-20.04` instead of `ubuntu-latest` for appimage releases

### ISSUE THREAD

**Issue by shenlebantongying** [xiaoyifang/goldendict-ng#874]
Related https://github.com/AppImage/appimage.github.io/pull/3155

`ubuntu-latest` becomes `22.04` late last year.

And we need a build for the PR :)

The one that got automatically picked up is from `Pre-release`'s qt5 build
https://github.com/AppImage/appimage.github.io/actions/runs/5302837932/jobs/9598055454?pr=3155#step:4:105

**Comment by xiaoyifang** [comment]
This can be done

**Comment by xiaoyifang** [comment]
https://ubuntu.pkgs.org/20.04/ubuntu-universe-amd64/libzim-dev_4.0.4-5ubuntu3_amd64.deb.html

ubuntu 20.04 only has zim-4.0 which does not have "zim/archive.h"

**Comment by shenlebantongying** [comment]
The version in the middle are completely skipped :sweat_smile:
