### ISSUE TITLE
AutoGroupBy folder,which folder should website be put into?

### ISSUE THREAD

**Issue by xiaoyifang** [xiaoyifang/goldendict-ng#886]
**Describe the bug**
as title.

@shenlebantongying  can you help to check this?

**Comment by shenlebantongying** [comment]
Nowhere? Don't group things without a folder in "something by folder" make sense to me.

**Comment by xiaoyifang** [comment]
Actually the website use goldendict.exe's parent folder as a group.

**Comment by xiaoyifang** [comment]
maybe use a specified group name for website.

https://github.com/xiaoyifang/goldendict-ng/blob/b3d9d798168ae98e0d2337b45e48c2a89930848a/src/ui/groups_widgets.cc#L794-L801

for website dictionary ,  getContainingFolder return empty string which then resolve as the parent folder of executable file.

**Comment by xiaoyifang** [comment]
@shenlebantongying  can you help to check this?
