### ISSUE TITLE
Is this file `fixx11h.h` still useful nowdays?

### ISSUE THREAD

**Issue by xiaoyifang** [xiaoyifang/goldendict-ng#888]
https://github.com/xiaoyifang/goldendict-ng/blob/074c7a0acaeec8206292947d5b77d230511b4b7f/src/common/fixx11h.h#L4-L53

**Comment by shenlebantongying** [comment]
I tried to remove it before but failed.

The KDE's codebase also still have this and the problematic part of x11 headers is unchanged.

We cannot avoid direct x11 usages yet.

**Comment by xiaoyifang** [comment]
Ok, this can be marked as in the future.

**Comment by shenlebantongying** [comment]
I think we need it forever. Because the insanity of X11 redefining common names is not going to be fixed and the part in GD that require X11 cannot be removed (in foreseeable future).
