### ISSUE TITLE
Integrationf of ChatBots for translation

### ISSUE THREAD

**Issue by Atreyu-94** [xiaoyifang/goldendict-ng#895]
**Is your feature request related to a problem? Please describe.**
GoldenDict is a great project, but I feel it is lacking a good translation platform too if it add support to chatbots like ChatGPT.

Through API we can get amazing translations of sentences. Specially useful when you are reading papers of science and you need some context to get good translations.

Would it be possible?

**Comment by shenlebantongying** [comment]
Can GD integrate X service?

Yes.

But someone has to write some code that assembles charBot or whatever services API to text output.

Just find a command line version of chatBots, then add it as "Programs"

Similar to this https://kongxl.net/2019/03/2019-03-27-goldendict-sentence-translate/
https://github.com/rany2/edge-tts/discussions/94#discussioncomment-6040134
https://github.com/xinebf/google-translate-for-goldendict
