### ISSUE TITLE
Support "Translates from" an "Translates to" for DSL dictionaries

### ISSUE THREAD

**Issue by homocomputeris** [xiaoyifang/goldendict-ng#902]
**Is your feature request related to a problem? Please describe.**
It would be nice to show languages for DSL dictionaries too. Not the fields are empty. Does it affect "Group by language"?

![Screenshot 2023-06-24 at 13 01 11](https://github.com/xiaoyifang/goldendict-ng/assets/7422433/d882ea04-c4c6-47bb-a7e1-87d60acefc9d)

**Describe the solution you'd like**
Support "Translates from" an "Translates to" for DSL dictionaries

**Describe alternatives you've considered**
Leave as is.

**Additional context**
Language values supported in the original DSL
https://anatoly314.github.io/dsl-manual/#langs.html#supported

**Comment by xiaoyifang** [comment]
These two fields are readed from dsl metadata,
in your case , the dsl may not contains the language fields.
https://github.com/xiaoyifang/goldendict-ng/blob/a878e725f27c3b9cfc5e7fedc8a36262956f1039/src/dict/dsl.cc#L2298-L2300

**Comment by shenlebantongying** [comment]
It is a bug, for example, this one https://github.com/Tvangeste/SampleDSL/blob/master/sample.dsl

You have to reindex to reproduce it.

**Comment by xiaoyifang** [comment]
![image](https://github.com/xiaoyifang/goldendict-ng/assets/105986/bbda03ea-c519-43a9-8b2a-0cc3d394ee4b)

how to reindex?

**Comment by shenlebantongying** [comment]
> how do you reindex?

By deleting `~/.cache/goldendict` :sweat_smile: 

Another sample: https://downloads.freemdict.com/%E5%B0%9A%E6%9C%AA%E6%95%B4%E7%90%86/%E5%85%B1%E4%BA%AB2020.5.11/content/1_english/z_dictionary_others/KernermanDictionary/en-en_KAED_as_1_0.dsl.dz

![image](https://github.com/xiaoyifang/goldendict-ng/assets/20123683/821ee33b-bb2a-4057-a20e-2b50610d3a81)

**Comment by shenlebantongying** [comment]
I think the problem is this line:

`dslLanguageToId(U"English")` evaluates to `0`

![image](https://github.com/xiaoyifang/goldendict-ng/assets/20123683/ddeebfff-075b-4b4d-8e3d-c12bddbfac92)

**Comment by xiaoyifang** [comment]
Yes ,it has a bug

**Comment by homocomputeris** [comment]
>  in your case , the dsl may not contains the language fields.

They do contain.

----
By the way, does GD support parsing of ISO 639-* codes in those fields?

**Comment by xiaoyifang** [comment]
https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes

From the implementation . it support these codecs.
