### ISSUE TITLE
The MacOS qt6 version will flicker when inspecting elements, but the qt5 version does not have this problem

### ISSUE THREAD

**Issue by pk49800** [xiaoyifang/goldendict-ng#914]
**描述 bug**

**复现 bug 的步骤**
1. 打开任意词典查词并右键选择审查元素
2. 鼠标上下滑动屏幕
3. 屏幕闪烁

**受影响的词典**
任意

如果有可能，上传词典的文件或提供下载的链接。（GitHub 可以上传 25MiB 以下的 zip 文件）

**期望的结果**
开启审查元素时屏幕不闪烁

**相关的截图**

https://github.com/xiaoyifang/goldendict-ng/assets/36910388/b06f32a1-f679-4f29-bede-e3a36322c94b

**系统和软件的版本**

复制 & 粘贴 `帮助` -> `关于` -> `复制版本信息` 到这里

- OS: MacOS 13.4.1
- Version 6.4.3-GoldenDict_macos-13_homebrew_20230627

**额外的信息**

**Comment by xiaoyifang** [comment]
maybe this?
https://bugs.chromium.org/p/chromium/issues/detail?id=248966

**Comment by pk49800** [comment]
> maybe this? https://bugs.chromium.org/p/chromium/issues/detail?id=248966

Strange! But my local Chrome app does not have this problem.

**Comment by xiaoyifang** [comment]
等以后升级qt版本后，再看看
