### ISSUE TITLE
Restart fails after changing dictionary font

### ISSUE THREAD

**Issue by yshumy** [xiaoyifang/goldendict-ng#926]
版本：6.4.3-GoldenDict_macos-12_homebrew_20230702
改词典字体后重启失效，自动恢复原来字体。
是不是 bug ？发现问题出在这个“灯”上。
<img width="299" alt="截屏2023-07-03 03 12 19" src="https://github.com/xiaoyifang/goldendict-ng/assets/103359913/8509b2de-3321-4f87-a62b-13bc864562bc">

**Comment by xiaoyifang** [comment]
怎么修改的？
哪里失效？
是配置项中的值变了，还是显示没效果？

**Comment by yshumy** [comment]
> 版本：6.4.3-GoldenDict_macos-12_homebrew_20230702  改词典字体后重启失效，自动恢复原来字体。 是不是 bug ？发现问题出在这个“灯”上。 <img alt="截屏2023-07-03 03 12 19" width="299" src="https://user-images.githubusercontent.com/103359913/250393483-8509b2de-3321-4f87-a62b-13bc864562bc.png">



> 怎么修改的？ 哪里失效？ 是配置项中的值变了，还是显示没效果？

当时有效，退出重启后还原。
<img width="426" alt="截屏2023-07-03 14 22 50" src="https://github.com/xiaoyifang/goldendict-ng/assets/103359913/03c530e6-0202-443c-98a3-1ef1bc11ce0f">

**Comment by xiaoyifang** [comment]
![image](https://github.com/xiaoyifang/goldendict-ng/assets/105986/96f1a0a1-a9b3-43fe-b6f1-56128f4ec28a)
重启后，这个地方的配置还原了吗？

**Comment by yshumy** [comment]
> ![图像](https://user-images.githubusercontent.com/105986/250475017-96f1a0a1-a9b3-43fe-b6f1-56128f4ec28a.png)重启后，这个地方的配置还原了吗？

是的。

**Comment by yshumy** [comment]
> ![图像](https://user-images.githubusercontent.com/105986/250475017-96f1a0a1-a9b3-43fe-b6f1-56128f4ec28a.png)重启后，这个地方的配置还原了吗？

是的。

**Comment by xiaoyifang** [comment]
linux上的没重现。macos应该不至于啊

**Comment by xiaoyifang** [comment]
用最新的版本试一下，这个地方有重构
