### ISSUE TITLE
In some cases, the full-text index cannot be created in portable mode

### ISSUE THREAD

**Issue by popyoung** [xiaoyifang/goldendict-ng#930]
https://github.com/xiaoyifang/goldendict-ng/pull/916#issuecomment-1616510203
之前反馈我下载的版本在portable模式下没有建立全文索引。
于是我在本地编译了最新的版本，然而debug时发现portable模式也能够建立索引。但可能因为我的Qt没有升级到6.5.1，attach到下载的gd文件后断点没有拦截到。后面几天空了我升级Qt后再看看。

**Comment by xiaoyifang** [comment]
如果有问题，再打开。
