### ISSUE TITLE
[Bug] Audio Folders: extension of files is not detected while saving audios

### ISSUE THREAD

**Issue by ApprobationBW** [xiaoyifang/goldendict-ng#937]
**Describe the bug**
There is an issue affecting "Audio Folders":

When collection of audios are added, GD correctly indexes all the audios in a folder and audios play correctly. However, when a user tries to "right-click the Audio" to save it, GoldenDict fails to recognize the “file EXTENSION” and users need to manually add the suffix .mp3, .opus, etc.

It is a regression since the function was working correctly several months ago. That is, several months ago, if a collection of .opus audios were added, GoldenDict was able to recognize the .opus format while "Saving the audio".

**To Reproduce**

1. Add a Collection of Audios
2. right-Click on the word and "Save Audio"
3. No file extension is detected by GoldenDict (error).

For example, if an audio in the computer is called "China.opus" , when one tries to save the word it only shows as random number WITHOUT EXTENSION "12713".

**Affected Dictionaries**

Collection of audios (folders) in .opus format. For example, the German Wiktionary audios:

https://cloud.freemdict.com/index.php/s/asX8cktzaP4fWrM

**Expected behavior**
If a filename in the computer is called "China.opus", GoldenDict should save the file with the file extension as "China.opus". Not a random number without extension forcing users to manually rename the file (add the extension).

**Screenshots**
![grafik](https://github.com/xiaoyifang/goldendict-ng/assets/121114125/1e575a11-c09a-4a3f-bf06-11c6f510a87e)

![grafik](https://github.com/xiaoyifang/goldendict-ng/assets/121114125/483bc86d-a89f-47a4-b9d4-f5d41af38a20)

**OS and software versions**
Goldendict-ng 23.06.02-alpha.7696f47a on Sat Jul 1 20:41:56 2023
Qt 6.5.1 GCC 13.1.1 20230429manjaro linux 6.1.36-1-MANJARO x86_64-little_endian-lp64
Flags:USE_XAPIAN MAKE_ZIM_SUPPORT MAKE_CHINESE_CONVERSION_SUPPORT

**Additional context**
The Problem is important because some users need to save audios from GoldenDict to make ANKI Cards.

I need to manually export 3000 audios from GoldenDict right now and this bug makes the process extremely slow. Everything was working fine 6 months ago...

**Comment by ApprobationBW** [comment]
Anki will not detect files without an audio extension (.opus, .mp3, etc). So, if users save the audios with random numbers (e.g. 172872) then those files cannot be added to Anki. The software ignores them.

Therefore, one needs to manually rename the files while exporting from GoldenDict. That is okay when someone only saves 1-2 audios per day but some users do it more than 100 times per day to make Anki Cards.

That is a huge problem.... One can waste 1 hour per day renaming audios within GD.

**Comment by xiaoyifang** [comment]
the save audio function has not been changed for a time.  need investigation.

**Comment by xiaoyifang** [comment]
@ApprobationBW can you try to save the audio in some other dictionaries not the audio from the sound dir.

**Comment by ApprobationBW** [comment]
The bug only happens with "**Sound Directories**".  

.mdx and .dsl dictionaries with audios work normally. However, the situation is certainly a regression. With 100% confidence I can assure you that audios from "Sound Directories" could be saved the last year without issues.
