### ISSUE TITLE
Some website dicts' encoding looks wrong, for example, lingvolive, milononline

### ISSUE THREAD

**Issue by shenlebantongying** [xiaoyifang/goldendict-ng#941]
left -> browser, right -> inside GD
https://www.milononline.net/do_search.php?sDIN=&Q=%GDWORD%
![image](https://github.com/xiaoyifang/goldendict-ng/assets/20123683/49d1f321-2c5d-429e-9249-41a19b378106)

https://www.lingvolive.com/en-us/translate/en-ru/%GDWORD%
![image](https://github.com/xiaoyifang/goldendict-ng/assets/20123683/208b2d27-b5aa-4e28-b845-64c2c5bf1cb2)

https://dict.youdao.com/ works fine.

**Comment by xiaoyifang** [comment]
can you try the branch on linux

**Comment by shenlebantongying** [comment]
The problem is fixed on Linux :)

**Comment by shenlebantongying** [comment]
Surprisingly, https://github.com/xiaoyifang/goldendict-ng/pull/942 breaks Qt5's website :cry: 

![image](https://github.com/xiaoyifang/goldendict-ng/assets/20123683/f047ec85-cf8e-439d-9e98-2c63e6e0d88c)

**Comment by xiaoyifang** [comment]
try this fix/website-qt5
