### ISSUE TITLE
How to reduce flash when changing articles?

### ISSUE THREAD

**Issue by itkind** [xiaoyifang/goldendict-ng#957]
Hi, when changing articles in dark mode there is a short white flash that makes pain in the eyes. See gif attached. 
![2023-07-11_21-18-36 (2)](https://github.com/xiaoyifang/goldendict-ng/assets/22380863/c51c5ebe-8e1b-4524-9687-6b847d979e97)

Is there a possibility to cut it out or delete it or to apply dark mode to it? 

Big thanks.

**Comment by xiaoyifang** [comment]
最新版应该可以了，可以尝试下

**Comment by xiaoyifang** [comment]
#357

**Comment by Enlight432** [comment]
@xiaoyifang 
Do you mean the pre-release version? Because the stable version has a white flash problem
