### ISSUE TITLE
Unlimited new page issues

### ISSUE THREAD

**Issue by Username-Adrian** [xiaoyifang/goldendict-ng#961]
**Bug**
当我使用 GoldenDict 查询百度百科内的内容时，当百度百科未查询到该内容时，会出现“未查询到该内容，将跳转到百度百科首页”。然后我的浏览器中就会无限创建百度百科页面。

**复现**
![bug3](https://github.com/xiaoyifang/goldendict-ng/assets/47768706/82553acf-ed3f-4c8d-b7ec-bf2b875c2af2)

**系统和软件的版本**

系统：Windows 10 21H2
软件版本：Goldendict-ng 23.06.02-alpha.20230623.2a7d4d5e
Qt 6.5.1 Visual C++ Compiler 192930148windows winnt 10.0.19044 x86_64-little_endian-llp64
Flags:USE_XAPIAN MAKE_ZIM_SUPPORT USE_ICONV MAKE_CHINESE_CONVERSION_SUPPORT

**Comment by xiaoyifang** [comment]
应该是百科里面的某些故意或者无意造成的脚本。

**Comment by xiaoyifang** [comment]
![image](https://github.com/xiaoyifang/goldendict-ng/assets/105986/06ae576e-1733-4324-aa8c-a7223319100d)

**Comment by xiaoyifang** [comment]
可以试下这个版本。  https://github.com/xiaoyifang/goldendict-ng/releases/tag/valpha.224d3278

**Comment by Username-Adrian** [comment]
> 可以试下这个版本。 https://github.com/xiaoyifang/goldendict-ng/releases/tag/valpha.224d3278

新版本完美解决了这个问题！
