### ISSUE TITLE
Stop popping up “New Release Availale” automatically

### ISSUE THREAD

**Issue by GrimPixel** [xiaoyifang/goldendict-ng#964]
Just don't pop up any prompt by default, OK?

**Comment by xiaoyifang** [comment]
![image](https://github.com/xiaoyifang/goldendict-ng/assets/105986/7ef7635c-0b72-4c3e-bfb7-27892fffb35f)

**Comment by GrimPixel** [comment]
I didn't express accurately. I wished that when I were doing something else, there would be no prompt that informs me to update a program. If it checks the update, only do it at the startup of the program.

**Comment by xiaoyifang** [comment]
Yes ,  check  one time only at the startup make sense.
