### ISSUE TITLE
goldendict not using system (kde plasma 5.27.6) cursor 

### ISSUE THREAD

**Issue by Ilya-JBR** [xiaoyifang/goldendict-ng#971]
Instead of displaying the kde plasma cursor it displays wrong cursor

![image](https://github.com/xiaoyifang/goldendict-ng/assets/91881001/b7624d22-c568-4212-a0d0-78e735bea6e0)

expected:
![image](https://github.com/xiaoyifang/goldendict-ng/assets/91881001/00287711-5279-4993-9fc8-55882f44a0c9)

Arch Linux 
Goldendict-ng 23.06.02-alpha.86f9fa6c on Sun Jul 9 21:44:58 2023
Qt 6.5.1 GCC 13.1.1 20230429arch linux 6.4.3-arch1-1 x86_64-little_endian-lp64
Flags:USE_XAPIAN MAKE_ZIM_SUPPORT MAKE_CHINESE_CONVERSION_SUPPORT

**Comment by xiaoyifang** [comment]
https://www.reddit.com/r/kde/comments/xj45bg/how_do_i_stop_my_cursor_from_changing_im_using/

**Comment by shenlebantongying** [comment]
The "Default" cursor is bugged on kde plasma 5.27.6 on X11.

Specificly choosing to use "Breeze Light" will fix the problem.

![Peek 2023-07-14 20-17](https://github.com/xiaoyifang/goldendict-ng/assets/20123683/aa6cd9b5-d7e5-49ee-a12f-1ce31ea73142)

**Comment by shenlebantongying** [comment]
This is KDE's bug.
