### ISSUE TITLE
Frequent crashes in multiple scenarios, no crash logs

### ISSUE THREAD

**Issue by offlineface** [xiaoyifang/goldendict-ng#979]
**经常发生崩溃现象，无具体原因不能稳定复现**

**可能的复现 bug 的步骤**
1. 查单词点击候选词条后卡死崩溃
2. 在字典中继续点击某单词加载过程卡死崩溃
3. 在搜索栏输入字符后点击回车卡死崩溃
4. 其他暂时想不起来的崩溃原因

**已安装的词典**
牛津英汉汉英词典
牛津高阶英汉双解词典（第10版）V3
Concise Oxford English Dictionary 11th
Merriam-Webster's Collegiate Dictionary
The Chambers Thesaurus 5th
牛津英语同义词英汉双解
大辞海
English (US) Morphology
English Wikipedia

**系统和软件的版本**

- Goldendict-ng 23.06.02-alpha.20230715.119a5ccb
- Qt 6.5.1 Visual C++ Compiler 192930151windows winnt 10.0.22621 x86_64-little_endian-llp64
- Flags:USE_XAPIAN MAKE_ZIM_SUPPORT USE_ICONV MAKE_CHINESE_CONVERSION_SUPPORT

- OS: [Windows11 Pro]
- Version [22H2]

**Comment by xiaoyifang** [comment]
打开你的配置文件夹。
![image](https://github.com/xiaoyifang/goldendict-ng/assets/105986/f84d86fa-79fa-4c89-bd28-f7305f18c4e3)

文件夹里有个crash文件夹，里面的dmp文件传上来。

**Comment by xiaoyifang** [comment]
也可以将你的词典逐个禁用，看下是否哪个词典引起的

**Comment by offlineface** [comment]
事实上，crash文件夹里什么都没有，我百思不得其解

**Comment by xiaoyifang** [comment]
没法排查，等后续有更详细的信息的时候，再打开。
